#!/usr/bin/env python3
"""Append W31-W40 questions"""
import os
DIR = 'E:/scripts-python/worldexams/questions_data/colombia/sociales-ciudadanas/grado-3/2026/weekly'
with open(os.path.join(DIR, 'gen_all.py'), 'r', encoding='utf-8') as f:
    old = f.read()
marker = "def main():"
parts = old.split(marker)
chunk = '''
Q['W31'] = [
    (1,1,1,0.86,'I.E. San Felipe, Bogota. Pisos termicos.','Que determina el clima en las diferentes zonas de Colombia?','La altura sobre el nivel del mar (pisos termicos).',
     ['B) La hora del dia. <!-- feedback: Es la altura. -->','C) El mes del ano. <!-- feedback: Es la altura. -->','D) La cantidad de arboles. <!-- feedback: Es la altura. -->'],
     'Los pisos termicos son zonas determinadas por la altura: calido (0-1000m), templado (1000-2000m) y frio (2000-3000m).'),
    (1,1,1,0.84,'I.E. Los Andes, Pasto. Clima calido.','Donde encontramos clima calido en Colombia?','En las costas del Caribe y Pacifico, y en los llanos orientales.',
     ['B) En Bogota. <!-- feedback: Bogota tiene clima frio. -->','C) En el Nevado del Ruiz. <!-- feedback: Es clima frio. -->','D) En Tunja. <!-- feedback: Es clima frio. -->'],
     'El clima calido predomina en zonas bajas como costas, llanos y valles interandinos.'),
    (2,2,2,0.76,'I.E. INEM, Medellin. Clima templado.','Que caracteriza al clima templado?','Temperatura agradable, entre 18 y 24 grados, en zonas de altura media.',
     ['B) Mucho calor todo el ano. <!-- feedback: Eso es calido. -->','C) Frio intenso y nieve. <!-- feedback: Eso es frio. -->','D) Lluvia todo el dia. <!-- feedback: No es exclusivo. -->'],
     'El clima templado se encuentra entre 1000 y 2000 metros de altura. Ciudades como Medellin y Cali tienen clima templado.'),
    (2,2,2,0.73,'I.E. Fe y Alegria, Cali. Clima frio.','Donde encontramos clima frio en Colombia?','En ciudades de alta montana como Bogota, Tunja y Pasto.',
     ['B) En la costa Caribe. <!-- feedback: Es calido. -->','C) En Leticia. <!-- feedback: Es calido. -->','D) En Barranquilla. <!-- feedback: Es calido. -->'],
     'El clima frio predomina en ciudades ubicadas a mas de 2000 metros sobre el nivel del mar.'),
    (3,3,3,0.65,'I.E. Tecnico, Ibague. Aplicacion.','La familia Perez vive en Bogota. Que tipo de ropa debe usar normalmente?','Ropa abrigada: chaqueta, buzo y pantalon largo, porque el clima es frio.',
     ['B) Ropa de bano. <!-- feedback: Bogota no es caliente. -->','C) Solo camiseta. <!-- feedback: Hace frio. -->','D) Traje de bano. <!-- feedback: No. -->'],
     'Bogota tiene clima frio (aproximadamente 14 grados promedio), por lo que se necesita ropa abrigada.'),
    (3,3,3,0.62,'I.E. Simon Bolivar, Santa Marta. Aplicacion.','En Santa Marta hace calor casi todo el ano. Que clima tiene?','Clima calido, porque esta a nivel del mar en la costa Caribe.',
     ['B) Clima frio. <!-- feedback: Costa Caribe es calida. -->','C) Clima templado. <!-- feedback: Es calido. -->','D) Clima polar. <!-- feedback: No. -->'],
     'Santa Marta esta a nivel del mar, por lo que tiene clima calido todo el ano.'),
    (4,4,4,0.48,'I.E. Manuelita, Neiva. Analisis.','Por que Colombia tiene variedad de climas?','Porque tiene diferentes altitudes: desde el nivel del mar hasta nevados de mas de 5000 metros.',
     ['B) Porque cambia el clima cada dia. <!-- feedback: Por las altitudes. -->','C) Porque esta cerca del sol. <!-- feedback: No. -->','D) Porque llueve mucho. <!-- feedback: Es por altura. -->'],
     'La variedad de altitudes en Colombia crea diferentes pisos termicos y por tanto climas diversos.'),
    (5,5,5,0.40,'I.E. San Jose, Palmira. Evaluacion.','Como influye el clima en las actividades de las personas?','Determina el tipo de ropa, cultivos, vivienda y actividades economicas de cada region.',
     ['B) No influye. <!-- feedback: Si influye mucho. -->','C) Solo en la ropa. <!-- feedback: Tambien en cultivos y economia. -->','D) Solo en vacaciones. <!-- feedback: En todo. -->'],
     'El clima influye en casi todos los aspectos de la vida: agricultura, vestimenta, vivienda y economia.'),
]

Q['W32'] = [
    (1,1,1,0.86,'I.E. San Bartolome, Bogota. Fauna.','Cual es el ave nacional de Colombia?','El condor de los Andes.',
     ['B) La guacamaya. <!-- feedback: No es el ave nacional. -->','C) El colibri. <!-- feedback: No. -->','D) El gallo. <!-- feedback: No. -->'],
     'El condor de los Andes es el ave nacional de Colombia, simbolo de libertad en el escudo nacional.'),
    (1,1,1,0.84,'I.E. Los Andes, Pasto. Flora.','Cual es la flor nacional de Colombia?','La orquidea (Cattleya trianae).',
     ['B) La rosa. <!-- feedback: No es la flor nacional. -->','C) El girasol. <!-- feedback: No. -->','D) El clavel. <!-- feedback: No. -->'],
     'La orquidea Cattleya trianae es la flor nacional de Colombia, con colores de la bandera.'),
    (2,2,2,0.76,'I.E. INEM, Medellin. Palma de cera.','Que arbol es el arbol nacional de Colombia?','La palma de cera del Quindio.',
     ['B) El eucalipto. <!-- feedback: No. -->','C) El pino. <!-- feedback: No. -->','D) El roble. <!-- feedback: No. -->'],
     'La palma de cera del Quindio es el arbol nacional de Colombia. Puede alcanzar hasta 60 metros de altura.'),
    (2,2,2,0.73,'I.E. Fe y Alegria, Cali. Biodiversidad.','Por que Colombia es considerada un pais mega diverso?','Porque tiene una enorme cantidad de especies de plantas y animales en todo su territorio.',
     ['B) Porque es grande. <!-- feedback: No solo por tamanio. -->','C) Porque tiene petroleo. <!-- feedback: Es por biodiversidad. -->','D) Porque tiene muchos rios. <!-- feedback: Es por especies. -->'],
     'Colombia es el segundo pais mas biodiverso del mundo, con miles de especies de fauna y flora.'),
    (3,3,3,0.65,'I.E. Tecnico, Ibague. Aplicacion.','En el zoologico, los ninos ven jaguares, osos hormigueros y delfines. Son animales de:','La fauna representativa de Colombia, que habita en diferentes regiones.',
     ['B) Otro pais. <!-- feedback: Son colombianos. -->','C) Solo la Amazonia. <!-- feedback: De varias regiones. -->','D) Solo los llanos. <!-- feedback: De varias regiones. -->'],
     'El jaguar, el oso hormiguero y el delfin rosado son especies representativas de Colombia.'),
    (3,3,3,0.62,'I.E. Simon Bolivar, Leticia. Aplicacion.','En el Amazonas colombiano, que tipo de animales encontramos?','Delfines rosados, jaguares, monos, anacondas y guacamayas.',
     ['B) Solo peces. <!-- feedback: Hay muchos mas. -->','C) Solo aves. <!-- feedback: Hay mamiferos y reptiles. -->','D) Pingueinos. <!-- feedback: No hay en Amazonas. -->'],
     'La Amazonia colombiana alberga una gran diversidad de fauna.'),
    (4,4,4,0.48,'I.E. Manuelita, Neiva. Analisis.','Por que debemos cuidar la fauna y flora de Colombia?','Porque son patrimonio natural del pais y muchas especies estan en peligro de extincion.',
     ['B) No es necesario. <!-- feedback: Si es necesario. -->','C) Solo las flores necesitan cuidado. <!-- feedback: Todos los seres vivos. -->','D) Los animales no necesitan proteccion. <!-- feedback: Si necesitan. -->'],
     'La biodiversidad colombiana es un tesoro que debemos proteger para las futuras generaciones.'),
    (5,5,5,0.40,'I.E. San Jose, Palmira. Evaluacion.','Que pasaria si desapareciera el condor de los Andes?','Perderiamos un simbolo nacional y se afectaria el equilibrio ecologico de las altas montanas.',
     ['B) No pasaria nada. <!-- feedback: Si afectaria. -->','C) Otro ave lo reemplazaria. <!-- feedback: No es igual. -->','D) Seria mejor. <!-- feedback: No, es una perdida. -->'],
     'Cada especie cumple una funcion en el ecosistema. Proteger la biodiversidad es proteger la vida.'),
]

Q['W33'] = [
    (1,1,1,0.78,'I.E. San Felipe, Bogota. Repaso regiones.','Cuantas regiones tiene Colombia?','Seis: Andina, Caribe, Pacifica, Orinoquia, Amazonia e Insular.',
     ['B) Cuatro. <!-- feedback: Son seis. -->','C) Cinco. <!-- feedback: Son seis. -->','D) Siete. <!-- feedback: Son seis. -->'],
     'Colombia tiene seis regiones naturales.'),
    (1,1,1,0.76,'I.E. Los Andes, Pasto. Repaso climas.','Que pisos termicos existen en Colombia?','Calido, templado y frio.',
     ['B) Solo calido. <!-- feedback: Tambien templado y frio. -->','C) Tropical, polar, desertico. <!-- feedback: Son pisos termicos colombianos. -->','D) Oceantico y continental. <!-- feedback: No. -->'],
     'Los pisos termicos en Colombia son calido, templado y frio.'),
    (2,2,2,0.74,'I.E. INEM, Medellin. Repaso fauna.','Cual es el ave nacional de Colombia?','El condor de los Andes.',
     ['B) La orquidea. <!-- feedback: Es la flor nacional. -->','C) La palma de cera. <!-- feedback: Es el arbol nacional. -->','D) El colibri. <!-- feedback: No. -->'],
     'El condor de los Andes es el ave nacional.'),
    (2,2,2,0.72,'I.E. Fe y Alegria, Cali. Repaso flora.','Cual es la flor nacional?','La orquidea Cattleya trianae.',
     ['B) El girasol. <!-- feedback: No. -->','C) La rosa. <!-- feedback: No. -->','D) El clavel. <!-- feedback: No. -->'],
     'La orquidea Cattleya trianae es la flor nacional.'),
    (3,3,3,0.64,'I.E. Tecnico, Pasto. Aplicacion.','Por que en la costa Caribe la gente usa ropa fresca?','Porque el clima es calido, las temperaturas son altas todo el ano.',
     ['B) Por moda. <!-- feedback: Es por el clima. -->','C) Porque no hay otra ropa. <!-- feedback: Es por el clima calido. -->','D) Porque les gusta el color blanco. <!-- feedback: Es por temperatura. -->'],
     'El clima calido de la costa determina el tipo de vestimenta.'),
    (3,3,3,0.60,'I.E. Simon Bolivar, Ibague. Aplicacion.','En que region estan las montanas mas altas de Colombia?','En la region Andina, donde estan las tres cordilleras y los nevados.',
     ['B) Region Caribe. <!-- feedback: Es plana. -->','C) Region Amazonia. <!-- feedback: Es selva plana. -->','D) Region Orinoquia. <!-- feedback: Llanuras. -->'],
     'Las cordilleras colombianas estan en la region Andina.'),
    (4,4,4,0.48,'I.E. Manuelita, Neiva. Analisis.','Relacion entre regiones y clima.','Cada region tiene un clima predominante segun su altura: Andina variado, Caribe calido, etc.',
     ['B) Todas tienen el mismo clima. <!-- feedback: Son diferentes. -->','C) El clima no depende de la region. <!-- feedback: Si depende. -->','D) Solo la altura importa. <!-- feedback: Altura y ubicacion. -->'],
     'Las regiones tienen climas diferentes segun su altura y ubicacion geografica.'),
    (5,5,5,0.40,'I.E. San Jose, Palmira. Evaluacion.','Que riqueza natural hemos aprendido que tiene Colombia?','Una gran biodiversidad con miles de especies de flora y fauna, y variedad de climas y regiones.',
     ['B) Ninguna. <!-- feedback: Si tiene. -->','C) Solo petroleo. <!-- feedback: Mucho mas. -->','D) Solo cafe. <!-- feedback: Mucha biodiversidad. -->'],
     'Colombia es uno de los paises mas biodiversos del mundo.'),
]

Q['W34'] = [
    (1,1,1,0.86,'I.E. San Felipe, Bogota. 20 de julio.','Que se celebra el 20 de julio en Colombia?','El Dia de la Independencia de Colombia.',
     ['B) El dia de la raza. <!-- feedback: Eso es 12 de octubre. -->','C) La Batalla de Boyaca. <!-- feedback: Eso es 7 de agosto. -->','D) El dia del trabajo. <!-- feedback: Es 1 de mayo. -->'],
     'El 20 de julio de 1810 se conmemora el grito de independencia de Colombia.'),
    (1,1,1,0.84,'I.E. Los Andes, Pasto. 7 de agosto.','Que se celebra el 7 de agosto en Colombia?','La Batalla de Boyaca, que sello la independencia.',
     ['B) El descubrimiento de America. <!-- feedback: 12 de octubre. -->','C) La independencia de Cartagena. <!-- feedback: 11 de noviembre. -->','D) El dia del idioma. <!-- feedback: 23 de abril. -->'],
     'El 7 de agosto de 1819, el ejercito patriota vencio al espanol en el Puente de Boyaca.'),
    (2,2,2,0.76,'I.E. INEM, Medellin. Importancia 20 julio.','Por que el 20 de julio es una fecha importante?','Porque marco el inicio del proceso de independencia de Colombia.',
     ['B) Porque se fundo Bogota. <!-- feedback: No. -->','C) Porque nacio Simon Bolivar. <!-- feedback: 24 de julio. -->','D) Porque termino la independencia. <!-- feedback: Inicio. -->'],
     'El 20 de julio de 1810 fue el primer paso hacia la libertad de Colombia.'),
    (2,2,2,0.73,'I.E. Fe y Alegria, Cali. Batalla Boyaca.','Quien lidero la Batalla de Boyaca?','Simon Bolivar, el Libertador.',
     ['B) Cristobal Colon. <!-- feedback: No. -->','C) Francisco de Paula Santander. <!-- feedback: Fue su general. -->','D) Antonio Narino. <!-- feedback: Precursor. -->'],
     'Simon Bolivar lidero el ejercito patriota en la Batalla de Boyaca, ayudado por Santander.'),
    (3,3,3,0.65,'I.E. Tecnico, Ibague. Aplicacion.','En el colegio, el 20 de julio se iza la bandera y se canta el himno. Esto es:','Un acto civico para conmemorar la independencia de Colombia.',
     ['B) Una celebracion cualquiera. <!-- feedback: Es un acto patriotico. -->','C) Una actividad deportiva. <!-- feedback: No. -->','D) Un dia de vacaciones. <!-- feedback: Es conmemorativo. -->'],
     'Los actos civicos del 20 de julio honran la memoria de los heroes de la independencia.'),
    (3,3,3,0.62,'I.E. Simon Bolivar, Tunja. Aplicacion.','Donde se libro la Batalla de Boyaca?','En el Puente de Boyaca, cerca de Tunja.',
     ['B) En Bogota. <!-- feedback: No. -->','C) En Cartagena. <!-- feedback: No. -->','D) En Medellin. <!-- feedback: No. -->'],
     'El Puente de Boyaca, en el departamento de Boyaca, es el lugar de la batalla decisiva.'),
    (4,4,4,0.48,'I.E. Manuelita, Neiva. Analisis.','Por que la independencia fue importante para Colombia?','Porque nos liberamos del dominio espanol y comenzamos a ser un pais libre.',
     ['B) Porque cambio el nombre del pais. <!-- feedback: Fue por la libertad. -->','C) Porque se fueron todos los espanoles. <!-- feedback: Proceso gradual. -->','D) Porque llego la tecnologia. <!-- feedback: Fue por libertad. -->'],
     'La independencia permitio a Colombia gobernarse a si misma.'),
    (5,5,5,0.40,'I.E. San Jose, Palmira. Evaluacion.','Que significa ser un pais independiente?','Que podemos tomar nuestras propias decisiones sin que otro pais nos gobierne.',
     ['B) Que no necesitamos a nadie. <!-- feedback: No es aislamiento. -->','C) Que somos los mejores. <!-- feedback: Es autogobierno. -->','D) Que no hay gobierno. <!-- feedback: Tenemos gobierno propio. -->'],
     'La independencia significa autodeterminacion y soberania.'),
]

Q['W35'] = [
    (1,1,1,0.86,'I.E. San Felipe, Bogota. 12 octubre.','Que se conmemora el 12 de octubre?','La llegada de Cristobal Colon a America en 1492.',
     ['B) La independencia de Colombia. <!-- feedback: 20 de julio. -->','C) La Batalla de Boyaca. <!-- feedback: 7 de agosto. -->','D) El descubrimiento del fuego. <!-- feedback: No. -->'],
     'El 12 de octubre de 1492, Colon llego a America, iniciando el encuentro entre dos mundos.'),
    (1,1,1,0.84,'I.E. Los Andes, Pasto. Diversidad cultural.','Que representa el 12 de octubre hoy en dia?','El encuentro de culturas: europea, indigena y africana.',
     ['B) Solo la cultura espanola. <!-- feedback: Es encuentro de varias. -->','C) Solo la cultura indigena. <!-- feedback: Varias culturas. -->','D) Una derrota. <!-- feedback: Es encuentro cultural. -->'],
     'Actualmente el 12 de octubre se reconoce como el Dia de la Diversidad Cultural.'),
    (2,2,2,0.76,'I.E. INEM, Medellin. Independencias.','Que paises se independizaron de Espana en America?','Colombia, Venezuela, Ecuador, Peru, Bolivia, Argentina, entre otros.',
     ['B) Solo Colombia. <!-- feedback: Muchos paises. -->','C) Estados Unidos. <!-- feedback: Se independizo de Inglaterra. -->','D) Brasil. <!-- feedback: Se independizo de Portugal. -->'],
     'Varios paises sudamericanos se independizaron de Espana entre 1810 y 1825.'),
    (2,2,2,0.73,'I.E. Fe y Alegria, Cali. Simon Bolivar.','Que papel tuvo Simon Bolivar en las independencias?','Liberto a Colombia, Venezuela, Ecuador, Peru y Bolivia del dominio espanol.',
     ['B) Solo liberto Colombia. <!-- feedback: Liberto varios paises. -->','C) No participo. <!-- feedback: Fue protagonista. -->','D) Ayudo a los espanoles. <!-- feedback: No. -->'],
     'Simon Bolivar es conocido como el Libertador de cinco naciones sudamericanas.'),
    (3,3,3,0.65,'I.E. Tecnico, Ibague. Aplicacion.','En muchos paises, el 12 de octubre es feriado. Por que?','Para recordar el encuentro de culturas y reflexionar sobre nuestra historia.',
     ['B) Para descansar nomas. <!-- feedback: Tiene significado historico. -->','C) Para celebrar la conquista. <!-- feedback: Es encuentro cultural. -->','D) Porque no hay clases. <!-- feedback: Tiene proposito conmemorativo. -->'],
     'El 12 de octubre es una fecha para reflexionar sobre la diversidad cultural de America.'),
    (3,3,3,0.62,'I.E. Simon Bolivar, Cucuta. Aplicacion.','Por que Cucuta es importante en la historia de independencia?','Porque ahi se creo la Gran Colombia y nacio Simon Bolivar (en Caracas, pero Cucuta fue clave).',
     ['B) No tiene importancia. <!-- feedback: Si tiene. -->','C) Solo comercio. <!-- feedback: Historia independentista. -->','D) Solo hoy. <!-- feedback: Historia. -->'],
     'Cucuta fue sede del Congreso de Cucuta en 1821 que creo la Gran Colombia.'),
    (4,4,4,0.48,'I.E. Manuelita, Neiva. Analisis.','Por que el 12 de octubre es una fecha controversial?','Porque unos lo ven como descubrimiento y otros como invasion y sufrimiento indigena.',
     ['B) No es controversial. <!-- feedback: Si es debatido. -->','C) Todos lo celebran igual. <!-- feedback: Diferentes perspectivas. -->','D) Solo los indigenas se quejan. <!-- feedback: Varias posturas. -->'],
     'El 12 de octubre genera debate: unos celebran el encuentro, otros recuerdan la violencia colonial.'),
    (5,5,5,0.40,'I.E. San Jose, Palmira. Evaluacion.','Que podemos aprender del 12 de octubre hoy?','A valorar la diversidad cultural y respetar a los pueblos indigenas y afrodescendientes.',
     ['B) Que los europeos eran superiores. <!-- feedback: No. -->','C) Que la conquista fue buena. <!-- feedback: Perspectiva compleja. -->','D) Que los indigenas no importan. <!-- feedback: Si importan. -->'],
     'El 12 de octubre nos invita a celebrar la diversidad cultural de America.'),
]

Q['W36'] = [
    (1,1,1,0.88,'I.E. San Felipe, Bogota. Tipos de familia.','Cuales son algunos tipos de familia?','Nuclear (papa, mama e hijos), extensa (abuelos, tios) y monoparental (un solo padre).',
     ['B) Solo la familia nuclear. <!-- feedback: Hay varios tipos. -->','C) Familia de dos personas. <!-- feedback: Hay mas. -->','D) Solo padres y abuelos. <!-- feedback: Varios tipos. -->'],
     'Existen diferentes tipos de familia: nuclear, extensa, monoparental, ensamblada, entre otras.'),
    (1,1,1,0.86,'I.E. Los Andes, Pasto. Funcion familia.','Cual es la funcion principal de la familia?','Proteger, educar y dar amor a sus miembros, especialmente a los ninos.',
     ['B) Solo dar dinero. <!-- feedback: Es mas que eso. -->','C) Solo alimentar. <!-- feedback: Educa y protege. -->','D) Solo castigar. <!-- feedback: No. -->'],
     'La familia es el primer nucleo de socializacion, donde se aprenden valores y se recibe proteccion.'),
    (2,2,2,0.76,'I.E. INEM, Medellin. Valores familiares.','Que valores se aprenden en la familia?','Respeto, responsabilidad, solidaridad, honestidad y amor.',
     ['B) Solo a trabajar. <!-- feedback: Valores humanos. -->','C) Solo a estudiar. <!-- feedback: Valores eticos. -->','D) Solo a cocinar. <!-- feedback: Valores fundamentales. -->'],
     'En la familia se aprenden los valores fundamentales para la convivencia en sociedad.'),
    (2,2,2,0.73,'I.E. Fe y Alegria, Cali. Familia extensa.','Que es una familia extensa?','La que incluye padres, hijos, abuelos, tios y primos viviendo juntos o cerca.',
     ['B) Solo padres e hijos. <!-- feedback: Esa es nuclear. -->','C) Solo abuelos. <!-- feedback: Incluye mas. -->','D) Una sola persona. <!-- feedback: No. -->'],
     'La familia extensa incluye a varios parientes que conviven o colaboran estrechamente.'),
    (3,3,3,0.65,'I.E. Tecnico, Ibague. Aplicacion.','Maria vive con su mama y su abuela. Su papa vive en otra ciudad. Que tipo de familia tiene?','Familia monoparental (vive solo con la mama) con apoyo de la abuela.',
     ['B) Nuclear. <!-- feedback: Le falta el papa en casa. -->','C) Extensa sin nucleo. <!-- feedback: Es monoparental con abuela. -->','D) No es familia. <!-- feedback: Si es familia. -->'],
     'Las familias monoparentales son aquellas donde los hijos viven con un solo progenitor.'),
    (3,3,3,0.62,'I.E. Simon Bolivar, Sincelejo. Aplicacion.','Los abuelos de Pedro viven con su familia. Todos se ayudan. Que tipo es?','Familia extensa, donde varias generaciones conviven.',
     ['B) Nuclear. <!-- feedback: Incluye abuelos. -->','C) Monoparental. <!-- feedback: Ambos padres presentes. -->','D) No es familia. <!-- feedback: Si es. -->'],
     'Cuando abuelos, padres e hijos viven juntos, se forma una familia extensa.'),
    (4,4,4,0.48,'I.E. Manuelita, Neiva. Analisis.','Por que la familia es importante para la sociedad?','Porque forma a las personas en valores y prepara a los ciudadanos del futuro.',
     ['B) No es importante. <!-- feedback: Si es fundamental. -->','C) Solo es importante para los ninos. <!-- feedback: Para toda la sociedad. -->','D) Es solo un grupo de personas. <!-- feedback: Es el nucleo social. -->'],
     'La familia es la base de la sociedad. De ella surgen ciudadanos responsables.'),
    (5,5,5,0.40,'I.E. San Jose, Palmira. Evaluacion.','Todas las familias son iguales?','No, hay diferentes tipos de familia, pero todas cumplen la funcion de cuidar y educar.',
     ['B) Si, todas son iguales. <!-- feedback: Hay diversidad. -->','C) Solo las nucleares son familia. <!-- feedback: Todos los tipos. -->','D) No importa. <!-- feedback: Si importa. -->'],
     'La diversidad familiar es normal. Lo importante es que haya amor y respeto.'),
]

print("W31-W36 added")
'''
with open(os.path.join(DIR, 'gen_all.py'), 'w', encoding='utf-8') as f:
    f.write(parts[0] + chunk + '\n' + marker + parts[1])
print("Appended W31-W36 successfully")
