#!/usr/bin/env python3
"""
Build _questions_data_full.json for Grades 3, 5, 6.
Creates complete question data for ALL bundles.
"""
import json, os

Q = {}

# ═══════════════════════════════════════════════════
# GRADE 3
# ═══════════════════════════════════════════════════

# --- G3 Lengua P1 (already in part1) ---
# Add more grades here

# G3 - Ciencias Naturales P1 - Los Sentidos
Q["3_ciencias-naturales_P1"] = [
    {"c":"En la clase de ciencias en Bogot\u00e1, la profesora explica los \u00f3rganos de los sentidos.","e":"\u00bfCon qu\u00e9 sentido percibimos los olores?","opts":[["A","Vista","Incorrecto. La vista percibe im\u00e1genes y colores."],["B","O\u00eddo","Incorrecto. El o\u00eddo percibe sonidos."],["C","Olfato","Correcto. El olfato nos permite percibir olores a trav\u00e9s de la nariz."],["D","Gusto","Incorrecto. El gusto percibe sabores en la lengua."]],"a":"C","fb":"El sentido del olfato se localiza en la nariz y nos permite detectar y distinguir diferentes olores."},
    {"c":"En Medell\u00edn, los estudiantes tocan diferentes texturas en clase.","e":"\u00bfQu\u00e9 sentido nos permite saber si algo es suave o \u00e1spero?","opts":[["A","Gusto","Incorrecto. El gusto detecta sabores."],["B","Tacto","Correcto. El tacto nos permite percibir texturas, temperatura y presi\u00f3n."],["C","Vista","Incorrecto. La vista solo ve, no siente texturas."],["D","Olfato","Incorrecto. El olfato percibe olores."]],"a":"B","fb":"El sentido del tacto est\u00e1 distribuido por toda la piel y nos permite sentir texturas, temperatura y presi\u00f3n."},
    {"c":"En Cali, identifican \u00f3rganos de los sentidos.","e":"\u00bfCu\u00e1l es el \u00f3rgano del sentido del gusto?","opts":[["A","La nariz","Incorrecto. La nariz es el \u00f3rgano del olfato."],["B","Los ojos","Incorrecto. Los ojos son el \u00f3rgano de la vista."],["C","La lengua","Correcto. La lengua contiene las papilas gustativas que detectan sabores."],["D","Los o\u00eddos","Incorrecto. Los o\u00eddos son el \u00f3rgano de la audici\u00f3n."]],"a":"C","fb":"La lengua tiene papilas gustativas que detectan los sabores b\u00e1sicos: dulce, salado, \u00e1cido y amargo."},
    {"c":"En Barranquilla, los ni\u00f1os aprenden sobre la protecci\u00f3n de los sentidos.","e":"\u00bfC\u00f3mo debemos proteger nuestros o\u00eddos?","opts":[["A","Escuchando m\u00fasica muy fuerte","Incorrecto. El volumen alto da\u00f1a el o\u00eddo."],["B","No limpi\u00e1ndolos nunca","Incorrecto. La higiene es importante."],["C","Evitando ruidos muy fuertes y limpi\u00e1ndolos con cuidado","Correcto. Protegemos el o\u00eddo evitando ruidos extremos y con higiene adecuada."],["D","Tap\u00e1ndolos todo el d\u00eda","Incorrecto. Necesitamos escuchar para comunicarnos."]],"a":"C","fb":"Cuidar nuestros sentidos es importante. Para proteger el o\u00eddo debemos evitar ruidos muy fuertes y mantener una higiene adecuada."},
    {"c":"En Bucaramanga, experimentan con los sentidos.","e":"Si cerramos los ojos y tocamos un objeto, \u00bfqu\u00e9 sentidos estamos usando?","opts":[["A","Solo la vista","Incorrecto. Con los ojos cerrados no usamos la vista."],["B","El tacto y quiz\u00e1s el o\u00eddo","Correcto. Usamos el tacto para sentir la textura y quiz\u00e1s el o\u00eddo si el objeto hace ruido."],["C","Solo el gusto","Incorrecto. No estamos probando el objeto."],["D","El olfato solamente","Incorrecto. No necesitamos oler para identificar la textura."]],"a":"B","fb":"A menudo usamos varios sentidos al mismo tiempo para obtener informaci\u00f3n completa sobre nuestro entorno."},
    {"c":"En Cartagena, identifican sabores en clase de ciencias.","e":"\u00bfQu\u00e9 sabor detectamos con la punta de la lengua?","opts":[["A","Amargo","Incorrecto. El amargo se percibe m\u00e1s en la parte posterior."],["B","Dulce","Correcto. El sabor dulce se detecta principalmente en la punta de la lengua."],["C","Salado","Incorrecto. El salado se percibe en los bordes frontales."],["D","\u00c1cido","Incorrecto. El \u00e1cido se percibe en los bordes laterales."]],"a":"B","fb":"Las papilas gustativas est\u00e1n distribuidas en diferentes zonas de la lengua, cada una especializada en ciertos sabores."},
    {"c":"En Pereira, los estudiantes dibujan los \u00f3rganos de los sentidos.","e":"\u00bfCu\u00e1ntos sentidos tenemos los seres humanos?","opts":[["A","3","Incorrecto. Tenemos m\u00e1s de 3 sentidos."],["B","4","Incorrecto. Adem\u00e1s de los 4 mencionados, tenemos el tacto."],["C","5","Correcto. Tenemos 5 sentidos: vista, o\u00eddo, tacto, gusto y olfato."],["D","7","Incorrecto. Tradicionalmente reconocemos 5 sentidos principales."]],"a":"C","fb":"Los cinco sentidos cl\u00e1sicos son: vista (ojos), o\u00eddo (orejas), tacto (piel), gusto (lengua) y olfato (nariz)."},
    {"c":"En Manizales, aprenden la importancia de cada sentido.","e":"\u00bfQu\u00e9 sentido es m\u00e1s importante para cruzar una calle de forma segura?","opts":[["A","El gusto","Incorrecto. Probar no ayuda a cruzar la calle."],["B","El olfato","Incorrecto. Oler no es suficiente para cruzar."],["C","La vista y el o\u00eddo","Correcto. Necesitamos ver los carros y escuchar las bocinas o motores."],["D","El tacto","Incorrecto. Tocar no es seguro ni \u00fatil para cruzar."]],"a":"C","fb":"Para cruzar una calle de forma segura usamos principalmente la vista (ver veh\u00edculos) y el o\u00eddo (escuchar aproximaciones)."},
    {"c":"En C\u00facuta, hablan sobre la higiene de los sentidos.","e":"\u00bfPor qu\u00e9 es importante lavarse las manos antes de comer?","opts":[["A","Para no ensuciar la mesa","Incorrecto. Es por otra raz\u00f3n."],["B","Para proteger el sentido del tacto y evitar enfermedades","Correcto. Las manos limpias evitan que g\u00e9rmenes lleguen a la boca y al cuerpo."],["C","Para no manchar la comida","Incorrecto. La raz\u00f3n principal es la salud."],["D","Para que la comida sepa mejor","Incorrecto. El lavado de manos no cambia el sabor."]],"a":"B","fb":"Lavarse las manos antes de comer protege nuestra salud al evitar que g\u00e9rmenes entren a nuestro cuerpo a trav\u00e9s de la boca."},
    {"c":"En Ibagu\u00e9, juegan a adivinar objetos con los sentidos.","e":"Si te vendan los ojos y te dan a probar lim\u00f3n, \u00bfqu\u00e9 sabor percibes?","opts":[["A","Dulce","Incorrecto. El lim\u00f3n no es dulce."],["B","Salado","Incorrecto. El lim\u00f3n no es salado."],["C","\u00c1cido","Correcto. El lim\u00f3n tiene sabor \u00e1cido debido al \u00e1cido c\u00edtrico."],["D","Amargo","Incorrecto. El lim\u00f3n es \u00e1cido, no amargo."]],"a":"C","fb":"El lim\u00f3n contiene \u00e1cido c\u00edtrico, que es detectado por las papilas gustativas en los bordes de la lengua como sabor \u00e1cido."},
]

# G3 - Ciencias Naturales P2 - Plantas y Animales
Q["3_ciencias-naturales_P2"] = [
    {"c":"En el jard\u00edn del colegio en Bogot\u00e1, los estudiantes observan las plantas.","e":"\u00bfQu\u00e9 parte de la planta se encarga de absorber agua y minerales del suelo?","opts":[["A","Las hojas","Incorrecto. Las hojas hacen la fotos\u00edntesis."],["B","El tallo","Incorrecto. El tallo transporta agua pero no la absorbe."],["C","Las ra\u00edces","Correcto. Las ra\u00edces absorben agua y minerales del suelo."],["D","Las flores","Incorrecto. Las flores son para la reproducci\u00f3n."]],"a":"C","fb":"Las ra\u00edces son la parte de la planta que crece bajo tierra y absorbe el agua y los nutrientes minerales del suelo."},
    {"c":"En Medell\u00edn, clasifican animales seg\u00fan su alimentaci\u00f3n.","e":"\u00bfC\u00f3mo se llaman los animales que solo comen plantas?","opts":[["A","Carn\u00edvoros","Incorrecto. Los carn\u00edvoros comen carne."],["B","Omn\u00edvoros","Incorrecto. Los omnn\u00edvoros comen de todo."],["C","Herb\u00edvoros","Correcto. Los herb\u00edvoros se alimentan solo de plantas."],["D","Insect\u00edvoros","Incorrecto. Los insect\u00edvoros comen insectos."]],"a":"C","fb":"Los animales herb\u00edvoros como vacas, caballos y conejos se alimentan exclusivamente de plantas, hojas, frutas o semillas."},
    {"c":"En Cali, aprenden sobre el ciclo de vida de las plantas.","e":"\u00bfQu\u00e9 necesita una semilla para germinar?","opts":[["A","Solo luz solar","Incorrecto. Adem\u00e1s necesita agua."],["B","Agua, aire y temperatura adecuada","Correcto. La semilla necesita agua, ox\u00edgeno y temperatura apropiada para germinar."],["C","Solo tierra","Incorrecto. La tierra sola no es suficiente."],["D","Arena y piedras","Incorrecto. La arena y piedras no tienen los nutrientes necesarios."]],"a":"B","fb":"Para que una semilla germine necesita condiciones adecuadas de humedad (agua), ox\u00edgeno (aire) y temperatura."},
    {"c":"En Barranquilla, observan animales de la regi\u00f3n Caribe.","e":"\u00bfCu\u00e1l de estos animales vive en el mar?","opts":[["A","Cebra","Incorrecto. La cebra vive en la sabana africana."],["B","Delf\u00edn","Correcto. El delf\u00edn vive en el mar."],["C","Oso","Incorrecto. El oso vive en bosques y monta\u00f1as."],["D","Conejo","Incorrecto. El conejo vive en madrigueras en la tierra."]],"a":"B","fb":"Los delfines son mam\u00edferos marinos que viven en oc\u00e9anos y mares de todo el mundo, incluyendo el mar Caribe colombiano."},
    {"c":"En Bucaramanga, estudian las partes de una flor.","e":"\u00bfCu\u00e1l es la funci\u00f3n de las flores en las plantas?","opts":[["A","Absorber agua","Incorrecto. Las ra\u00edces absorben agua."],["B","Hacer la fotos\u00edntesis","Incorrecto. Las hojas hacen fotos\u00edntesis."],["C","Reproducci\u00f3n","Correcto. Las flores son los \u00f3rganos reproductores de las plantas."],["D","Sostener la planta","Incorrecto. El tallo sostiene la planta."]],"a":"C","fb":"Las flores contienen los \u00f3rganos reproductores de la planta y dan origen a los frutos y las semillas."},
    {"c":"En Cartagena, clasifican animales dom\u00e9sticos y salvajes.","e":"\u00bfCu\u00e1l de estos es un animal DOM\u00c9STICO?","opts":[["A","Le\u00f3n","Incorrecto. El le\u00f3n es un animal salvaje."],["B","Tigre","Incorrecto. El tigre vive en libertad."],["C","Perro","Correcto. El perro es un animal dom\u00e9stico que vive con las personas."],["D","Cocodrilo","Incorrecto. El cocodrilo es salvaje y peligroso."]],"a":"C","fb":"Los animales dom\u00e9sticos como perros, gatos y gallinas han sido adaptados para vivir con los seres humanos."},
    {"c":"En Pereira, aprenden sobre la fotos\u00edntesis.","e":"\u00bfQu\u00e9 producen las plantas durante la fotos\u00edntesis?","opts":[["A","Dioxido de carbono","Incorrecto. Las plantas consumen CO2."],["B","Ox\u00edgeno","Correcto. Las plantas producen ox\u00edgeno durante la fotos\u00edntesis."],["C","Agua","Incorrecto. Las plantas consumen agua."],["D","Tierra","Incorrecto. La tierra no es producida por las plantas."]],"a":"B","fb":"Durante la fotos\u00edntesis, las plantas usan luz solar, agua y di\u00f3xido de carbono para producir su alimento y liberan ox\u00edgeno."},
    {"c":"En Manizales, identifican animales por su cubierta corporal.","e":"\u00bfQu\u00e9 cubierta corporal tienen las aves?","opts":[["A","Escamas","Incorrecto. Las escamas son de peces y reptiles."],["B","Pelos","Incorrecto. El pelo es de mam\u00edferos."],["C","Plumas","Correcto. Las aves tienen plumas que las cubren."],["D","Caparaz\u00f3n","Incorrecto. El caparaz\u00f3n es de tortugas."]],"a":"C","fb":"Las plumas son caracter\u00edsticas exclusivas de las aves y les sirven para volar, protegerse y regular su temperatura."},
    {"c":"En C\u00facuta, aprenden sobre la utilidad de las plantas.","e":"\u00bfDe d\u00f3nde obtenemos la madera para construir muebles?","opts":[["A","De las ra\u00edces","Incorrecto. Las ra\u00edces no producen madera."],["B","Del tallo o tronco de los \u00e1rboles","Correcto. La madera se obtiene del tronco de los \u00e1rboles."],["C","De las hojas","Incorrecto. Las hojas no producen madera."],["D","De las flores","Incorrecto. Las flores no producen madera."]],"a":"B","fb":"La madera proviene del tronco de los \u00e1rboles, que es el tallo le\u00f1oso que les da soporte y estructura."},
    {"c":"En Ibagu\u00e9, hablan sobre la importancia de cuidar animales y plantas.","e":"\u00bfPor qu\u00e9 es importante cuidar las plantas?","opts":[["A","Porque son bonitas","Incorrecto. Aunque son bonitas, la raz\u00f3n es m\u00e1s importante."],["B","Porque producen ox\u00edgeno y alimento","Correcto. Las plantas producen ox\u00edgeno para respirar y alimentos para comer."],["C","Porque dan sombra","Incorrecto. Dar sombra no es la raz\u00f3n principal."],["D","Porque decoran","Incorrecto. Decorar es solo un beneficio adicional."]],"a":"B","fb":"Las plantas son fundamentales para la vida porque producen el ox\u00edgeno que respiramos y son la base de la cadena alimenticia."},
]

# Save what we have so far
outpath = os.path.join(THIS, "_questions_part_g3cn.json")
with open(outpath, "w", encoding="utf-8") as f:
    json.dump(Q, f, ensure_ascii=False, indent=2)
print(f"Saved {len(Q)} question sets to {outpath}")
