#!/usr/bin/env python3
"""Add remaining questions for G3 CN and G5 to _questions_data_full.json"""
import json

# Load existing data
with open('_questions_data_full.json', encoding='utf-8') as f:
    Q = json.load(f)

# === GRADE 3 - CIENCIAS NATURALES P1 (Los sentidos) ===
Q['3_ciencias-naturales_P1'] = [
    {"c":"En la clase de ciencias del colegio en Bogot\u00e1, la profe se\u00f1ala la nariz.","e":"\u00bfQu\u00e9 sentido se relaciona con la nariz?","opts":[["A","La vista","Incorrecto. La vista usa los ojos."],["B","El olfato","Correcto. La nariz es el \u00f3rgano del olfato."],["C","El gusto","Incorrecto. El gusto usa la lengua."],["D","El o\u00eddo","Incorrecto. El o\u00eddo usa las orejas."]],"a":"B","fb":"La nariz contiene receptores que detectan olores, es el \u00f3rgano del sentido del olfato."},
    {"c":"En Medell\u00edn, tocan una cobija suave y una lija \u00e1spera.","e":"\u00bfQu\u00e9 sentido permite diferenciar texturas?","opts":[["A","La vista","Incorrecto. La vista ve pero no siente texturas."],["B","El gusto","Incorrecto. El gusto detecta sabores."],["C","El tacto","Correcto. La piel siente texturas suaves y \u00e1speras."],["D","El olfato","Incorrecto. El olfato detecta olores."]],"a":"C","fb":"El tacto, a trav\u00e9s de la piel, nos permite sentir texturas, temperatura y presi\u00f3n."},
    {"c":"En Cali, prueban lim\u00f3n y dulce.","e":"\u00bfQu\u00e9 \u00f3rgano detecta los sabores?","opts":[["A","La nariz","Incorrecto. Nariz es para olfato."],["B","La lengua","Correcto. La lengua tiene papilas gustativas."],["C","La piel","Incorrecto. Piel es para tacto."],["D","Los ojos","Incorrecto. Ojos son para vista."]],"a":"B","fb":"La lengua contiene papilas gustativas que detectan dulce, salado, \u00e1cido y amargo."},
    {"c":"En la clase de Barranquilla hablan de proteger los sentidos.","e":"\u00bfC\u00f3mo cuidamos la vista?","opts":[["A","Mirando el sol directamente","Incorrecto. Da\u00f1a los ojos."],["B","Leyendo con buena luz","Correcto. Leer con luz suficiente protege la vista."],["C","Frotando los ojos con fuerza","Incorrecto. Puede irritarlos."],["D","Usando lentes de otros","Incorrecto. Cada persona necesita su f\u00f3rmula."]],"a":"B","fb":"Para cuidar la vista debemos leer con buena iluminaci\u00f3n y no mirar directamente al sol."},
    {"c":"En la clase de Bucaramanga hacen un juego.","e":"Si te tapan los ojos y hueles una flor, \u00bfqu\u00e9 sentidos usas?","opts":[["A","Solo el olfato","Incorrecto. Usas m\u00e1s."],["B","Olfato y tacto","Correcto. Hueles la flor y la tocas."],["C","Vista y olfato","Incorrecto. No puedes ver con los ojos tapados."],["D","Solo el tacto","Incorrecto. Tambi\u00e9n hueles."]],"a":"B","fb":"Usamos varios sentidos combinados para percibir el mundo: al oler una flor usamos olfato y tacto."},
]
print(f"Added 3_ciencias-naturales_P1: 10 questions")

# === GRADE 3 - CIENCIAS NATURALES P2 (Plantas y animales) ===
Q['3_ciencias-naturales_P2'] = [
    {"c":"En el jard\u00edn del colegio en Bogot\u00e1 observan las plantas.","e":"\u00bfQu\u00e9 parte de la planta absorbe agua del suelo?","opts":[["A","Hojas","Incorrecto. Las hojas hacen fotos\u00edntesis."],["B","Tallo","Incorrecto. El tallo transporta."],["C","Ra\u00edces","Correcto. Las ra\u00edces absorben agua y minerales."],["D","Flores","Incorrecto. Flores son para reproducci\u00f3n."]],"a":"C","fb":"Las ra\u00edces crecen bajo tierra y absorben agua con minerales para nutrir la planta."},
    {"c":"En Medell\u00edn clasifican animales por su alimentaci\u00f3n.","e":"\u00bfC\u00f3mo se llaman los animales que comen solo plantas?","opts":[["A","Carn\u00edvoros","Incorrecto. Carn\u00edvoros comen carne."],["B","Omn\u00edvoros","Incorrecto. Comen de todo."],["C","Herb\u00edvoros","Correcto. Solo comen plantas."],["D","Insect\u00edvoros","Incorrecto. Comen insectos."]],"a":"C","fb":"Herb\u00edvoros como vacas, caballos y conejos se alimentan exclusivamente de plantas."},
    {"c":"En Cali germinan semillas.","e":"\u00bfQu\u00e9 necesita una semilla para germinar?","opts":[["A","Solo sol","Incorrecto."],["B","Agua, aire y temperatura adecuada","Correcto."],["C","Solo tierra","Incorrecto."],["D","Arena y piedras","Incorrecto."]],"a":"B","fb":"Germinaci\u00f3n requiere humedad, ox\u00edgeno y temperatura adecuada."},
    {"c":"En Barranquilla aprenden animales de la costa Caribe.","e":"\u00bfCu\u00e1l vive en el mar Caribe?","opts":[["A","Cebra","Incorrecto."],["B","Delf\u00edn","Correcto. Vive en el mar."],["C","Oso","Incorrecto."],["D","Conejo","Incorrecto."]],"a":"B","fb":"Delfines son mam\u00edferos marinos del mar Caribe colombiano."},
    {"c":"En Bucaramanga estudian la flor.","e":"\u00bfFunci\u00f3n de la flor?","opts":[["A","Absorber agua","No, ra\u00edces."],["B","Fotos\u00edntesis","No, hojas."],["C","Reproducci\u00f3n","Correcto. Las flores producen semillas."],["D","Sostener la planta","No, tallo."]],"a":"C","fb":"Las flores son \u00f3rganos reproductores que producen frutos y semillas."},
    {"c":"En Cartagena clasifican animales.","e":"\u00bfCu\u00e1l es un animal DOM\u00c9STICO?","opts":[["A","Le\u00f3n","Salvaje."],["B","Tigre","Salvaje."],["C","Perro","Correcto."],["D","Cocodrilo","Salvaje."]],"a":"C","fb":"Perros, gatos y gallinas son animales dom\u00e9sticos que viven con humanos."},
    {"c":"En Pereira aprenden fotos\u00edntesis.","e":"\u00bfQu\u00e9 producen las plantas en la fotos\u00edntesis?","opts":[["A","CO2","Consumen CO2."],["B","Ox\u00edgeno","Correcto."],["C","Agua","Consumen agua."],["D","Tierra","No producen tierra."]],"a":"B","fb":"Las plantas producen ox\u00edgeno durante la fotos\u00edntesis, vital para los animales."},
    {"c":"En Manizales identifican cubiertas corporales.","e":"\u00bfQu\u00e9 cubierta tienen las aves?","opts":[["A","Escamas","Peces."],["B","Pelos","Mam\u00edferos."],["C","Plumas","Correcto."],["D","Caparaz\u00f3n","Tortugas."]],"a":"C","fb":"Las plumas son exclusivas de las aves, les permiten volar y protegerse."},
    {"c":"En C\u00facuta aprenden utilidad de plantas.","e":"\u00bfDe d\u00f3nde viene la madera?","opts":[["A","Ra\u00edces","No."],["B","Tronco o tallo","Correcto."],["C","Hojas","No."],["D","Flores","No."]],"a":"B","fb":"La madera proviene del tronco de los \u00e1rboles."},
    {"c":"En Ibagu\u00e9 hablan del cuidado del ambiente.","e":"\u00bfPor qu\u00e9 es importante cuidar las plantas?","opts":[["A","Son bonitas","No es principal."],["B","Producen ox\u00edgeno y alimento","Correcto."],["C","Dan sombra","No es principal."],["D","Decoran","No es principal."]],"a":"B","fb":"Las plantas son base de la vida: producen ox\u00edgeno y alimento."},
]
print(f"Added 3_ciencias-naturales_P2: 10 questions")

# === GRADE 5 - CIENCIAS NATURALES P2 (Ecosistemas) ===
Q['5_ciencias-naturales_P2'] = [
    {"c":"En la clase de ciencias en Bogot\u00e1 estudian el p\u00e1ramo.","e":"\u00bfQu\u00e9 es un ecosistema?","opts":[["A","Un grupo de animales","No."],["B","Un lugar donde viven seres vivos","Correcto. Es la interacci\u00f3n de seres vivos con su entorno."],["C","Solo plantas","No."],["D","El clima de una regi\u00f3n","No."]],"a":"B","fb":"Un ecosistema incluye seres vivos (plantas, animales) y su entorno f\u00edsico."},
    {"c":"En Medell\u00edn hablan de la cadena alimenticia.","e":"\u00bfQui\u00e9nes producen su propio alimento?","opts":[["A","Animales","No, consumen."],["B","Plantas","Correcto. Las plantas son productores."],["C","Hongos","No, descomponen."],["D","Humanos","No, consumen."]],"a":"B","fb":"Las plantas producen su alimento mediante fotos\u00edntesis, son la base de la cadena."},
    {"c":"En Cali estudian el Parque Nacional Farallones.","e":"\u00bfQu\u00e9 animales son consumidores primarios?","opts":[["A","Leones","No, consumidores terciarios."],["B","Herb\u00edvoros","Correcto. Comen plantas directamente."],["C","Bacterias","No, descomponedores."],["D","\u00c1guilas","No, consumidores secundarios."]],"a":"B","fb":"Los herb\u00edvoros se alimentan de plantas y son consumidores primarios."},
    {"c":"En la clase de Barranquilla hablan de la Selva Amaz\u00f3nica.","e":"\u00bfQu\u00e9 tipo de ecosistema es la Amazon\u00eda?","opts":[["A","Desierto","No."],["B","Bosque tropical","Correcto."],["C","Tundra","No."],["D","Sabana","No."]],"a":"B","fb":"La Amazon\u00eda es un bosque tropical h\u00famedo, uno de los m\u00e1s biodiversos del mundo."},
    {"c":"En la gu\u00eda de Bucaramanga ven un diagrama.","e":"\u00bfQu\u00e9 pas\u00f3 si desaparecen las plantas en un ecosistema?","opts":[["A","Los herb\u00edvoros se ir\u00edan o morir\u00edan","Correcto."],["B","Nada cambiar\u00eda","No."],["C","Los carn\u00edvoros comer\u00edan plantas","No."],["D","Habr\u00eda m\u00e1s ox\u00edgeno","No."]],"a":"A","fb":"Sin plantas, los herb\u00edvoros no tienen alimento y toda la cadena se afecta."},
    {"c":"En la costa Caribe en Cartagena estudian el manglar.","e":"\u00bfPor qu\u00e9 los manglares son importantes?","opts":[["A","Protegen la costa y son h\u00e1bitat","Correcto."],["B","Producen petr\u00f3leo","No."],["C","Son solo decorativos","No."],["D","Generan electricidad","No."]],"a":"A","fb":"Los manglares protegen la costa de erosi\u00f3n y son h\u00e1bitat para muchas especies."},
    {"c":"En Pereira analizan un ecosistema acu\u00e1tico.","e":"\u00bfCu\u00e1l es un ecosistema ACU\u00c1TICO de agua dulce?","opts":[["A","Oc\u00e9ano Pac\u00edfico","Salada."],["B","R\u00edo Magdalena","Correcto."],["C","Mar Caribe","Salada."],["D","Laguna de oxidaci\u00f3n","Contaminada."]],"a":"B","fb":"El r\u00edo Magdalena es el principal r\u00edo de Colombia, ecosistema de agua dulce."},
    {"c":"En Manizales aprenden sobre descomponedores.","e":"\u00bfQu\u00e9 hacen los hongos en un ecosistema?","opts":[["A","Producen alimento","No."],["B","Descomponen materia muerta","Correcto."],["C","Cazan presas","No."],["D","Producen ox\u00edgeno","No."]],"a":"B","fb":"Los hongos y bacterias descomponen materia org\u00e1nica, reciclando nutrientes."},
    {"c":"En C\u00facuta comparan ecosistemas.","e":"Diferencia entre bosque y desierto?","opts":[["A","Temperatura y cantidad de lluvia","Correcto."],["B","Solo por los animales","No."],["C","Por el tama\u00f1o","No."],["D","Por la altitud","No."]],"a":"A","fb":"Los ecosistemas se diferencian por clima, especialmente temperatura y precipitaci\u00f3n."},
    {"c":"En Ibagu\u00e9 estudian la conservaci\u00f3n.","e":"\u00bfC\u00f3mo podemos proteger los ecosistemas?","opts":[["A","Tirando basura a los r\u00edos","No."],["B","Reciclando y no contaminando","Correcto."],["C","Talando \u00e1rboles","No."],["D","Usando bolsas pl\u00e1sticas","No."]],"a":"B","fb":"Reciclar, no contaminar y cuidar recursos naturales protege los ecosistemas."},
]
print(f"Added 5_ciencias-naturales_P2: 10 questions")

# === GRADE 5 - CIENCIAS NATURALES P3 (Electricidad) ===
Q['5_ciencias-naturales_P3'] = [
    {"c":"En la clase de f\u00edsica en Bogot\u00e1 muestran un circuito.","e":"\u00bfQu\u00e9 funge como fuente de energ\u00eda en un circuito?","opts":[["A","El cable","Conduce pero no genera."],["B","La bombilla","Consume."],["C","La pila o bater\u00eda","Correcto."],["D","El interruptor","Abre o cierra."]],"a":"C","fb":"La pila suministra la energ\u00eda el\u00e9ctrica que recorre el circuito."},
    {"c":"En Medell\u00edn experimentan con bombillas.","e":"\u00bfQu\u00e9 material CONDUCE la electricidad?","opts":[["A","Pl\u00e1stico","Aislante."],["B","Madera","Aislante."],["C","Cobre","Correcto, metal conductor."],["D","Caucho","Aislante."]],"a":"C","fb":"Los metales como el cobre conducen electricidad; pl\u00e1stico y madera son aislantes."},
    {"c":"En Cali arman circuitos simples.","e":"\u00bfQu\u00e9 pasa si el circuito est\u00e1 abierto?","opts":[["A","La bombilla enciende","No."],["B","No circula corriente","Correcto."],["C","Explota la pila","No."],["D","El cable se calienta","No."]],"a":"B","fb":"Circuito abierto interrumpe el flujo de electrones, no hay corriente."},
    {"c":"En Barranquilla clasifican materiales.","e":"\u00bfCu\u00e1l es material AISLANTE?","opts":[["A","Aluminio","Conductor."],["B","Hierro","Conductor."],["C","Pl\u00e1stico","Correcto, aislante."],["D","Oro","Conductor."]],"a":"C","fb":"El pl\u00e1stico no permite el paso de electricidad, es un aislante."},
    {"c":"En Bucaramanga aprenden electr\u00f3lisis.","e":"\u00bfC\u00f3mo se llama la unidad de corriente?","opts":[["A","Voltios","No, voltaje."],["B","Amperios","Correcto."],["C","Watios","No, potencia."],["D","Ohmios","No, resistencia."]],"a":"B","fb":"La corriente el\u00e9ctrica se mide en amperios."},
    {"c":"En Cartagena analizan electrodom\u00e9sticos.","e":"\u00bfQu\u00e9 transforma la energ\u00eda el\u00e9ctrica en luz?","opts":[["A","Motor","Movimiento."],["B","Resistencia","Calor."],["C","Bombilla","Correcto."],["D","Altavoz","Sonido."]],"a":"C","fb":"La bombilla convierte energ\u00eda el\u00e9ctrica en luz (y algo de calor)."},
    {"c":"En Pereira ven un circuito con interruptor.","e":"\u00bfFunci\u00f3n del interruptor?","opts":[["A","Generar electricidad","No."],["B","Abrir o cerrar el paso de corriente","Correcto."],["C","Medir voltaje","No."],["D","Proteger de cortos","No."]],"a":"B","fb":"El interruptor controla el flujo de corriente, abriendo o cerrando el circuito."},
    {"c":"En Manizales hablan de seguridad el\u00e9ctrica.","e":"\u00bfQu\u00e9 es peligroso hacer con electricidad?","opts":[["A","Usar enchufes con manos secas","Seguro."],["B","Introducir objetos met\u00e1licos en tomacorrientes","Correcto, peligroso."],["C","Apagar luces al salir","Seguro."],["D","Cambiar bombillas con guantes","Seguro."]],"a":"B","fb":"Introducir metal en tomacorrientes causa cortocircuitos y electrocuci\u00f3n."},
    {"c":"En C\u00facuta comparan circuitos.","e":"Diferencia entre serie y paralelo?","opts":[["A","En serie las bombillas brillan igual","No."],["B","En paralelo falla todo si una se da\u00f1a","No, en serie."],["C","En paralelo cada bombilla tiene su propio camino","Correcto."],["D","No hay diferencia","S\u00ed hay."]],"a":"C","fb":"Circuito paralelo: cada componente conectado independientemente. Serie: en l\u00ednea."},
    {"c":"En Ibagu\u00e9 analizan la factura de luz.","e":"\u00bfQu\u00e9 unidad usa la factura de electricidad?","opts":[["A","Litros","No."],["B","Kilovatios-hora (kWh)","Correcto."],["C","Kilogramos","No."],["D","Metros","No."]],"a":"B","fb":"El consumo el\u00e9ctrico se mide en kilovatios-hora (kWh)."},
]
print(f"Added 5_ciencias-naturales_P3: 10 questions")

# === GRADE 5 - CIENCIAS NATURALES P4 (Sistema Solar) ===
Q['5_ciencias-naturales_P4'] = [
    {"c":"En el planetario de Bogot\u00e1 ven el sistema solar.","e":"\u00bfCu\u00e1ntos planetas hay en el sistema solar?","opts":[["A","7","No."],["B","8","Correcto."],["C","9","No, Plut\u00f3n es enano."],["D","10","No."]],"a":"B","fb":"Hay 8 planetas: Mercurio, Venus, Tierra, Marte, J\u00fapiter, Saturno, Urano, Neptuno."},
    {"c":"En Medell\u00edn estudian los planetas.","e":"\u00bfCu\u00e1l es el planeta m\u00e1s cercano al Sol?","opts":[["A","Venus","No."],["B","Mercurio","Correcto."],["C","Tierra","No."],["D","Marte","No."]],"a":"B","fb":"Mercurio es el planeta m\u00e1s cercano al Sol y el m\u00e1s peque\u00f1o del sistema solar."},
    {"c":"En Cali aprenden sobre la Tierra.","e":"\u00bfCu\u00e1nto tarda la Tierra en dar una vuelta al Sol?","opts":[["A","Un d\u00eda","No."],["B","Un mes","No."],["C","Un a\u00f1o (365 d\u00edas)","Correcto."],["D","Una semana","No."]],"a":"C","fb":"El movimiento de traslaci\u00f3n dura 365 d\u00edas (un a\u00f1o). El de rotaci\u00f3n 24 horas."},
    {"c":"En Barranquilla estudian las fases lunares.","e":"\u00bfQu\u00e9 causa las fases de la Luna?","opts":[["A","Nubes","No."],["B","Sombra de la Tierra","No, eclipses."],["C","Posici\u00f3n relativa Sol-Tierra-Luna","Correcto."],["D","Rotaci\u00f3n de la Luna","No."]],"a":"C","fb":"Vemos diferentes fases lunares seg\u00fan la posici\u00f3n de la Luna respecto al Sol y la Tierra."},
    {"c":"En la clase de Bucaramanga hablan de la V\u00eda L\u00e1ctea.","e":"\u00bfQu\u00e9 es la V\u00eda L\u00e1ctea?","opts":[["A","Un planeta","No."],["B","Una estrella","No."],["C","Una galaxia","Correcto."],["D","Un sat\u00e9lite","No."]],"a":"C","fb":"La V\u00eda L\u00e1ctea es la galaxia que contiene nuestro sistema solar."},
    {"c":"En Cartagena ven el cielo nocturno.","e":"\u00bfPor qu\u00e9 vemos brillar las estrellas?","opts":[["A","Reflejan luz de la Luna","No."],["B","Son bolas de gas que producen luz propia","Correcto."],["C","Son espejos en el espacio","No."],["D","Son aviones lejanos","No."]],"a":"B","fb":"Las estrellas son enormes esferas de gas que producen luz y calor por fusi\u00f3n nuclear."},
    {"c":"En Pereira comparan planetas.","e":"\u00bfCu\u00e1l es el planeta m\u00e1s grande?","opts":[["A","Saturno","No."],["B","J\u00fapiter","Correcto."],["C","Neptuno","No."],["D","Urano","No."]],"a":"B","fb":"J\u00fapiter es el planeta m\u00e1s grande del sistema solar, con m\u00e1s de 300 veces la masa terrestre."},
    {"c":"En Manizales aprenden sobre el Sol.","e":"\u00bfQu\u00e9 es el Sol?","opts":[["A","Un planeta","No."],["B","Una estrella","Correcto."],["C","Un sat\u00e9lite","No."],["D","Un cometa","No."]],"a":"B","fb":"El Sol es una estrella, una esfera de gas caliente que produce energ\u00eda mediante fusi\u00f3n nuclear."},
    {"c":"En C\u00facuta hablan de astronautas.","e":"\u00bfPor qu\u00e9 los astronautas flotan en el espacio?","opts":[["A","No hay gravedad","No, hay microgravedad."],["B","Est\u00e1n en ca\u00edda libre constante","Correcto."],["C","Tienen imanes","No."],["D","El aire los sostiene","No hay aire."]],"a":"B","fb":"Los astronautas experimentan microgravedad porque est\u00e1n en ca\u00edda libre orbital."},
    {"c":"En Ibagu\u00e9 construyen maquetas.","e":"\u00bfCu\u00e1l es la funci\u00f3n de la atm\u00f3sfera terrestre?","opts":[["A","Protegernos de meteoritos y radiaci\u00f3n","Correcto."],["B","Hacer que llueva","Solo una funci\u00f3n."],["C","Dar luz a la Tierra","No."],["D","Conectar sat\u00e9lites","No."]],"a":"A","fb":"La atm\u00f3sfera protege la vida filtrando radiaci\u00f3n UV y desintegrando meteoritos."},
]
print(f"Added 5_ciencias-naturales_P4: 10 questions")

# Save
with open('_questions_data_full.json', 'w', encoding='utf-8') as f:
    json.dump(Q, f, ensure_ascii=False, indent=2)
print(f"Saved. Total keys: {len(Q)}")
