#!/usr/bin/env python3
"""Add Grade 5 Social Studies and English questions to _questions_data_full.json"""
import json

with open('_questions_data_full.json', encoding='utf-8') as f:
    Q = json.load(f)

# === GRADE 5 - SOCIALES P1 (Colombia precolombina) ===
Q['5_sociales-ciudadanas_P1'] = [
    {"c":"En la clase de sociales en Bogot\u00e1 estudian los primeros pobladores.","e":"\u00bfQui\u00e9nes habitaban Am\u00e9rica antes de la llegada de los espa\u00f1oles?","opts":[["A","Los africanos","No."],["B","Los pueblos ind\u00edgenas","Correcto."],["C","Los europeos","No."],["D","Los asi\u00e1ticos","No."]],"a":"B","fb":"Pueblos ind\u00edgenas como Muiscas, Taironas y Zen\u00faes habitaban el territorio colombiano."},
    {"c":"En Medell\u00edn estudian la cultura Muisca.","e":"\u00bfD\u00f3nde viv\u00edan los Muiscas?","opts":[["A","Costa Caribe","No, Taironas."],["B","Altipiano Cundiboyacense","Correcto."],["C","Amazon\u00eda","No."],["D","Pac\u00edfico","No."]],"a":"B","fb":"Los Muiscas habitaron el altiplano Cundiboyacense (Boyac\u00e1 y Cundinamarca)."},
    {"c":"En Cali estudian la cultura Tairona.","e":"\u00bfQu\u00e9 construyeron los Taironas en la Sierra Nevada?","opts":[["A","Rascacielos","No."],["B","Ciudad Perdida o Teyuna","Correcto."],["C","Machu Picchu","Peruano."],["D","Chich\u00e9n Itz\u00e1","Mexicano."]],"a":"B","fb":"Los Taironas construyeron la Ciudad Perdida (Teyuna) en la Sierra Nevada de Santa Marta."},
    {"c":"En Barranquilla estudian los Zen\u00fa.","e":"\u00bfQu\u00e9 sistema construyeron los Zen\u00fa en la regi\u00f3n Caribe?","opts":[["A","Carreteras","No."],["B","Canales de riego","Correcto."],["C","Puentes colgantes","No."],["D","Ferrocarriles","No."]],"a":"B","fb":"Los Zen\u00fa construyeron un avanzado sistema de canales para controlar el agua en Sucre y C\u00f3rdoba."},
    {"c":"En Bucaramanga comparan culturas.","e":"\u00bfQu\u00e9 cultivaban principalmente los pueblos precolombinos?","opts":[["A","Trigo","No europeo."],["B","Ma\u00edz","Correcto."],["C","Arroz","No."],["D","Cebada","No."]],"a":"B","fb":"El ma\u00edz era el cultivo principal de la mayor\u00eda de pueblos precolombinos americanos."},
    {"c":"En Cartagena ven arte precolombino.","e":"\u00bfQu\u00e9 material usaban para hacer objetos de oro?","opts":[["A","Plomo","No."],["B","Oro","Correcto."],["C","Hierro","No."],["D","Bronce","No."]],"a":"B","fb":"Los orfebres precolombinos trabajaban el oro con t\u00e9cnicas avanzadas de fundici\u00f3n."},
    {"c":"En Pereira estudian ritos funerarios.","e":"\u00bfQu\u00e9 construyeron los hipogeos?","opts":[["A","Tumbas subterr\u00e1neas","Correcto."],["B","Templos","No."],["C","Casas","No."],["D","Puentes","No."]],"a":"A","fb":"Hipogeos son tumbas subterr\u00e1neas talladas en roca, usadas por culturas como los Tierradentro."},
    {"c":"En Manizales hablan de la organizaci\u00f3n social.","e":"\u00bfC\u00f3mo se organizaban pol\u00edticamente los Muiscas?","opts":[["A","Rey \u00fanico","No."],["B","Caciques y zipazgo","Correcto."],["C","Presidentes","No."],["D","Gobernadores","No."]],"a":"B","fb":"Los Muiscas ten\u00edan dos confederaciones: zipazgo (sur) y zacazgo (norte)."},
    {"c":"En C\u00facuta analizan cambios culturales.","e":"\u00bfQu\u00e9 trajeron los espa\u00f1oles a Am\u00e9rica?","opts":[["A","Caballos y vacas","Correcto."],["B","Ma\u00edz","Ya exist\u00eda."],["C","Papas","Ya exist\u00edan."],["D","Tomates","Ya exist\u00edan."]],"a":"A","fb":"Los espa\u00f1oles introdujeron caballos, vacas, ovejas, trigo y ca\u00f1a de az\u00facar."},
    {"c":"En Ibagu\u00e9 reflexionan sobre el legado.","e":"\u00bfQu\u00e9 legado dejaron los pueblos ind\u00edgenas?","opts":[["A","El idioma ingl\u00e9s","No."],["B","Palabras como chocolate y canoa","Correcto."],["C","La electricidad","No."],["D","El autom\u00f3vil","No."]],"a":"B","fb":"Palabras de origen ind\u00edgena: chocolate (n\u00e1huatl), canoa (ta\u00edno), papa (quechua)."},
]
print("Added 5_sociales-ciudadanas_P1")

# === GRADE 5 - SOCIALES P2 (Independencia) ===
Q['5_sociales-ciudadanas_P2'] = [
    {"c":"En la clase de historia en Bogot\u00e1 hablan del 20 de julio de 1810.","e":"\u00bfQu\u00e9 se conmemora el 20 de julio en Colombia?","opts":[["A","La independencia definitiva","No, fue el grito."],["B","El Grito de Independencia","Correcto."],["C","La muerte de Bol\u00edvar","No."],["D","La Constituci\u00f3n","No."]],"a":"B","fb":"El 20 de julio de 1810 marc\u00f3 el primer Grito de Independencia de Colombia."},
    {"c":"En Medell\u00edn estudian a Sim\u00f3n Bol\u00edvar.","e":"\u00bfPor qu\u00e9 es conocido Sim\u00f3n Bol\u00edvar?","opts":[["A","Pintor","No."],["B","Libertador de Am\u00e9rica","Correcto."],["C","Rey de Espa\u00f1a","No."],["D","Cient\u00edfico","No."]],"a":"B","fb":"Sim\u00f3n Bol\u00edvar liber\u00f3 Colombia, Venezuela, Ecuador, Per\u00fa y Bolivia del dominio espa\u00f1ol."},
    {"c":"En Cali estudian la Campa\u00f1a Libertadora.","e":"\u00bfCu\u00e1l fue la batalla decisiva para la independencia?","opts":[["A","Boyac\u00e1 (1819)","Correcto."],["B","Pichincha","No."],["C","Ayacucho","No."],["D","Pamplona","No."]],"a":"A","fb":"La Batalla de Boyac\u00e1 el 7 de agosto de 1819 sell\u00f3 la independencia de Nueva Granada."},
    {"c":"En Barranquilla hablan de Francisco de Paula Santander.","e":"\u00bfQui\u00e9n fue Santander?","opts":[["A","Rey espa\u00f1ol","No."],["B","General y presidente","Correcto."],["C","Cient\u00edfico alem\u00e1n","No."],["D","Pirata ingl\u00e9s","No."]],"a":"B","fb":"Santander fue vicepresidente de la Gran Colombia y luego presidente, llamado el 'Hombre de las Leyes'."},
    {"c":"En Bucaramanga analizan la Reconquista.","e":"\u00bfQu\u00e9 fue la Reconquista?","opts":[["A","Espa\u00f1oles recuperaron control temporal","Correcto."],["B","Los ind\u00edgenas recuperaron tierras","No."],["C","Bol\u00edvar conquist\u00f3 Espa\u00f1a","No."],["D","Colombia conquist\u00f3 Per\u00fa","No."]],"a":"A","fb":"Espa\u00f1a intent\u00f3 recuperar sus colonias (1815-1819) pero fracas\u00f3 finalmente."},
    {"c":"En Cartagena estudian el sitio de Cartagena.","e":"\u00bfQui\u00e9n siti\u00f3 Cartagena en 1815?","opts":[["A","Sim\u00f3n Bol\u00edvar","No."],["B","Pablo Morillo","Correcto."],["C","Francisco Pizarro","No."],["D","Jos\u00e9 de San Mart\u00edn","No."]],"a":"B","fb":"Pablo Morillo, 'El Pacificador', siti\u00f3 Cartagena durante 106 d\u00edas en 1815."},
    {"c":"En Pereira hablan de la Gran Colombia.","e":"\u00bfQu\u00e9 pa\u00edses formaron la Gran Colombia?","opts":[["A","Colombia, Venezuela, Ecuador, Panam\u00e1","Correcto."],["B","Colombia, Per\u00fa, Bolivia","No."],["C","Colombia, Chile, Argentina","No."],["D","Colombia, Brasil, M\u00e9xico","No."]],"a":"A","fb":"La Gran Colombia (1819-1831) incluy\u00f3 Colombia, Venezuela, Ecuador y Panam\u00e1."},
    {"c":"En Manizales analizan el Congreso de Angostura.","e":"\u00bfQu\u00e9 buscaba Bol\u00edvar en Angostura?","opts":[["A","Unidad de los pueblos liberados","Correcto."],["B","Volver a Espa\u00f1a","No."],["C","Crear una monarqu\u00eda","No."],["D","Dividir el territorio","No."]],"a":"A","fb":"Bol\u00edvar buscaba la unidad pol\u00edtica de las naciones liberadas bajo la Gran Colombia."},
    {"c":"En C\u00facuta estudian la disoluci\u00f3n.","e":"\u00bfEn qu\u00e9 a\u00f1o se disolvi\u00f3 la Gran Colombia?","opts":[["A","1825","No."],["B","1830","Correcto."],["C","1840","No."],["D","1850","No."]],"a":"B","fb":"La Gran Colombia se disolvi\u00f3 en 1830 luego de las diferencias pol\u00edticas entre Bol\u00edvar y Santander."},
    {"c":"En Ibagu\u00e9 reflexionan sobre el legado.","e":"\u00bfQu\u00e9 legado dej\u00f3 la independencia?","opts":[["A","Esclavitud","No, se aboli\u00f3."],["B","Rep\u00fablica y soberan\u00eda","Correcto."],["C","Monarqu\u00eda","No."],["D","Colonias espa\u00f1olas","No."]],"a":"B","fb":"La independencia estableci\u00f3 la rep\u00fablica y la soberan\u00eda del pueblo colombiano."},
]
print("Added 5_sociales-ciudadanas_P2")

# === GRADE 5 - SOCIALES P3 (Geograf\u00eda de Colombia) ===
Q['5_sociales-ciudadanas_P3'] = [
    {"c":"En la clase de geograf\u00eda en Bogot\u00e1.","e":"\u00bfCu\u00e1les son los oc\u00e9anos que ba\u00f1an Colombia?","opts":[["A","Pac\u00edfico y \u00c1rtico","No."],["B","Pac\u00edfico y Atl\u00e1ntico (Caribe)","Correcto."],["C","Atl\u00e1ntico e \u00cdndico","No."],["D","\u00c1rtico y Ant\u00e1rtico","No."]],"a":"B","fb":"Colombia tiene costas en el oc\u00e9ano Pac\u00edfico y el mar Caribe (Atl\u00e1ntico)."},
    {"c":"En Medell\u00edn estudian las cordilleras.","e":"\u00bfCu\u00e1ntas cordilleras tiene la regi\u00f3n Andina en Colombia?","opts":[["A","Dos","No."],["B","Tres","Correcto: Occidental, Central, Oriental."],["C","Cuatro","No."],["D","Cinco","No."]],"a":"B","fb":"Los Andes se dividen en tres cordilleras en Colombia: Occidental, Central y Oriental."},
    {"c":"En Cali estudian regiones naturales.","e":"\u00bfCu\u00e1l es la capital de la regi\u00f3n Pac\u00edfica?","opts":[["A","Medell\u00edn","Andina."],["B","Bogot\u00e1","Andina."],["C","Cali","Correcto."],["D","Cartagena","Caribe."]],"a":"C","fb":"Cali es la ciudad principal de la regi\u00f3n Pac\u00edfica colombiana."},
    {"c":"En Barranquilla hablan de su regi\u00f3n.","e":"\u00bfQu\u00e9 regi\u00f3n natural es Barranquilla?","opts":[["A","Andina","No."],["B","Caribe","Correcto."],["C","Pac\u00edfica","No."],["D","Orinoqu\u00eda","No."]],"a":"B","fb":"Barranquilla se encuentra en la regi\u00f3n Caribe, a orillas del r\u00edo Magdalena."},
    {"c":"En Bucaramanga estudian el relieve.","e":"\u00bfCu\u00e1l es la monta\u00f1a m\u00e1s alta de Colombia?","opts":[["A","Nevado del Ruiz","No."],["B","Pico Crist\u00f3bal Col\u00f3n","Correcto."],["C","Volc\u00e1n Galeras","No."],["D","Sierra Nevada","No."]],"a":"B","fb":"Pico Crist\u00f3bal Col\u00f3n (5.775 m) en la Sierra Nevada de Santa Marta es la cima m\u00e1s alta."},
    {"c":"En Cartagena estudian r\u00edos.","e":"\u00bfCu\u00e1l es el r\u00edo m\u00e1s importante de Colombia?","opts":[["A","Amazonas","Compartido."],["B","Magdalena","Correcto."],["C","Cauca","No principal."],["D","Orinoco","Compartido."]],"a":"B","fb":"El r\u00edo Magdalena es el principal r\u00edo colombiano, nace en el Huila y desemboca en el Caribe."},
    {"c":"En Pereira analizan climas.","e":"\u00bfQu\u00e9 determina los pisos t\u00e9rmicos en Colombia?","opts":[["A","Latitud","No."],["B","Altitud sobre el nivel del mar","Correcto."],["C","Cercan\u00eda al mar","No."],["D","Estaci\u00f3n del a\u00f1o","No."]],"a":"B","fb":"En Colombia los pisos t\u00e9rmicos dependen de la altura: c\u00e1lido, templado, fr\u00edo y p\u00e1ramo."},
    {"c":"En Manizales hablan de p\u00e1ramos.","e":"\u00bfPor qu\u00e9 son importantes los p\u00e1ramos?","opts":[["A","Producen petr\u00f3leo","No."],["B","Son f\u00e1bricas de agua","Correcto."],["C","Tienen mucho oro","No."],["D","Son desiertos","No."]],"a":"B","fb":"Los p\u00e1ramos regulan el agua, capturando y liberando agua dulce para los r\u00edos."},
    {"c":"En C\u00facuta analizan la Amazon\u00eda colombiana.","e":"\u00bfQu\u00e9 departamentos tiene la Amazon\u00eda colombiana?","opts":[["A","Amazonas, Caquet\u00e1, Putumayo","Correcto."],["B","Antioquia, Boyac\u00e1","No."],["C","Atl\u00e1ntico, Bol\u00edvar","No."],["D","Valle, Cauca","No."]],"a":"A","fb":"La Amazon\u00eda colombiana incluye Amazonas, Caquet\u00e1, Putumayo, Guaviare, Vaup\u00e9s y Guain\u00eda."},
    {"c":"En Ibagu\u00e9 hablan de la Orinoqu\u00eda.","e":"\u00bfQu\u00e9 actividad econ\u00f3mica predomina en los Llanos Orientales?","opts":[["A","Miner\u00eda","No."],["B","Ganader\u00eda","Correcto."],["C","Pesca mar\u00edtima","No."],["D","Industria textil","No."]],"a":"B","fb":"La ganader\u00eda extensiva es la actividad principal en la Orinoqu\u00eda (Llanos Orientales)."},
]
print("Added 5_sociales-ciudadanas_P3")

# === GRADE 5 - SOCIALES P4 (Derechos ciudadanos) ===
Q['5_sociales-ciudadanas_P4'] = [
    {"c":"En la clase de \u00e9tica en Bogot\u00e1.","e":"\u00bfQu\u00e9 documento contiene los derechos fundamentales en Colombia?","opts":[["A","El manual de convivencia","No."],["B","La Constituci\u00f3n Pol\u00edtica","Correcto."],["C","El libro de matem\u00e1ticas","No."],["D","El carnet estudiantil","No."]],"a":"B","fb":"La Constituci\u00f3n Pol\u00edtica de Colombia de 1991 es la ley de leyes del pa\u00eds."},
    {"c":"En Medell\u00edn hablan de derechos del ni\u00f1o.","e":"\u00bfQu\u00e9 derecho protege la educaci\u00f3n?","opts":[["A","Derecho al trabajo","No."],["B","Derecho a la recreaci\u00f3n","No."],["C","Derecho a la educaci\u00f3n","Correcto."],["D","Derecho a la propiedad","No."]],"a":"C","fb":"Todo ni\u00f1o tiene derecho a recibir educaci\u00f3n gratuita y de calidad."},
    {"c":"En Cali estudian la Constituci\u00f3n.","e":"\u00bfEn qu\u00e9 a\u00f1o se promulg\u00f3 la actual Constituci\u00f3n de Colombia?","opts":[["A","1886","No, anterior."],["B","1991","Correcto."],["C","2000","No."],["D","1819","No."]],"a":"B","fb":"La Constituci\u00f3n de 1991 reemplaz\u00f3 la de 1886, estableciendo un Estado Social de Derecho."},
    {"c":"En Barranquilla hablan de deberes.","e":"\u00bfCu\u00e1l es un DEBER de los ni\u00f1os en Colombia?","opts":[["A","Votar","No, mayores."],["B","Pagar impuestos","No."],["C","Respetar a los dem\u00e1s","Correcto."],["D","Gobernar","No."]],"a":"C","fb":"Los ni\u00f1os deben respetar a los dem\u00e1s, cuidar el ambiente y cumplir sus responsabilidades."},
    {"c":"En la clase de Cartagena hablan de la ONU.","e":"\u00bfQu\u00e9 es la Declaraci\u00f3n Universal de Derechos Humanos?","opts":[["A","Un cuento","No."],["B","Un documento con derechos para todas las personas","Correcto."],["C","Una ley de Colombia","No, es internacional."],["D","Un himno","No."]],"a":"B","fb":"La ONU proclam\u00f3 en 1948 los derechos que toda persona tiene por el hecho de ser humana."},
    {"c":"En Pereira aplican derechos.","e":"\u00bfQu\u00e9 hacer si un compa\u00f1ero es discriminado?","opts":[["A","Ignorarlo","No."],["B","Unirse a la burla","No."],["C","Apoyarlo y reportar la situaci\u00f3n","Correcto."],["D","Alejarse","No."]],"a":"C","fb":"La dignidad humana exige respeto. Todos tenemos derecho a no ser discriminados."},
    {"c":"En Manizales analizan la igualdad.","e":"\u00bfQu\u00e9 significa igualdad ante la ley?","opts":[["A","Todos somos id\u00e9nticos","No."],["B","Todos tienen los mismos derechos sin discriminaci\u00f3n","Correcto."],["C","Solo algunos tienen derechos","No."],["D","Las leyes no aplican a todos","No."]],"a":"B","fb":"Igualdad significa que la ley se aplica igual a todas las personas, sin distinci\u00f3n."},
    {"c":"En C\u00facuta hablan de democracia.","e":"\u00bfQu\u00e9 significa democracia?","opts":[["A","Gobierno de uno","No."],["B","Gobierno del pueblo","Correcto."],["C","Gobierno de ricos","No."],["D","Gobierno militar","No."]],"a":"B","fb":"Democracia (del griego: demos=pueblo, kratos=gobierno) significa poder del pueblo."},
    {"c":"En C\u00facuta analizan el voto.","e":"\u00bfA qu\u00e9 edad se puede votar en Colombia?","opts":[["A","16 a\u00f1os","No."],["B","18 a\u00f1os","Correcto."],["C","21 a\u00f1os","No."],["D","25 a\u00f1os","No."]],"a":"B","fb":"En Colombia el sufragio es a partir de los 18 a\u00f1os, es un derecho y un deber."},
    {"c":"En Ibagu\u00e9 reflexionan sobre paz.","e":"\u00bfQu\u00e9 organismo promueve los derechos humanos en Colombia?","opts":[["A","Defensor\u00eda del Pueblo","Correcto."],["B","Ej\u00e9rcito Nacional","Solo defensa."],["C","Empresas privadas","No."],["D","Colegios","No."]],"a":"A","fb":"La Defensor\u00eda del Pueblo protege y promueve los derechos humanos en Colombia."},
]
print("Added 5_sociales-ciudadanas_P4")

with open('_questions_data_full.json', 'w', encoding='utf-8') as f:
    json.dump(Q, f, ensure_ascii=False, indent=2)
print(f"Saved. Total keys: {len(Q)}")
