#!/usr/bin/env python3
"""Build G3 Ciencias Naturales P3-P4, G3 Lengua P3-P4"""
import json, os

def append_to_data(new_data, filename="_questions_data_full.json"):
    existing = {}
    if os.path.exists(filename):
        with open(filename, "r", encoding="utf-8") as f:
            existing = json.load(f)
    existing.update(new_data)
    with open(filename, "w", encoding="utf-8") as f:
        json.dump(existing, f, ensure_ascii=False, indent=2)
    print(f"Appended {len(new_data)} sets. Total: {len(existing)}")

D = {}

# ═══════ G3 CIENCIAS NATURALES P3 - El Agua ═══════
D["3_ciencias-naturales_P3"] = [
    {"c":"En clase de ciencias en Bogot\u00e1, la profe pregunta sobre los estados del agua.","e":"\u00bfEn qu\u00e9 estado est\u00e1 el agua de un r\u00edo?","opts":[["A","S\u00f3lido","No."],["B","L\u00edquido","Correcto. El agua de r\u00edos est\u00e1 en estado l\u00edquido."],["C","Gaseoso","No."],["D","Plasma","No."]],"a":"B","fb":"El agua en los r\u00edos est\u00e1 en estado l\u00edquido, que fluye y toma la forma del recipiente."},
    {"c":"En Medell\u00edn, ponen agua a congelar en el laboratorio.","e":"\u00bfEn qu\u00e9 se convierte el agua l\u00edquida al congelarse?","opts":[["A","Vapor","No, eso es al calentar."],["B","Hielo","Correcto. El agua l\u00edquida se convierte en hielo (s\u00f3lido)."],["C","Gas","No."],["D","Nube","No."]],"a":"B","fb":"Al congelarse, el agua pasa de estado l\u00edquido a s\u00f3lido (hielo) a 0\u00b0C."},
    {"c":"En Cali, la profe hierve agua en un vaso.","e":"\u00bfQu\u00e9 pasa cuando el agua hierve?","opts":[["A","Se congela","No."],["B","Se convierte en vapor","Correcto. Se evapora."],["C","Se vuelve s\u00f3lida","No."],["D","Desaparece","No desaparece, cambia de estado."]],"a":"B","fb":"Al hervir a 100\u00b0C, el agua pasa de l\u00edquido a gaseoso (vapor)."},
    {"c":"En Barranquilla preguntan sobre el ciclo del agua.","e":"\u00bfQu\u00e9 proceso convierte el agua l\u00edquida en vapor en la naturaleza?","opts":[["A","Condensaci\u00f3n","No, eso es gas a l\u00edquido."],["B","Evaporaci\u00f3n","Correcto. El sol calienta el agua y se evapora."],["C","Solidificaci\u00f3n","No, eso es l\u00edquido a s\u00f3lido."],["D","Precipitaci\u00f3n","No, es cuando cae el agua."]],"a":"B","fb":"La evaporaci\u00f3n ocurre cuando el sol calienta el agua y se convierte en vapor."},
    {"c":"En Bucaramanga, ven las nubes en el cielo.","e":"\u00bfDe qu\u00e9 est\u00e1n formadas las nubes?","opts":[["A","Humo","No."],["B","Algod\u00f3n","No."],["C","Gotitas de agua","Correcto. Nubes = gotitas de agua condensada."],["D","Aire","No."]],"a":"C","fb":"Las nubes se forman por peque\u00f1as gotitas de agua que se condensan en la atm\u00f3sfera."},
    {"c":"En Cartagena hablan sobre el cuidado del agua.","e":"\u00bfPor qu\u00e9 debemos cerrar la llave mientras nos cepillamos?","opts":[["A","Porque hace ruido","Incorrecto."],["B","Para ahorrar agua","Correcto. Ahorramos agua potable."],["C","Porque se da\u00f1a el lava manos","Incorrecto."],["D","Porque el agua sale fr\u00eda","Incorrecto."]],"a":"B","fb":"Cerrar la llave mientras nos cepillamos ahorra litros de agua potable."},
    {"c":"En Pereira preguntan sobre la lluvia.","e":"\u00bfC\u00f3mo se llama cuando el vapor de agua en las nubes se convierte en lluvia?","opts":[["A","Evaporaci\u00f3n","No."],["B","Fusi\u00f3n","No."],["C","Precipitaci\u00f3n","Correcto. El agua cae como lluvia."],["D","Congelaci\u00f3n","No."]],"a":"C","fb":"La precipitaci\u00f3n ocurre cuando el agua condensada en las nubes cae a la tierra como lluvia, nieve o granizo."},
    {"c":"En Manizales experimentan con el vapor.","e":"Si dejamos un vaso de agua al sol por horas, \u00bfqu\u00e9 pasa?","opts":[["A","El agua se vuelve m\u00e1s fr\u00eda","No."],["B","Se llena m\u00e1s","No."],["C","El nivel de agua baja","Correcto. Se evapora."],["D","El agua se vuelve s\u00f3lida","No."]],"a":"C","fb":"El agua se evapora con el calor del sol, por eso el nivel baja."},
    {"c":"En C\u00facuta preguntan sobre el ciclo del agua.","e":"\u00bfCu\u00e1l es el orden correcto del ciclo del agua?","opts":[["A","Lluvia, evaporaci\u00f3n, condensaci\u00f3n","Incorrecto."],["B","Evaporaci\u00f3n, condensaci\u00f3n, precipitaci\u00f3n","Correcto."],["C","Precipitaci\u00f3n, evaporaci\u00f3n, fusi\u00f3n","Incorrecto."],["D","Condensaci\u00f3n, precipitaci\u00f3n, evaporaci\u00f3n","Incorrecto."]],"a":"B","fb":"El ciclo: 1.Evaporaci\u00f3n 2.Condensaci\u00f3n (nubes) 3.Precipitaci\u00f3n (lluvia)."},
    {"c":"En Ibagu\u00e9, el agua del suelo se filtra profundamente.","e":"\u00bfC\u00f3mo se llama el agua que se almacena bajo tierra?","opts":[["A","Agua superficial","Incorrecto."],["B","Agua subterr\u00e1nea","Correcto."],["C","Agua de lluvia","No."],["D","Agua de mar","No."]],"a":"B","fb":"El agua subterr\u00e1nea se filtra y almacena en acu\u00edferos bajo la superficie."},
]

# ═══════ G3 CIENCIAS NATURALES P4 - El Clima ═══════
D["3_ciencias-naturales_P4"] = [
    {"c":"En la clase de ciencias de Bogot\u00e1 hablan sobre el clima.","e":"\u00bfQu\u00e9 instrumento mide la temperatura del ambiente?","opts":[["A","Bar\u00f3metro","Mide presi\u00f3n."],["B","Term\u00f3metro","Correcto."],["C","Pluvi\u00f3metro","Mide lluvia."],["D","Anem\u00f3metro","Mide viento."]],"a":"B","fb":"El term\u00f3metro mide la temperatura en grados Celsius (\u00b0C)."},
    {"c":"En Medell\u00edn, el clima es primaveral todo el a\u00f1o.","e":"\u00bfC\u00f3mo se describe el clima de Medell\u00edn?","opts":[["A","Frio polar","No."],["B","C\u00e1lido todo el a\u00f1o","No, es templado."],["C","Templado y agradable","Correcto. Medell\u00edn = ciudad de la eterna primavera."],["D","Siempre seco","Incorrecto."]],"a":"C","fb":"Medell\u00edn tiene clima templado c\u00e1lido, conocido como 'ciudad de la eterna primavera'."},
    {"c":"En Cali, miran el cielo y ven nubes grises.","e":"\u00bfQu\u00e9 tipo de nubes traen lluvia?","opts":[["A","Nubes blancas delgadas","Generalmente no llueven."],["B","Nubes grises y oscuras","Correcto. Nubes nimbos."],["C","Cirros","Son delgadas."],["D","C\u00famulos blancos","Son de buen tiempo."]],"a":"B","fb":"Las nubes grises y oscuras (nimbostratos) generalmente indican lluvia cercana."},
    {"c":"En Barranquilla hay mucho sol.","e":"\u00bfQu\u00e9 nos protege de los rayos del sol?","opts":[["A","El viento","No."],["B","Las nubes","A veces."],["C","La capa de ozono","Correcto. Filtra rayos UV."],["D","La lluvia","No."]],"a":"C","fb":"La capa de ozono en la atm\u00f3sfera nos protege de los rayos ultravioleta."},
    {"c":"En Bucaramanga preguntan sobre las estaciones.","e":"Colombia est\u00e1 cerca del Ecuador. \u00bfCu\u00e1ntas estaciones clim\u00e1ticas tiene?","opts":[["A","4 (invierno, verano, oto\u00f1o, primavera)","No, eso es en pa\u00edses lejanos al Ecuador."],["B","2 (\u00e9poca seca y \u00e9poca lluviosa)","Correcto."],["C","1 (solo invierno)","No."],["D","6 estaciones","No."]],"a":"B","fb":"En Colombia, por estar en el Ecuador, solo hay dos estaciones: seca y lluviosa."},
    {"c":"En Cartagena, la ciudad es calurosa.","e":"\u00bfQu\u00e9 ropa es m\u00e1s adecuada para el clima de Cartagena?","opts":[["A","Chaquetas y bufandas","No, hace calor."],["B","Ropa ligera y fresca","Correcto."],["C","Traje de nieve","No."],["D","Poncho de lana","No."]],"a":"B","fb":"Cartagena tiene clima c\u00e1lido, ideal para ropa ligera, fresca y c\u00f3moda."},
    {"c":"En Pereira, hablan sobre la brisa.","e":"\u00bfQu\u00e9 es el viento?","opts":[["A","Agua movi\u00e9ndose","No."],["B","Aire en movimiento","Correcto."],["C","Nubes que se mueven","No."],["D","Rayos del sol","No."]],"a":"B","fb":"El viento es aire que se mueve de zonas de alta a baja presi\u00f3n."},
    {"c":"En Manizales, la profe pregunta.","e":"\u00bfQu\u00e9 se usa para medir cu\u00e1nta lluvia cay\u00f3?","opts":[["A","Term\u00f3metro","No."],["B","Bar\u00f3metro","No."],["C","Pluvi\u00f3metro","Correcto."],["D","Anem\u00f3metro","Mide viento."]],"a":"C","fb":"El pluvi\u00f3metro mide la cantidad de precipitaci\u00f3n en mil\u00edmetros."},
    {"c":"En C\u00facuta, miran el pron\u00f3stico del tiempo.","e":"\u00bfPara qu\u00e9 sirve el pron\u00f3stico del tiempo?","opts":[["A","Para saber la hora","No."],["B","Para saber qu\u00e9 clima esperar","Correcto."],["C","Para adivinar la loter\u00eda","No."],["D","Para medir monta\u00f1as","No."]],"a":"B","fb":"El pron\u00f3stico del tiempo nos ayuda a planificar actividades seg\u00fan el clima esperado."},
    {"c":"En Ibagu\u00e9 comparan climas.","e":"\u00bfPor qu\u00e9 en la costa colombiana hace m\u00e1s calor que en Bogot\u00e1?","opts":[["A","Bogot\u00e1 est\u00e1 a mayor altura","Correcto. A mayor altura, menor temperatura."],["B","La costa tiene m\u00e1s \u00e1rboles","No."],["C","Bogot\u00e1 tiene mar","No."],["D","No hay raz\u00f3n","S\u00ed hay."]],"a":"A","fb":"Bogot\u00e1 est\u00e1 a 2600m de altura; la temperatura baja ~6\u00b0C por cada 1000m de ascenso."},
]

# ═══════ G3 LENGUA P3 - Gramática fundamental ═══════
D["3_lengua_P3"] = [
    {"c":"En la clase de lengua en Bogot\u00e1, la profe explica las letras may\u00fasculas.","e":"\u00bfCu\u00e1l palabra est\u00e1 escrita correctamente?","opts":[["A","colombia","Incorrecto. Pa\u00edses llevan may\u00fascula."],["B","Colombia","Correcto. Los nombres propios llevan may\u00fascula."],["C","cOLOMBIA","Incorrecto."],["D","colOMBIA","Incorrecto."]],"a":"B","fb":"Los nombres de pa\u00edses y ciudades se escriben con may\u00fascula inicial."},
    {"c":"En Medell\u00edn aprenden las partes de una oraci\u00f3n.","e":"\u00bfCu\u00e1l palabra es un VERBO?","opts":[["A","Casa","Sustantivo."],["B","Bonito","Adjetivo."],["C","Correr","Correcto. Expresa una acci\u00f3n."],["D","R\u00e1pido","Adverbio."]],"a":"C","fb":"El verbo expresa acci\u00f3n, estado o proceso en la oraci\u00f3n."},
    {"c":"En Cali, la profe explica los signos de puntuaci\u00f3n.","e":"\u00bfQu\u00e9 signo usamos al final de una pregunta?","opts":[["A",". (Punto)","Final de enunciado."],["B",", (Coma)","Separaci\u00f3n."],["C","? (Signo de interrogaci\u00f3n)","Correcto."],["D","! (Signo de admiraci\u00f3n)","Para exclamaciones."]],"a":"C","fb":"Las preguntas se escriben entre signos de interrogaci\u00f3n (\u00bf?)."},
    {"c":"En Barranquilla reconocen art\u00edculos.","e":"\u00bfCu\u00e1l es un ART\u00cdCULO?","opts":[["A","Grande","Adjetivo."],["B","El","Correcto. Art\u00edculo definido masculino singular."],["C","Saltar","Verbo."],["D","Amable","Adjetivo."]],"a":"B","fb":"Los art\u00edculos (el, la, los, las, un, una) acompa\u00f1an al sustantivo."},
    {"c":"En Bucaramanga, la profe escribe en el tablero.","e":"\u00bfCu\u00e1l palabra tiene un DIPTONGO?","opts":[["A","Casa","No, CA-SA."],["B","Piedra","Correcto. IE forman diptongo."],["C","Sol","No, una vocal."],["D","Manso","No, AN."]],"a":"B","fb":"El diptongo es la uni\u00f3n de dos vocales en una misma s\u00edlaba (piedra: PIEDRA)."},
    {"c":"En Cartagena forman oraciones.","e":"Ordena las palabras: gato - el - duerme - sof\u00e1 - en - el","opts":[["A","Gato el duerme sof\u00e1 en el","No."],["B","El gato duerme en el sof\u00e1","Correcto."],["C","Sof\u00e1 el en duerme gato el","No."],["D","Duerme gato el sof\u00e1 el en","No."]],"a":"B","fb":"Orden correcto: art\u00edculo+nombre+verbo+complemento (en espa\u00f1ol)."},
    {"c":"En Pereira identifican adjetivos.","e":"\u00bfCu\u00e1l palabra es un ADJETIVO?","opts":[["A","Colegio","Sustantivo."],["B","Inteligente","Correcto. Describe cualidad."],["C","Caminar","Verbo."],["D","All\u00e1","Adverbio de lugar."]],"a":"B","fb":"El adjetivo califica o describe al sustantivo (ej: ni\u00f1o inteligente)."},
    {"c":"En Manizales aprenden sin\u00f3nimos.","e":"\u00bfCu\u00e1l es SIN\u00d3NIMO de contento?","opts":[["A","Triste","Ant\u00f3nimo."],["B","Enojado","Opuesto."],["C","Feliz","Correcto. Significa lo mismo."],["D","Cansado","No."]],"a":"C","fb":"Sin\u00f3nimos son palabras con significado igual o parecido."},
    {"c":"En C\u00facuta, la profe explica los acentos.","e":"\u00bfCu\u00e1l palabra lleva acento en la \u00faltima s\u00edlaba?","opts":[["A","Casa","No, es grave."],["B","Caf\u00e9","Correcto. Aguda, \u00faltima s\u00edlaba t\u00f3nica."],["C","P\u00e1jaro","No, es esdr\u00fajula."],["D","\u00c1rbol","No, es grave."]],"a":"B","fb":"Las palabras agudas tienen la \u00faltima s\u00edlaba t\u00f3nica y llevan acento si terminan en N, S o vocal."},
    {"c":"En Ibagu\u00e9 diferencian entre singular y plural.","e":"Plural de flor?","opts":[["A","Flores","Correcto."],["B","Floris","Incorrecto."],["C","Floras","Incorrecto."],["D","Flor","Singular."]],"a":"A","fb":"El plural de palabras terminadas en consonante agrega -es."},
]

# ═══════ G3 LENGUA P4 - Producción textual ═══════
D["3_lengua_P4"] = [
    {"c":"En Bogot\u00e1, la profe pide escribir una invitaci\u00f3n de cumplea\u00f1os.","e":"\u00bfQu\u00e9 datos debe tener una invitaci\u00f3n?","opts":[["A","Solo el nombre del invitado","No."],["B","Fecha, hora, lugar y motivo","Correcto."],["C","Solo la fecha","No."],["D","El men\u00fa de la fiesta","No es esencial."]],"a":"B","fb":"Una invitaci\u00f3n debe incluir: a qui\u00e9n, evento, fecha, hora y lugar."},
    {"c":"En Medell\u00edn escriben una carta a un amigo.","e":"\u00bfC\u00f3mo se inicia una carta formal?","opts":[["A","Oye, qu\u00e9 hubo","Informal."],["B","Querido(a) / Estimado(a)","Correcto. Saludo formal."],["C","Bueno, ah\u00ed te va","Informal."],["D","A ver","Incorrecto."]],"a":"B","fb":"Las cartas formales comienzan con un saludo respetuoso como 'Estimado'."},
    {"c":"En Cali, la profe pide escribir una descripci\u00f3n de mascota.","e":"\u00bfQu\u00e9 informaci\u00f3n lleva una descripci\u00f3n?","opts":[["A","Solo el nombre","No."],["B","Caracter\u00edsticas f\u00edsicas y comportamiento","Correcto."],["C","Solo su color","No."],["D","D\u00f3nde vivi\u00f3 antes","No es necesario."]],"a":"B","fb":"Describir es decir c\u00f3mo es algo: sus caracter\u00edsticas f\u00edsicas y de comportamiento."},
    {"c":"En Barranquilla escriben una receta de cocina.","e":"\u00bfQu\u00e9 tipo de texto es una receta?","opts":[["A","Instructivo","Correcto. Da pasos a seguir."],["B","Narrativo","Cuenta historias."],["C","Po\u00e9tico","Expresa sentimientos."],["D","Informativo","Da datos."]],"a":"A","fb":"Los textos instructivos gu\u00edan paso a paso c\u00f3mo hacer algo, como una receta."},
    {"c":"En Bucaramanga, escriben un diario personal.","e":"\u00bfEn qu\u00e9 tiempo verbal se escribe un diario personal?","opts":[["A","Futuro","No."],["B","Presente","Puede ser."],["C","Pasado o presente","Correcto. Se narran experiencias."],["D","Condicional","No."]],"a":"C","fb":"En un diario se escriben experiencias vividas (pasado) o reflexiones (presente)."},
    {"c":"En Cartagena, la profe habla sobre p\u00e1rrafos.","e":"\u00bfQu\u00e9 es un p\u00e1rrafo?","opts":[["A","Una palabra","No."],["B","Un conjunto de oraciones sobre un tema","Correcto."],["C","Una sola oraci\u00f3n","No."],["D","Un dibujo","No."]],"a":"B","fb":"Un p\u00e1rrafo es un conjunto de oraciones que desarrollan una idea principal."},
    {"c":"En Pereira, aprenden a organizar ideas.","e":"\u00bfQu\u00e9 usamos para ordenar los pasos de un proceso?","opts":[["A","Dibujos","No."],["B","Palabras de orden (primero, luego, finalmente)","Correcto."],["C","Signos de interrogaci\u00f3n","No."],["D","Adjetivos","No."]],"a":"B","fb":"Palabras como primero, luego, despu\u00e9s y finalmente ordenan secuencias."},
    {"c":"En Manizales escriben un cuento corto.","e":"\u00bfQu\u00e9 debe tener un cuento?","opts":[["A","Solo ilustraciones","No."],["B","Personajes, lugar y trama","Correcto."],["C","Solo di\u00e1logos","No."],["D","Definiciones","No."]],"a":"B","fb":"Un cuento necesita personajes que act\u00faan en un lugar, con una trama (inicio-nudo-desenlace)."},
    {"c":"En C\u00facuta revisan ortograf\u00eda.","e":"\u00bfCu\u00e1l oraci\u00f3n est\u00e1 escrita correctamente?","opts":[["A","La casa tiene ventanas grandes","Correcto."],["B","La kasa tiene bentanas grandes","Incorrecto."],["C","La caza tiene ventanas grandes","No, caza=cazar."],["D","La casa tiene bentanas grandes","No."]],"a":"A","fb":"Ortograf\u00eda correcta: casa con C, ventanas con V."},
    {"c":"En Ibagu\u00e9, la profe pide un cartel.","e":"\u00bfCaracter\u00edstica principal de un cartel?","opts":[["A","Tener mucho texto","No."],["B","Ser informativo y atractivo visualmente","Correcto."],["C","Estar escrito a mano","No necesariamente."],["D","Ser muy largo","No."]],"a":"B","fb":"Un cartel combina texto breve e im\u00e1genes para comunicar un mensaje claro."},
]

append_to_data(D)
