#!/usr/bin/env python3
"""Build Grade 5 question data"""
import json, os

def append_to_data(new_data, filename="_questions_data_full.json"):
    existing = {}
    if os.path.exists(filename):
        with open(filename, "r", encoding="utf-8") as f:
            existing = json.load(f)
    existing.update(new_data)
    with open(filename, "w", encoding="utf-8") as f:
        json.dump(existing, f, ensure_ascii=False, indent=2)
    print(f"Appended {len(new_data)} sets. Total: {len(existing)}")

D = {}

# ═══════ G5 LECTURA CRITICA P1 - Textos narrativos ═══════
D["5_lectura-critica_P1"] = [
    {"c":"Lean el siguiente fragmento: 'El guerrero se levant\u00f3 al amanecer. Tom\u00f3 su escudo y espada, y camin\u00f3 hacia la monta\u00f1a donde el drag\u00f3n dorm\u00eda. Sab\u00eda que esta batalla decidir\u00eda el destino del reino.'","e":"\u00bfQu\u00e9 tipo de texto es?","opts":[["A","Informativo","No da datos objetivos."],["B","Narrativo","Correcto. Narra una historia con personajes y acci\u00f3n."],["C","Po\u00e9tico","No tiene estructura de poema."],["D","Expositivo","No explica un tema."]],"a":"B","fb":"El texto narrativo cuenta una historia con personajes, tiempo y espacio."},
    {"c":"Del fragmento anterior: 'El guerrero se levant\u00f3 al amanecer'.","e":"\u00bfQui\u00e9n es el personaje principal?","opts":[["A","El drag\u00f3n","No, es mencionado pero no el principal."],["B","El reino","No es un personaje."],["C","El guerrero","Correcto. Es quien realiza las acciones."],["D","La monta\u00f1a","No es un personaje."]],"a":"C","fb":"El personaje principal es el guerrero, alrededor de quien gira la historia."},
    {"c":"Del texto: 'Camin\u00f3 hacia la monta\u00f1a donde el drag\u00f3n dorm\u00eda'.","e":"\u00bfQu\u00e9 ambiente o lugar se describe?","opts":[["A","Un castillo","No se menciona."],["B","Una monta\u00f1a","Correcto. All\u00ed se dirige."],["C","El mar","No se menciona."],["D","Un bosque","No se menciona."]],"a":"B","fb":"La historia se desarrolla en el camino hacia una monta\u00f1a."},
    {"c":"En un cuento de la clase en Cali.","e":"\u00bfCu\u00e1l es la estructura de un texto narrativo?","opts":[["A","Introducci\u00f3n, desarrollo, conclusi\u00f3n","Correcto."],["B","T\u00edtulo, subt\u00edtulos, glosario","Estructura de texto expositivo."],["C","Problema, soluci\u00f3n","Parte de la trama."],["D","Verso, estrofa, rima","Estructura po\u00e9tica."]],"a":"A","fb":"Todo texto narrativo tiene inicio (introducci\u00f3n), nudo (desarrollo) y desenlace (conclusi\u00f3n)."},
    {"c":"En la clase de Bogot\u00e1, la profe lee un cuento de Gabriel Garc\u00eda M\u00e1rquez.","e":"\u00bfQu\u00e9 caracteriza a un cuento?","opts":[["A","Es muy extenso","No, el cuento es corto."],["B","Tiene pocos personajes y trama simple","Correcto."],["C","No tiene final","Toda historia tiene final."],["D","Solo tiene di\u00e1logos","No es obligatorio."]],"a":"B","fb":"El cuento es una narraci\u00f3n breve con pocos personajes y una trama sencilla."},
    {"c":"En Medell\u00edn leen La siesta del martes.","e":"\u00bfQu\u00e9 sentimiento predomina en el texto?","opts":[["A","Alegr\u00eda","No es el tono principal."],["B","Tensi\u00f3n y tristeza","Correcto. La historia tiene un tono melanc\u00f3lico."],["C","Envidia","No."],["D","Sorpresa","No."]],"a":"B","fb":"El tono del cuento es melanc\u00f3lico y tenso, reflejando la situaci\u00f3n de los personajes."},
    {"c":"En Barranquilla, leen un fragmento con di\u00e1logos.","e":"\u00bfPara qu\u00e9 sirven los di\u00e1logos en un cuento?","opts":[["A","Para decorar","No."],["B","Para que los personajes hablen y avance la historia","Correcto."],["C","Para dividir cap\u00edtulos","No necesariamente."],["D","Para poner moraleja","No."]],"a":"B","fb":"Los di\u00e1logos permiten que los personajes se expresen y la trama avance."},
    {"c":"En Bucaramanga analizan el narrador.","e":"\u00bfQui\u00e9n cuenta la historia en 'El guerrero se levant\u00f3...'?","opts":[["A","El guerrero","No habla en primera persona."],["B","El drag\u00f3n","No."],["C","Un narrador externo","Correcto. Narra en tercera persona."],["D","El reino","No."]],"a":"C","fb":"El narrador externo (tercera persona) cuenta la historia desde fuera."},
    {"c":"En Cartagena comparan cuento y novela.","e":"\u00bfDiferencia entre cuento y novela?","opts":[["A","No hay diferencia","S\u00ed hay."],["B","La novela es m\u00e1s larga y compleja","Correcto."],["C","El cuento tiene m\u00e1s personajes","No."],["D","La novela no tiene final","S\u00ed tiene."]],"a":"B","fb":"La novela es m\u00e1s extensa, con m\u00e1s personajes y tramas m\u00e1s complejas."},
    {"c":"En Pereira preguntan sobre la trama.","e":"\u00bfQu\u00e9 parte del cuento presenta el conflicto?","opts":[["A","Inicio","Presenta personajes."],["B","Nudo","Correcto. Aqu\u00ed surge el conflicto."],["C","Desenlace","Resuelve el conflicto."],["D","Ep\u00edlogo","Despu\u00e9s del final."]],"a":"B","fb":"El nudo es la parte donde se desarrolla el conflicto principal de la historia."},
]

# ═══════ G5 LECTURA CRITICA P2 - Textos informativos ═══════
D["5_lectura-critica_P2"] = [
    {"c":"Lean: 'El \u00e1guila real es una de las aves m\u00e1s grandes de Colombia. Habita en las monta\u00f1as de los Andes. Se alimenta de conejos y zarig\u00fceyas. Est\u00e1 en peligro de extinci\u00f3n.'","e":"\u00bfQu\u00e9 tipo de texto es?","opts":[["A","Narrativo","No cuenta una historia."],["B","Informativo","Correcto. Da datos objetivos."],["C","Po\u00e9tico","No."],["D","Instructivo","No da pasos."]],"a":"B","fb":"El texto informativo presenta datos y hechos de manera objetiva."},
    {"c":"Del texto del \u00e1guila real.","e":"\u00bfD\u00f3nde habita el \u00e1guila real?","opts":[["A","En la selva amaz\u00f3nica","No."],["B","En las monta\u00f1as de los Andes","Correcto."],["C","En el mar Caribe","No."],["D","En los llanos orientales","No."]],"a":"B","fb":"Seg\u00fan el texto, habita en las monta\u00f1as de los Andes colombianos."},
    {"c":"Sobre el \u00e1guila real.","e":"\u00bfPor qu\u00e9 es importante proteger al \u00e1guila real?","opts":[["A","Porque es bonita","No es la raz\u00f3n principal."],["B","Porque est\u00e1 en peligro de extinci\u00f3n","Correcto. El texto lo menciona."],["C","Porque vuela alto","No."],["D","Porque come conejos","No."]],"a":"B","fb":"El peligro de extinci\u00f3n hace urgente su protecci\u00f3n."},
    {"c":"En Medell\u00edn leen un art\u00edculo de peri\u00f3dico.","e":"\u00bfQu\u00e9 informaci\u00f3n lleva el titular de una noticia?","opts":[["A","Opini\u00f3n del periodista","No."],["B","Lo m\u00e1s importante de forma breve","Correcto."],["C","Toda la historia completa","No."],["D","Un poema","No."]],"a":"B","fb":"El titular resume lo esencial de la noticia para captar atenci\u00f3n."},
    {"c":"En Cali leen un art\u00edculo sobre cambio clim\u00e1tico.","e":"\u00bfQu\u00e9 diferencia hay entre hecho y opini\u00f3n?","opts":[["A","Son lo mismo","No."],["B","Los hechos son comprobables, las opiniones son personales","Correcto."],["C","Las opiniones siempre son verdaderas","No."],["D","Los hechos no importan","No."]],"a":"B","fb":"Hecho: se puede verificar. Opini\u00f3n: expresi\u00f3n personal del autor."},
    {"c":"En Barranquilla analizan un texto de historia.","e":"\u00bfPara qu\u00e9 sirven las fechas en un texto informativo?","opts":[["A","Para decorar","No."],["B","Para ubicar los hechos en el tiempo","Correcto."],["C","Para confundir","No."],["D","Para hacer rimas","No."]],"a":"B","fb":"Las fechas sit\u00faan los acontecimientos cronol\u00f3gicamente."},
    {"c":"En Bucaramanga leen un texto con subt\u00edtulos.","e":"\u00bfFunci\u00f3n de los subt\u00edtulos?","opts":[["A","Dividir el texto en secciones","Correcto."],["B","Hacer el texto m\u00e1s largo","No."],["C","Reemplazar dibujos","No."],["D","Agregar opini\u00f3n","No."]],"a":"A","fb":"Los subt\u00edtulos organizan la informaci\u00f3n en secciones tem\u00e1ticas."},
    {"c":"En Cartagena eval\u00faan un texto.","e":"\u00bfQu\u00e9 hace confiable un texto informativo?","opts":[["A","Que tenga colores","No."],["B","Que cite fuentes confiables y datos verificables","Correcto."],["C","Que sea largo","No."],["D","Que tenga muchas im\u00e1genes","No."]],"a":"B","fb":"Un texto confiable se basa en fuentes verificables y datos precisos."},
    {"c":"En Pereira comparan textos.","e":"\u00bfQu\u00e9 tipo de texto es un reportaje?","opts":[["A","Narrativo","No."],["B","Informativo","Correcto. Investiga un tema a fondo."],["C","Po\u00e9tico","No."],["D","Instructivo","No."]],"a":"B","fb":"El reportaje es un texto informativo que investiga un tema en profundidad."},
    {"c":"En Manizales, leen sobre deforestaci\u00f3n.","e":"\u00bfCu\u00e1l es la idea principal del texto?","opts":[["A","Los \u00e1rboles son bonitos","No."],["B","La deforestaci\u00f3n afecta el medio ambiente","Correcto."],["C","Los animales viven en los \u00e1rboles","Detalle, no idea principal."],["D","La madera se usa para muebles","Detalle."]],"a":"B","fb":"La idea principal resume el tema central del texto informativo."},
]

# ═══════ G5 LECTURA CRITICA P3 - Comprensión inferencial ═══════
D["5_lectura-critica_P3"] = [
    {"c":"Lee: 'Mar\u00eda lleg\u00f3 a casa, dej\u00f3 la mochila y se sent\u00f3 frente al televisor. Afuera llov\u00eda fuertemente. Tom\u00f3 el control remoto pero la pantalla segu\u00eda apagada. Suspir\u00f3 profundamente.'","e":"\u00bfQu\u00e9 podemos inferir que pas\u00f3?","opts":[["A","Mar\u00eda no quiere ver TV","Incorrecto."],["B","No hay electricidad","Correcto. TV apagada, suspira."],["C","Mar\u00eda est\u00e1 contenta","No, suspira."],["D","El control no funciona","No es lo m\u00e1s probable."]],"a":"B","fb":"Inferimos por falta de luz y el suspiro que hay un apag\u00f3n."},
    {"c":"En Bogot\u00e1 leen un texto sobre un ni\u00f1o que guarda su dinero en una alcanc\u00eda.","e":"\u00bfQu\u00e9 podemos inferir del ni\u00f1o?","opts":[["A","Es perezoso","No."],["B","Est\u00e1 ahorrando para algo","Correcto."],["C","No tiene dinero","S\u00ed tiene, lo guarda."],["D","No le gusta gastar","Ahorrar no implica no gastar."]],"a":"B","fb":"Inferimos que ahorra porque guarda el dinero, probablemente para un objetivo."},
    {"c":"En Medell\u00edn: 'El perro de Pablo no se movi\u00f3 cuando \u00e9l lleg\u00f3. Solo movi\u00f3 la cola d\u00e9bilmente.'","e":"\u00bfQu\u00e9 podemos inferir del perro?","opts":[["A","Est\u00e1 feliz y saltando","No, solo mueve cola d\u00e9bil."],["B","Est\u00e1 cansado o enfermo","Correcto. Poca energ\u00eda."],["C","Est\u00e1 enojado","No."],["D","Est\u00e1 jugando","No."]],"a":"B","fb":"La falta de movimiento y el movimiento d\u00e9bil de cola sugiere cansancio o enfermedad."},
    {"c":"En Cali: 'Pedro sudaba mientras caminaba bajo el sol del mediod\u00eda. Se quit\u00f3 la chaqueta.'","e":"\u00bfQu\u00e9 inferimos?","opts":[["A","Hace fr\u00edo","No, al contrario."],["B","Hace calor","Correcto."],["C","Est\u00e1 lloviendo","No."],["D","Es de noche","No."]],"a":"B","fb":"Sudar y quitarse la chaqueta indica que hace calor."},
    {"c":"En Barranquilla: 'La abuela sac\u00f3 el \u00e1lbum de fotos y se qued\u00f3 mirando una p\u00e1gina por varios minutos.'","e":"\u00bfQu\u00e9 sentimiento podemos inferir?","opts":[["A","Felicidad","No necesariamente."],["B","Nostalgia","Correcto. Mirar fotos viejas causa nostalgia."],["C","Enojo","No."],["D","Aburrimiento","No."]],"a":"B","fb":"Mirar fotos antiguas por largo tiempo sugiere nostalgia o recuerdos."},
    {"c":"En Bucaramanga leen sobre un ni\u00f1o que siempre lleva gafas.","e":"\u00bfQu\u00e9 inferimos?","opts":[["A","No ve bien","Correcto. Las gafas corrigen la visi\u00f3n."],["B","Es inteligente","No necesariamente."],["C","Le gusta el color","No."],["D","Es deportista","No."]],"a":"A","fb":"Usar gafas indica problemas de visi\u00f3n que necesitan correcci\u00f3n."},
    {"c":"En Cartagena: 'El ni\u00f1o abri\u00f3 el refrigerador, mir\u00f3 adentro y cerr\u00f3 la puerta. Luego llam\u00f3 a su mam\u00e1.'","e":"\u00bfQu\u00e9 podemos inferir?","opts":[["A","No ten\u00eda hambre","No, buscaba comida."],["B","No encontr\u00f3 lo que buscaba","Correcto."],["C","El refrigerador est\u00e1 vac\u00edo","No sabemos."],["D","Llam\u00f3 para hablar","No."]],"a":"B","fb":"Buscar y no tomar nada, luego llamar, sugiere que no encontr\u00f3 lo que quer\u00eda."},
    {"c":"En Pereira: un texto dice 'Ella tom\u00f3 el paraguas al salir'.","e":"\u00bfQu\u00e9 inferimos del clima?","opts":[["A","Hace sol","No."],["B","Est\u00e1 lloviendo o va a llover","Correcto."],["C","Hace viento","No necesariamente."],["D","Nieva","No."]],"a":"B","fb":"Tomar un paraguas implica que hay o se espera lluvia."},
    {"c":"En Manizales: 'El examen era muy dif\u00edcil. Muchos estudiantes se ve\u00edan preocupados.'","e":"\u00bfQu\u00e9 inferimos sobre los estudiantes?","opts":[["A","Estaban felices","No."],["B","No estudiaron suficiente o el examen era complejo","Correcto."],["C","El examen era f\u00e1cil","No."],["D","No les importaba","Estaban preocupados."]],"a":"B","fb":"La preocupaci\u00f3n ante un examen dif\u00edcil sugiere falta de preparaci\u00f3n o dificultad."},
    {"c":"En C\u00facuta: 'Juan mir\u00f3 su reloj y empez\u00f3 a correr.'","e":"\u00bfQu\u00e9 inferimos?","opts":[["A","Estaba haciendo ejercicio","Posible pero no seguro."],["B","Iba tarde a alg\u00fan lugar","Correcto. Mirar reloj+correr=apuro."],["C","Vio algo interesante","No."],["D","Estaba huyendo","No hay contexto."]],"a":"B","fb":"Mirar el reloj y luego correr indica que la persona va tarde."},
]

# ═══════ G5 LECTURA CRITICA P4 - Poesía ═══════
D["5_lectura-critica_P4"] = [
    {"c":"Lee: 'Blanca, redonda, / en el cielo brilla, / de noche aparece, / al sol se humilla.'","e":"\u00bfQu\u00e9 tipo de texto es?","opts":[["A","Cuento","No, no narra historia larga."],["B","Poema","Correcto. Tiene versos y rima."],["C","Noticia","No."],["D","Receta","No."]],"a":"B","fb":"El poema se caracteriza por versos, rima y lenguaje figurado."},
    {"c":"Del poema anterior: 'Blanca, redonda, / en el cielo brilla'.","e":"\u00bfA qu\u00e9 se refiere?","opts":[["A","El sol","No, 'de noche aparece'."],["B","La luna","Correcto. Blanca, redonda, aparece de noche."],["C","Una nube","No."],["D","Una estrella","No es redonda y blanca."]],"a":"B","fb":"La descripci\u00f3n corresponde a la luna: blanca, redonda, visible de noche."},
    {"c":"En Bogot\u00e1, la profe explica la estructura del poema.","e":"\u00bfC\u00f3mo se llama cada l\u00ednea de un poema?","opts":[["A","Estrofa","No, eso es el conjunto de versos."],["B","Verso","Correcto."],["C","Rima","No, es la coincidencia de sonidos."],["D","P\u00e1rrafo","Propio de prosa."]],"a":"B","fb":"Cada l\u00ednea del poema es un verso. El conjunto de versos forma una estrofa."},
    {"c":"En Medell\u00edn leen: 'Esta es la casa que Juan construy\u00f3. / Esta es la leche que la vaca dio...'","e":"\u00bfQu\u00e9 tipo de rima usan estos versos?","opts":[["A","Asonante","Solo vocales."],["B","Consonante","Correcto. construy\u00f3/dio riman completamente."],["C","Libre","Sin rima."],["D","Interna","Dentro del verso."]],"a":"B","fb":"La rima consonante repite todos los sonidos desde la \u00faltima vocal acentuada."},
    {"c":"En Cali leen: 'Verde que te quiero verde.'","e":"\u00bfQu\u00e9 figura literaria se usa al repetir 'verde'?","opts":[["A","Met\u00e1fora","No."],["B","Repetici\u00f3n o an\u00e1fora","Correcto."],["C","Hip\u00e9rbole","No."],["D","Comparaci\u00f3n","No usa 'como'."]],"a":"B","fb":"La an\u00e1fora repite palabras al inicio de versos para dar \u00e9nfasis."},
    {"c":"En Barranquilla leen un poema de amor.","e":"\u00bfQu\u00e9 sentimiento expresa principalmente la poes\u00eda l\u00edrica?","opts":[["A","Enojo","No."],["B","Amor, alegr\u00eda o tristeza","Correcto. La l\u00edrica expresa emociones."],["C","Indiferencia","No."],["D","Odio","Puede, pero no principalmente."]],"a":"B","fb":"La poes\u00eda l\u00edrica expresa sentimientos y emociones del poeta."},
    {"c":"En Bucaramanga preguntan.","e":"\u00bfCu\u00e1ntos versos tiene un pareado?","opts":[["A","1","No."],["B","2","Correcto. Pareado = dos versos."],["C","3","No."],["D","4","No."]],"a":"B","fb":"El pareado es una estrofa de dos versos que riman entre s\u00ed."},
    {"c":"En Cartagena leen un poema infantil.","e":"\u00bfCu\u00e1l es la funci\u00f3n de la rima en la poes\u00eda infantil?","opts":[["A","Dificultar la lectura","No."],["B","Hacerla m\u00e1s divertida y f\u00e1cil de recordar","Correcto."],["C","Ocultar el significado","No."],["D","Hacerla m\u00e1s larga","No."]],"a":"B","fb":"La rima hace los poemas infantiles m\u00e1s r\u00edtmicos y memorables."},
    {"c":"En Pereira analizan 'El s\u00e1ndwich de Mariana' de un libro colombiano.","e":"\u00bfQu\u00e9 diferencia hay entre poema y prosa?","opts":[["A","No hay diferencia","S\u00ed hay."],["B","El poema usa versos y ritmo; la prosa usa p\u00e1rrafos","Correcto."],["C","La prosa rima","No."],["D","El poema no tiene significado","S\u00ed tiene."]],"a":"B","fb":"El poema se organiza en versos y estrofas; la prosa en p\u00e1rrafos."},
    {"c":"En Manizales crean poemas.","e":"\u00bfQu\u00e9 es la m\u00e9trica en poes\u00eda?","opts":[["A","El n\u00famero de estrofas","No."],["B","La cantidad de s\u00edlabas por verso","Correcto."],["C","El tema del poema","No."],["D","La rima","No."]],"a":"B","fb":"La m\u00e9trica mide la cantidad de s\u00edlabas de cada verso."},
]

append_to_data(D)
