#!/usr/bin/env python3
"""Add remaining Grade 6: Science P3-P4, Social Studies all, English all"""
import json

with open('_questions_data_full.json', encoding='utf-8') as f:
    Q = json.load(f)

# === GRADE 6 - CIENCIAS NATURALES P3 (Matter) ===
Q['6_ciencias-naturales_P3'] = [
    {"c":"In science class in Bogot\u00e1 they study matter.","e":"What are the three states of matter?","opts":[["A","Solid, liquid, gas","Correcto."],["B","Earth, water, air","No."],["C","Rock, fire, ice","No."],["D","Hard, soft, wet","No."]],"a":"A","fb":"Matter exists as solid (fixed shape), liquid (flows), and gas (expands)."},
    {"c":"In Medell\u00edn they experiment with melting ice.","e":"Melting is a change from ___ to ___.","opts":[["A","Gas to liquid","Condensation."],["B","Solid to liquid","Correcto."],["C","Liquid to gas","Evaporation."],["D","Solid to gas","Sublimation."]],"a":"B","fb":"Melting: solid absorbs heat and changes to liquid (ice \u2192 water)."},
    {"c":"In Cali they study boiling water.","e":"At what temperature does water boil at sea level?","opts":[["A","50\u00b0C","No."],["B","100\u00b0C","Correcto."],["C","0\u00b0C","Freezing point."],["D","200\u00b0C","No."]],"a":"B","fb":"Water boils at 100\u00b0C (212\u00b0F) at standard atmospheric pressure."},
    {"c":"In Barranquilla they learn about density.","e":"Oil floats on water because oil is ___.","opts":[["A","Less dense than water","Correcto."],["B","More dense","No."],["C","Heavier","No."],["D","Colder","No."]],"a":"A","fb":"Density = mass/volume. Oil is less dense than water, so it floats."},
    {"c":"In Bucaramanga they classify changes.","e":"Burning wood is a ___ change.","opts":[["A","Physical","No, composition changes."],["B","Chemical","Correcto."],["C","Reversible","No."],["D","Temporary","No."]],"a":"B","fb":"Chemical change produces new substances (ash, smoke), not easily reversible."},
    {"c":"In Cartagena they study atoms.","e":"What particles make up an atom?","opts":[["A","Protons, neutrons, electrons","Correcto."],["B","Cells, tissue, organs","Biology."],["C","Elements, compounds, mixtures","No."],["D","Solids, liquids, gases","States."]],"a":"A","fb":"Atoms have: protons (+) and neutrons in nucleus; electrons (-) orbiting."},
    {"c":"In Pereira they explore mixtures.","e":"Sand and water is an example of a ___.","opts":[["A","Compound","No."],["B","Element","No."],["C","Heterogeneous mixture","Correcto."],["D","Solution","Homogeneous."]],"a":"C","fb":"Heterogeneous: components are visible and can be separated."},
    {"c":"In Manizales they study solubility.","e":"Sugar dissolves in water because it is ___.","opts":[["A","Insoluble","No."],["B","Soluble","Correcto."],["C","Solid","No."],["D","Heavy","No."]],"a":"B","fb":"Solubility: ability to dissolve. Sugar is soluble in water; oil is not."},
    {"c":"In C\u00facuta they learn about elements.","e":"Water (H\u2082O) is made of what elements?","opts":[["A","Helium and oxygen","No."],["B","Hydrogen and oxygen","Correcto."],["C","Hydrogen and nitrogen","No."],["D","Oxygen and carbon","No."]],"a":"B","fb":"Water = 2 hydrogen atoms + 1 oxygen atom."},
    {"c":"In Ibagu\u00e9 they analyze conservation of mass.","e":"If 10g of wood burns, the mass of products (ash+gas) is ___.","opts":[["A","Less than 10g","No."],["B","About 10g","Correcto, mass is conserved."],["C","More than 10g","No."],["D","0g","No."]],"a":"B","fb":"Law of Conservation of Mass: mass is neither created nor destroyed in reactions."},
]
print("Added 6_ciencias-naturales_P3")

# === GRADE 6 - CIENCIAS NATURALES P4 (Energy) ===
Q['6_ciencias-naturales_P4'] = [
    {"c":"In science in Bogot\u00e1 they study energy.","e":"What is energy?","opts":[["A","A type of matter","No."],["B","The ability to do work","Correcto."],["C","A physical object","No."],["D","A liquid","No."]],"a":"B","fb":"Energy is the capacity to do work or produce change."},
    {"c":"In Medell\u00edn they identify energy forms.","e":"A moving car has ___ energy.","opts":[["A","Potential","Stored."],["B","Kinetic","Correcto."],["C","Nuclear","No."],["D","Chemical","No."]],"a":"B","fb":"Kinetic energy = energy of motion. Potential = stored energy."},
    {"c":"In Cali they study energy transformations.","e":"A light bulb converts electrical energy to ___.","opts":[["A","Chemical","No."],["B","Light and heat","Correcto."],["C","Sound","No."],["D","Nuclear","No."]],"a":"B","fb":"Light bulbs produce light and heat from electrical energy."},
    {"c":"In Barranquilla they learn about renewable energy.","e":"Which is a RENEWABLE energy source?","opts":[["A","Coal","Non-renewable."],["B","Solar","Correcto."],["C","Oil","Non-renewable."],["D","Natural gas","Non-renewable."]],"a":"B","fb":"Solar energy is renewable (infinite). Coal and oil are non-renewable (finite)."},
    {"c":"In Bucaramanga they study the Law of Conservation of Energy.","e":"Energy cannot be ___.","opts":[["A","Transformed","Can."],["B","Created or destroyed","Correcto."],["C","Transferred","Can."],["D","Used","Can."]],"a":"B","fb":"Law of Conservation: energy is neither created nor destroyed, only transformed."},
    {"c":"In Cartagena they explore heat transfer.","e":"Heat transfer through direct contact is ___.","opts":[["A","Convection","Fluids."],["B","Radiation","Waves."],["C","Conduction","Correcto."],["D","Insulation","No."]],"a":"C","fb":"Conduction: heat transfer through direct contact (e.g., pan on stove)."},
    {"c":"In Pereira they study electricity generation.","e":"Hydroelectric plants convert ___ to electricity.","opts":[["A","Solar energy","No."],["B","Kinetic energy of water","Correcto."],["C","Wind","No."],["D","Nuclear","No."]],"a":"B","fb":"Hydroelectric: falling water turns turbines, converting kinetic to electrical energy."},
    {"c":"In Manizales they identify energy sources in Colombia.","e":"Most of Colombia's electricity comes from ___.","opts":[["A","Coal","No."],["B","Hydroelectric","Correcto."],["C","Nuclear","No."],["D","Solar","Growing but not majority."]],"a":"B","fb":"Colombia generates ~70% of electricity from hydroelectric plants."},
    {"c":"In C\u00facuta they study potential energy.","e":"A book on a shelf has ___ energy.","opts":[["A","Kinetic","Not moving."],["B","Gravitational potential","Correcto."],["C","Chemical","No."],["D","Nuclear","No."]],"a":"B","fb":"Gravitational potential energy = mass x gravity x height (mgh)."},
    {"c":"In Ibagu\u00e9 they discuss energy efficiency.","e":"Energy efficiency means ___.","opts":[["A","Using more energy","No."],["B","Getting more output from less input","Correcto."],["C","Wasting energy","No."],["D","Stopping energy use","No."]],"a":"B","fb":"Energy efficiency: doing the same work with less energy input."},
]
print("Added 6_ciencias-naturales_P4")

# === GRADE 6 - SOCIALES P1 (River civilizations) ===
Q['6_sociales-ciudadanas_P1'] = [
    {"c":"In social studies in Bogot\u00e1.","e":"Which river was key to the Egyptian civilization?","opts":[["A","Tigris","Mesopotamia."],["B","Nile","Correcto."],["C","Indus","India."],["D","Yangtze","China."]],"a":"B","fb":"The Nile River was essential for Egyptian agriculture and transportation."},
    {"c":"In Medell\u00edn they compare civilizations.","e":"Mesopotamia developed between which rivers?","opts":[["A","Nile and Amazon","No."],["B","Tigris and Euphrates","Correcto."],["C","Indus and Ganges","No."],["D","Danube and Rhine","No."]],"a":"B","fb":"Mesopotamia = 'land between rivers' (Tigris and Euphrates)."},
    {"c":"In Cali they study ancient China.","e":"What was the Great Wall of China used for?","opts":[["A","Trade route","No."],["B","Defense against invasions","Correcto."],["C","Palace","No."],["D","Temple","No."]],"a":"B","fb":"The Great Wall was built to protect China from northern invasions."},
    {"c":"In Barranquilla they study the Indus Valley.","e":"Modern-day countries of the Indus Valley?","opts":[["A","Egypt and Sudan","No."],["B","India and Pakistan","Correcto."],["C","China and Japan","No."],["D","Peru and Mexico","No."]],"a":"B","fb":"The Indus Valley civilization was in present-day Pakistan and northwest India."},
    {"c":"In Bucaramanga they compare writing systems.","e":"Cuneiform writing was developed by the ___.","opts":[["A","Egyptians","Hieroglyphs."],["B","Sumerians","Correcto."],["C","Chinese","Characters."],["D","Romans","Latin alphabet."]],"a":"B","fb":"Sumerians in Mesopotamia developed cuneiform, one of the first writing systems."},
    {"c":"In Cartagena they study irrigation.","e":"Why did civilizations develop near rivers?","opts":[["A","For fertile soil and water","Correcto."],["B","For ocean travel","No."],["C","For mountains","No."],["D","For forest resources","No."]],"a":"A","fb":"Rivers provided water for irrigation, fertile soil, transportation, and fishing."},
    {"c":"In Pereira they study social hierarchy.","e":"Egyptian society was structured with Pharaoh at ___.","opts":[["A","Bottom","No."],["B","Top","Correcto."],["C","Middle","No."],["D","Equal to all","No."]],"a":"B","fb":"Pharaoh was at the top, followed by priests/nobles, scribes, artisans, then slaves."},
    {"c":"In Manizales they study religion.","e":"Ancient Egyptians believed in ___.","opts":[["A","One god","Monotheism."],["B","Many gods","Correcto (polytheism)."],["C","No gods","No."],["D","Astrology only","No."]],"a":"B","fb":"Egyptians were polytheistic, worshipping many gods like Ra, Osiris, Anubis."},
    {"c":"In C\u00facuta they study architecture.","e":"Pyramids in Egypt were built as ___.","opts":[["A","Palaces","No."],["B","Tombs for pharaohs","Correcto."],["C","Temples","No."],["D","Markets","No."]],"a":"B","fb":"Pyramids served as monumental tombs for Egyptian pharaohs."},
    {"c":"In Ibagu\u00e9 they reflect on legacy.","e":"Which legacy came from Roman civilization?","opts":[["A","Paper","Chinese."],["B","Roads and aqueducts","Correcto."],["C","Gunpowder","Chinese."],["D","Compass","Chinese."]],"a":"B","fb":"Romans built extensive road networks and aqueducts for water supply."},
]
print("Added 6_sociales-ciudadanas_P1")

# === GRADE 6 - SOCIALES P2 (Colombian geography) ===
Q['6_sociales-ciudadanas_P2'] = [
    {"c":"In geography class in Bogot\u00e1.","e":"How many natural regions does Colombia have?","opts":[["A","4","No."],["B","5","No."],["C","6","Correcto."],["D","7","No."]],"a":"C","fb":"Colombia has 6 natural regions: Andina, Caribe, Pac\u00edfica, Orinoqu\u00eda, Amazon\u00eda, Insular."},
    {"c":"In Medell\u00edn they study the Andean region.","e":"Which cities are in the Andean region?","opts":[["A","Bogot\u00e1, Medell\u00edn, Cali","Correcto."],["B","Cartagena, Barranquilla","Caribe."],["C","Leticia, Mocoa","Amazon\u00eda."],["D","San Andr\u00e9s","Insular."]],"a":"A","fb":"Major Andean cities: Bogot\u00e1 (Cundinamarca), Medell\u00edn (Antioquia), Cali (Valle)."},
    {"c":"In Cali they study the Pacific region.","e":"The Pacific region is known for its ___.","opts":[["A","Dry climate","No, humid."],["B","High rainfall and Afro-Colombian culture","Correcto."],["C","Deserts","No."],["D","Snow peaks","No."]],"a":"B","fb":"Pacific region is very rainy, with rich Afro-Colombian culture."},
    {"c":"In Barranquilla, their home region.","e":"The Caribbean region is characterized by ___.","opts":[["A","Cold climate","No, warm."],["B","Warm weather, beaches, and Carnival","Correcto."],["C","Deserts","No."],["D","High mountains","No."]],"a":"B","fb":"Caribbean region is warm, with beautiful beaches and famous Carnival."},
    {"c":"In Bucaramanga they learn about the Orinoqu\u00eda.","e":"Economic activity in the Llanos Orientales?","opts":[["A","Mining","Some."],["B","Cattle ranching and oil","Correcto."],["C","Fishing","Limited."],["D","Manufacturing","No."]],"a":"B","fb":"Orinoqu\u00eda is known for cattle ranching and oil extraction."},
    {"c":"In Cartagena they study maritime borders.","e":"Colombia has sovereignty over islands in the ___.","opts":[["A","Pacific only","No."],["B","Caribbean and Pacific","Correcto."],["C","Atlantic only","No."],["D","Indian Ocean","No."]],"a":"B","fb":"Colombia has Caribbean islands (San Andr\u00e9s, Providencia) and Pacific islands (Gorgona, Malpelo)."},
    {"c":"In Pereira they study the coffee axis.","e":"The Eje Cafetero includes which departments?","opts":[["A","Caldas, Quind\u00edo, Risaralda","Correcto."],["B","Antioquia, Boyac\u00e1","No."],["C","Cundinamarca, Tolima","No."],["D","Valle, Cauca","No."]],"a":"A","fb":"Eje Cafetero = Caldas, Quind\u00edo, Risaralda. Famous for coffee production."},
    {"c":"In Manizales they study climate zones.","e":"Manizales (2,150 m) is in which thermal floor?","opts":[["A","C\u00e1lido","0-1,000 m."],["B","Templado","1,000-2,000 m."],["C","Fr\u00edo","2,000-3,000 m."],["D","P\u00e1ramo","3,000+ m."]],"a":"C","fb":"Thermal floors: c\u00e1lido (0-1000m), templado (1000-2000m), fr\u00edo (2000-3000m), p\u00e1ramo (3000+)."},
    {"c":"In C\u00facuta they study borders.","e":"Colombia borders how many countries?","opts":[["A","3","No."],["B","4","No."],["C","5","Correcto."],["D","6","No."]],"a":"C","fb":"Colombia borders: Venezuela, Brazil, Peru, Ecuador, and Panama."},
    {"c":"In Ibagu\u00e9 they study rivers.","e":"The longest river in Colombia is ___.","opts":[["A","Cauca","No."],["B","Atrato","No."],["C","Magdalena","Correcto."],["D","Meta","No."]],"a":"C","fb":"The Magdalena River is ~1,528 km long, the longest entirely in Colombia."},
]
print("Added 6_sociales-ciudadanas_P2")

# === GRADE 6 - SOCIALES P3 (Constitution 1991) ===
Q['6_sociales-ciudadanas_P3'] = [
    {"c":"In class in Bogot\u00e1 they study the Constitution.","e":"What year was Colombia's current constitution approved?","opts":[["A","1886","Previous."],["B","1991","Correcto."],["C","2000","No."],["D","1819","No."]],"a":"B","fb":"The 1991 Constitution replaced the 1886 Constitution."},
    {"c":"In Medell\u00edn they learn about rights.","e":"The Constitution defines Colombia as a ___.","opts":[["A","Monarchy","No."],["B","State of Law and Social State","Correcto."],["C","Military dictatorship","No."],["D","Colony","No."]],"a":"B","fb":"Colombia is a 'Estado Social de Derecho' under the 1991 Constitution."},
    {"c":"In Cali they study branches of power.","e":"How many branches of public power in Colombia?","opts":[["A","Two","No."],["B","Three","Correcto."],["C","Four","No."],["D","Five","No."]],"a":"B","fb":"Three branches: Executive, Legislative, Judicial."},
    {"c":"In Barranquilla they identify each branch.","e":"Who leads the Executive branch?","opts":[["A","Congress","Legislative."],["B","President","Correcto."],["C","Supreme Court","Judicial."],["D","Mayor","Local."]],"a":"B","fb":"Executive is led by the President, who is both head of state and government."},
    {"c":"In Bucaramanga they study fundamental rights.","e":"Which is a fundamental right in the Constitution?","opts":[["A","Right to own a car","No."],["B","Right to life","Correcto."],["C","Right to unlimited internet","No."],["D","Right to drive","No."]],"a":"B","fb":"Life is the first fundamental right protected in the Constitution."},
    {"c":"In Cartagena they study mechanisms of participation.","e":"Voting is a mechanism of ___.","opts":[["A","Judicial control","No."],["B","Citizen participation","Correcto."],["C","Police action","No."],["D","Tax collection","No."]],"a":"B","fb":"Voting, plebiscite, referendum, and popular consultation are participation mechanisms."},
    {"c":"In Pereira they learn about tutela.","e":"Acci\u00f3n de Tutela protects ___.","opts":[["A","Property rights","No."],["B","Fundamental rights","Correcto."],["C","Tax collection","No."],["D","Environmental protection","No."]],"a":"B","fb":"Tutela is a mechanism to protect fundamental rights when they are violated."},
    {"c":"In Manizales they study decentralization.","e":"Colombia is divided into how many departments?","opts":[["A","28","No."],["B","32","Correcto."],["C","35","No."],["D","25","No."]],"a":"B","fb":"Colombia has 32 departments plus the Capital District (Bogot\u00e1)."},
    {"c":"In C\u00facuta they study constitutional reform.","e":"Who can propose constitutional reforms?","opts":[["A","Only the president","No."],["B","Congress, government, or citizens","Correcto."],["C","Only judges","No."],["D","Only governors","No."]],"a":"B","fb":"Constitutional reform can be proposed by Congress, the Government, or citizens."},
    {"c":"In Ibagu\u00e9 they reflect on citizenship.","e":"A citizen is someone who ___.","opts":[["A","Only pays taxes","No."],["B","Has rights and duties in a country","Correcto."],["C","Lives in the city","No."],["D","Is an adult","No."]],"a":"B","fb":"Citizenship means having both rights and responsibilities within a state."},
]
print("Added 6_sociales-ciudadanas_P3")

# === GRADE 6 - SOCIALES P4 (Conflict resolution) ===
Q['6_sociales-ciudadanas_P4'] = [
    {"c":"In class in Bogot\u00e1 they study conflict.","e":"What is conflict?","opts":[["A","Always violent","No."],["B","A disagreement or clash of interests","Correcto."],["C","Only physical fights","No."],["D","Something to avoid always","No."]],"a":"B","fb":"Conflict is natural; it becomes negative when not managed properly."},
    {"c":"In Medell\u00edn they learn negotiation.","e":"Win-win negotiation means ___.","opts":[["A","One side wins","No."],["B","Both sides benefit","Correcto."],["C","Nobody wins","No."],["D","The mediator wins","No."]],"a":"B","fb":"Win-win: finding a solution that satisfies both parties."},
    {"c":"In Cali they practice mediation.","e":"A mediator is a ___.","opts":[["A","Judge who decides","No."],["B","Neutral third party who helps reach agreement","Correcto."],["C","Lawyer","No."],["D","Police officer","No."]],"a":"B","fb":"Mediator facilitates communication but does not impose a solution."},
    {"c":"In Barranquilla they identify types of violence.","e":"Insults and humiliation are forms of ___ violence.","opts":[["A","Physical","No."],["B","Verbal/psychological","Correcto."],["C","Economic","No."],["D","Sexual","No."]],"a":"B","fb":"Verbal/psychological violence includes insults, threats, and humiliation."},
    {"c":"In Bucaramanga they study peacebuilding.","e":"What does 'culture of peace' promote?","opts":[["A","Violence","No."],["B","Dialogue and respect","Correcto."],["C","War","No."],["D","Revenge","No."]],"a":"B","fb":"Culture of peace: resolving differences through dialogue, respect, and non-violence."},
    {"c":"In Cartagena they learn about bullying.","e":"Bullying is repeated ___.","opts":[["A","Accidental harm","No."],["B","Aggressive behavior with power imbalance","Correcto."],["C","Friendly teasing","No."],["D","Competition","No."]],"a":"B","fb":"Bullying = intentional, repeated, and involves a power imbalance."},
    {"c":"In Pereira they practice active listening.","e":"Active listening means ___.","opts":[["A","Pretending to listen","No."],["B","Paying full attention and understanding","Correcto."],["C","Interrupting","No."],["D","Ignoring","No."]],"a":"B","fb":"Active listening: focus fully, understand, respond thoughtfully."},
    {"c":"In Manizales they study restorative justice.","e":"Restorative justice focuses on ___.","opts":[["A","Punishment only","No."],["B","Repairing harm and reconciliation","Correcto."],["C","Revenge","No."],["D","Ignoring the problem","No."]],"a":"B","fb":"Restorative justice seeks to repair harm and restore relationships."},
    {"c":"In C\u00facuta they study Colombia's peace process.","e":"What did the 2016 peace agreement seek?","opts":[["A","Start a war","No."],["B","End conflict with FARC","Correcto."],["C","Create more weapons","No."],["D","Divide the country","No."]],"a":"B","fb":"The 2016 peace agreement aimed to end the armed conflict with the FARC."},
    {"c":"In Ibagu\u00e9 they reflect on skills.","e":"Which skill helps resolve conflicts peacefully?","opts":[["A","Shouting","No."],["B","Empathy","Correcto."],["C","Fighting","No."],["D","Avoidance","No."]],"a":"B","fb":"Empathy (understanding others' feelings) helps find peaceful solutions."},
]
print("Added 6_sociales-ciudadanas_P4")

with open('_questions_data_full.json', 'w', encoding='utf-8') as f:
    json.dump(Q, f, ensure_ascii=False, indent=2)
print(f"Saved. Total keys: {len(Q)}")
