#!/usr/bin/env python3
"""Add Grade 6 Reading, Math, Science to _questions_data_full.json"""
import json

with open('_questions_data_full.json', encoding='utf-8') as f:
    Q = json.load(f)

# === GRADE 6 - LECTURA CRITICA P1 (Narrative texts) ===
Q['6_lectura-critica_P1'] = [
    {"c":"In Bogot\u00e1, students read a story about a boy who finds a hidden treasure in Monserrate.","e":"What type of text is a story with characters and a plot?","opts":[["A","Informative","No, that gives facts."],["B","Narrative","Correcto."],["C","Argumentative","No, persuades."],["D","Descriptive","No, describes."]],"a":"B","fb":"Narrative texts tell stories with characters, setting, and plot (beginning, middle, end)."},
    {"c":"In class in Medell\u00edn, the teacher asks about story elements.","e":"What is the 'setting' of a story?","opts":[["A","The characters","No."],["B","The problem","No."],["C","Where and when the story happens","Correcto."],["D","The ending","No."]],"a":"C","fb":"Setting = time and place where the story occurs."},
    {"c":"Students in Cali read 'El ahogado m\u00e1s hermoso del mundo' by M\u00e1rquez.","e":"In a narrative, what is the climax?","opts":[["A","The beginning","No."],["B","The highest point of tension","Correcto."],["C","The resolution","No."],["D","The introduction","No."]],"a":"B","fb":"Climax is the moment of greatest tension in the story, before the resolution."},
    {"c":"In Barranquilla they analyze 'La siesta del martes'.","e":"Who tells the story in first-person narration?","opts":[["A","An outside observer","No, third person."],["B","A character in the story","Correcto."],["C","A camera","No."],["D","The author directly","No."]],"a":"B","fb":"First-person narrator uses 'I' or 'we', is a character within the story."},
    {"c":"In Bucaramanga, they compare text types.","e":"'Once upon a time' typically starts what kind of text?","opts":[["A","News article","No."],["B","Fairy tale","Correcto."],["C","Scientific report","No."],["D","Recipe","No."]],"a":"B","fb":"Fairy tales and narratives often begin with 'Once upon a time' or '\u00c9rase una vez'."},
    {"c":"In Cartagena, students identify plot structure.","e":"What is the correct order of plot elements?","opts":[["A","Exposition, climax, resolution","No."],["B","Exposition, rising action, climax, falling action, resolution","Correcto."],["C","Climax, resolution, exposition","No."],["D","Rising action, exposition, falling action","No."]],"a":"B","fb":"Plot structure: exposition, rising action, climax, falling action, resolution."},
    {"c":"In Pereira they analyze character development.","e":"A character who changes during the story is called ___.","opts":[["A","Static","No, doesn't change."],["B","Flat","No, one-dimensional."],["C","Dynamic","Correcto."],["D","Minor","No."]],"a":"C","fb":"Dynamic characters change through the story; static characters remain the same."},
    {"c":"In Manizales they examine dialogue.","e":"In written stories, what punctuation marks dialogue?","opts":[["A","Parentheses","No."],["B","Quotation marks or guiones","Correcto."],["C","Commas","No."],["D","Colons","No."]],"a":"B","fb":"Dialogue is marked with quotation marks (\" \") or em dashes (\u2014) in Spanish."},
    {"c":"In C\u00facuta compare short story vs novel.","e":"A short story is different from a novel because it has ___.","opts":[["A","More characters","No, less."],["B","A simpler plot and fewer pages","Correcto."],["C","No ending","No, it does."],["D","No conflict","No."]],"a":"B","fb":"Short stories are shorter, with fewer characters and a simpler plot structure."},
    {"c":"In Ibagu\u00e9, they create their own narrative.","e":"To create suspense, a writer should ___.","opts":[["A","Reveal everything immediately","No."],["B","Use cliffhangers and pacing","Correcto."],["C","Describe only the setting","No."],["D","Skip the problem","No."]],"a":"B","fb":"Suspense is created through pacing, cliffhangers, and withholding some information."},
]
print("Added 6_lectura-critica_P1")

# === GRADE 6 - LECTURA CRITICA P2 (Informative texts) ===
Q['6_lectura-critica_P2'] = [
    {"c":"In Bogot\u00e1, the teacher presents a news article about the Bogot\u00e1 River.","e":"What is the main purpose of an informative text?","opts":[["A","Entertain","No."],["B","Inform or explain","Correcto."],["C","Persuade","No."],["D","Sell a product","No."]],"a":"B","fb":"Informative texts aim to provide factual information about a topic."},
    {"c":"Students in Medell\u00edn read a newspaper article.","e":"What is the 'lead' in a news article?","opts":[["A","The headline only","No."],["B","First paragraph with key info (who, what, when, where, why)","Correcto."],["C","The conclusion","No."],["D","The author's photo","No."]],"a":"B","fb":"The lead is the first paragraph answering the 5 Ws: who, what, when, where, why."},
    {"c":"In Cali they read an encyclopedia entry about the Cauca River.","e":"Which text feature helps find information quickly in textbooks?","opts":[["A","Illustrations","Helpful."],["B","Table of contents and index","Correcto."],["C","Font size","No."],["D","Margin size","No."]],"a":"B","fb":"Table of contents and index help locate specific information in books."},
    {"c":"In Barranquilla they analyze a report on climate change.","e":"What makes a source reliable?","opts":[["A","It is from a blog","No."],["B","It has facts, citations, and expert authors","Correcto."],["C","It is old","No."],["D","It uses informal language","No."]],"a":"B","fb":"Reliable sources have verified facts, expert authors, and proper citations."},
    {"c":"In Bucaramanga they read an infographic about the Amazon.","e":"What is the purpose of a graph in an informative text?","opts":[["A","Decorate the page","No."],["B","Present data visually","Correcto."],["C","Fill space","No."],["D","Confuse the reader","No."]],"a":"B","fb":"Graphs and charts present data in a clear, visual format for better understanding."},
    {"c":"In Cartagena, they distinguish fact vs opinion.","e":"Which is a FACT?","opts":[["A","Bogot\u00e1 is the best city","Opinion."],["B","Bogot\u00e1 is the capital of Colombia","Correcto."],["C","Colombian coffee is delicious","Opinion."],["D","Carnival is fun","Opinion."]],"a":"B","fb":"Facts can be verified. 'Bogot\u00e1 is the capital' is verifiable; 'best' is an opinion."},
    {"c":"In Pereira they compare text structures.","e":"'Cause and effect' is an example of text ___.","opts":[["A","genre","No."],["B","structure","Correcto."],["C","purpose","No."],["D","style","No."]],"a":"B","fb":"Text structures include: cause/effect, compare/contrast, sequence, problem/solution."},
    {"c":"In Manizales they read a scientific article about p\u00e1ramos.","e":"Technical vocabulary in informative texts is called ___.","opts":[["A","Slang","No."],["B","Jargon","Correcto."],["C","Dialect","No."],["D","Colloquialism","No."]],"a":"B","fb":"Jargon is specialized vocabulary used in a particular field (e.g., 'ecosystem')."},
    {"c":"In C\u00facuta, examine a timeline of Colombian independence.","e":"A timeline presents information in ___ order.","opts":[["A","Alphabetical","No."],["B","Chronological","Correcto."],["C","Spatial","No."],["D","Random","No."]],"a":"B","fb":"Timelines show events in chronological (time) order."},
    {"c":"In Ibagu\u00e9 they summarize a text.","e":"A good summary should ___.","opts":[["A","Include every detail","No, too long."],["B","Only include main ideas","Correcto."],["C","Add personal opinions","No."],["D","Change the facts","No."]],"a":"B","fb":"Summaries condense the main ideas without adding personal opinions."},
]
print("Added 6_lectura-critica_P2")

# === GRADE 6 - LECTURA CRITICA P3 (Literal and inferential comprehension) ===
Q['6_lectura-critica_P3'] = [
    {"c":"In Bogot\u00e1, students read: 'The boy cried because his dog ran away.'","e":"The boy cried. Is this literal or inferential?","opts":[["A","Inferential","No, it's directly stated."],["B","Literal","Correcto."],["C","Critical","No."],["D","Invisible","No."]],"a":"B","fb":"Literal comprehension = information directly stated in the text."},
    {"c":"In Medell\u00edn they read: 'Mar\u00eda saw dark clouds gather.'","e":"What can you INFER will happen?","opts":[["A","It might rain","Correcto."],["B","Mar\u00eda will sing","No."],["C","The sun will shine","No."],["D","It will snow in Medell\u00edn","No."]],"a":"A","fb":"Inference uses text clues + prior knowledge. Dark clouds suggest rain."},
    {"c":"In Cali, they read a dialogue between two friends.","e":"If a friend says 'I'm fine' but looks sad, what do you infer?","opts":[["A","He is happy","Contradicts."],["B","He might not be telling the truth","Correcto."],["C","He is hungry","No."],["D","He needs water","No."]],"a":"B","fb":"Inference: words say one thing, but tone and body language say another."},
    {"c":"In Barranquilla they practice making predictions.","e":"Prediction during reading is a type of ___.","opts":[["A","Literal reading","No."],["B","Inference","Correcto."],["C","Memorization","No."],["D","Recitation","No."]],"a":"B","fb":"Predicting is an inferential skill: using clues to guess what comes next."},
    {"c":"In a fable in Bucaramanga: 'The tortoise wins the race.'","e":"What is the main idea of this fable?","opts":[["A","Tortoises are fast","No."],["B","Slow and steady wins the race","Correcto."],["C","Rabbits are lazy","No."],["D","Tortoises don't like races","No."]],"a":"B","fb":"Main idea = the central message. Fables often end with a moral."},
    {"c":"In Cartagena they identify supporting details.","e":"'The Amazon River is 6,400 km long.' This is a ___.","opts":[["A","Main idea","No."],["B","Supporting detail","Correcto."],["C","Opinion","It's a fact."],["D","Title","No."]],"a":"B","fb":"Supporting details provide evidence or elaboration for the main idea."},
    {"c":"In Pereira, the teacher asks about implicit meaning.","e":"'He slammed the door.' This suggests the character is ___.","opts":[["A","Happy","No."],["B","Angry or upset","Correcto."],["C","Tired","No."],["D","Hungry","No."]],"a":"B","fb":"Implicit meaning: actions and descriptions convey emotions indirectly."},
    {"c":"In Manizales, compare literal vs figurative.","e":"'It's raining cats and dogs' is ___.","opts":[["A","Literal","No, idiom."],["B","Figurative","Correcto, idiom."],["C","Informational","No."],["D","Narrative","No."]],"a":"B","fb":"Figurative language uses metaphors, idioms, and similes, not literal meaning."},
    {"c":"In C\u00facuta they analyze author's purpose.","e":"A text trying to convince you to recycle has purpose: ___.","opts":[["A","Inform","Maybe."],["B","Persuade","Correcto."],["C","Entertain","No."],["D","Describe","No."]],"a":"B","fb":"Author's purpose: inform, persuade, entertain (IPE). This text wants to persuade."},
    {"c":"In Ibagu\u00e9 they evaluate arguments.","e":"'All dogs are dangerous' is an example of ___.","opts":[["A","Fact","No."],["B","Generalization","Correcto (overgeneralization)."],["C","Specific detail","No."],["D","Neutral statement","No."]],"a":"B","fb":"Overgeneralization uses words like 'all', 'never', 'always' without evidence."},
]
print("Added 6_lectura-critica_P3")

# === GRADE 6 - LECTURA CRITICA P4 (Introduction to argumentation) ===
Q['6_lectura-critica_P4'] = [
    {"c":"In Bogot\u00e1 they analyze: 'School uniforms should be mandatory.'","e":"This statement is an example of an ___.","opts":[["A","Opinion","Partially."],["B","Argument","Correcto."],["C","Fact","No."],["D","Question","No."]],"a":"B","fb":"An argument states a position and is supported by reasons and evidence."},
    {"c":"Students in Medell\u00edn learn argument structure.","e":"What are the three parts of an argument?","opts":[["A","Introduction, body, conclusion","No."],["B","Claim, evidence, reasoning","Correcto."],["C","Nouns, verbs, adjectives","No."],["D","Title, images, caption","No."]],"a":"B","fb":"Argument structure: Claim (thesis), Evidence (facts/examples), Reasoning (explanation)."},
    {"c":"In Cali debate: 'Social media is harmful to teens.'","e":"What would be strong evidence for this claim?","opts":[["A","'I don't like social media'","Opinion."],["B","'Studies show increased anxiety in teens using social media'","Correcto."],["C","'My friend says it's bad'","Anecdotal."],["D","'Social media has colors'","Irrelevant."]],"a":"B","fb":"Strong evidence comes from studies, statistics, or expert sources."},
    {"c":"In Barranquilla they identify counterarguments.","e":"A counterargument is ___.","opts":[["A","Your main claim","No."],["B","An opposing viewpoint","Correcto."],["C","The conclusion","No."],["D","The introduction","No."]],"a":"B","fb":"Counterarguments anticipate what someone who disagrees might say."},
    {"c":"In Bucaramanga they learn persuasive language.","e":"'You must act NOW!' uses which persuasive technique?","opts":[["A","Facts and data","No."],["B","Imperative and urgency","Correcto."],["C","Humor","No."],["D","Question","No."]],"a":"B","fb":"Imperatives and urgency create a call to action, common in persuasion."},
    {"c":"In Cartagena analyze an editorial.","e":"Where should a thesis statement appear in an essay?","opts":[["A","At the end","Can be."],["B","In the introduction","Correcto (typically)."],["C","In the middle","No."],["D","Never","No."]],"a":"B","fb":"The thesis statement typically appears at the end of the introductory paragraph."},
    {"c":"In Pereira, identify logical fallacies.","e":"'Everyone does it, so it's OK.' This is a ___.","opts":[["A","Valid argument","No."],["B","Bandwagon fallacy","Correcto."],["C","Scientific fact","No."],["D","Example","No."]],"a":"B","fb":"Bandwagon fallacy: arguing something is right because 'everyone does it'."},
    {"c":"In Manizales they learn about bias.","e":"Bias in a text means ___.","opts":[["A","Objective perspective","No."],["B","One-sided or unbalanced viewpoint","Correcto."],["C","Complete neutrality","No."],["D","More citations","No."]],"a":"B","fb":"Bias shows preference for one side, lacking neutrality."},
    {"c":"In C\u00facuta compare persuasion vs manipulation.","e":"Manipulation differs from persuasion because it ___.","opts":[["A","Uses facts","No."],["B","Deceives or misleads","Correcto."],["C","Respects choices","No."],["D","Provides evidence","No."]],"a":"B","fb":"Manipulation tricks people; persuasion respects their ability to choose."},
    {"c":"In Ibagu\u00e9 they write a simple argumentative paragraph.","e":"A good argumentative paragraph begins with ___.","opts":[["A","A question","Optional."],["B","A topic sentence stating the claim","Correcto."],["C","A picture","No."],["D","A quote","Optional."]],"a":"B","fb":"Topic sentence introduces the paragraph's main claim, followed by supporting evidence."},
]
print("Added 6_lectura-critica_P4")

with open('_questions_data_full.json', 'w', encoding='utf-8') as f:
    json.dump(Q, f, ensure_ascii=False, indent=2)
print(f"Saved. Total keys: {len(Q)}")
