#!/usr/bin/env python3
"""Step 1: Build G3 questions and save to _questions_data_full.json"""
import json

Q = {}

# === GRADE 3 - LENGUA ===
Q["3_lengua_P1"] = [
    {"c": "En la clase de lengua del Colegio Sim\u00f3n Bol\u00edvar en Bogot\u00e1, la profesora Carolina escribe MARIPOSA en el tablero.", "e": "\u00bfCu\u00e1ntas s\u00edlabas tiene la palabra MARIPOSA?", "opts": [["A","2","Incorrecto."],["B","3","Incorrecto."],["C","4","Correcto. MA-RI-PO-SA tiene cuatro s\u00edlabas."],["D","5","Incorrecto."]], "a": "C", "fb": "MARIPOSA tiene cuatro s\u00edlabas."},
    {"c": "En Medell\u00edn piden escribir oraciones con 'sol'.", "e": "\u00bfCu\u00e1l es una ORACI\u00d3N completa?", "opts": [["A","El sol","Incorrecto. No tiene verbo."],["B","Sol brilla","Incorrecto. Falta art\u00edculo."],["C","El sol brilla fuerte.","Correcto. Sujeto+verbo+complemento."],["D","Brilla","Incorrecto. Solo es un verbo."]], "a": "C", "fb": "Una oraci\u00f3n completa tiene sujeto y verbo."},
    {"c": "En Cali leen La tortuga y la liebre.", "e": "Seg\u00fan el cuento, \u00bfpor qu\u00e9 gan\u00f3 la tortuga?", "opts": [["A","Era m\u00e1s r\u00e1pida","Incorrecto."],["B","La liebre se durmi\u00f3","Incorrecto. La raz\u00f3n es la constancia."],["C","Fue constante y nunca se rindi\u00f3","Correcto."],["D","El camino era corto","Incorrecto."]], "a": "C", "fb": "Moraleja: la constancia es m\u00e1s importante que la velocidad."},
    {"c": "En Barranquilla aprenden tipos de palabras.", "e": "\u00bfCu\u00e1l es un SUSTANTIVO?", "opts": [["A","Correr","Verbo."],["B","Hermoso","Adjetivo."],["C","Escuela","Correcto. Nombra un lugar."],["D","R\u00e1pidamente","Adverbio."]], "a": "C", "fb": "Los sustantivos nombran personas, animales, lugares o cosas."},
    {"c": "En la biblioteca de Bucaramanga.", "e": "Toby enterr\u00f3 el hueso: \u00bfd\u00f3nde?", "opts": [["A","En la casa","No."],["B","En el jard\u00edn","Lo encontr\u00f3 ah\u00ed."],["C","Debajo de un \u00e1rbol","Correcto. El texto lo dice."],["D","En su cama","No se menciona."]], "a": "C", "fb": "Comprensi\u00f3n literal: recordar informaci\u00f3n expl\u00edcita."},
    {"c": "En Cartagena ordenan palabras.", "e": "Ordena: juega - parque - en - el - Mar\u00eda", "opts": [["A","Mar\u00eda juega en el parque.","Correcto."],["B","El parque juega Mar\u00eda en.","Incorrecto."],["C","Juega Mar\u00eda parque el en.","Incorrecto."],["D","En juega Mar\u00eda el parque.","Incorrecto."]], "a": "A", "fb": "Orden: sujeto+verbo+complemento."},
    {"c": "En Pereira explican ant\u00f3nimos.", "e": "Ant\u00f3nimo de grande?", "opts": [["A","Enorme","Sin\u00f3nimo."],["B","Gigante","Sin\u00f3nimo."],["C","Peque\u00f1o","Correcto."],["D","Mediano","No es opuesto."]], "a": "C", "fb": "Los ant\u00f3nimos tienen significados opuestos."},
    {"c": "En Manizales preguntan plural.", "e": "Plural de l\u00e1piz?", "opts": [["A","L\u00e1pizes","Incorrecto."],["B","L\u00e1pices","Correcto. Z\u2192C+es."],["C","L\u00e1pis","No existe."],["D","L\u00e1pi","No existe."]], "a": "B", "fb": "Palabras terminadas en Z: cambian Z por C y agregan -es."},
    {"c": "En C\u00facuta leen un poema.", "e": "El viento baila... \u00bfQu\u00e9 figura literaria?", "opts": [["A","Comparaci\u00f3n","No usa como."],["B","Personificaci\u00f3n","Correcto."],["C","Rima","No riman."],["D","Exageraci\u00f3n","No exagera."]], "a": "B", "fb": "Personificaci\u00f3n: atribuir acciones humanas a elementos naturales."},
    {"c": "En Ibagu\u00e9 identifican sujeto.", "e": "Sujeto de 'Los ni\u00f1os alegres juegan en el patio'?", "opts": [["A","juegan","Verbo."],["B","en el patio","Complemento."],["C","Los ni\u00f1os alegres","Correcto."],["D","Los ni\u00f1os","Incompleto."]], "a": "C", "fb": "El sujeto indica qui\u00e9n realiza la acci\u00f3n."},
]

Q["3_lengua_P2"] = [
    {"c": "En Bogot\u00e1 leen Los tres cerditos.", "e": "\u00bfPor qu\u00e9 no pudo el lobo derribar la casa de ladrillos?", "opts": [["A","Estaba cansado","No."],["B","La casa era peque\u00f1a","No."],["C","Los ladrillos eran resistentes","Correcto."],["D","Los cerditos lo enga\u00f1aron","No."]], "a": "C", "fb": "Materiales resistentes protegen mejor."},
    {"c": "En Medell\u00edn leen Caperucita Roja.", "e": "\u00bfQui\u00e9n enga\u00f1a a Caperucita?", "opts": [["A","Su abuelita","No."],["B","El lobo","Correcto."],["C","El cazador","No, ayuda."],["D","Su mam\u00e1","No, advierte."]], "a": "B", "fb": "El lobo es el antagonista que enga\u00f1a."},
    {"c": "En Cali leen la f\u00e1bula del le\u00f3n y el rat\u00f3n.", "e": "\u00bfC\u00f3mo ayuda el rat\u00f3n al le\u00f3n?", "opts": [["A","Le trae comida","No."],["B","Ruge fuerte","No puede."],["C","Roer la red que atrapaba al le\u00f3n","Correcto."],["D","Llama a otros","No."]], "a": "C", "fb": "No subestimes a los peque\u00f1os, todos pueden ayudar."},
    {"c": "En Barranquilla leen El patito feo.", "e": "\u00bfC\u00f3mo se sent\u00eda el patito al principio?", "opts": [["A","Feliz","No."],["B","Triste porque se burlaban de \u00e9l","Correcto."],["C","Enojado con mam\u00e1","No."],["D","Orgulloso","No."]], "a": "B", "fb": "El cuento trata sobre aceptaci\u00f3n y autoestima."},
    {"c": "En Bucaramanga analizan La liebre y la tortuga.", "e": "\u00bfQu\u00e9 hizo mal la liebre?", "opts": [["A","Tom\u00f3 mal camino","No."],["B","Se durmi\u00f3","Correcto."],["C","Se cay\u00f3","No."],["D","Ayud\u00f3 a otro","No."]], "a": "B", "fb": "La confianza excesiva lleva a errores."},
    {"c": "En Cartagena ordenan eventos.", "e": "Primer evento de Los tres cerditos?", "opts": [["A","El lobo derrib\u00f3 la casa de paja","Despu\u00e9s."],["B","Los cerditos construyeron sus casas","Correcto."],["C","El lobo cay\u00f3 al agua","Final."],["D","Huyeron a casa del mayor","Despu\u00e9s."]], "a": "B", "fb": "Secuencia narrativa: primero construyen."},
    {"c": "En Pereira identifican personajes.", "e": "\u00bfQui\u00e9n NO aparece en Caperucita Roja?", "opts": [["A","La abuelita","S\u00ed aparece."],["B","El lobo","S\u00ed."],["C","El cazador","S\u00ed."],["D","El le\u00f1ador","Correcto. No aparece."]], "a": "D", "fb": "Identificar personajes ayuda a comprender la historia."},
    {"c": "En Manizales preguntan sobre cuentos.", "e": "\u00bfQu\u00e9 tipo de texto es un cuento?", "opts": [["A","Informativo","No."],["B","Narrativo","Correcto."],["C","Noticia","No."],["D","Poema","No."]], "a": "B", "fb": "Los cuentos narran historias con personajes y eventos."},
    {"c": "En C\u00facuta analizan el mensaje.", "e": "Mensaje de El patito feo?", "opts": [["A","Patos vs cisnes","No."],["B","Ser como los dem\u00e1s","No."],["C","La verdadera belleza es ser uno mismo","Correcto."],["D","Cisnes son m\u00e1s bonitos","No."]], "a": "C", "fb": "Aceptarnos como somos, nuestras diferencias nos hacen \u00fanicos."},
    {"c": "En Ibagu\u00e9 crean cuentos.", "e": "\u00bfQu\u00e9 debe tener un cuento completo?", "opts": [["A","Solo personajes","No."],["B","Inicio, nudo y desenlace","Correcto."],["C","Solo ilustraciones","No."],["D","Final triste","No."]], "a": "B", "fb": "Estructura b\u00e1sica: inicio (presentaci\u00f3n), nudo (conflicto), desenlace (soluci\u00f3n)."},
]

# === GRADE 3 - MATEMATICAS ===
Q["3_matematicas_P1"] = [
    {"c": "En el mercado de Paloquemao en Bogot\u00e1, Do\u00f1a Mar\u00eda vende 345 manzanas y 432 naranjas.", "e": "\u00bfCu\u00e1ntas frutas tiene en total?", "opts": [["A","700","No, 345+432=777."],["B","777","Correcto."],["C","787","No."],["D","677","No."]], "a": "B", "fb": "345+432=777. Se suman unidades, decenas y centenas."},
    {"c": "Un vendedor en Medell\u00edn tiene 650 globos, vende 280.", "e": "\u00bfCu\u00e1ntos le quedan?", "opts": [["A","430","No."],["B","370","Correcto. 650-280=370."],["C","330","No."],["D","470","No."]], "a": "B", "fb": "650-280=370. Se restan unidades, decenas y centenas."},
    {"c": "En Cali, la profe muestra el 582.", "e": "\u00bfValor de la cifra 8 en 582?", "opts": [["A","8","No, est\u00e1 en decenas."],["B","80","Correcto. 8 decenas = 80."],["C","800","No, eso ser\u00edan centenas."],["D","88","No."]], "a": "B", "fb": "Valor posicional: 5=500, 8=80, 2=2."},
    {"c": "En Barranquilla comparan n\u00fameros.", "e": "\u00bfCu\u00e1l es el MAYOR: 345, 453, 543, 534?", "opts": [["A","345","No."],["B","453","No."],["C","543","Correcto. Tiene 5 centenas."],["D","534","No, 543>534."]], "a": "C", "fb": "Comparar centenas, luego decenas, luego unidades."},
    {"c": "En la biblioteca de Bucaramanga.", "e": "234 libros + 125 libros = ?", "opts": [["A","359","Correcto."],["B","349","No."],["C","369","No."],["D","259","No."]], "a": "A", "fb": "234+125=359."},
    {"c": "En Cartagena, 5 bolsas con 10 canicas cada una.", "e": "\u00bfCu\u00e1ntas canicas en total?", "opts": [["A","15","No, 5x10=50."],["B","50","Correcto."],["C","500","No."],["D","25","No."]], "a": "B", "fb": "5x10=50. La multiplicaci\u00f3n es suma repetida."},
    {"c": "En Pereira, la profe escribe 300.", "e": "\u00bfCu\u00e1ntas centenas tiene 300?", "opts": [["A","0","No."],["B","3","Correcto. 300=3 centenas."],["C","30","No, 30 centenas=3000."],["D","300","No."]], "a": "B", "fb": "Una centena=100 unidades. 300=3 centenas."},
    {"c": "En Manizales, 9 filas con 5 naranjas.", "e": "\u00bfCu\u00e1ntas naranjas?", "opts": [["A","14","No."],["B","40","No."],["C","45","Correcto. 9x5=45."],["D","50","No."]], "a": "C", "fb": "9x5=45, representa 9 grupos de 5."},
    {"c": "En C\u00facuta ordenan: 215, 152, 521, 125.", "e": "Orden de menor a mayor?", "opts": [["A","125, 152, 215, 521","Correcto."],["B","521, 215, 152, 125","Mayor a menor."],["C","125, 215, 152, 521","No."],["D","152, 125, 215, 521","No."]], "a": "A", "fb": "Comparar centenas, decenas, unidades."},
    {"c": "En Ibagu\u00e9 descomponen 736.", "e": "Descomposici\u00f3n correcta de 736?", "opts": [["A","700+30+6","Correcto."],["B","700+36","No."],["C","736","No."],["D","700+300+6","No."]], "a": "A", "fb": "736=7 centenas+3 decenas+6 unidades=700+30+6."},
]

with open("_questions_data_full.json", "w", encoding="utf-8") as f:
    json.dump(Q, f, ensure_ascii=False, indent=2)
print(f"Built {len(Q)} question sets, saved to _questions_data_full.json")
