#!/usr/bin/env python3
"""
Mass generator for Ciencias Naturales Weekly Packs G3, G4, G5 W01-W40.
Uses template-driven question generation with topic-specific content.
"""
import os, random, textwrap, hashlib

random.seed(2026)

BASE = "E:/scripts-python/worldexams/questions_data/colombia/ciencias-naturales"

CITIES = [
    ("Bogotá","Colegio La Salle en Bogotá"),
    ("Medellín","IE San José de Medellín"),
    ("Cali","Colegio Santa Cecilia de Cali"),
    ("Barranquilla","Escuela Normal Superior de Barranquilla"),
    ("Bucaramanga","Colegio San Pedro de Bucaramanga"),
    ("Cartagena","IE San Felipe de Cartagena"),
    ("Pereira","Colegio SURAMERICANA de Pereira"),
    ("Manizales","Escuela Normal Superior de Manizales"),
    ("Ibagué","Colegio San Simón de Ibagué"),
    ("Neiva","IE Santa Teresa de Neiva"),
    ("Sincelejo","Colegio Francisco de Paula Santander"),
    ("Valledupar","IE Alfonso López de Valledupar"),
    ("Riohacha","Colegio Nacional José María Córdoba"),
    ("Pasto","Colegio San Francisco Javier de Pasto"),
    ("Tunja","Escuela Normal Santiago de Tunja"),
    ("Cúcuta","Colegio San José de Cúcuta"),
    ("Leticia","Escuela Rural La Esperanza en Leticia"),
    ("Quibdó","IE Técnica de Quibdó, Chocó"),
    ("Mocoa","Escuela Ecológica de Mocoa, Putumayo"),
    ("San Andrés","Colegio Sagrado Corazón de San Andrés"),
]

def ctx():
    return random.choice(CITIES)

# ═══════════════════════════════════════════════════════════════════
# G3 TOPIC-SPECIFIC QUESTION DATA
# ═══════════════════════════════════════════════════════════════════
# Each segment has 40 questions (4 weeks x 10) stored as dicts

G3_QDATA = {
    "seres-vivos": {
        # 40 preguntas for W01-W04 (10 each)
        "q": [
            # W01
            {"bloom":"Remember","icfes":"Uso comprensivo del conocimiento científico","s":0.85,
             "stem":"¿Cuál de los siguientes es un ser vivo?",
             "opts":[("A)","Un gato","Los gatos nacen, crecen, se reproducen y mueren"),
              ("B)","Una piedra","Las piedras son objetos inertes"),
              ("C)","Una mesa","Las mesas son objetos inertes"),
              ("D)","Una silla","Las sillas son objetos inertes")]},
            {"bloom":"Remember","icfes":"Indagación y Comprensión","s":0.80,
             "stem":"¿Qué necesitan todos los seres vivos para vivir?",
             "opts":[("A)","Agua y alimento","Todos los seres vivos necesitan agua y alimento"),
              ("B)","Solo juguetes","Los juguetes no son necesarios"),
              ("C)","Un celular","Los celulares no son necesarios"),
              ("D)","Solo televisor","Los televisores no son necesarios")]},
            {"bloom":"Understand","icfes":"Explicación de fenómenos","s":0.75,
             "stem":"Un árbol crece más alto cada año. ¿Qué característica de los seres vivos se observa?",
             "opts":[("A)","Crece","El crecimiento es el aumento de tamaño en los seres vivos"),
              ("B)","Se reproduce","Crecer no es igual a reproducirse"),
              ("C)","Juega","Los árboles no juegan"),
              ("D)","Habla","Los árboles no hablan")]},
            {"bloom":"Understand","icfes":"Uso comprensivo del conocimiento científico","s":0.70,
             "stem":"¿Cómo se llama la capacidad de los seres vivos de reaccionar al ser tocados?",
             "opts":[("A)","Irritabilidad","Es la capacidad de responder a estímulos del ambiente"),
              ("B)","Crecimiento","El crecimiento es aumento de tamaño"),
              ("C)","Reproducción","Reproducción es crear nuevos seres"),
              ("D)","Digestión","Digestión es procesar alimentos")]},
            {"bloom":"Understand","icfes":"Indagación y Comprensión","s":0.65,
             "stem":"De esta lista: hormiga, libro, rosa, carro, pez. ¿Cuántos son seres vivos?",
             "opts":[("A)","3","Hormiga, rosa y pez son seres vivos"),
              ("B)","2","Revisa bien la lista, hay más"),
              ("C)","5","No todos son seres vivos"),
              ("D)","1","Hay más de uno")]},
            {"bloom":"Apply","icfes":"Formulación y Ejecución","s":0.60,
             "stem":"Si pones una semilla con tierra, agua y sol, ¿qué pasará?",
             "opts":[("A)","Germinará y crecerá","La semilla usa agua y sol para germinar"),
              ("B)","Se hará piedra","No se transforma en piedra"),
              ("C)","Desaparecerá","No desaparece"),
              ("D)","Se hará plástico","Eso no ocurre")]},
            {"bloom":"Apply","icfes":"Formulación y Ejecución","s":0.55,
             "stem":"Una mariposa pone huevos en una hoja. ¿Qué función vital realiza?",
             "opts":[("A)","Reproducción","Poner huevos para crear nuevas mariposas es reproducción"),
              ("B)","Nutrición","Nutrición es obtener alimento"),
              ("C)","Crecimiento","Crecimiento es aumentar de tamaño"),
              ("D)","Respiración","Respiración es intercambiar gases")]},
            {"bloom":"Analyze","icfes":"Razonamiento y Argumentación","s":0.50,
             "stem":"¿Por qué una lagartija busca el sol pero una estatua no?",
             "opts":[("A)","La lagartija es un ser vivo que necesita calor; la estatua es inerte","Los seres vivos responden a estímulos; los objetos inertes no"),
              ("B)","La estatua está cansada","Las estatuas no se cansan"),
              ("C)","La lagartija quiere jugar","Busca calor, no juego"),
              ("D)","La estatua está dormida","Las estatuas no duermen")]},
            {"bloom":"Analyze","icfes":"Explicación de fenómenos","s":0.50,
             "stem":"¿Por qué las plantas necesitan luz solar?",
             "opts":[("A)","Para fabricar su alimento mediante fotosíntesis","La luz les da energía para producir glucosa"),
              ("B)","Porque les gusta el calor","No es cuestión de gusto"),
              ("C)","Sin luz se aburren","Las plantas no se aburren"),
              ("D)","Para crecer de noche","Las plantas crecen con luz")]},
            {"bloom":"Evaluate","icfes":"Razonamiento y Argumentación","s":0.45,
             "stem":"¿Estás de acuerdo con que 'una piedra está viva porque está en la naturaleza'?",
             "opts":[("A)","No, porque las piedras no realizan funciones vitales","Las piedras no nacen, crecen ni se reproducen"),
              ("B)","Sí, porque está en el suelo","Estar en la naturaleza no es estar vivo"),
              ("C)","Sí, porque es dura","La dureza no es signo de vida"),
              ("D)","Sí, porque tiene color","El color no determina vida")]},
            # W02
            {"bloom":"Remember","icfes":"Uso comprensivo del conocimiento científico","s":0.85,
             "stem":"¿Cuál de estos NO es un ser vivo?",
             "opts":[("A)","Una roca","Las rocas son objetos inertes"),
              ("B)","Un árbol","Los árboles son seres vivos"),
              ("C)","Un perro","Los perros son seres vivos"),
              ("D)","Un hongo","Los hongos son seres vivos")]},
            {"bloom":"Remember","icfes":"Indagación y Comprensión","s":0.80,
             "stem":"¿Cuál es el hábitat natural de los peces?",
             "opts":[("A)","El agua (ríos, lagos, mares)","Allí obtienen oxígeno y alimento"),
              ("B)","Una cueva","No es su hábitat"),
              ("C)","Un árbol","No viven en árboles"),
              ("D)","El desierto","No sobreviven allí")]},
            {"bloom":"Understand","icfes":"Uso comprensivo del conocimiento científico","s":0.75,
             "stem":"¿Cómo se llaman los grandes grupos en que se clasifican los seres vivos?",
             "opts":[("A)","Reinos","Monera, Protista, Fungi, Plantae, Animalia"),
              ("B)","Países","Los países son divisiones geográficas"),
              ("C)","Colores","El color no clasifica"),
              ("D)","Números","Los números no clasifican")]},
            {"bloom":"Understand","icfes":"Explicación de fenómenos","s":0.70,
             "stem":"¿Qué necesitan los animales para sobrevivir?",
             "opts":[("A)","Agua, alimento, oxígeno y hábitat","Todas son necesidades básicas"),
              ("B)","Solo un celular","No necesitan celulares"),
              ("C)","Televisor y ropa","No necesitan eso"),
              ("D)","Dinero","Los animales no usan dinero")]},
            {"bloom":"Understand","icfes":"Indagación y Comprensión","s":0.65,
             "stem":"¿Por qué los peces tienen branquias y los humanos pulmones?",
             "opts":[("A)","Los peces viven en el agua y los humanos en la tierra","Cada órgano se adapta al medio"),
              ("B)","Los humanos son más grandes","El tamaño no determina el órgano"),
              ("C)","A los peces no les gusta el aire","También respiran oxígeno, pero del agua"),
              ("D)","Los humanos respiran bajo el agua","No podemos")]},
            {"bloom":"Apply","icfes":"Formulación y Ejecución","s":0.60,
             "stem":"Un pájaro recoge ramitas para hacer un nido. ¿Por qué?",
             "opts":[("A)","Para proteger a sus crías","Los nidos sirven para proteger huevos y polluelos"),
              ("B)","Porque juega","No es juego, es instinto"),
              ("C)","Porque decora","No es decoración"),
              ("D)","Porque está aburrido","No es aburrimiento")]},
            {"bloom":"Apply","icfes":"Formulación y Ejecución","s":0.55,
             "stem":"¿Qué debes hacer para mantener saludable a tu mascota?",
             "opts":[("A)","Darle agua, comida y cariño","Agua, alimento y afecto son esenciales"),
              ("B)","Ponerla a ver TV","No necesita TV"),
              ("C)","Dejarla sola","Necesita atención"),
              ("D)","No darle agua","Todos necesitan agua")]},
            {"bloom":"Analyze","icfes":"Razonamiento y Argumentación","s":0.50,
             "stem":"¿Por qué un cactus vive en el desierto pero un helecho no?",
             "opts":[("A)","El cactus tiene adaptaciones para almacenar agua y resistir calor","Los cactus almacenan agua en sus tallos y tienen espinas"),
              ("B)","El cactus es más fuerte","No es cuestión de fuerza"),
              ("C)","El helecho no quiere","No es decisión"),
              ("D)","Al cactus le gusta el calor","No es cuestión de gustos")]},
            {"bloom":"Analyze","icfes":"Explicación de fenómenos","s":0.50,
             "stem":"¿Por qué hay más biodiversidad en la selva tropical que en el desierto?",
             "opts":[("A)","Hay más agua, luz y nutrientes","Condiciones favorables permiten más vida"),
              ("B)","La selva es más bonita","La belleza no determina biodiversidad"),
              ("C)","En el desierto se esconden","Hay menos, no se esconden"),
              ("D)","Solo plantas pequeñas viven en la selva","Hay plantas de todos tamaños")]},
            {"bloom":"Evaluate","icfes":"Razonamiento y Argumentación","s":0.45,
             "stem":"Un amigo dice: 'Los humanos no somos animales'. ¿Qué piensas?",
             "opts":[("A)","Somos animales del reino Animalia, mamíferos","Biológicamente somos animales"),
              ("B)","Tiene razón, somos diferentes","También somos animales"),
              ("C)","Somos plantas","No somos plantas"),
              ("D)","Somos minerales","No somos minerales")]},
            # W03
            {"bloom":"Remember","icfes":"Uso comprensivo del conocimiento científico","s":0.85,
             "stem":"¿Cómo se llama la capacidad de sentir cambios en el ambiente y responder?",
             "opts":[("A)","Irritabilidad","Los seres vivos detectan estímulos y responden"),
              ("B)","Digestión","La digestión procesa alimentos"),
              ("C)","Fotosíntesis","La fotosíntesis la hacen las plantas"),
              ("D)","Masticación","Masticar es triturar")]},
            {"bloom":"Remember","icfes":"Indagación y Comprensión","s":0.80,
             "stem":"¿Cuál es una adaptación al frío extremo?",
             "opts":[("A)","Piel gruesa y capa de grasa","La grasa aísla del frío"),
              ("B)","Piel muy delgada","No protege del frío"),
              ("C)","Respirar rápido","No ayuda contra el frío"),
              ("D)","Tener muchas patas","No es adaptación al frío")]},
            {"bloom":"Understand","icfes":"Uso comprensivo del conocimiento científico","s":0.75,
             "stem":"¿Por qué algunos animales cambian de color según la estación?",
             "opts":[("A)","Para camuflarse y protegerse","El camuflaje ayuda a sobrevivir"),
              ("B)","Para verse diferentes","No es decisión consciente"),
              ("C)","Porque se aburren","No es aburrimiento"),
              ("D)","Para asustar","No es para asustar")]},
            {"bloom":"Understand","icfes":"Explicación de fenómenos","s":0.70,
             "stem":"¿Qué le pasa a una planta en un cuarto oscuro por un mes?",
             "opts":[("A)","Se pondrá amarilla y se debilitará","Sin luz no puede hacer fotosíntesis"),
              ("B)","Crecerá más rápido","Sin luz no crece bien"),
              ("C)","Se volverá azul","No cambia así"),
              ("D)","Le saldrán flores","Sin luz no produce flores")]},
            {"bloom":"Understand","icfes":"Indagación y Comprensión","s":0.65,
             "stem":"¿Hacia dónde irá una lombriz si tiene tierra húmeda de un lado y seca del otro?",
             "opts":[("A)","Hacia la tierra húmeda","Necesitan humedad para respirar"),
              ("B)","Hacia la tierra seca","Prefieren húmeda"),
              ("C)","Se quedará quieta","Se moverá"),
              ("D)","Saltará fuera","No salta")]},
            {"bloom":"Apply","icfes":"Formulación y Ejecución","s":0.60,
             "stem":"Las plantas del jardín se inclinan hacia la ventana por donde entra el sol. ¿Por qué?",
             "opts":[("A)","Buscan la luz para hacer fotosíntesis","Es el fototropismo"),
              ("B)","El viento las empuja","No es el viento"),
              ("C)","Quieren salir","No es deseo"),
              ("D)","Están enfermas","Es normal")]},
            {"bloom":"Apply","icfes":"Formulación y Ejecución","s":0.55,
             "stem":"Un caracol se esconde en su concha al tocarlo. ¿Qué función vital es?",
             "opts":[("A)","Relación (irritabilidad)","Responde al estímulo del tacto"),
              ("B)","Nutrición","No se alimenta"),
              ("C)","Reproducción","No se reproduce"),
              ("D)","Crecimiento","No crece en ese momento")]},
            {"bloom":"Analyze","icfes":"Razonamiento y Argumentación","s":0.50,
             "stem":"Compara cactus (desierto) y helecho (selva). ¿Difieren en adaptaciones?",
             "opts":[("A)","Cactus almacena agua, helecho necesita mucha agua","Cada uno adaptado a su hábitat"),
              ("B)","Son iguales","Son muy diferentes"),
              ("C)","El cactus no necesita luz","Todas las plantas necesitan luz"),
              ("D)","El helecho vive en el desierto","No sobrevive")]},
            {"bloom":"Analyze","icfes":"Explicación de fenómenos","s":0.50,
             "stem":"¿Por qué el frailejón del páramo acumula agua en sus hojas?",
             "opts":[("A)","Para almacenar agua en épocas secas y regular el ciclo hídrico","Es clave para los páramos colombianos"),
              ("B)","Para decorar","No es decoración"),
              ("C)","Para hacer sombra","No es su función"),
              ("D)","Para que los animales se escondan","No es para eso")]},
            {"bloom":"Evaluate","icfes":"Razonamiento y Argumentación","s":0.45,
             "stem":"¿Por qué es importante conservar los diferentes hábitats?",
             "opts":[("A)","Cada hábitat alberga seres vivos que dependen de él","Perder hábitats extingue especies"),
              ("B)","Son bonitos para fotos","Es más que eso"),
              ("C)","Para construir casas","No es la razón"),
              ("D)","Los animales viven en cualquier parte","Cada especie necesita un hábitat específico")]},
            # W04 - Repaso
            {"bloom":"Remember","icfes":"Uso comprensivo del conocimiento científico","s":0.85,
             "stem":"¿Cuál es una característica de TODOS los seres vivos?",
             "opts":[("A)","Reproducirse","Todos se reproducen para continuar la especie"),
              ("B)","Tener patas","Las plantas no tienen patas"),
              ("C)","Volar","Muchos no vuelan"),
              ("D)","Vivir en el agua","Muchos viven en tierra")]},
            {"bloom":"Remember","icfes":"Indagación y Comprensión","s":0.80,
             "stem":"Los seres vivos que viven en el agua se llaman...",
             "opts":[("A)","Acuáticos","Como peces, algas y ballenas"),
              ("B)","Terrestres","Viven en tierra"),
              ("C)","Voladores","Vuelan"),
              ("D)","Subterráneos","Viven bajo tierra")]},
            {"bloom":"Understand","icfes":"Uso comprensivo del conocimiento científico","s":0.75,
             "stem":"¿Qué pasaría si desaparecieran todas las plantas?",
             "opts":[("A)","Faltaría oxígeno y alimento","Las plantas producen oxígeno y alimento"),
              ("B)","Los animales tendrían más espacio","Sería catastrófico"),
              ("C)","Nada cambiaría","Gran impacto"),
              ("D)","Habría más agua","No habría más agua")]},
            {"bloom":"Understand","icfes":"Explicación de fenómenos","s":0.70,
             "stem":"¿Por qué algunas plantas tienen espinas en lugar de hojas?",
             "opts":[("A)","Para reducir pérdida de agua y protegerse","Adaptación a climas secos"),
              ("B)","Porque están enojadas","Las plantas no se enojan"),
              ("C)","Para decorar","No es decoración"),
              ("D)","Para atraer insectos","Las flores atraen, no las espinas")]},
            {"bloom":"Understand","icfes":"Indagación y Comprensión","s":0.65,
             "stem":"¿Cuál de estas NO es una función vital?",
             "opts":[("A)","Jugar","Jugar no es necesario para vivir"),
              ("B)","Nutrición","Es una función vital"),
              ("C)","Reproducción","Es una función vital"),
              ("D)","Relación","Es una función vital")]},
            {"bloom":"Apply","icfes":"Formulación y Ejecución","s":0.60,
             "stem":"Un gato se acerca al fuego porque tiene frío. ¿Qué función vital demuestra?",
             "opts":[("A)","Irritabilidad","Responde a la temperatura como estímulo"),
              ("B)","Nutrición","No se alimenta"),
              ("C)","Reproducción","No se reproduce"),
              ("D)","Crecimiento","No crece")]},
            {"bloom":"Apply","icfes":"Formulación y Ejecución","s":0.55,
             "stem":"Si una planta no recibe agua por varios días, ¿qué ocurrirá?",
             "opts":[("A)","Se marchitará","Necesita agua para transportar nutrientes"),
              ("B)","Crecerá más","Sin agua no crece"),
              ("C)","Producirá más flores","Sin agua no produce flores"),
              ("D)","Se volverá más verde","Sin agua pierde color")]},
            {"bloom":"Analyze","icfes":"Razonamiento y Argumentación","s":0.50,
             "stem":"¿Por qué los organismos unicelulares (una sola célula) se consideran seres vivos?",
             "opts":[("A)","Porque realizan funciones vitales: se nutren, crecen y se reproducen","Una célula puede hacer todo lo necesario para vivir"),
              ("B)","Porque son muy pequeños","El tamaño no define vida"),
              ("C)","Porque se mueven","No todos se mueven"),
              ("D)","Porque tienen colores","El color no define vida")]},
            {"bloom":"Analyze","icfes":"Explicación de fenómenos","s":0.50,
             "stem":"Un estudiante dice: 'las nubes crecen, así que son seres vivos'. ¿Qué le responderías?",
             "opts":[("A)","Las nubes no son seres vivos porque no se reproducen ni se nutren","Crecer no es suficiente, deben cumplir todas las funciones vitales"),
              ("B)","Tiene razón","Las nubes no son seres vivos"),
              ("C)","Las nubes son plantas","No son plantas"),
              ("D)","Las nubes son animales","No son animales")]},
            {"bloom":"Evaluate","icfes":"Razonamiento y Argumentación","s":0.45,
             "stem":"¿Por qué es importante que los niños aprendan sobre los seres vivos y su clasificación?",
             "opts":[("A)","Para entender y cuidar la naturaleza que nos rodea","Conocer los seres vivos nos ayuda a respetarlos y protegerlos"),
              ("B)","Para tener mejores notas","Es más que una nota"),
              ("C)","No es importante","Sí es importante"),
              ("D)","Solo para ser científicos","Es útil para todos")]},
        ],
        "expl": {
            # Map question stems to explanations
            "¿Cuál de los siguientes es un ser vivo?":"Los gatos son seres vivos porque realizan funciones vitales: nacen, crecen, se alimentan, se reproducen y mueren. Los objetos como piedras, mesas y sillas son inertes.",
            "¿Qué necesitan todos los seres vivos para vivir?":"Todos los seres vivos necesitan agua, alimento (nutrientes) y energía para sobrevivir. Sin estos elementos no pueden realizar sus funciones vitales.",
            "Un árbol crece más alto cada año. ¿Qué característica de los seres vivos se observa?":"El crecimiento es una característica fundamental de los seres vivos. Las plantas aumentan de tamaño con el tiempo gracias a la fotosíntesis y absorción de nutrientes.",
            "¿Cómo se llama la capacidad de los seres vivos de reaccionar al ser tocados?":"La irritabilidad permite a los seres vivos detectar cambios en el ambiente (luz, temperatura, tacto) y responder a ellos para sobrevivir.",
            "De esta lista: hormiga, libro, rosa, carro, pez. ¿Cuántos son seres vivos?":"De la lista, la hormiga (insecto), la rosa (planta) y el pez (animal) son seres vivos. El carro y el libro son objetos inertes.",
            "Si pones una semilla con tierra, agua y sol, ¿qué pasará?":"Las semillas son seres vivos en estado de latencia. Con agua, tierra y luz solar germinan: la planta bebé sale de la semilla y crecen raíces y tallos.",
            "Una mariposa pone huevos en una hoja. ¿Qué función vital realiza?":"La reproducción permite a los seres vivos crear descendencia. La mariposa pone huevos para que nazcan nuevas orugas que continúen el ciclo de vida.",
            "¿Por qué una lagartija busca el sol pero una estatua no?":"Los seres vivos tienen irritabilidad: responden a estímulos como la temperatura. La lagartija, de sangre fría, necesita sol para calentar su cuerpo. La estatua no responde a estímulos.",
            "¿Por qué las plantas necesitan luz solar?":"Las plantas realizan fotosíntesis usando luz solar para convertir agua y dióxido de carbono en glucosa (alimento) y oxígeno. Sin luz no pueden fabricar su alimento.",
            "¿Estás de acuerdo con que 'una piedra está viva porque está en la naturaleza'?":"Para que algo sea considerado ser vivo debe cumplir funciones vitales: nacer, crecer, nutrirse, relacionarse, reproducirse y morir. Las piedras no hacen nada de esto.",
            "¿Cuál de estos NO es un ser vivo?":"Las rocas son objetos inertes porque no realizan funciones vitales. Los árboles, perros y hongos son seres vivos que nacen, crecen, se reproducen y mueren.",
            "¿Cuál es el hábitat natural de los peces?":"El hábitat es el lugar donde un ser vivo encuentra todo lo que necesita. Los peces viven en el agua porque allí obtienen oxígeno, alimento y pueden moverse.",
            "¿Cómo se llaman los grandes grupos en que se clasifican los seres vivos?":"Los seres vivos se clasifican en cinco reinos: Monera (bacterias), Protista (protozoos), Fungi (hongos), Plantae (plantas) y Animalia (animales).",
            "¿Qué necesitan los animales para sobrevivir?":"Todos los animales necesitan agua para hidratarse, alimento para obtener energía, oxígeno para respirar y un hábitat adecuado donde vivir.",
            "¿Por qué los peces tienen branquias y los humanos pulmones?":"Las branquias captan oxígeno disuelto en el agua. Los pulmones captan oxígeno del aire. Cada órgano está adaptado al medio donde vive el organismo.",
            "Un pájaro recoge ramitas para hacer un nido. ¿Por qué?":"Los pájaros construyen nidos para proteger a sus huevos y crías. Esta conducta de cuidado parental ayuda a la supervivencia de la especie.",
            "¿Qué debes hacer para mantener saludable a tu mascota?":"Las mascotas son seres vivos que dependen de nosotros. Necesitan agua limpia, alimento balanceado, ejercicio, atención veterinaria y cariño.",
            "¿Por qué un cactus vive en el desierto pero un helecho no?":"Los seres vivos tienen adaptaciones para su hábitat. Los cactus almacenan agua en sus tallos y tienen espinas en lugar de hojas para reducir la pérdida de agua.",
            "¿Por qué hay más biodiversidad en la selva tropical que en el desierto?":"La biodiversidad depende de las condiciones del ambiente. Las selvas tropicales tienen abundante agua, luz solar y nutrientes, permitiendo que muchas especies vivan allí.",
            "Un amigo dice: 'Los humanos no somos animales'. ¿Qué piensas?":"Los seres humanos pertenecemos al reino Animalia, somos mamíferos del orden de los primates. Compartimos características con otros animales.",
            "¿Cómo se llama la capacidad de sentir cambios en el ambiente y responder?":"La irritabilidad permite a los seres vivos detectar estímulos del ambiente y responder adecuadamente para sobrevivir.",
            "¿Cuál es una adaptación al frío extremo?":"Los animales que viven en climas fríos tienen piel gruesa, capas de grasa (ballenas) o pelaje denso (osos polares) para conservar el calor corporal.",
            "¿Por qué algunos animales cambian de color según la estación?":"El camuflaje permite a los animales confundirse con el ambiente. El conejo ártico cambia a blanco en invierno para no ser visto en la nieve.",
            "¿Qué le pasa a una planta en un cuarto oscuro por un mes?":"Las plantas necesitan luz para la fotosíntesis. Sin luz no pueden producir alimento, pierden clorofila y se debilitan hasta morir.",
            "¿Hacia dónde irá una lombriz si tiene tierra húmeda de un lado y seca del otro?":"Las lombrices necesitan humedad para respirar por su piel. Buscan tierra húmeda y evitan lugares secos. Esto demuestra irritabilidad.",
            "Las plantas del jardín se inclinan hacia la ventana por donde entra el sol. ¿Por qué?":"El fototropismo es el crecimiento de las plantas hacia la luz. Orientan sus hojas y tallos hacia donde hay más luz para la fotosíntesis.",
            "Un caracol se esconde en su concha al tocarlo. ¿Qué función vital es?":"La función de relación permite detectar cambios en el ambiente y responder. El caracol detecta peligro (tacto) y se protege en su concha.",
            "Compara cactus (desierto) y helecho (selva). ¿Difieren en adaptaciones?":"El cactus tiene tallos gruesos para almacenar agua y espinas para reducir pérdida. El helecho tiene hojas grandes para captar luz en la selva húmeda.",
            "¿Por qué el frailejón del páramo acumula agua en sus hojas?":"El frailejón, planta típica de páramos colombianos, tiene hojas peludas y carnosas que almacenan agua, regulando el ciclo hídrico del páramo.",
            "¿Por qué es importante conservar los diferentes hábitats?":"Cada ser vivo está adaptado a un hábitat específico. Si destruimos los hábitats, las especies pierden su hogar y pueden desaparecer.",
            "¿Cuál es una característica de TODOS los seres vivos?":"La reproducción es función vital común a todos los seres vivos. Aunque las formas varían, todos producen descendencia para continuar la especie.",
            "Los seres vivos que viven en el agua se llaman...":"Los organismos acuáticos viven en el agua (peces, ballenas, algas). Su cuerpo está adaptado para este medio.",
            "¿Qué pasaría si desaparecieran todas las plantas?":"Las plantas son organismos productores. Mediante fotosíntesis producen oxígeno y son la base de las cadenas alimenticias. Sin ellas la vida animal sería imposible.",
            "¿Por qué algunas plantas tienen espinas en lugar de hojas?":"Las espinas son hojas modificadas que reducen la pérdida de agua por evaporación. Es una adaptación a climas secos como el de los cactus.",
            "¿Cuál de estas NO es una función vital?":"Las funciones vitales de los seres vivos son nutrición, relación y reproducción. Jugar es una actividad, no una función vital.",
            "Un gato se acerca al fuego porque tiene frío. ¿Qué función vital demuestra?":"El gato detecta el frío (estímulo) y busca calor (respuesta). Esto es irritabilidad o función de relación con el medio.",
            "Si una planta no recibe agua por varios días, ¿qué ocurrirá?":"El agua es esencial para transportar nutrientes y mantener la estructura de la planta. Sin agua, las células se deshidratan y la planta se marchita.",
            "¿Por qué los organismos unicelulares se consideran seres vivos?":"Una sola célula puede realizar todas las funciones vitales: nutrición, relación y reproducción. Las bacterias y protozoos son ejemplos.",
            "Un estudiante dice: 'las nubes crecen, así que son seres vivos'. ¿Qué le responderías?":"Crecer no es suficiente para ser un ser vivo. Las nubes no se nutren, no se reproducen ni responden a estímulos como lo hacen los seres vivos.",
            "¿Por qué es importante que los niños aprendan sobre los seres vivos?":"Conocer los seres vivos y su clasificación nos ayuda a entender la biodiversidad, respetar la naturaleza y tomar decisiones informadas para proteger el ambiente.",
        }
    },
    # Similar data for other segments...
}

# Build expl lookup
G3_EXPL = {}
for seg, data in G3_QDATA.items():
    G3_EXPL[seg] = data.get("expl", {})

# ═══════════════════════════════════════════════════════════════════
# TOPIC MAPS
# ═════════════════════════════════════════════════════════════