#!/usr/bin/env python3
"""Jules G3 CN: W05-W10 Bundle Generator - Part 2"""
import os, sys
sys.stdout.reconfigure(encoding='utf-8')

BASEDIR = r"E:\scripts-python\worldexams\questions_data\colombia\ciencias-naturales\grado-3\2026"
WEEKLY_DIR = os.path.join(BASEDIR, "weekly")
os.makedirs(WEEKLY_DIR, exist_ok=True)
C,I=True,False

def wb(t,s,pqs):
    fid=f"CO-CIE-3-2026-{s}-{t}-001-MASTERY"
    h=["---",f'id: "{fid}"','country: "colombia"','grado: 3','asignatura: "ciencias-naturales"',f'tema: "{t}"',f'semana: "{s}"','protocol_version: "5.2"','bundle_type: "weekly"','bundle_index: 1',f'bundle_size: {len(pqs)}','alignment: "DBA MEN Grado 3 - Ciencias Naturales"','modern_context: true','distractor_profile: "plausible_peer_set"','calibration:','  expected_success_rate: 0.65','  discrimination_index_target: ">= 0.22"','  simulated_responses: 100',f'rubric_baseline: "{t.replace("-","_")}"',"---"]
    fm="\n".join(h)
    l=[fm,"",f"# Bundle MASTERY: Ciencias Naturales Grado 3 - Semana {s}",""]
    for i,qd in enumerate(pqs):
        n=i+1;d,b,ic,ctx,en,ops,ex=qd
        l+=[f"## Pregunta {n} [D{d}]","",f"**ID:** `{fid}-v{n}`",f"**Bloom:** {b}",f"**ICFES:** {ic}","",f"**Context:** {ctx}","","### Enunciado",en,"","### Opciones"]
        for c_,lt,tt,fb in ops:
            l.append(f"- {'[x]' if c_ else '[ ]'} {lt}) {tt} <!-- feedback: {fb} -->")
        l+=["","### Explicacion Pedagogica",ex,"","---",""]
    content="\n".join(l)
    fp=os.path.join(WEEKLY_DIR,f"{fid}-bundle.md")
    with open(fp,"w",encoding="utf-8") as f:f.write(content)
    print(f"OK {fid}")

# W05: animales-alimentacion
wb("animales-alimentacion","W05",[
(3,"Remember","Uso comprensivo del conocimiento científico","La profesora explica los grupos de animales según su alimentación.","¿Cómo se llaman los animales que se alimentan principalmente de plantas?",[(I,"A","Carnívoros","Incorrecto. Los carnívoros se alimentan de carne."),(C,"B","Herbívoros","¡Correcto! Los herbívoros se alimentan de plantas: hierba, hojas, frutos, semillas."),(I,"C","Omnívoros","Incorrecto. Los omnívoros comen tanto plantas como carne."),(I,"D","Insectívoros","Incorrecto. Los insectívoros se alimentan de insectos.")],"Los herbívoros tienen adaptaciones como molares planos para moler plantas y sistemas digestivos largos para descomponer celulosa. En Colombia encontramos venado cola blanca, tapir, lapa y perezoso como herbívoros representativos."),
(3,"Remember","Uso comprensivo del conocimiento científico","Los estudiantes identifican la alimentación del jaguar.","El jaguar, que caza y se alimenta de otros animales, es un animal:",[(C,"A","Carnívoro","¡Muy bien! El jaguar es carnívoro, se alimenta de la carne de animales que caza."),(I,"B","Herbívoro","Incorrecto. Los herbívoros se alimentan de plantas."),(I,"C","Omnívoro","Incorrecto. Los omnívoros comen plantas y carne."),(I,"D","Frugívoro","Incorrecto. Los frugívoros se alimentan de frutas.")],"El jaguar (Panthera onca) es el felino más grande de América y habita en selvas colombianas como la Amazonía y el Pacífico. Como superdepredador, controla las poblaciones de sus presas y mantiene el equilibrio ecológico."),
(4,"Understand","Explicación de fenómenos","Sofía tiene un perro que come concentrado y un conejo que come zanahorias.","¿Cómo se clasifican el perro y el conejo según su alimentación?",[(I,"A","Ambos son herbívoros","Incorrecto. El perro no es herbívoro."),(I,"B","El perro es carnívoro y el conejo es omnívoro","Incorrecto."),(C,"C","El perro es omnívoro y el conejo es herbívoro","¡Correcto! Los perros descienden de carnívoros pero se han adaptado a dieta variada. El conejo come solo plantas."),(I,"D","El perro es herbívoro y el conejo es carnívoro","Incorrecto.")],"El perro doméstico desciende del lobo, carnívoro por naturaleza, pero la domesticación le ha dado capacidad de digerir carbohidratos. El conejo es herbívoro estricto con incisivos de crecimiento continuo y sistema digestivo adaptado a la celulosa."),
(4,"Understand","Explicación de fenómenos","En la cafetería del colegio, las palomas comen pan, semillas e insectos.","¿Qué tipo de alimentación tienen las palomas?",[(I,"A","Herbívora exclusiva","Incorrecto. También comen insectos."),(C,"B","Omnívora","¡Excelente! Las palomas comen tanto alimentos vegetales como animales."),(I,"C","Carnívora","Incorrecto. También comen muchos alimentos vegetales."),(I,"D","Nectarívora","Incorrecto. No se alimentan de néctar como los colibríes.")],"Los animales omnívoros tienen dieta variada, lo que les da ventaja adaptativa. En Colombia, ejemplos de omnívoros incluyen cerdos, osos de anteojos, micos cariblancos y el ser humano."),
(5,"Apply","Uso comprensivo del conocimiento científico","Los estudiantes agrupan animales según alimentación: vaca, león, cerdo, oso, oveja, tigre.","¿Cuál grupo contiene solo herbívoros?",[(I,"A","León y tigre","Incorrecto. Son carnívoros."),(C,"B","Vaca y oveja","¡Correcto! Son herbívoros rumiantes."),(I,"C","Cerdo y oso","Incorrecto. Son omnívoros."),(I,"D","Vaca y cerdo","Incorrecto. El cerdo es omnívoro.")],"Los rumiantes como vacas y ovejas tienen un estómago con cuatro compartimentos (rumen, retículo, omaso, abomaso). Microorganismos en el rumen fermentan la celulosa y permiten aprovechar nutrientes de plantas fibrosas."),
(5,"Apply","Uso comprensivo del conocimiento científico","La profesora muestra dentaduras de animales.","Un animal con colmillos afilados y molares puntiagudos probablemente es:",[(I,"A","Herbívoro","Incorrecto. Los herbívoros tienen molares planos."),(C,"B","Carnívoro","¡Muy bien! Los carnívoros tienen caninos largos para sujetar presas y molares carniceros para cortar carne."),(I,"C","Omnívoro","Incorrecto. Los omnívoros tienen dientes intermedios."),(I,"D","Insectívoro","Incorrecto. Los insectívoros tienen dientes pequeños y puntiagudos.")],"La dentadura refleja la dieta. Los carnívoros tienen caninos desarrollados para desgarrar, molares carniceros para cortar carne y mandíbulas de movimiento vertical. Jaguares, pumas, zorros y nutrias son ejemplos colombianos."),
(6,"Apply","Explicación de fenómenos","En una vereda de Antioquia, un campesino nota que sus gallinas picotean granos y lombrices.","¿Por qué las gallinas comen tanto granos como lombrices?",[(I,"A","Porque tienen hambre y cualquier cosa sirve","Incorrecto. Las gallinas seleccionan su alimento."),(C,"B","Porque son omnívoras y necesitan nutrientes de ambos orígenes","¡Correcto! Necesitan proteína animal para huevos y carbohidratos para energía."),(I,"C","Porque las lombrices son postre","Incorrecto."),(I,"D","Porque quieren variar su menú","Incorrecto. La razón es nutricional.")],"Las gallinas son omnívoras. En libertad complementan su dieta de granos con insectos y lombrices que aportan proteína esencial para la producción de huevos. Por eso los campesinos colombianos dejan las gallinas libres para alimentarse naturalmente."),
(7,"Apply","Indagación","Los estudiantes investigan si los osos de anteojos de Colombia engordan antes del invierno.","¿Los osos de anteojos engordan antes del invierno como los osos del norte?",[(I,"A","Sí, porque todos los osos son iguales","Incorrecto. Los osos de anteojos viven en el trópico."),(C,"B","No, porque en los Andes colombianos no hay inviernos extremos y hay alimento todo el año","¡Correcto! El oso de anteojos no hiberna porque en el trópico hay alimento constante."),(I,"C","Sí, porque todos los osos hibernan","Incorrecto. No todos los osos hibernan."),(I,"D","No, porque son herbívoros","Incorrecto. Son omnívoros, pero la razón es climática.")],"El oso de anteojos (Tremarctos ornatus) es la única especie de oso en Suramérica y habita en los Andes colombianos. Es omnívoro con preferencia por frutas y bromelias. Como en el trópico hay alimento disponible todo el año, no necesita hibernar."),
(8,"Analyze","Explicación de fenómenos","Un estudiante pregunta: 'Si las vacas solo comen pasto, ¿cómo producen proteína en su leche?'","¿Cómo obtienen las vacas la proteína?",[(I,"A","Convierten el pasto directamente en proteína","Incorrecto. El pasto es bajo en proteína."),(C,"B","Microorganismos en el rumen transforman la celulosa en proteína que la vaca absorbe","¡Excelente! Los microorganismos sintetizan proteína de alta calidad que la vaca digiere."),(I,"C","La vaca come insectos sin darse cuenta","Incorrecto. Son herbívoras estrictas."),(I,"D","El pasto tiene suficiente proteína","Incorrecto. Los microorganismos la mejoran.")],"Las vacas son rumiantes. En el rumen viven billones de microorganismos que fermentan la celulosa y convierten compuestos nitrogenados en proteína microbiana de alta calidad. La vaca digiere estos microorganismos y absorbe los aminoácidos, produciendo leche rica en proteínas."),
(9,"Evaluate","Indagación","Un estudiante dice: 'Los carnívoros son malos porque matan animales.'","¿Qué opinas?",[(I,"A","Tiene razón, los carnívoros son malos","Incorrecto. Cumplen funciones ecológicas naturales."),(C,"B","Es incorrecto. Todos los animales cumplen funciones necesarias en el ecosistema. No hay animales 'buenos' o 'malos'","¡Excelente! Cada animal cumple su rol en la naturaleza."),(I,"C","Parcialmente correcto, los herbívoros nunca dañan","Incorrecto. Los herbívoros también afectan su entorno."),(I,"D","Los carnívoros solo existen para equilibrar herbívoros","Incorrecto. Todos evolucionaron en relaciones complejas.")],"En los ecosistemas no hay animales 'buenos' o 'malos'. Los carnívoros controlan poblaciones de herbívoros, evitando sobrepastura y manteniendo biodiversidad. Los herbívoros dispersan semillas y fertilizan el suelo. Todos son necesarios para el equilibrio natural.")])
