#!/usr/bin/env python3
"""Jules G3 CN: W06-W10"""
import os,sys;sys.stdout.reconfigure(encoding='utf-8')
BASEDIR=r"E:\scripts-python\worldexams\questions_data\colombia\ciencias-naturales\grado-3\2026"
WD=os.path.join(BASEDIR,"weekly");os.makedirs(WD,exist_ok=True)
C,I=True,False
def wb(t,s,pqs):
    fid=f"CO-CIE-3-2026-{s}-{t}-001-MASTERY"
    h=["---",f'id: "{fid}"','country: "colombia"','grado: 3','asignatura: "ciencias-naturales"',f'tema: "{t}"',f'semana: "{s}"','protocol_version: "5.2"','bundle_type: "weekly"','bundle_index: 1',f'bundle_size: {len(pqs)}','alignment: "DBA MEN Grado 3 - Ciencias Naturales"','modern_context: true','distractor_profile: "plausible_peer_set"','calibration:','  expected_success_rate: 0.65', '  discrimination_index_target: ">= 0.22"','  simulated_responses: 100',f'rubric_baseline: "{t.replace("-","_")}"',"---"]
    l=["\n".join(h),"",f"# Bundle MASTERY: Ciencias Naturales Grado 3 - Semana {s}",""]
    for i,qd in enumerate(pqs):
        n=i+1;d,b,ic,ctx,en,ops,ex=qd
        l+=[f"## Pregunta {n} [D{d}]","",f"**ID:** `{fid}-v{n}`",f"**Bloom:** {b}",f"**ICFES:** {ic}","",f"**Context:** {ctx}","","### Enunciado",en,"","### Opciones"]
        for c_,lt,tt,fb in ops:
            l.append(f"- {'[x]' if c_ else '[ ]'} {lt}) {tt} <!-- feedback: {fb} -->")
        l+=["","### Explicacion Pedagogica",ex,"","---",""]
    fp=os.path.join(WD,f"{fid}-bundle.md")
    with open(fp,"w",encoding="utf-8") as f:f.write("\n".join(l))
    print(f"OK {s}")

# W06: aire
wb("aire","W06",[
(3,"Remember","Uso comprensivo del conocimiento científico","La profesora pregunta qué hay en una bolsa 'vacía'.","El aire que respiramos está compuesto principalmente por:",[(I,"A","Oxígeno puro","Incorrecto. El aire tiene oxígeno pero también otros gases."),(C,"B","Nitrógeno y oxígeno principalmente","¡Correcto! El aire es 78% nitrógeno, 21% oxígeno."),(I,"C","Solo dióxido de carbono","Incorrecto. El CO₂ es solo 0.04%."),(I,"D","Hidrógeno y helio","Incorrecto. Son gases minoritarios.")],"La atmósfera terrestre es 78% nitrógeno (N₂), 21% oxígeno (O₂), 0.93% argón y 0.04% CO₂, más vapor de agua. El oxígeno es esencial para la respiración."),
(3,"Remember","Uso comprensivo del conocimiento científico","Los estudiantes inflan globos.","¿Qué propiedad del aire se demuestra al inflar un globo?",[(I,"A","El aire no pesa","Incorrecto. Tiene peso, aunque poco."),(C,"B","El aire ocupa espacio (tiene volumen)","¡Muy bien! Al inflar un globo, el aire expande el globo porque ocupa espacio."),(I,"C","El aire es invisible","Incorrecto. Aunque invisible, esa no es la propiedad demostrada."),(I,"D","El aire está en movimiento","Incorrecto. Puede estar quieto dentro del globo.")],"El aire es materia y ocupa espacio (volumen) y tiene masa. Inflar un globo demuestra el volumen del aire porque el globo se expande. El aire es incoloro, inodoro e insípido."),
(4,"Understand","Explicación de fenómenos","En Fusagasugá, los estudiantes sumergen un vaso boca abajo en agua.","¿Por qué no entra agua al vaso?",[(I,"A","El agua rechaza el vaso","Incorrecto."),(C,"B","El aire dentro del vaso ocupa espacio y no deja entrar el agua","¡Correcto! El aire atrapado ocupa el volumen."),(I,"C","El vaso es impermeable","Incorrecto. El agua podría entrar por la boca."),(I,"D","El agua es más densa","Incorrecto. La razón es que el aire ocupa el espacio.")],"El vaso contiene aire que no puede escapar y ejerce presión, ocupando el volumen e impidiendo que el agua entre. Si inclinas el vaso, el aire sale en burbujas y el agua entra."),
(4,"Understand","Explicación de fenómenos","En La Candelaria (Bogotá), los niños notan que la ropa se seca más rápido con viento.","¿Por qué el viento seca la ropa más rápido?",[(I,"A","El viento tira las gotas","Incorrecto."),(C,"B","El viento renueva el aire seco alrededor de la ropa, acelerando la evaporación","¡Correcto! El aire seco absorbe más humedad."),(I,"C","El viento calienta la ropa","Incorrecto. Puede estar frío."),(I,"D","Mueve la ropa y el agua se cae","Incorrecto. El agua se evapora.")],"La evaporación es el paso de agua líquida a vapor. El viento acelera el proceso porque desplaza la capa de aire húmedo alrededor de la ropa, reemplazándola con aire seco que puede absorber más vapor de agua."),
(5,"Apply","Uso comprensivo del conocimiento científico","Los estudiantes dan ejemplos de usos del aire.","¿Cuál NO es una forma de usar el aire?",[(I,"A","Inflar llantas de bicicleta","Sí es usar aire comprimido."),(I,"B","Generar electricidad con molinos de viento","Sí es energía eólica."),(C,"C","Fabricar plásticos","¡Correcto! Los plásticos vienen del petróleo."),(I,"D","Secar el cabello con secador","Sí es usar aire en movimiento.")],"El aire tiene muchos usos: inflar objetos, energía eólica, secado, combustión (oxígeno), comunicación (sonido viaja por el aire) y vuelo. Los plásticos se fabrican del petróleo, no del aire."),
(5,"Apply","Uso comprensivo del conocimiento científico","Explican la diferencia entre aire inhalado y exhalado.","¿Qué exhalamos principalmente?",[(I,"A","Oxígeno puro","Incorrecto. Exhalamos menos oxígeno."),(C,"B","Dióxido de carbono y nitrógeno, más algo de oxígeno","¡Correcto! CO₂ (desecho celular), N₂ y O₂."),(I,"C","Solo dióxido de carbono","Incorrecto. Es una mezcla."),(I,"D","Vapor de agua y oxígeno","Incorrecto. La mayor parte es nitrógeno.")],"Inhalamos 21% O₂. Las células usan O₂ en respiración celular y producen CO₂. Exhalamos ~16% O₂, 4-5% CO₂, 78% N₂ y vapor de agua. Las plantas toman ese CO₂ para fotosíntesis."),
(6,"Apply","Explicación de fenómenos","En Pereira, un niño tapa una jeringa y no puede empujar el émbolo.","¿Por qué?",[(I,"A","La jeringa está dañada","Incorrecto."),(C,"B","El aire atrapado se comprime y ejerce resistencia","¡Excelente! El aire no escapa y ofrece resistencia."),(I,"C","No tiene suficiente aire","Incorrecto."),(I,"D","El vacío succiona","Incorrecto. No hay vacío.")],"Al tapar la salida y empujar, las moléculas de aire se juntan y la presión aumenta, sintiéndose como resistencia. El aire es un fluido compresible, a diferencia del agua."),
(7,"Apply","Indagación","Investigan por qué en el Nevado del Ruiz cuesta respirar.","¿Por qué es más difícil respirar en altitud?",[(I,"A","Hay menos oxígeno","Parcialmente correcto. La proporción es igual, la presión es menor."),(C,"B","La presión atmosférica es menor, entra menos oxígeno a los pulmones","¡Correcto! La presión disminuye con la altitud."),(I,"C","El aire está más contaminado","Incorrecto."),(I,"D","El frío contrae los pulmones","Incorrecto.")],"La presión atmosférica disminuye con la altitud. En Bogotá (2600m) es menor que en la costa. En el Nevado del Ruiz (5300m) es mucho menor. Aunque el O₂ es 21%, entra con menos fuerza a los alvéolos."),
(8,"Analyze","Explicación de fenómenos","Un incendio en el Valle del Cauca se extiende rápido con viento.","¿Por qué el viento propaga el fuego?",[(I,"A","El viento calienta","Incorrecto. Enfría."),(C,"B","El viento lleva más oxígeno y empuja las llamas","¡Correcto! El oxígeno alimenta la combustión."),(I,"C","El viento seca la vegetación","Incorrecto. Ya está seca."),(I,"D","Sopla brasas","Eso es secundario.")],"El fuego necesita combustible, oxígeno y calor (triángulo del fuego). El viento aporta más oxígeno intensificando la combustión y dirige las llamas hacia vegetación no quemada. Por eso se crean cortafuegos."),
(9,"Evaluate","Indagación","Un estudiante dice: 'Como el viento no se ve, no existe.'","¿Qué le responderías?",[(I,"A","Tiene razón","Incorrecto. Muchas cosas existen sin verse."),(C,"B","Existe aunque no lo veamos; observamos sus efectos: hojas, banderas, molinos","¡Excelente! Conocemos algo por sus efectos."),(I,"C","Se ve cuando hace frío","Incorrecto. Lo visible es vapor condensado."),(I,"D","No se puede saber","Incorrecto. Hay muchas evidencias.")],"Podemos conocer la existencia de algo por sus efectos. El viento es aire en movimiento. Vemos sus efectos: hojas moviéndose, cometas volando, molinos girando. En Colombia, los vientos alisios y las brisas marinas son ejemplos regionales."),
])

# W07: suelo
wb("suelo","W07",[
(3,"Remember","Uso comprensivo del conocimiento científico","La profesora muestra tierra del jardín del colegio.","¿Cuál NO es un componente natural del suelo?",[(I,"A","Arena","Sí es componente."),(I,"B","Arcilla","Sí es componente."),(I,"C","Humus","Sí es componente importante."),(C,"D","Plástico reciclado","¡Correcto! Es un contaminante.")],"El suelo tiene minerales (arena, arcilla, limo), materia orgánica (humus), agua y aire. El humus viene de la descomposición de plantas y animales y es esencial para la fertilidad."),
(3,"Remember","Uso comprensivo del conocimiento científico","Los estudiantes aprenden cómo se forma el suelo.","¿De dónde provienen los minerales del suelo?",[(I,"A","De las plantas","Incorrecto. Las plantas los toman."),(C,"B","De la descomposición de las rocas","¡Correcto! Por meteorización de rocas."),(I,"C","Del aire","Incorrecto. Aporta algo, pero la fuente principal son las rocas."),(I,"D","De los animales","Incorrecto.")],"El suelo se forma por meteorización de rocas, proceso que toma miles de años. Agua, viento, temperatura y seres vivos descomponen las rocas en partículas. Suelos colombianos: arcillosos (Valle del Cauca), arenosos (Guajira), volcánicos (Eje Cafetero)."),
(4,"Understand","Explicación de fenómenos","La tierra con lombrices es más oscura y esponjosa.","¿Qué hacen las lombrices por el suelo?",[(I,"A","Decorar","Incorrecto."),(C,"B","Excavan túneles que airean el suelo y su excremento fertiliza","¡Correcto! Airean y producen humus."),(I,"C","Comen malas hierbas","Incorrecto. Comen materia orgánica."),(I,"D","Aumentan la arena","Incorrecto.")],"Las lombrices son 'ingenieras del suelo'. Sus galerías permiten aireación y drenaje. Su excremento (vermicompost) es rico en N, P y K. En Colombia, los campesinos consideran las lombrices señal de suelo fértil."),
(4,"Understand","Explicación de fenómenos","En el Quindío, el suelo se erosiona en laderas sin árboles.","¿Por qué los árboles protegen el suelo?",[(I,"A","Decorar","Incorrecto."),(C,"B","Las raíces sujetan el suelo y las copas amortiguan la lluvia","¡Correcto! Fijan el suelo y reducen impacto."),(I,"C","La sombra evita erosión","Incorrecto. La sombra sola no protege."),(I,"D","Producen oxígeno","Incorrecto. El O₂ no protege.")],"Los árboles previenen la erosión: raíces forman red que sujeta partículas, copas reducen impacto de lluvia, hojas caídas forman capa protectora, troncos reducen viento. En zonas cafeteras se siembran árboles de sombrío."),
(5,"Apply","Uso comprensivo del conocimiento científico","Identifican el mejor suelo para agricultura.","¿Cuál es el suelo más adecuado para cultivar?",[(I,"A","Solo arena","Incorrecto. Drena rápido, pocos nutrientes."),(I,"B","Solo arcilla","Incorrecto. Se compacta."),(C,"C","Suelo franco (mezcla equilibrada)","¡Correcto! Buena retención de agua, nutrientes y drenaje."),(I,"D","Solo grava","Incorrecto.")],"El suelo franco tiene mezcla equilibrada de arena (drenaje), arcilla (retención), limo (textura) y humus (fertilidad). Suelos volcánicos del Eje Cafetero y aluviales del Valle del Cauca son ejemplos."),
(5,"Apply","Uso comprensivo del conocimiento científico","Pasan agua por tres muestras de suelo.","¿Cuál deja pasar el agua más rápido?",[(C,"A","El arenoso","¡Correcto! Partículas grandes, espacios grandes."),(I,"B","El arcilloso","Incorrecto. Partículas microscópicas."),(I,"C","El que tiene humus","Incorrecto. Retiene agua."),(I,"D","El limoso","Incorrecto. Permeabilidad intermedia.")],"La textura determina la permeabilidad. Arena: partículas grandes (0.05-2mm), espacios grandes, agua pasa rápido. Arcilla: partículas <0.002mm, compactas, baja permeabilidad. Suelo franco: permeabilidad intermedia, ideal para cultivos."),
(6,"Apply","Explicación de fenómenos","Después de lluvia, en tierra arcillosa hay charcos.","¿Por qué?",[(I,"A","La arcilla es más oscura","Incorrecto. El color no determina."),(C,"B","Las partículas de arcilla son tan pequeñas que el agua no se infiltra rápido","¡Correcto! Se compactan y bloquean el paso."),(I,"C","La arcilla repele el agua","Incorrecto."),(I,"D","Hay más lombrices allí","Incorrecto.")],"La arcilla tiene partículas <0.002mm. Al compactarse, los espacios entre ellas son muy pequeños. El agua no puede infiltrarse rápido y se acumula en la superficie. En cambio, el suelo arenoso permite infiltración rápida."),
(7,"Apply","Indagación","Investigan por qué los campesinos abonan la tierra.","¿Cuál es la función principal del abono?",[(I,"A","Oscurecer el suelo","Incorrecto."),(C,"B","Aportar nutrientes (NPK) para que las plantas crezcan","¡Correcto! Nitrógeno, fósforo, potasio."),(I,"C","Eliminar plagas","Incorrecto. Para plagas se usan pesticidas."),(I,"D","Endurecer el suelo","Incorrecto.")],"Los fertilizantes aportan nutrientes esenciales: N para hojas verdes, P para raíces y flores, K para frutos y resistencia. En Colombia se usan abonos orgánicos (compost, gallinaza) y químicos."),
(8,"Analyze","Explicación de fenómenos","En la costa Caribe, el suelo salino daña los cultivos.","¿Por qué el exceso de sal daña las plantas?",[(I,"A","La sal embellece el suelo","Incorrecto."),(C,"B","La sal extrae agua de las raíces por ósmosis, deshidratando la planta","¡Correcto! El agua sale de las raíces hacia el suelo salino."),(I,"C","La sal nutre demasiado","Incorrecto. El exceso de sales es tóxico."),(I,"D","La sal endurece el suelo","Incorrecto.")],"Cuando el suelo tiene mucha sal, el agua del suelo tiene mayor concentración de sales que el interior de las raíces. Por ósmosis, el agua sale de la raíz hacia el suelo, deshidratando la planta (estrés salino). En la costa Caribe colombiana esto afecta cultivos."),
(9,"Evaluate","Indagación","Un estudiante dice: 'La tierra es solo suciedad, no sirve para nada importante.'","¿Qué opinas?",[(I,"A","Tiene razón","Incorrecto."),(C,"B","Es incorrecto. El suelo es esencial para la vida: produce alimentos, filtra agua, almacena carbono y es hábitat de millones de organismos","¡Excelente! El suelo es un recurso vital."),(I,"C","Solo sirve para que jueguen los niños","Incorrecto."),(I,"D","Sirve solo para construir","Incorrecto. Es mucho más que eso.")],"El suelo es un recurso natural no renovable esencial. Produce el 95% de nuestros alimentos, filtra y purifica el agua, almacena carbono (mitigando cambio climático), es hábitat de innumerables organismos y soporta todos los ecosistemas terrestres. En Colombia, el suelo sostiene la agricultura del café, flores, frutas y la biodiversidad."),
])

print("W06-W07 done")
