#!/usr/bin/env python3
"""Generate SOC G6 W08-W40 weekly bundles - PART 1: Config + W08-W17"""
import json, os

OUT = r"E:\scripts-python\worldexams\questions_data\colombia\sociales-ciudadanas\grado-6\2026\weekly"
PROTO = "5.2"
YEAR = 2026

W = {}  # week -> {slug, title, rubric}

def add(w, slug, title, rubric):
    W[w] = {"slug": slug, "title": title, "rubric": rubric}

add(8, "primeras-civilizaciones-mesopotamia", "Primeras Civilizaciones: Mesopotamia", "mesopotamia, pueblos_antiguos, sumerios, acadios, babilonios, asirios, escritura_cuneiforme, codigo_hammurabi, zigurats, tigris_eurfrates, civilizacion_fluvial")
add(9, "primeras-civilizaciones-egipto", "Primeras Civilizaciones: Egipto", "egipto, nilo, faraones, piramides, jeroglificos, momificacion, teocracia, sociedad_egipcia, calendario_solar, religion_egipcia")
add(10, "primeras-civilizaciones-india-china", "Primeras Civilizaciones: India y China", "india_antigua, china_antigua, hinduismo, sistema_castas, budismo, confucianismo, rio_indo, rio_amarillo, gran_muralla, invenciones_chinas")
add(11, "primeras-civilizaciones-fenicios-hebreos-persas", "Primeras Civilizaciones: Fenicios, Hebreos y Persas", "fenicios, hebreos, persas, alfabeto_fenicio, comercio_maritimo, monoteismo, ciro_grande, imperio_persa, exodo, zoroastrismo")
add(12, "repaso-p2", "Repaso P2: Civilizaciones Antiguas", "repaso_periodo, civilizaciones_antiguas, pueblos_antiguos, legado_cultural, mesopotamia, egipto, india, china, fenicios, hebreos, persas")
add(13, "grecia-antigua-organizacion-politica", "Grecia Antigua: Organizacion Politica", "grecia_antigua, polis, atenas, esparta, democracia_ateniense, pericles, colonizacion_griega, guerras_medicas, alejandro_magno, imperialismo_ateniense")
add(14, "grecia-antigua-cultura-arte", "Grecia Antigua: Cultura y Arte", "filosofia_griega, arte_griego, arquitectura, escultura, teatro_griego, olimpiadas, mitologia, socrates, platon, aristoteles")
add(15, "roma-antigua-republica", "Roma Antigua: La Republica", "roma_republica, senado, patricios, plebeyos, tribunos, consules, derecho_romano, guerras_punicas, conquistas, via_romanas")
add(16, "roma-antigua-imperio", "Roma Antigua: El Imperio", "imperio_romano, augusto, ciudadania, pax_romana, propagacion, cristianismo, division_imperio, constantino, caida_imperio, legado_romano")
add(17, "repaso-p3", "Repaso P3: Grecia y Roma", "repaso, grecia_antigua, roma_antigua, polis, republica, imperio, democracia, derecho_romano, cultura_clasica, legado_grecorromano")
add(18, "edad-media-caida-imperio-romano", "Edad Media: Caida del Imperio Romano", "caida_imperio_romano, invasiones_barbaras, reinos_germanicos, imperio_bizantino, justiniano, expansion_islamica, carlomagno, edad_media_inicio, migraciones_germanicas, crisis_imperio")
add(19, "edad-media-feudalismo", "Edad Media: El Feudalismo", "feudalismo, vasallaje, feudo, senor_feudal, siervos, nobleza, clero, castillo_medieval, caballero, sociedad_estamental")
add(20, "edad-media-iglesia-cultura", "Edad Media: Iglesia y Cultura", "iglesia_medieval, monacato, monasterios, arte_romanico, arte_gotico, catedrales, universidad_medieval, escolastica, cruzadas, poder_clerical")
add(21, "edad-media-comercio-ciudades", "Edad Media: Comercio y Ciudades", "comercio_medieval, burguesia, gremios, ferias_comerciales, rutas, hans, ciudad_medieval, artesania, renacimiento_urbano, crisis_medieval")
add(22, "repaso-p4", "Repaso P4: Edad Media", "repaso, edad_media, feudalismo, imperio_bizantino, islam, cruzadas, arte_medieval, comercio_medieval, ciudades_medievales, legado_medieval")

# W23-W27
add(23, "edad-moderna-renacimiento", "Edad Moderna: Renacimiento", "renacimiento, humanismo, arte_renacentista, ciencia_renacentista, gutemberg, imprenta, mecenazgo, rafael, leonardo, reforma_cultural")
add(24, "edad-moderna-descubrimiento-america", "Edad Moderna: Descubrimiento de America", "descubrimiento_america, 1492, colon_viajes, navegacion, carabelas, rutas_indias, especias, intercambio_colombino, islas_caribe, espanoles")
add(25, "edad-moderna-conquista-america", "Edad Moderna: Conquista de America", "conquista_america, cortes, pizarro, pueblos_precolombinos, aztecas, incas, colonizacion, virreinato, encomienda, mestizaje")
add(26, "edad-moderna-reforma-contrarreforma", "Edad Moderna: Reforma y Contrarreforma", "reforma, luterana, calvino, contrarreforma, trento, jesuitas, guerras_religion, iglesia_anglicana, catolicismo, protestantismo")
add(27, "repaso-p5", "Repaso P5: Edad Moderna", "repaso, renacimiento, descubrimiento_america, conquista, colonizacion, reforma, contrarreforma, edad_moderna, humanismo, legado_moderno")
add(28, "la-tierra-sistema-solar", "La Tierra en el Sistema Solar", "sistema_solar, tierra, sol, planetas, movimiento_rotacion, movimiento_traslacion, estaciones, satelites, gravedad, via_lactea")
add(29, "mapas-tipos-elementos", "Mapas: Tipos y Elementos", "mapas, cartografia, tipos_mapas, mapa_fisico, mapa_politico, escala, leyenda, rosa_vientos, proyecciones_cartograficas, orientacion")
add(30, "coordenadas-geograficas", "Coordenadas Geograficas", "latitud, longitud, paralelos, meridianos, ecuador, greenwich, hemisferios, tropicos, circulos_polares, geoposicionamiento")
add(31, "husos-horarios", "Husos Horarios", "husos_horarios, GMT, UTC, meridiano_greenwich, linea_fecha, rotacion, hora_mundial, colombia_hora, diferencia_horaria, viajes_tiempo")
add(32, "repaso-p6", "Repaso P6: Geografia Fisica", "repaso, sistema_solar, mapas, coordenadas, husos_horarios, geografia_fisica, tierra, orientacion, cartografia, representacion")
add(33, "economia-produccion", "Economia: Procesos de Produccion", "produccion, sectores_economicos, primario, secundario, terciario, factores_productivos, recursos, trabajo, capital, cadena_productiva")
add(34, "economia-distribucion-consumo", "Economia: Distribucion y Consumo", "distribucion, consumo, mercado, oferta_demanda, comercio, consumo_responsable, derechos_consumidor, ahorro, presupuesto, economia_familiar")
add(35, "publicidad-medios-comunicacion", "Publicidad y Medios de Comunicacion", "publicidad, medios, prensa, radio, television, internet, redes_sociales, mensaje_publicitario, consumo_mediatico, influencia_medios")
add(36, "repaso-p7", "Repaso P7: Economia y Medios", "repaso, produccion, distribucion, consumo, publicidad, medios, economia, mercado, consumo_responsable, ciudadania")
add(37, "poblacion-mundial-distribucion", "La Poblacion Mundial: Distribucion", "poblacion, demografia, distribucion, densidad, censo, crecimiento_urbano, urbanizacion, esperanza_vida, piramide_poblacional, censo_colombia")
add(38, "migraciones-cultura-global", "Migraciones y Cultura Global", "migraciones, emigracion, inmigracion, causas, desplazamiento, multiculturalidad, globalizacion, identidad, xenofobia, colombia_migracion")
add(39, "la-democracia-como-sistema", "La Democracia como Sistema", "democracia, sistema_politico, constitucion_1991, participacion, elecciones, partidos, separacion_poderes, estado_derecho, mecanismos_participacion, voto")
add(40, "repaso-integral-anual", "Repaso Integral Anual", "repaso_anual, historia_antigua, grecia, roma, edad_media, edad_moderna, geografia, economia, democracia, contenidos_anuales")

def qid(w, slug, n):
    return f"CO-SOC-6-2026-W{w:02d}-{slug}-001-MASTERY-v{n+1}"

def fn(w, slug):
    return f"CO-SOC-6-2026-W{w:02d}-{slug}-001-MASTERY-bundle.md"

def render_bundle(w, slug, title, rubric, questions):
    lines = []
    lines.append("---")
    lines.append(f'id: "CO-SOC-6-2026-W{w:02d}-{slug}-001-MASTERY"')
    lines.append('country: "colombia"')
    lines.append("grado: 6")
    lines.append('asignatura: "sociales-ciudadanas"')
    lines.append(f'tema: "{slug}"')
    lines.append(f"semana: {w}")
    lines.append(f'protocol_version: "{PROTO}"')
    lines.append("bundle_index: 1")
    lines.append(f"bundle_size: {len(questions)}")
    lines.append('alignment: "DBA MEN + Estandares Basicos de Competencias Ciudadanas"')
    lines.append("modern_context: true")
    lines.append('distractor_profile: "plausible_peer_set"')
    lines.append("calibration:")
    lines.append("  expected_success_rate: 0.65")
    lines.append('  discrimination_index_target: ">= 0.22"')
    lines.append("  simulated_responses: 100")
    lines.append(f'rubric_baseline: "{rubric}"')
    lines.append("---")
    lines.append("")
    lines.append(f"# Bundle Mastery: {title} -- Semana {w}")
    lines.append("")
    lines.append(f"Este bundle cubre los temas correspondientes a la semana {w}. Alineado con los DBA de Competencias Ciudadanas para grado 6.")
    lines.append("")
    
    for i, q in enumerate(questions):
        lines.append("---")
        lines.append("")
        lines.append(f"## Question {i+1}")
        lines.append("")
        lines.append(f"**ID:** `{q['id']}`")
        lines.append(f"**Bloom:** {q['bloom']}")
        if q.get('icfes'):
            lines.append(f"**ICFES:** {q['icfes']}")
        lines.append("")
        lines.append("### Enunciado")
        lines.append(q['stem'])
        lines.append("")
        lines.append("### Options")
        for label, text, fb in q['options']:
            marker = "x" if label == q['correct'] else " "
            lines.append(f"- [{marker}] {label}) {text} <!-- feedback: {fb} -->")
        lines.append("")
        lines.append("### Explicacion Pedagogica")
        lines.append(q['explanation'])
    
    return "\n".join(lines)

def write_bundle(w):
    c = W[w]
    slug, title, rubric = c["slug"], c["title"], c["rubric"]
    qs = c.get("qs")
    if not qs:
        print(f"SKIP W{w:02d}: no questions defined")
        return False
    if len(qs) != 10:
        print(f"WARN W{w:02d}: {len(qs)} questions")
    for i, q in enumerate(qs):
        q["id"] = qid(w, slug, i)
    content = render_bundle(w, slug, title, rubric, qs)
    fpath = os.path.join(OUT, fn(w, slug))
    with open(fpath, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"OK W{w:02d}: {fn(w, slug)} ({len(qs)} preg)")
    return True

# ============================================================
# QUESTIONS DATA
# ============================================================

# W08: Mesopotamia
W[8]["qs"] = [
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"Entre que dos rios se desarrollo la civilizacion de Mesopotamia?","options":[["A","Rio Nilo y Rio Jordan","Incorrecto. El Nilo esta en Egipto y el Jordan en Palestina."],["B","Rio Danubio y Rio Rin","Incorrecto. Estos rios estan en Europa."],["C","Rio Tigris y Rio Eufrates","Correcto. Mesopotamia significa 'tierra entre rios' en griego."],["D","Rio Indo y Rio Ganges","Incorrecto. Estos rios estan en la India."]],"correct":"C","explanation":"Mesopotamia, que significa 'tierra entre rios', se desarrollo entre los rios Tigris y Eufrates en el actual Irak. Alli surgieron las primeras ciudades y sistemas de escritura."},
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"Que invento se atribuye a los sumerios de Mesopotamia?","options":[["A","El papel","Incorrecto. El papel fue inventado en China siglos despues."],["B","La escritura cuneiforme","Correcto. Los sumerios inventaron la escritura cuneiforme alrededor del 3500 a.C."],["C","El alfabeto fonetico","Incorrecto. El alfabeto fenicio es el precursor de los alfabetos modernos."],["D","Los jeroglificos","Incorrecto. Los jeroglificos son egipcios."]],"correct":"B","explanation":"Los sumerios crearon la escritura cuneiforme, un sistema de signos en forma de cuna grabados en tablillas de arcilla. Es considerada la primera forma de escritura de la humanidad."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Por que es importante el Codigo de Hammurabi?","options":[["A","Es el primer libro de poemas conocido","Incorrecto. No es una obra literaria sino un codigo legal."],["B","Es uno de los primeros conjuntos de leyes escritas de la historia","Correcto. El Codigo de Hammurabi contenio 282 leyes que regulaban la sociedad babilonica."],["C","Describe como construir las piramides","Incorrecto. Es un codigo de leyes, no de arquitectura."],["D","Narra la creacion del mundo segun los sumerios","Incorrecto. El Poema de Gilgamesh es la obra epica mesopotamica."]],"correct":"B","explanation":"El Codigo de Hammurabi (1754 a.C.), creado por el rey Hammurabi de Babilonia, es uno de los primeros conjuntos de leyes escritas conocidos."},
    {"bloom":"Apply","icfes":"Pensamiento Social","stem":"Un estudiante en Bogota visita un museo y ve una maqueta de un zigurat. Cual era la funcion de estas construcciones?","options":[["A","Eran tumbas para faraones","Incorrecto. Las piramides egipcias cumplian esa funcion."],["B","Eran templos religiosos en forma de torre escalonada","Correcto. Los zigurats eran templos escalonados donde se adoraba a los dioses de la ciudad."],["C","Eran mercados para el comercio","Incorrecto. Tenian funcion religiosa, no comercial."],["D","Eran fortalezas militares","Incorrecto. Las murallas defendian las ciudades."]],"correct":"B","explanation":"Los zigurats eran enormes torres escalonadas que funcionaban como templos. Cada ciudad mesopotamica tenia uno dedicado a su dios protector."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Como estaba organizada la sociedad en Mesopotamia?","options":[["A","Era una sociedad sin clases sociales","Incorrecto. Mesopotamia tenia una clara jerarquia social."],["B","Rey en la cima, luego sacerdotes, escribas, comerciantes, campesinos y esclavos","Correcto. La sociedad era una piramide jerarquica con el monarca en la cuspide."],["C","Solo habian dos clases: libres y esclavos","Incorrecto. Habia multiples niveles sociales intermedios."],["D","El pueblo elegia a sus gobernantes","Incorrecto. El gobierno era monarquico."]],"correct":"B","explanation":"La sociedad mesopotamica estaba jerarquizada: el rey en la cima, seguido por sacerdotes y funcionarios, escribas, comerciantes, artesanos, campesinos y finalmente esclavos."},
    {"bloom":"Analyze","icfes":"Pensamiento Social","stem":"Por que se considera a Mesopotamia la 'cuna de la civilizacion'?","options":[["A","Porque alli aparecio el primer ser humano","Incorrecto. Los primeros humanos aparecieron en Africa."],["B","Porque alli surgieron las primeras ciudades, la escritura y el Estado","Correcto. En Mesopotamia aparecieron innovaciones fundamentales."],["C","Porque alli se construyeron las primeras piramides","Incorrecto. Las piramides son egipcias."],["D","Porque alli se domesticaron los primeros animales","Incorrecto. La domesticacion ocurrio en el Neolitico en varias regiones."]],"correct":"B","explanation":"Mesopotamia es la cuna de la civilizacion porque alli surgieron ciudades organizadas, escritura, leyes escritas y agricultura de regadio."},
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"Cual era el principal dios de los babilonios?","options":[["A","Zeus","Incorrecto. Zeus es un dios griego."],["B","Ra","Incorrecto. Ra es un dios egipcio."],["C","Marduk","Correcto. Marduk era el dios principal de Babilonia."],["D","Odin","Incorrecto. Odin es un dios nordico."]],"correct":"C","explanation":"Marduk era el dios patrono de Babilonia. Segun el mito babilonico, vencio al caos (Tiamat) y creo el orden del mundo."},
    {"bloom":"Apply","icfes":"Pensamiento Social","stem":"En clase de sociales en Cali, la profesora explica que los mesopotamicos construyeron canales de riego. Cual era su proposito?","options":[["A","Navegar entre ciudades","Incorrecto. Aunque ayudaban al transporte, ese no era su proposito principal."],["B","Llevar agua desde los rios a los campos de cultivo","Correcto. Los canales permitian controlar inundaciones y regar los cultivos."],["C","Proveer agua potable a las ciudades","Incorrecto. La funcion principal era agricola."],["D","Defender las ciudades de invasores","Incorrecto. La defensa se hacia con murallas, no canales."]],"correct":"B","explanation":"Los canales de riego mesopotamicos llevaban agua del Tigris y Eufrates a los campos de cultivo, permitiendo una agricultura productiva."},
    {"bloom":"Evaluate","icfes":"Pensamiento Social","stem":"Comparando la escritura mesopotamica con la comunicacion digital actual, que diferencia es mas significativa?","options":[["A","La escritura cuneiforme era mas rapida","Incorrecto. Escribir en tablillas de arcilla era lento y laborioso."],["B","La escritura mesopotamica era fisica y local; la digital es virtual e instantanea a escala global","Correcto. La informacion digital viaja en segundos a todo el mundo."],["C","Ambas usan el mismo alfabeto","Incorrecto. La cuneiforme usaba pictogramas y signos, no un alfabeto."],["D","Los mesopotamicos no tenian escritura","Incorrecto. Los sumerios inventaron la escritura."]],"correct":"B","explanation":"La escritura cuneiforme requeria tablillas fisicas que se transportaban a pie o en barco. Hoy la comunicacion digital transmite informacion globalmente en segundos."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Que tenian en comun los imperios acadio, babilonico y asirio?","options":[["A","Todos eran imperios maritimos","Incorrecto. Mesopotamia no tenia costa."],["B","Todos gobernaron desde la misma capital","Incorrecto. Cada imperio tuvo capitales distintas."],["C","Todos unificaron territorios bajo un gobierno centralizado en Mesopotamia","Correcto. Los tres imperios controlaron amplias zonas entre el Tigris y Eufrates."],["D","Todos fueron derrotados por Egipto","Incorrecto. Fueron conquistados por los persas."]],"correct":"C","explanation":"Acadios, babilonios y asirios crearon imperios que unificaron politicamente la region mesopotamica en distintos periodos."},
]

# W09: Egipto
W[9]["qs"] = [
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"Que rio fue esencial para el desarrollo de la civilizacion egipcia?","options":[["A","Rio Tigris","Incorrecto. Esta en Mesopotamia."],["B","Rio Nilo","Correcto. El Nilo proporciono agua y suelo fertil con sus inundaciones anuales."],["C","Rio Jordan","Incorrecto. Esta en Palestina."],["D","Rio Indo","Incorrecto. Esta en la India."]],"correct":"B","explanation":"El Nilo fue vital para Egipto. Herodoto dijo: 'Egipto es un don del Nilo'. Sus inundaciones anuales depositaban limo fertil en las orillas."},
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"Como se llamaba el gobernante del Antiguo Egipto considerado un dios viviente?","options":[["A","Emperador","Incorrecto. Titulo usado en Roma y China."],["B","Faraon","Correcto. El faraon era el gobernante absoluto, hijo del dios Ra."],["C","Rey-sacerdote","Incorrecto. Su titulo era faraon."],["D","Satrapa","Incorrecto. Los satrapas eran gobernadores persas."]],"correct":"B","explanation":"El faraon era el monarca absoluto, maxima autoridad politica, religiosa y militar, considerado un dios viviente."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Cual era el proposito de construir piramides en el Antiguo Egipto?","options":[["A","Observatorios astronomicos","Incorrecto. No eran observatorios."],["B","Templos para el culto a los dioses","Incorrecto. Los templos eran construcciones aparte."],["C","Tumbas monumentales para los faraones","Correcto. Las piramides albergaban el cuerpo momificado del faraon para la vida eterna."],["D","Almacenes de grano","Incorrecto. Los graneros eran edificios separados."]],"correct":"C","explanation":"Las piramides eran monumentos funerarios para preservar el cuerpo del faraon y sus tesoros para la otra vida."},
    {"bloom":"Apply","icfes":"Pensamiento Social","stem":"Un estudiante en Cartagena aprende sobre la momificacion egipcia. Cual era su proposito?","options":[["A","Conservar el cuerpo para que el alma lo reconociera en la otra vida","Correcto. Los egipcios creian que el alma necesitaba el cuerpo para la vida eterna."],["B","Curar enfermedades","Incorrecto. No tenia fines medicos."],["C","Crear obras de arte","Incorrecto. Era un proceso religioso, no artistico."],["D","Alimentar animales sagrados","Incorrecto. No se momificaba con ese proposito."]],"correct":"A","explanation":"La momificacion preservaba el cuerpo porque los egipcios creian que el alma (Ba) y la fuerza vital (Ka) necesitaban el cuerpo fisico."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Quienes estaban en la cima de la piramide social egipcia?","options":[["A","Los campesinos","Incorrecto. Estaban en la base."],["B","El faraon, la familia real y los altos sacerdotes","Correcto. En la cima estaba el faraon, seguido de nobles y sacerdotes."],["C","Los soldados","Incorrecto. Los militares tenian estatus medio."],["D","Los esclavos extranjeros","Incorrecto. Estaban en la base social."]],"correct":"B","explanation":"La sociedad egipcia era jerarquica: faraon en la cuspide, luego nobles y sacerdotes, escribas, comerciantes, artesanos, campesinos y esclavos."},
    {"bloom":"Analyze","icfes":"Pensamiento Social","stem":"Por que los egipcios crearon un calendario de 365 dias?","options":[["A","Lo copiaron de los romanos","Incorrecto. El calendario egipcio es anterior al romano."],["B","Para predecir las inundaciones del Nilo y organizar la agricultura","Correcto. Las inundaciones anuales del Nilo marcaban el ciclo agricola."],["C","Para celebrar el cumpleanos del faraon","Incorrecto. Tenia proposito practico."],["D","Para seguir las fases lunares","Incorrecto. Era un calendario solar."]],"correct":"B","explanation":"Los egipcios crearon uno de los primeros calendarios solares para predecir las inundaciones del Nilo, cruciales para la agricultura."},
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"Como se llama el sistema de escritura del Antiguo Egipto?","options":[["A","Cuneiforme","Incorrecto. Es de Mesopotamia."],["B","Jeroglifico","Correcto. Los jeroglificos combinaban simbolos que representaban sonidos, objetos e ideas."],["C","Alfabeto fenicio","Incorrecto. Es de los fenicios."],["D","Sanscrito","Incorrecto. Es de la India."]],"correct":"B","explanation":"Los jeroglificos combinaban logogramas (simbolos que representan palabras) y signos foneticos. Se usaban en monumentos."},
    {"bloom":"Apply","icfes":"Pensamiento Social","stem":"En una clase en Barranquilla preguntan: por que los egipcios adoraban al dios Ra?","options":[["A","Porque Ra era el dios de la guerra","Incorrecto. Ra no era dios de la guerra."],["B","Porque Ra era el dios del sol, fuente de vida para la agricultura","Correcto. El sol era vital para la vida en el desierto."],["C","Porque Ra era el dios del Nilo","Incorrecto. El dios del Nilo era Hapy."],["D","Porque Ra protegia las piramides","Incorrecto. Anubis era el dios de los muertos."]],"correct":"B","explanation":"Ra, el dios del sol, era la deidad mas importante. El sol era esencial para la vida en el desierto y la agricultura egipcia."},
    {"bloom":"Evaluate","icfes":"Pensamiento Social","stem":"Comparando el gobierno egipcio con la democracia colombiana actual, cual es la diferencia principal?","options":[["A","Ambos sistemas eligen a sus gobernantes por voto popular","Incorrecto. En Egipto no habia elecciones."],["B","Egipto era una teocracia con un faraon divino; Colombia es una democracia con separacion de poderes","Correcto. El faraon concentraba todo el poder."],["C","Ambos tienen congreso y senado","Incorrecto. Egipto no tenia legislatura."],["D","En Colombia el presidente tambien es considerado un dios","Incorrecto. Colombia no tiene un sistema teocratico."]],"correct":"B","explanation":"Egipto era una teocracia donde el faraon concentraba poder politico, religioso y militar. Colombia es una democracia con tres poderes independientes."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Que papel tenian los escribas en la sociedad egipcia?","options":[["A","Eran esclavos que construian piramides","Incorrecto. Los escribas gozaban de prestigio."],["B","Eran funcionarios que registraban cosechas, impuestos y documentos oficiales","Correcto. Los escribas eran alfabetizados y muy respetados."],["C","Eran guerreros del ejercito","Incorrecto. Los soldados tenian diferente funcion."],["D","Eran sacerdotes del templo","Incorrecto. Sacerdotes y escribas eran grupos distintos."]],"correct":"B","explanation":"Los escribas eran uno de los grupos mas respetados. Sabian leer y escribir jeroglificos, registraban cosechas, impuestos y administraban el Estado."},
]

# W10: India, China
W[10]["qs"] = [
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"A orillas de que rio se desarrollo la primera civilizacion en la India?","options":[["A","Rio Ganges","Incorrecto. Aunque importante, la civilizacion mas antigua fue en el Indo."],["B","Rio Indo","Correcto. La civilizacion del Valle del Indo florecio hacia el 2500 a.C."],["C","Rio Brahmaputra","Incorrecto. No fue el eje principal."],["D","Rio Nilo","Incorrecto. Esta en Egipto."]],"correct":"B","explanation":"La civilizacion del Valle del Indo, con ciudades como Harappa y Mohenjo-Daro, tenia avanzada planificacion urbana y sistemas de drenaje."},
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"Cual es el sistema de escritura mas antiguo de China?","options":[["A","Jeroglifico","Incorrecto. Es de Egipto."],["B","Cuneiforme","Incorrecto. Es de Mesopotamia."],["C","Caracteres en huesos oraculares","Correcto. Los primeros caracteres chinos se encuentran en huesos oraculares de la dinastia Shang."],["D","Sanscrito","Incorrecto. Es de la India."]],"correct":"C","explanation":"Los caracteres chinos mas antiguos se encontraron en huesos oraculares de la dinastia Shang (1600-1046 a.C.), usados para adivinacion."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Que es el sistema de castas en la India antigua?","options":[["A","Un sistema de gobierno democratico","Incorrecto. No era un sistema politico."],["B","Una jerarquia social hereditaria que dividia la sociedad en grupos cerrados","Correcto. Las castas determinaban la vida y ocupacion de las personas."],["C","Un sistema de escritura","Incorrecto. Era una organizacion social."],["D","Un tipo de templo religioso","Incorrecto. No era una construccion."]],"correct":"B","explanation":"El sistema de castas dividia la sociedad en cuatro grupos principales: brahmanes (sacerdotes), chatrias (guerreros), vaisias (comerciantes) y sudras (sirvientes). Era hereditario."},
    {"bloom":"Apply","icfes":"Pensamiento Social","stem":"Un estudiante en Bucaramanga investiga sobre Buda. Que ensenaba principalmente?","options":[["A","La existencia de muchos dioses","Incorrecto. El budismo no se centra en dioses."],["B","El camino para superar el sufrimiento mediante el desapego y alcanzar el Nirvana","Correcto. Buda enseno el camino octuple para alcanzar la iluminacion."],["C","La guerra santa contra los infieles","Incorrecto. Buda predicaba la no violencia."],["D","La construccion de piramides","Incorrecto. Esa es una practica egipcia."]],"correct":"B","explanation":"Siddhartha Gautama (Buda) enseno que el sufrimiento surge del deseo y el apego. Propuso el Noble Camino Octuple para alcanzar el Nirvana."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Confucio, importante filosofo chino, ensenaba principalmente sobre:","options":[["A","La vida despues de la muerte","Incorrecto. Confucio se centro en la vida terrenal."],["B","La armonia social, el respeto a los mayores y la rectitud moral","Correcto. El confucianismo enfatiza la etica, la familia y el orden social."],["C","La conquista militar de otros pueblos","Incorrecto. Predicaba la paz y el orden."],["D","La existencia de un solo dios","Incorrecto. No era una religion teista."]],"correct":"B","explanation":"Confucio (551-479 a.C.) enseno valores como el respeto a los mayores, la lealtad, la honestidad y la importancia de la educacion para la armonia social."},
    {"bloom":"Analyze","icfes":"Pensamiento Social","stem":"Por que la Gran Muralla China fue una construccion importante?","options":[["A","Era un templo religioso","Incorrecto. Era defensiva."],["B","Protegia el imperio chino de invasiones del norte","Correcto. Se construyo para defender la frontera norte de invasiones."],["C","Servia como mercado para comerciantes","Incorrecto. No era una construccion comercial."],["D","Era un canal de navegacion","Incorrecto. Era una muralla defensiva."]],"correct":"B","explanation":"La Gran Muralla, construida por varias dinastias, protegia el imperio chino de invasiones de pueblos del norte como los mongoles y xiongnu."},
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"Que invento la antigua China que revoluciono la navegacion?","options":[["A","El astrolabio","Incorrecto. Fue inventado por los griegos."],["B","La brujula","Correcto. Los chinos inventaron la brujula magnetica para la navegacion."],["C","El telescopio","Incorrecto. Es un invento europeo del siglo XVII."],["D","El barco de vapor","Incorrecto. Es un invento del siglo XIX."]],"correct":"B","explanation":"La brujula magnetica fue inventada en China durante la dinastia Han y perfeccionada para la navegacion maritima."},
    {"bloom":"Apply","icfes":"Pensamiento Social","stem":"Un nino en Medellin lee que el hinduismo es la religion mas antigua de la India. Que caracteristica tiene?","options":[["A","Cree en un solo dios","Incorrecto. El hinduismo tiene muchos dioses."],["B","Cree en muchos dioses y en la reencarnacion del alma","Correcto. El hinduismo es politeista con creencia en el karma y la reencarnacion."],["C","Rechaza la existencia de dioses","Incorrecto. El hinduismo es teista."],["D","Adora al faraon","Incorrecto. Esa es una practica egipcia."]],"correct":"B","explanation":"El hinduismo, una de las religiones mas antiguas, es politeista. Cree en la reencarnacion (samsara) determinada por el karma acumulado."},
    {"bloom":"Evaluate","icfes":"Pensamiento Social","stem":"Comparando las civilizaciones de India y China antiguas, que similitud tenian en su desarrollo?","options":[["A","Ambas eran democracias","Incorrecto. Ambas eran monarquias."],["B","Ambas se desarrollaron alrededor de grandes rios","Correcto. India (Indo, Ganges) y China (Amarillo, Yangtse) fueron civilizaciones fluviales."],["C","Ambas usaban el mismo alfabeto","Incorrecto. Tenian sistemas de escritura diferentes."],["D","Ambas rechazaban el comercio","Incorrecto. Ambas comerciaban activamente."]],"correct":"B","explanation":"Tanto India como China surgieron como civilizaciones fluviales alrededor de grandes rios que proporcionaban agua y suelos fertiles."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Como influyo la geografia de China en su aislamiento cultural?","options":[["A","China estaba rodeada de mares por todos lados","Incorrecto. No esta completamente rodeada de mares."],["B","El Himalaya, los desiertos y el mar la aislaban geograficamente","Correcto. Montanas, desiertos y oceano la separaban de otras culturas."],["C","China no tenia fronteras naturales","Incorrecto. Si tenia barreras naturales."],["D","Los chinos construyeron muros para aislarse","Incorrecto. El aislamiento fue principalmente geografico."]],"correct":"B","explanation":"China estuvo geograficamente aislada por el Himalaya, el desierto de Gobi y el oceano Pacifico, lo que favorecio un desarrollo cultural unico."},
]

# W11: Fenicios, Hebreos, Persas
W[11]["qs"] = [
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"Por que son conocidos principalmente los fenicios?","options":[["A","Por construir piramides","Incorrecto. Esa es una caracteristica egipcia."],["B","Por ser grandes navegantes y comerciantes, y crear el alfabeto","Correcto. Los fenicios fueron los grandes comerciantes maritimos de la antigueedad."],["C","Por conquistar el imperio mas grande del mundo","Incorrecto. Fueron comerciantes, no conquistadores."],["D","Por desarrollar la democracia","Incorrecto. La democracia se desarrollo en Grecia."]],"correct":"B","explanation":"Los fenicios, ubicados en el actual Libano, fueron grandes navegantes que crearon el primer alfabeto fonetico, base de los alfabetos occidentales."},
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"Cual fue la principal contribucion de los fenicios a la escritura?","options":[["A","La escritura cuneiforme","Incorrecto. Es de Mesopotamia."],["B","Los jeroglificos","Incorrecto. Son egipcios."],["C","El alfabeto fonetico de 22 signos","Correcto. Los fenicios crearon un alfabeto simple que los griegos adaptaron anadiendo vocales."],["D","El papel","Incorrecto. Fue inventado en China."]],"correct":"C","explanation":"Los fenicios simplificaron la escritura creando un alfabeto de 22 signos que representaban sonidos consonanticos. Los griegos lo adaptaron anadiendo vocales."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Que caracteristica distingue a los hebreos de otros pueblos antiguos?","options":[["A","Eran politeistas","Incorrecto. Los hebreos eran monoteistas."],["B","Fueron el primer pueblo en practicar el monoteismo de forma organizada","Correcto. Los hebreos adoraban a un solo Dios (Yahve)."],["C","Vivian en ciudades-estado independientes","Incorrecto. Se organizaban en tribus y luego en un reino."],["D","Construyeron grandes piramides","Incorrecto. No construyeron piramides."]],"correct":"B","explanation":"Los hebreos fueron pioneros en el monoteismo, adorando a un unico Dios. Su religion, el judaismo, es la base del cristianismo y el islam."},
    {"bloom":"Apply","icfes":"Pensamiento Social","stem":"Un estudiante en Bogota lee que los fenicios establecieron colonias en el Mediterraneo. Cual era el proposito de estas colonias?","options":[["A","Conquistar nuevos territorios para su imperio","Incorrecto. Los fenicios no tenian un imperio militar, eran comerciantes."],["B","Establecer puestos comerciales para intercambiar productos","Correcto. Las colonias fenicias eran puertos comerciales estrategicos."],["C","Difundir el monoteismo entre otros pueblos","Incorrecto. No tenian mision religiosa."],["D","Buscar refugio de las guerras","Incorrecto. Eran empresas comerciales planificadas."]],"correct":"B","explanation":"Los fenicios establecieron colonias comerciales como Cartago en todo el Mediterraneo para facilitar el intercambio de productos como madera, vidrio y tintes."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Quien fue Ciro el Grande y por que es importante en la historia?","options":[["A","Un faraon egipcio que construyo la Gran Piramide","Incorrecto. Ciro no era egipcio."],["B","El rey persa que creo el imperio mas grande de su epoca y respeto las costumbres de los pueblos conquistados","Correcto. Ciro fundo el Imperio Persa y fue conocido por su tolerancia."],["C","Un filosofo griego fundador de la democracia","Incorrecto. Ciro no era filosofo ni griego."],["D","Un profeta hebreo que libero a su pueblo de Egipto","Incorrecto. Moises fue el profeta que libero a los hebreos de Egipto."]],"correct":"B","explanation":"Ciro el Grande (559-530 a.C.) fundo el Imperio Persa Aquemenida. Conquisto Babilonia pero respeto las culturas y religiones de los pueblos sometidos."},
    {"bloom":"Analyze","icfes":"Pensamiento Social","stem":"Que ventaja tenia el alfabeto fenicio sobre otros sistemas de escritura de la antigueedad?","options":[["A","Era mas dificil de aprender","Incorrecto. Era mas simple."],["B","Era mas facil de aprender porque tenia pocos signos que representaban sonidos","Correcto. Con solo 22 signos se podia escribir cualquier palabra."],["C","Solo podia ser usado por sacerdotes","Incorrecto. Estaba disenado para el comercio, era practico."],["D","Usaba dibujos complejos para representar ideas","Incorrecto. Usaba signos simples para sonidos."]],"correct":"B","explanation":"Mientras otros sistemas tenian cientos de signos, el alfabeto fenicio tenia solo 22, facilitando su aprendizaje y difusion entre comerciantes."},
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"En que region se establecio originalmente el pueblo hebreo?","options":[["A","En la peninsula de Italia","Incorrecto. Los hebreos se establecieron en Canaan."],["B","En Canaan (actual Israel/Palestina)","Correcto. Los hebreos se establecieron en la tierra de Canaan, prometida segun su tradicion."],["C","En la India","Incorrecto. No se establecieron en la India."],["D","En Egipto","Incorrecto. Estuvieron esclavizados en Egipto pero no era su tierra de origen."]],"correct":"B","explanation":"Los hebreos se establecieron en Canaan, la 'tierra prometida'. Alli formaron un reino unificado bajo Saul, David y Salomon, con capital en Jerusalen."},
    {"bloom":"Apply","icfes":"Pensamiento Social","stem":"En clase de sociales en Medellin, el profesor explica que el Imperio Persa permitia cierta autonomia a las provincias conquistadas. Esto se conoce como:","options":[["A","Democracia","Incorrecto. No era democracia, las provincias seguian bajo control persa."],["B","Descentralizacion administrativa con satrapias","Correcto. El imperio se dividio en satrapias (provincias) con gobernadores que tenian cierta autonomia."],["C","Esclavitud","Incorrecto. No tiene relacion."],["D","Feudalismo","Incorrecto. El feudalismo es un sistema medieval europeo."]],"correct":"B","explanation":"El Imperio Persa dividio su territorio en satrapias, cada una con un satrapa (gobernador). Esto permitio administrar eficientemente un imperio enorme y diverso."},
    {"bloom":"Evaluate","icfes":"Pensamiento Social","stem":"Comparando los fenicios con los hebreos, que diferencias fundamentales habia entre ambos pueblos?","options":[["A","Ambos eran monoteistas y comerciantes","Incorrecto. Los fenicios eran politeistas, no monoteistas."],["B","Los fenicios eran politeistas y comerciantes maritimos; los hebreos eran monoteistas y se centraban en su religion y tradiciones","Correcto. Eran pueblos muy diferentes en religion y actividad economica."],["C","Ambos construyeron grandes imperios militares","Incorrecto. Ninguno construyo un imperio militar como los persas."],["D","Los fenicios eran monoteistas y los hebreos politeistas","Incorrecto. Es al reves: los fenicios eran politeistas y los hebreos monoteistas."]],"correct":"B","explanation":"Mientras los fenicios comerciaban por todo el Mediterraneo y adoraban a varios dioses, los hebreos se enfocaban en su relacion con Yahve y conservaban su identidad religiosa."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Cual fue el legado mas importante del Imperio Persa?","options":[["A","La democracia","Incorrecto. La democracia es griega."],["B","La administracion eficiente de un imperio multicultural y el respeto por las culturas locales","Correcto. Los persas crearon un sistema de gobierno tolerante y eficiente."],["C","La construccion de las piramides","Incorrecto. Es egipcio."],["D","El alfabeto","Incorrecto. El alfabeto es fenicio."]],"correct":"B","explanation":"El Imperio Persa se destaco por administrar un territorio multicultural con tolerancia, permitiendo a los pueblos conservar sus costumbres mientras pagaban tributo."},
]

# W12: Repaso P2
W[12]["qs"] = [
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"Cual de las siguientes civilizaciones se desarrollo entre los rios Tigris y Eufrates?","options":[["A","Egipto","Incorrecto. Egipto se desarrollo alrededor del Nilo."],["B","Mesopotamia","Correcto. Mesopotamia, cuyo nombre significa 'tierra entre rios', se ubico entre el Tigris y el Eufrates."],["C","India","Incorrecto. India se desarrollo alrededor del Indo."],["D","China","Incorrecto. China se desarrollo en los rios Amarillo y Yangtse."]],"correct":"B","explanation":"Mesopotamia significa 'tierra entre rios'. Esta civilizacion florecio en el valle fertil entre los rios Tigris y Eufrates."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Que civilizacion construyo piramides como tumbas monumentales para sus gobernantes?","options":[["A","Mesopotamia","Incorrecto. Los mesopotamicos construian zigurats."],["B","El Antiguo Egipto","Correcto. Los egipcios construyeron piramides como tumbas para los faraones."],["C","La India antigua","Incorrecto. En la India no hay piramides."],["D","Los fenicios","Incorrecto. Los fenicios no construian piramides."]],"correct":"B","explanation":"Las piramides egipcias, como la de Keops, son monumentos funerarios construidos para albergar la momia del faraon y sus pertenencias."},
    {"bloom":"Apply","icfes":"Pensamiento Social","stem":"Un estudiante en Cali esta haciendo una tarea sobre sistemas de escritura antiguos. Si encuentra un texto grabado en tablillas de arcilla con signos en forma de cuna, de que civilizacion proviene?","options":[["A","Egipto","Incorrecto. Los egipcios usaban jeroglificos en papiro y piedra."],["B","Mesopotamia","Correcto. La escritura cuneiforme mesopotamica se grababa en tablillas de arcilla con un punzon."],["C","China","Incorrecto. Los chinos usaban caracteres en huesos y seda."],["D","Fenicia","Incorrecto. Los fenicios escribian con tinta sobre papiro."]],"correct":"B","explanation":"La escritura cuneiforme, inventada por los sumerios, se realizaba presionando un punzon sobre tablillas de arcilla blanda que luego se secaban al sol o al horno."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Cual de las siguientes NO es una caracteristica de las civilizaciones fluviales?","options":[["A","Se desarrollaron alrededor de grandes rios","Incorrecto. Esta SI es una caracteristica de las civilizaciones fluviales."],["B","Dependian de la agricultura de regadio","Incorrecto. La agricultura de regadio SI era fundamental."],["C","Eran sociedades nomas sin ciudades permanentes","Correcto. Las civilizaciones fluviales construyeron ciudades permanentes, no eran nomas."],["D","Desarrollaron sistemas de escritura y gobierno","Incorrecto. El desarrollo de escritura y Estado SI es caracteristico."]],"correct":"C","explanation":"Las civilizaciones fluviales (Mesopotamia, Egipto, India, China) eran sedentarias y construyeron ciudades permanentes con agricultura organizada."},
    {"bloom":"Analyze","icfes":"Pensamiento Social","stem":"Comparando el gobierno de Egipto (faraon) y Mesopotamia (reyes), que similitud importante compartian?","options":[["A","Ambos eran elegidos por voto popular","Incorrecto. Ninguno era democratico."],["B","Ambos concentraban el poder politico y religioso, aunque en Egipto el faraon era considerado un dios viviente","Correcto. En ambos casos el gobernante tenia poder absoluto, pero el faraon tenia caracter divino."],["C","Ambos gobernaban con un parlamento","Incorrecto. No habia parlamentos en la antigueedad."],["D","Ambos sistemas eran republicanos","Incorrecto. Eran monarquias absolutas."]],"correct":"B","explanation":"Tanto el faraon egipcio como los reyes mesopotamicos concentraban el poder. Sin embargo, el faraon era considerado directamente un dios viviente."},
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"Que alfabeto simplificado de 22 signos fue creado por los fenicios?","options":[["A","El alfabeto griego","Incorrecto. El alfabeto griego se baso en el fenicio, pero fue posterior."],["B","El alfabeto fenicio","Correcto. Los fenicios crearon el primer alfabeto fonetico de 22 signos consonanticos."],["C","El alfabeto latino","Incorrecto. El alfabeto latino es aun posterior."],["D","Los jeroglificos","Incorrecto. Los jeroglificos no son un alfabeto, sino un sistema de escritura egipcio."]],"correct":"B","explanation":"El alfabeto fenicio, con solo 22 signos que representaban sonidos, revoluciono la comunicacion. Fue adoptado y adaptado por griegos y romanos."},
    {"bloom":"Evaluate","icfes":"Pensamiento Social","stem":"Que civilizacion antigua contribuyo mas al desarrollo de la ciencia y las matematicas, segun lo que has estudiado?","options":[["A","Mesopotamia, con el sistema sexagesimal y la astronomia","Correcto. Los mesopotamicos desarrollaron el sistema de 60 (minutos, horas), la rueda y avanzados conocimientos astronomicos."],["B","Fenicia, con el alfabeto","Incorrecto. Aunque importante, el alfabeto no es ciencia."],["C","Egipto, con el calendario","Incorrecto. El calendario es importante pero no cubre todas las areas cientificas."],["D","China, con el papel","Incorrecto. El papel es un invento tecnologico, no cientifico."]],"correct":"A","explanation":"Mesopotamia hizo contribuciones fundamentales: el sistema sexagesimal (base de nuestras horas y minutos), la rueda, la astronomia y las matematicas aplicadas."},
    {"bloom":"Apply","icfes":"Pensamiento Social","stem":"En un examen de sociales en Pereira, preguntan: que tienen en comun el Codigo de Hammurabi, los jeroglificos egipcios y el alfabeto fenicio?","options":[["A","Fueron inventados por el mismo pueblo","Incorrecto. Cada uno pertenece a una civilizacion diferente."],["B","Son invenciones que demuestran el desarrollo cultural y tecnologico de las civilizaciones antiguas","Correcto. Las leyes, la escritura y el alfabeto muestran avances fundamentales."],["C","Fueron descubiertos en el siglo XX","Incorrecto. Son invenciones antiguas, no descubrimientos modernos."],["D","Ninguno de ellos fue importante para la historia","Incorrecto. Todos fueron muy importantes."]],"correct":"B","explanation":"El Codigo de Hammurabi (leyes), los jeroglificos (escritura) y el alfabeto fenicio demuestran el alto nivel de desarrollo alcanzado por estas civilizaciones."},
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"Cual de los siguientes pueblos antiguos practicaba el monoteismo?","options":[["A","Fenicios","Incorrecto. Los fenicios eran politeistas, adoraban a Baal y Astarte."],["B","Hebreos","Correcto. Los hebreos fueron el primer pueblo monoteista organizado."],["C","Egipcios","Incorrecto. Los egipcios adoraban a muchos dioses como Ra, Osiris e Isis."],["D","Mesopotamicos","Incorrecto. Eran politeistas con dioses como Marduk, Ishtar y Enlil."]],"correct":"B","explanation":"Los hebreos se distinguieron por adorar a un unico Dios (Yahve), a diferencia de los pueblos vecinos que adoraban a multiples deidades."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Que region geografica compartieron las civilizaciones de Mesopotamia, Fenicia y los Hebreos?","options":[["A","Asia oriental (China, India)","Incorrecto. Esas civilizaciones estan en el Lejano Oriente."],["B","El Creciente Fertil (Oriente Medio)","Correcto. Las tres civilizaciones se ubicaron en la region del Creciente Fertil en Oriente Medio."],["C","Africa subsahariana","Incorrecto. No se ubicaron en Africa subsahariana."],["D","Europa occidental","Incorrecto. Estas civilizaciones no estaban en Europa occidental."]],"correct":"B","explanation":"El Creciente Fertil es una region en forma de media luna que abarca desde Mesopotamia hasta el Mediterraneo. Alli surgieron las primeras civilizaciones de Oriente Medio."},
]

# W13: Grecia antigua: organizacion politica
W[13]["qs"] = [
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"Como se llamaban las ciudades-estado independientes de la antigua Grecia?","options":[["A","Satrapias","Incorrecto. Las satrapias eran provincias del Imperio Persa."],["B","Polis","Correcto. Las polis eran ciudades-estado griegas independientes con su propio gobierno."],["C","Provincias","Incorrecto. Las provincias son una division administrativa romana."],["D","Reinos","Incorrecto. Aunque habia reinos, el termino correcto para las ciudades-estado griegas es polis."]],"correct":"B","explanation":"La polis era la unidad politica fundamental de Grecia. Cada polis era independiente, con sus propias leyes, ejercito y gobierno."},
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"Cuales eran las dos polis mas importantes de la antigua Grecia?","options":[["A","Roma y Cartago","Incorrecto. Roma y Cartago no son polis griegas."],["B","Atenas y Esparta","Correcto. Atenas y Esparta fueron las dos polis mas poderosas e influyentes de Grecia."],["C","Troya y Micenas","Incorrecto. Aunque fueron ciudades importantes, no eran las polis mas representativas del periodo clasico."],["D","Babilonia y Nieve","Incorrecto. Estas ciudades son de Mesopotamia."]],"correct":"B","explanation":"Atenas destaco por su democracia y cultura, mientras Esparta era una sociedad militarizada. Fueron rivales en la Guerra del Peloponeso."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Que tipo de gobierno se desarrollo en Atenas durante el siglo V a.C.?","options":[["A","Monarquia absoluta","Incorrecto. Atenas no era una monarquia en el periodo clasico."],["B","Democracia directa","Correcto. En Atenas los ciudadanos participaban directamente en las decisiones politicas."],["C","Dictadura militar","Incorrecto. Atenas no era una dictadura militar."],["D","Teocracia","Incorrecto. El poder no estaba en manos de sacerdotes."]],"correct":"B","explanation":"Atenas desarrollo la democracia directa, donde los ciudadanos (varones libres atenienses) votaban directamente las leyes en la Asamblea (Ekklesia)."},
    {"bloom":"Apply","icfes":"Pensamiento Social","stem":"Un profesor en Bucaramanga explica que en Esparta los ninos desde los 7 anos comenzaban un entrenamiento militar. Esto se debia a que:","options":[["A","Esparta valoraba mas la educacion artistica","Incorrecto. Esparta no priorizaba las artes."],["B","La sociedad espartana estaba organizada para la guerra y el control de los ilotas","Correcto. Esparta era una sociedad militarizada que controlaba a una poblacion de siervos (ilotas)."],["C","Esparta era una democracia como Atenas","Incorrecto. Esparta era una oligarquia con dos reyes y un consejo."],["D","Los espartanos no tenian ejercito","Incorrecto. Sparta tenia el ejercito mas poderoso de Grecia."]],"correct":"B","explanation":"Esparta era una sociedad militar donde los hombres dedicaban su vida al ejercito para mantener el control sobre los ilotas (siervos) y defenderse de enemigos externos."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Quien fue Pericles y que hizo por Atenas?","options":[["A","Un rey espartano que conquisto Atenas","Incorrecto. Pericles fue un lider ateniense, no espartano."],["B","Un filosofo que fundo la Academia","Incorrecto. Platon fundo la Academia. Pericles fue un estadista."],["C","Un lider que fortalecio la democracia y embellecio Atenas con el Partenon","Correcto. Pericles promovio la democracia, las artes y construyo el Partenon."],["D","Un general persa que invadio Grecia","Incorrecto. Pericles era ateniense, no persa."]],"correct":"C","explanation":"Pericles, lider de Atenas en el siglo V a.C., fortalecio las instituciones democraticas, impulso las artes y ordeno la construccion del Partenon en la Acropolis."},
    {"bloom":"Analyze","icfes":"Pensamiento Social","stem":"Por que las polis griegas eran independientes y no formaban un solo pais?","options":[["A","Porque no querian tener un gobierno comun","Incorrecto. El analisis requiere entender causas geograficas e historicas."],["B","Porque la geografia montanosa de Grecia aislaba a las comunidades y cada una desarrollo su propia identidad","Correcto. Las montanas y el mar fragmentaron Grecia en comunidades independientes."],["C","Porque un imperio extranjero les impedia unificarse","Incorrecto. No habia un imperio que les impidiera unificarse."],["D","Porque todos los griegos tenian el mismo gobierno","Incorrecto. Cada polis tenia su propio gobierno."]],"correct":"B","explanation":"El relieve montanoso de Grecia y sus multiples islas dificultaron la comunicacion terrestre, favoreciendo el desarrollo de comunidades independientes con identidad propia."},
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"Que nombre recibian las guerras entre griegos y persas en el siglo V a.C.?","options":[["A","Guerras Punicas","Incorrecto. Las Guerras Punicas fueron entre Roma y Cartago."],["B","Guerras Medicas","Correcto. Las Guerras Medicas enfrentaron a las polis griegas contra el Imperio Persa."],["C","Guerra del Peloponeso","Incorrecto. Esa guerra fue entre Atenas y Esparta."],["D","Guerras de Alejandro","Incorrecto. Las conquistas de Alejandro fueron posteriores."]],"correct":"B","explanation":"Las Guerras Medicas (492-449 a.C.) enfrentaron a los griegos contra los persas. Incluyen batallas famosas como Maraton, Termopilas y Salamina."},
    {"bloom":"Apply","icfes":"Pensamiento Social","stem":"Un estudiante en Barranquilla esta viendo la pelicula '300' sobre la batalla de las Termopilas. Que hecho historico representa?","options":[["A","La conquista de Grecia por Roma","Incorrecto. No es romana."],["B","La resistencia de 300 espartanos y otros griegos contra el ejercito persa","Correcto. La pelicula narra la resistencia espartana liderada por Leonidas en el paso de las Termopilas."],["C","La guerra civil entre Atenas y Esparta","Incorrecto. No es la Guerra del Peloponeso."],["D","La fundacion de la ciudad de Esparta","Incorrecto. No trata sobre la fundacion de Esparta."]],"correct":"B","explanation":"La Batalla de las Termopilas (480 a.C.) fue parte de las Guerras Medicas. Un pequeno ejercito griego, incluyendo 300 espartanos, resistio heroicamente al enorme ejercito persa."},
    {"bloom":"Evaluate","icfes":"Pensamiento Social","stem":"Comparando la democracia ateniense con la democracia colombiana actual, que diferencia fundamental encontramos?","options":[["A","No hay diferencias, ambas son iguales","Incorrecto. Hay diferencias importantes."],["B","Atenas tenia democracia directa donde los ciudadanos votaban personalmente las leyes; Colombia tiene democracia representativa con eleccion de representantes","Correcto. En Atenas votaban directamente; hoy elegimos representantes."],["C","Colombia tiene un rey y Atenas tenia presidente","Incorrecto. Colombia no tiene rey y Atenas no tenia presidente."],["D","En Atenas votaban todos los habitantes, incluidos esclavos y mujeres","Incorrecto. En Atenas solo votaban los ciudadanos varones libres mayores de edad."]],"correct":"B","explanation":"La democracia ateniense era directa (los ciudadanos votaban leyes en asamblea), mientras la colombiana es representativa (elegimos congresistas y presidente que toman decisiones)."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Quien fue Alejandro Magno?","options":[["A","Un filosofo ateniense","Incorrecto. No fue filosofo."],["B","Un rey espartano","Incorrecto. Era macedonio, no espartano."],["C","El rey de Macedonia que conquisto un enorme imperio desde Grecia hasta la India","Correcto. Alejandro creo uno de los imperios mas grandes del mundo antiguo."],["D","Un emperador persa","Incorrecto. No era persa, era macedonio (griego del norte)."]],"correct":"C","explanation":"Alejandro Magno (356-323 a.C.), rey de Macedonia, conquisto el Imperio Persa y llego hasta la India, difundiendo la cultura griega (helenismo) por todo Oriente."},
]

# W14: Grecia antigua: cultura y arte
W[14]["qs"] = [
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"Quien fue Socrates y cual era su metodo de ensenanza?","options":[["A","Un arquitecto que diseno el Partenon","Incorrecto. Socrates no era arquitecto."],["B","Un filosofo que usaba preguntas (mayeutica) para hacer reflexionar a sus alumnos","Correcto. Socrates desarrollaba el pensamiento critico mediante preguntas."],["C","Un general ateniense que gano la Guerra del Peloponeso","Incorrecto. Era filosofo, no militar."],["D","Un poeta que escribio la Ilada","Incorrecto. Homero escribio la Ilada, no Socrates."]],"correct":"B","explanation":"Socrates (469-399 a.C.) desarrollo la mayeutica: mediante preguntas guiaba a sus interlocutores a descubrir la verdad por si mismos. Es considerado padre de la filosofia occidental."},
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"Que filósofo griego fundo la Academia y escribio 'La Republica'?","options":[["A","Aristoteles","Incorrecto. Aristoteles fundo el Liceo."],["B","Socrates","Incorrecto. Socrates no escribio libros, su ensenanza era oral."],["C","Platon","Correcto. Platon escribio 'La Republica' y fundo la Academia en Atenas."],["D","Herodoto","Incorrecto. Herodoto es considerado el padre de la Historia."]],"correct":"C","explanation":"Platon (427-347 a.C.), discipulo de Socrates, fundo la Academia, la primera institucion de educacion superior. Su obra 'La Republica' trata sobre la justicia y el Estado ideal."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Como se llamaba el templo mas importante de la Acropolis de Atenas, dedicado a la diosa Atenea?","options":[["A","El Coliseo","Incorrecto. El Coliseo es un anfiteatro romano."],["B","El Partenon","Correcto. El Partenon es el templo dedicado a Atenea Partenos en la Acropolis ateniense."],["C","El Templo de Artemisa","Incorrecto. Ese templo estaba en Efeso (Asia Menor)."],["D","El Templo de Karnak","Incorrecto. Karnak es un complejo de templos egipcios."]],"correct":"B","explanation":"El Partenon, construido en el siglo V a.C. bajo Pericles, es el simbolo de la Grecia clasica. Es el templo mas importante de la Acropolis de Atenas."},
    {"bloom":"Apply","icfes":"Pensamiento Social","stem":"Un grupo de estudiantes colombianos visita un museo de arte antiguo. Ven esculturas idealizadas del cuerpo humano con gran realismo y proporcion. Estas obras probablemente pertenecen a:","options":[["A","El arte egipcio","Incorrecto. El arte egipcio era mas rigido y simbolico."],["B","El arte griego","Correcto. Los griegos buscaban la proporcion, la belleza ideal y el realismo en sus esculturas."],["C","El arte mesopotamico","Incorrecto. El arte mesopotamico era mas narrativo y ceremonial."],["D","El arte fenicio","Incorrecto. El arte fenicio tenia influencia egipcia y mesopotamica."]],"correct":"B","explanation":"El arte griego clasico se caracteriza por buscar la perfeccion, la proporcion y el realismo idealizado del cuerpo humano. Es la base del arte occidental."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Que importante evento deportivo y cultural se celebraba cada cuatro anos en Olimpia (Grecia)?","options":[["A","Las Saturnales","Incorrecto. Las Saturnales eran festividades romanas."],["B","Los Juegos Olimpicos","Correcto. En Olimpia se realizaban los Juegos Olimpicos en honor a Zeus."],["C","Las Panateneas","Incorrecto. Las Panateneas eran en Atenas, no en Olimpia."],["D","Los Gladiadores","Incorrecto. Los combates de gladiadores eran romanos."]],"correct":"B","explanation":"Los Juegos Olimpicos comenzaron en 776 a.C. en Olimpia. Se celebraban cada cuatro anos en honor a Zeus e incluían competencias deportivas y artisticas."},
    {"bloom":"Analyze","icfes":"Pensamiento Social","stem":"Por que el teatro griego es considerado la base del teatro occidental?","options":[["A","Porque los griegos inventaron el cine","Incorrecto. El cine es un invento del siglo XIX."],["B","Porque desarrollaron la tragedia y la comedia como generos teatrales que aun se usan","Correcto. Los griegos crearon la tragedia (Esquilo, Sofocles, Euripides) y la comedia (Aristofanes)."],["C","Porque construyeron los primeros teatros en Colombia","Incorrecto. No hay teatro griego en Colombia."],["D","Porque el teatro moderno solo existe en Grecia","Incorrecto. El teatro existe mundialmente, pero sus origenes occidentales son griegos."]],"correct":"B","explanation":"Los griegos inventaron el teatro como genero literario y espectaculo publico. Sus obras de tragedia y comedia establecieron las bases del teatro occidental."},
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"Que ordenes arquitectonicos griegos existen?","options":[["A","Romanico, Gotico y Barroco","Incorrecto. Esos son estilos arquitectonicos medievales y modernos."],["B","Dorico, Jonico y Corintio","Correcto. Los tres ordenes clasicos griegos se distinguen por el diseno de las columnas."],["C","Egipto, Mesopotamia y Fenicio","Incorrecto. Esos son nombres de civilizaciones, no de ordenes arquitectonicos."],["D","Colonial, Republicano y Moderno","Incorrecto. Esos son estilos latinoamericanos."]],"correct":"B","explanation":"Los ordenes dorico (austero), jonico (elegante) y corintio (ornamentado) definen los estilos de las columnas griegas y fueron adoptados por los romanos."},
    {"bloom":"Apply","icfes":"Pensamiento Social","stem":"En Medellin hay un edificio que tiene columnas con capiteles decorados con hojas de acanto. Este estilo arquitectonico se llama:","options":[["A","Dorico","Incorrecto. El dorico tiene capiteles simples y sin decoracion."],["B","Jonico","Incorrecto. El jonico tiene volutas (espirales), no hojas de acanto."],["C","Corintio","Correcto. El capitel corintio se caracteriza por hojas de acanto talladas."],["D","Romanico","Incorrecto. El romanico es un estilo medieval, no griego."]],"correct":"C","explanation":"El orden corintio es el mas ornamentado de los ordenes griegos. Su capitel se decora con hojas de acanto y es frecuente en edificios neoclasicos."},
    {"bloom":"Evaluate","icfes":"Pensamiento Social","stem":"Por que decimos que la cultura griega es la base de la cultura occidental?","options":[["A","Porque Grecia fue el pais mas poderoso militarmente","Incorrecto. El legado griego es cultural, no militar."],["B","Porque los griegos nos dejaron la democracia, la filosofia, el teatro, el arte clasico y los Juegos Olimpicos","Correcto. Las instituciones y formas culturales griegas son fundamentales en Occidente."],["C","Porque todos los paises occidentales hablan griego","Incorrecto. Los idiomas occidentales no son griego."],["D","Porque Grecia conquisto todo el mundo","Incorrecto. Alejandro conquisto vastos territorios, pero Grecia clasica no domino el mundo."]],"correct":"B","explanation":"La filosofia (Socrates, Platon, Aristoteles), la democracia, el teatro, el arte clasico, las Olimpiadas y la ciencia griega son pilares de la cultura occidental."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Que obra epica atribuida a Homero narra la guerra de Troya?","options":[["A","La Odisea","Incorrecto. La Odisea narra el regreso de Odiseo a Itaca."],["B","La Ilada","Correcto. La Ilada narra los ultimos meses de la guerra de Troya y la ira de Aquiles."],["C","La Eneida","Incorrecto. La Eneida es una obra epica romana de Virgilio."],["D","Las Traquinias","Incorrecto. Es una tragedia de Sofocles."]],"correct":"B","explanation":"La Ilada, atribuida a Homero, es el poema epico mas antiguo de la literatura occidental. Narra la guerra de Troya y la historia de heroes como Aquiles y Hector."},
]

# W15: Roma antigua: Republica
W[15]["qs"] = [
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"En que ciudad se fundo la civilizacion romana?","options":[["A","Atenas","Incorrecto. Atenas es una ciudad griega."],["B","Roma","Correcto. Roma fue fundada como una pequena aldea en la peninsula italica en el siglo VIII a.C."],["C","Cartago","Incorrecto. Cartago era una colonia fenicia en Africa del Norte."],["D","Constantinopla","Incorrecto. Constantinopla fue fundada deapues como capital del Imperio Romano de Oriente."]],"correct":"B","explanation":"Roma fue fundada en la peninsula italica, cerca del rio Tiber. Segun la leyenda, fue fundada por Romulo y Remo en 753 a.C."},
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"Como se llamaba la asamblea de nobles que gobernaba la Republica Romana?","options":[["A","La Asamblea del Pueblo","Incorrecto. La asamblea popular era diferente."],["B","El Senado","Correcto. El Senado era la institucion mas poderosa de la Republica Romana, compuesto por patricios."],["C","El Areopago","Incorrecto. El Areopago era un consejo ateniense."],["D","El Sinedrio","Incorrecto. El Sinedrio era el consejo judio."]],"correct":"B","explanation":"El Senado romano era un consejo de ancianos (patricios) que asesoraba a los magistrados y controlaba la politica exterior y las finanzas."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Que eran los tribunos de la plebe en la Republica Romana?","options":[["A","Esclavos que trabajaban en el Senado","Incorrecto. Los tribunos eran representantes de los plebeyos, no esclavos."],["B","Funcionarios que protegian a los plebeyos del abuso de los patricios y podian vetar leyes","Correcto. Los tribunos defendian los derechos de la plebe."],["C","Generales del ejercito romano","Incorrecto. Los tribunos tenian funcion politica, no militar."],["D","Sacerdotes del templo de Jupiter","Incorrecto. No eran sacerdotes."]],"correct":"B","explanation":"Los tribunos eran representantes elegidos por la plebe para proteger sus derechos. Podian vetar (bloquear) leyes que consideraran injustas para los plebeyos."},
    {"bloom":"Apply","icfes":"Pensamiento Social","stem":"Un estudiante en Bogota lee que en Roma habia conflicto entre patricios y plebeyos. Los patricios eran:","options":[["A","Los esclavos que trabajaban en el campo","Incorrecto. Los patricios no eran esclavos."],["B","La clase alta, descendientes de los fundadores de Roma, con privilegios politicos","Correcto. Los patricios eran la aristocracia romana que controlaba el Senado."],["C","Los comerciantes extranjeros","Incorrecto. Los comerciantes no eran necesariamente patricios."],["D","Los soldados del ejercito","Incorrecto. Los soldados provenían de ambas clases sociales."]],"correct":"B","explanation":"Los patricios eran la clase noble romana, descendientes de los primeros senadores. Controlaban el poder politico y religioso durante la Republica."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Que eran las Guerras Punicas?","options":[["A","Guerras entre Grecia y Persia","Incorrecto. Esas son las Guerras Medicas."],["B","Guerras entre Roma y Cartago por el control del Mediterraneo","Correcto. Las Guerras Punicas (264-146 a.C.) enfrentaron a Roma y Cartago."],["C","Guerras civiles en Roma entre patricios y plebeyos","Incorrecto. Esas eran luchas internas, no las Punicas."],["D","Guerras entre Atenas y Esparta","Incorrecto. Esa es la Guerra del Peloponeso."]],"correct":"B","explanation":"Las Guerras Punicas enfrentaron a Roma contra Cartago por el dominio del Mediterraneo. Roma vencio, destruyo Cartago y se convirtio en la potencia hegemonica."},
    {"bloom":"Analyze","icfes":"Pensamiento Social","stem":"Por que el Derecho Romano es un legado importante para la humanidad?","options":[["A","Porque establecio la esclavitud como ley universal","Incorrecto. No fue su legado principal."],["B","Porque creo principios juridicos como la presuncion de inocencia y el derecho a la defensa que aun usamos","Correcto. El Derecho Romano es la base de muchos sistemas legales actuales."],["C","Porque permitia que cualquiera fuera rey","Incorrecto. No establecia eso."],["D","Porque prohibia todos los delitos","Incorrecto. Establecia leyes pero no prohibia todos los delitos."]],"correct":"B","explanation":"El Derecho Romano establecio principios fundamentales como 'inocente hasta que se demuestre lo contrario', el derecho a la defensa y la igualdad ante la ley."},
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"Quien fue el cartagines que casi derrota a Roma durante las Guerras Punicas?","options":[["A","Julio Cesar","Incorrecto. Cesar era romano, no cartagines."],["B","Anibal","Correcto. Anibal cruzo los Alpes con elefantes para atacar Roma desde el norte."],["C","Alejandro Magno","Incorrecto. Alejandro era macedonio, no cartagines."],["D","Ciro el Grande","Incorrecto. Ciro era persa."]],"correct":"B","explanation":"Anibal Barca, general cartagines, cruzo los Alpes con elefantes de guerra e infligio duras derrotas a Roma, pero finalmente fue vencido por Escipion."},
    {"bloom":"Apply","icfes":"Pensamiento Social","stem":"En clase de sociales en Cali, la profesora habla de la 'via romana'. Que importancia tenian las calzadas romanas?","options":[["A","Eran caminos religiosos para procesiones","Incorrecto. Tenian funcion practica, no solo religiosa."],["B","Conectaban todo el imperio, facilitando el comercio, la comunicacion y el movimiento de tropas","Correcto. Las vias romanas eran la columna vertebral del imperio."],["C","Eran murallas para defender las ciudades","Incorrecto. Las murallas eran construcciones defensivas diferentes."],["D","Eran canales de navegacion","Incorrecto. Eran caminos terrestres, no canales."]],"correct":"B","explanation":"Las calzadas romanas conectaban todas las provincias del imperio, permitiendo un rapido desplazamiento de tropas, comerciantes e informacion. 'Todos los caminos llevan a Roma'."},
    {"bloom":"Evaluate","icfes":"Pensamiento Social","stem":"Comparando la Republica Romana con la democracia colombiana, que similitud encontramos en la organizacion del poder?","options":[["A","Ambos sistemas tienen un rey que gobierna de por vida","Incorrecto. Ninguno tiene rey."],["B","Ambos tienen un senado y magistrados elegidos, aunque en Roma el poder era mas limitado a la aristocracia","Correcto. Ambas tienen senado y cargos electos, pero Roma era mas exclusiva."],["C","Colombia copio exactamente el sistema romano","Incorrecto. Hay diferencias significativas."],["D","Roma no tenia instituciones politicas","Incorrecto. Roma tenia un sistema politico sofisticado."]],"correct":"B","explanation":"Tanto la Republica Romana como Colombia tienen senado, cargos electos y separacion de funciones. Sin embargo, en Roma solo los patricios tenian poder real inicialmente."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Que significaba la frase 'Senatus Populusque Romanus' (SPQR)?","options":[["A","Solo los patricios pueden gobernar","Incorrecto. No es el significado exacto."],["B","El Senado y el Pueblo de Roma","Correcto. SPQR era el emblema de la Republica Romana, representando la autoridad del Senado y el pueblo."],["C","Roma vencera siempre","Incorrecto. No es el significado literal."],["D","Poder absoluto del emperador","Incorrecto. SPQR es de la Republica, no del Imperio."]],"correct":"B","explanation":"SPQR (Senatus Populusque Romanus) simbolizaba que el poder en Roma residia en el Senado y el pueblo (ciudadanos), no en un gobernante unico."},
]

# W16: Roma antigua: Imperio
W[16]["qs"] = [
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"Quien fue el primer emperador de Roma?","options":[["A","Julio Cesar","Incorrecto. Cesar fue un dictador, pero no llego a ser emperador formalmente."],["B","Augusto (Octavio)","Correcto. Augusto fue el primer emperador romano, iniciando el Imperio en 27 a.C."],["C","Neron","Incorrecto. Neron fue un emperador posterior."],["D","Constantino","Incorrecto. Constantino fue emperador mucho despues."]],"correct":"B","explanation":"Octavio Augusto, sobrino nieto de Julio Cesar, derroto a Marco Antonio y Cleopatra, y en 27 a.C. el Senado le otorgo el titulo de Augusto, iniciando el Imperio."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Que fue la 'Pax Romana'?","options":[["A","Un periodo de guerras civiles en Roma","Incorrecto. 'Pax' significa paz, no guerra."],["B","Un largo periodo de paz y estabilidad en el Imperio Romano","Correcto. La Pax Romana duro aproximadamente 200 anos (27 a.C.-180 d.C.)."],["C","La guerra entre Roma y Cartago","Incorrecto. Esas fueron las Guerras Punicas, anteriores."],["D","La invasion de los barbaros","Incorrecto. Las invasiones barbaras ocurrieron despues de la Pax Romana."]],"correct":"B","explanation":"La Pax Romana fue un periodo de paz, estabilidad y prosperidad que permitio el desarrollo del comercio, las artes y la construccion de infraestructura en todo el imperio."},
    {"bloom":"Apply","icfes":"Pensamiento Social","stem":"Un turista colombiano visita el Coliseo Romano en Italia. Que actividad se realizaba alli?","options":[["A","Ceremonias religiosas y oraciones","Incorrecto. El Coliseo no era un templo."],["B","Espectaculos publicos como combates de gladiadores y peleas de animales","Correcto. El Coliseo era un anfiteatro para espectaculos masivos."],["C","Reuniones del Senado","Incorrecto. El Senado se reunia en la Curia."],["D","Carreras de carros","Incorrecto. Las carreras de carros se realizaban en el Circo Maximo."]],"correct":"B","explanation":"El Coliseo, construido en el siglo I d.C., es el anfiteatro mas famoso de Roma. Alli se realizaban combates de gladiadores, cacerias de animales y ejecuciones publicas."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Como logro el cristianismo difundirse en el Imperio Romano?","options":[["A","Fue la religion oficial desde el principio del Imperio","Incorrecto. Al principio los cristianos eran perseguidos."],["B","Se difundio a traves de los apostoles por las rutas y calzadas romanas, aprovechando la paz y las comunicaciones del imperio","Correcto. La infraestructura romana facilito la difusion del cristianismo."],["C","Fue impuesto por la fuerza por Constantino","Incorrecto. Constantino lo legalizo, no lo impuso."],["D","Nunca se difundio fuera de Jerusalen","Incorrecto. El cristianismo se difundio por todo el imperio."]],"correct":"B","explanation":"El cristianismo aprovecho la red de calzadas romanas, la paz interna y la unidad linguistica (griego y latin) del imperio para difundir su mensaje."},
    {"bloom":"Analyze","icfes":"Pensamiento Social","stem":"Por que el emperador Constantino es importante en la historia del cristianismo?","options":[["A","Fue el primer cristiano crucificado","Incorrecto. No fue crucificado."],["B","Legalizo el cristianismo en el Imperio Romano con el Edicto de Milan (313 d.C.)","Correcto. Constantino permitio a los cristianos practicar su religion libremente."],["C","Construyo las piramides de Egipto","Incorrecto. Las piramides ya existian."],["D","Prohibio el cristianismo en todo el imperio","Incorrecto. Todo lo contrario: lo legalizo."]],"correct":"B","explanation":"El Edicto de Milan (313 d.C.) emitido por Constantino concedio libertad religiosa a los cristianos, terminando con siglos de persecucion."},
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"En que dos partes se dividio el Imperio Romano?","options":[["A","Imperio del Norte y del Sur","Incorrecto. No se dividio en Norte y Sur."],["B","Imperio Romano de Occidente (capital: Roma) y de Oriente (capital: Constantinopla)","Correcto. La division ocurrio en 395 d.C. bajo Teodosio."],["C","Imperio Griego y Romano","Incorrecto. No fue una division etnica."],["D","Imperio Africano y Europeo","Incorrecto. Esa no fue la division."]],"correct":"B","explanation":"El Imperio Romano se dividio en Occidental (Roma) y Oriental (Constantinopla). El de Occidente cayo en 476 d.C., mientras el de Oriente (Bizantino) sobrevivio hasta 1453."},
    {"bloom":"Evaluate","icfes":"Pensamiento Social","stem":"Que llevo a la caida del Imperio Romano de Occidente?","options":[["A","Una unica invasion barbara masiva","Incorrecto. Fue un proceso gradual, no un solo evento."],["B","Una combinacion de crisis interna, corrupcion, crisis economica y presion de pueblos barbaros","Correcto. La caida fue causada por multiples factores que actuaron durante siglos."],["C","El emperador decidio disolver el imperio","Incorrecto. No fue una decision voluntaria."],["D","Fue destruido por un terremoto","Incorrecto. No hay evidencia de un terremoto como causa."]],"correct":"B","explanation":"La caida de Roma (476 d.C.) fue resultado de crisis economicas, corrupcion politica, divisiones internas y las invasiones de pueblos germanicos (visigodos, ostrogodos, vándalos)."},
    {"bloom":"Apply","icfes":"Pensamiento Social","stem":"Un estudiante en Cucuta lee que el latín es la base del idioma espanol. Esto se debe a:","options":[["A","Los griegos trajeron el idioma a America","Incorrecto. No fueron los griegos."],["B","Roma conquisto la peninsula iberica (Hispania) y difundio el latin, que evoluciono al espanol","Correcto. Los romanos llevaron el latin a Hispania, que con el tiempo se convirtio en el espanol."],["C","Los fenicios trajeron el alfabeto a Espana","Incorrecto. Aunque los fenicios trajeron su alfabeto, el espanol viene del latin."],["D","El espanol no tiene relacion con el latin","Incorrecto. El espanol es una lengua romance derivada del latin."]],"correct":"B","explanation":"El latin, idioma de los romanos, se difundio por todo el imperio. En Hispania (Espana), el latin vulgar evoluciono hasta convertirse en el espanol actual."},
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"Que emperador romano es conocido por construir un muro en Britania (actual Inglaterra)?","options":[["A","Neron","Incorrecto. Neron no construyo muros en Britania."],["B","Adriano","Correcto. El Muro de Adriano protegia la frontera norte del Imperio en Britania."],["C","Caligula","Incorrecto. No se le atribuye esa construccion."],["D","Trajano","Incorrecto. Trajano fue un emperador conquistador, pero no construyo el muro."]],"correct":"B","explanation":"El Muro de Adriano, construido en el siglo II d.C., marcaba la frontera norte del Imperio en Britania y protegia de las tribus pictas (escocesas)."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Cual fue el legado mas importante del Imperio Romano?","options":[["A","La democracia directa","Incorrecto. La democracia directa es griega."],["B","El derecho, el idioma latin, el cristianismo, la arquitectura y la ingenieria","Correcto. El legado romano es enorme y aun perdura en nuestra cultura."],["C","El alfabeto","Incorrecto. El alfabeto es fenicio."],["D","La polis","Incorrecto. La polis es griega."]],"correct":"B","explanation":"Roma nos dejo el Derecho (base de los codigos legales actuales), el latin (idioma madre del espanol, frances, italiano), el cristianismo difundido, el arco, el acueducto y el hormigon."},
]

# W17: Repaso P3
W[17]["qs"] = [
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"Que son las polis griegas?","options":[["A","Los templos donde se adoraba a los dioses","Incorrecto. Los templos se llamaban templos, no polis."],["B","Ciudades-estado independientes con su propio gobierno y leyes","Correcto. Las polis eran la unidad politica basica de la antigua Grecia."],["C","Las provincias del Imperio Romano","Incorrecto. Las provincias son romanas."],["D","Los ejercitos espartanos","Incorrecto. Polis no significa ejercito."]],"correct":"B","explanation":"Las polis eran ciudades-estado independientes como Atenas, Esparta, Corinto y Tebas. Cada una tenia su propio gobierno, ejercito y leyes."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Que diferencia politica fundamental habia entre Atenas y Esparta?","options":[["A","No habia diferencias, ambas eran iguales","Incorrecto. Eran muy diferentes."],["B","Atenas desarrollo la democracia; Esparta era una oligarquia militar","Correcto. Atenas fue democratica y Esparta militarista y autoritaria."],["C","Esparta tenia democracia y Atenas era una monarquia","Incorrecto. Era al reves: Atenas democratica, Esparta no."],["D","Ambas eran imperios que conquistaron el mundo","Incorrecto. Ninguna fue un imperio mundial."]],"correct":"B","explanation":"Atenas se destaco por su democracia directa y su cultura. Esparta era una sociedad militarizada con dos reyes, un consejo de ancianos y una asamblea limitada."},
    {"bloom":"Apply","icfes":"Pensamiento Social","stem":"Un estudiante en Barranquilla aprende sobre los filosofos griegos. Si lee sobre un filosofo que usaba preguntas para hacer pensar a sus alumnos, esta aprendiendo sobre:","options":[["A","Aristoteles que fundo el Liceo","Incorrecto. Aristoteles fundo el Liceo pero su metodo era mas sistematico."],["B","Socrates y su metodo mayeutico","Correcto. Socrates usaba preguntas para guiar a sus alumnos a descubrir la verdad."],["C","Platon que escribio 'La Republica'","Incorrecto. Platon escribio obras, no usaba solo dialogo oral como Socrates."],["D","Homero, el poeta epico","Incorrecto. Homero era poeta, no filosofo."]],"correct":"B","explanation":"Socrates (469-399 a.C.) desarrollo la mayeutica: mediante preguntas sucesivas guiaba al interlocutor a descubrir sus propias contradicciones y llegar a la verdad."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Como se organizaba la Republica Romana?","options":[["A","Con un rey que tomaba todas las decisiones","Incorrecto. La Republica no tenia rey."],["B","Con un Senado, magistrados (consules, tribunos) y asambleas populares","Correcto. La Republica tenia separacion de funciones y cargos electos."],["C","Con un emperador que gobernaba de por vida","Incorrecto. El Imperio empezo despues de la Republica."],["D","Con un sistema feudal de senores y siervos","Incorrecto. El feudalismo es medieval, no romano."]],"correct":"B","explanation":"La Republica Romana tenia un sistema complejo: el Senado (consejo de patricios), magistrados anuales (consules, tribunos, pretores) y asambleas populares."},
    {"bloom":"Analyze","icfes":"Pensamiento Social","stem":"Por que el arte y la filosofia griega influyeron tanto en la cultura romana?","options":[["A","Porque Roma conquisto Grecia y adopto muchos elementos de su cultura","Correcto. Roma conquisto Grecia en el siglo II a.C. y quedo fascinada por su cultura."],["B","Porque Grecia conquisto Roma y le impuso su cultura","Incorrecto. Fue Roma la que conquisto Grecia."],["C","Porque griegos y romanos eran el mismo pueblo","Incorrecto. Eran pueblos diferentes con idiomas distintos."],["D","Porque nunca hubo contacto entre griegos y romanos","Incorrecto. Hubo intenso contacto."]],"correct":"A","explanation":"Roma conquisto Grecia militarmente, pero quedo cautivada por su cultura. Los romanos adoptaron la filosofia, el arte, la literatura y la religion griegas."},
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"Cual de los siguientes NO es un legado de la cultura clasica (Grecia y Roma)?","options":[["A","La democracia","Incorrecto. La democracia SI es un legado griego."],["B","El Derecho","Incorrecto. El Derecho SI es legado romano."],["C","La escritura cuneiforme","Correcto. La escritura cuneiforme es de Mesopotamia, no de Grecia o Roma."],["D","El idioma latin","Incorrecto. El latin SI es legado romano."]],"correct":"C","explanation":"La escritura cuneiforme pertenece a la civilizacion mesopotamica, no a la cultura clasica grecorromana. La democracia, el derecho y el latin son legados clasicos."},
    {"bloom":"Evaluate","icfes":"Pensamiento Social","stem":"Comparando la expansion territorial de Alejandro Magno con la del Imperio Romano, que similitud encuentran?","options":[["A","Ambos conquistaron America","Incorrecto. Ninguno conquisto America."],["B","Ambos difundieron su cultura (helenismo y romanizacion) por los territorios conquistados","Correcto. Alejandro difundio la cultura griega; Roma, la romana."],["C","Ambos imperios duraron exactamente lo mismo","Incorrecto. El de Alejandro duro poco; el Romano duro siglos."],["D","Ambos imperios eran democracias","Incorrecto. Ninguno era democratico en sentido moderno."]],"correct":"B","explanation":"Tanto Alejandro Magno (helenismo) como el Imperio Romano (romanizacion) difundieron su cultura, idioma y costumbres por los territorios que conquistaron."},
    {"bloom":"Apply","icfes":"Pensamiento Social","stem":"En un examen de sociales en Pereira preguntan: que institucion romana se asemeja mas a nuestro actual Congreso de la Republica?","options":[["A","El Senado romano","Correcto. El Senado romano era un cuerpo legislativo similar a nuestro Congreso."],["B","El Coliseo","Incorrecto. El Coliseo era un lugar de espectaculos."],["C","Las calzadas romanas","Incorrecto. Eran caminos."],["D","El ejercito romano","Incorrecto. Es una institucion militar."]],"correct":"A","explanation":"El Senado romano era una asamblea de ciudadanos que deliberaba sobre leyes, politica exterior y finanzas, funcion similar a la del Congreso colombiano actual."},
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"En que ano cayo el Imperio Romano de Occidente?","options":[["A","1492","Incorrecto. 1492 es el descubrimiento de America."],["B","476 d.C.","Correcto. En 476 d.C. el ultimo emperador romano de Occidente, Romulo Augustulo, fue depuesto."],["C","753 a.C.","Incorrecto. 753 a.C. es la fecha legendaria de la fundacion de Roma."],["D","27 a.C.","Incorrecto. 27 a.C. es el inicio del Imperio Romano."]],"correct":"B","explanation":"En 476 d.C., el jefe germano Odoacro depuso al ultimo emperador de Occidente. Esta fecha marca tradicionalmente el fin de la Edad Antigua y el inicio de la Edad Media."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Cual fue la principal causa de la caida del Imperio Romano de Occidente?","options":[["A","Un catastrofico terremoto","Incorrecto. No fue un desastre natural."],["B","Fue derrotado en una guerra contra Grecia","Incorrecto. Grecia ya era parte del imperio desde siglos antes."],["C","Una combinacion de crisis interna, division del imperio, problemas economicos e invasiones barbaras","Correcto. Fue un proceso multicausal que duro siglos."],["D","El emperador decidio disolver el imperio pacificamente","Incorrecto. Fue un colapso violento y caotico."]],"correct":"C","explanation":"La caida de Roma fue el resultado de la combinacion de: crisis economica, corrupcion politica, division del imperio, presion militar de los pueblos germanicos y disminucion de la poblacion."},
]

# W18: Edad Media: Caida del Imperio Romano
W[18]["qs"] = [
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"Que hecho marca tradicionalmente el inicio de la Edad Media?","options":[["A","El descubrimiento de America (1492)","Incorrecto. Ese hecho marca el inicio de la Edad Moderna."],["B","La caida del Imperio Romano de Occidente (476 d.C.)","Correcto. La caida de Roma en 476 da inicio a la Edad Media."],["C","La Revolucion Francesa (1789)","Incorrecto. Ese hecho marca el inicio de la Edad Contemporanea."],["D","El nacimiento de Cristo","Incorrecto. El nacimiento de Cristo es el inicio de la era cristiana, no de la Edad Media."]],"correct":"B","explanation":"La Edad Media comienza con la caida del Imperio Romano de Occidente (476 d.C.) y termina con la caida de Constantinopla (1453) o el descubrimiento de America (1492)."},
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"Quienes invadieron el Imperio Romano de Occidente y contribuyeron a su caida?","options":[["A","Los chinos","Incorrecto. China no invadio el Imperio Romano."],["B","Los vikingos","Incorrecto. Los vikingos atacaron Europa despues, en los siglos VIII-XI."],["C","Los pueblos germanicos (godos, vándalos, francos, etc.)","Correcto. Los pueblos germanicos invadieron y se establecieron en el territorio del imperio."],["D","Los mayas","Incorrecto. Los mayas estaban en America, sin contacto con Roma."]],"correct":"C","explanation":"Los pueblos germanicos (visigodos, ostrogodos, vándalos, francos, anglos, sajones) invadieron el Imperio de Occidente, estableciendo sus propios reinos."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Que fue el Imperio Bizantino?","options":[["A","Un imperio fundado por los germanos","Incorrecto. Los germanos fundaron reinos, no el Imperio Bizantino."],["B","La continuacion del Imperio Romano en Oriente, con capital en Constantinopla","Correcto. El Imperio Bizantino sobrevivio hasta 1453."],["C","Un imperio africano en Egipto","Incorrecto. Bizancio era el Imperio Romano de Oriente."],["D","El nombre del imperio de Carlomagno","Incorrecto. Carlomagno fundo el Imperio Carolingio, no Bizancio."]],"correct":"B","explanation":"El Imperio Bizantino o Romano de Oriente sobrevivio a la caida de Occidente. Su capital era Constantinopla y preservo la cultura griega y romana por mil anos mas."},
    {"bloom":"Apply","icfes":"Pensamiento Social","stem":"Un estudiante en Bogota lee que el emperador Justiniano reconquisto territorios del antiguo Imperio Romano. Justiniano gobernaba:","options":[["A","El Imperio Carolingio","Incorrecto. Justiniano fue emperador bizantino, no carolingio."],["B","El Imperio Romano de Occidente","Incorrecto. Occidente ya habia caido. Justiniano gobernaba desde Constantinopla."],["C","El Imperio Bizantino","Correcto. Justiniano (527-565) fue el emperador bizantino mas importante."],["D","El Imperio Romano de Alejandro Magno","Incorrecto. Alejandro Magno era macedonio, no bizantino."]],"correct":"C","explanation":"Justiniano fue emperador del Imperio Bizantino. Reconquisto Italia, Africa del Norte y parte de Espana, y creo el Codigo de Justiniano (base del derecho)."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Que religion surgio en Arabia en el siglo VII y se expandio rapidamente?","options":[["A","El cristianismo","Incorrecto. El cristianismo surgio antes, en el siglo I."],["B","El budismo","Incorrecto. El budismo surgio en la India en el siglo VI a.C."],["C","El islam","Correcto. El islam, fundado por Mahoma en el siglo VII, se expandio desde Arabia hasta Asia y Africa."],["D","El judaismo","Incorrecto. El judaismo es anterior, del segundo milenio a.C."]],"correct":"C","explanation":"El islam surgio en la peninsula arabiga en el siglo VII. En pocos siglos, el imperio islamico se extendio desde Espana hasta la India."},
    {"bloom":"Analyze","icfes":"Pensamiento Social","stem":"Por que se dice que la Iglesia catolica fue una institucion unificadora durante la Edad Media?","options":[["A","Porque construyo las piramides","Incorrecto. Las piramides no son medievales."],["B","Porque mantuvo cierta unidad cultural y religiosa en Europa despues de la caida de Roma","Correcto. La Iglesia fue el principal elemento de continuidad cultural."],["C","Porque creo un ejercito mundial","Incorrecto. La Iglesia no tenia ejercito propio."],["D","Porque unio a todos los reinos en un solo pais","Incorrecto. Europa siguio fragmentada politicamente."]],"correct":"B","explanation":"Tras la caida de Roma, la Iglesia catolica mantuvo la unidad religiosa, preservo el conocimiento (en monasterios) y ejercio una enorme influencia politica y cultural."},
    {"bloom":"Remember","icfes":"Pensamiento Social","stem":"Quien fue Carlomagno?","options":[["A","Un emperador bizantino","Incorrecto. Carlomagno era franco, no bizantino."],["B","El rey de los francos que fue coronado emperador en el ano 800 y unifico gran parte de Europa occidental","Correcto. Carlomagno creo el Imperio Carolingio."],["C","Un profeta del islam","Incorrecto. Carlomagno era cristiano, no musulman."],["D","Un filosofo griego","Incorrecto. No era filosofo ni griego."]],"correct":"B","explanation":"Carlomagno, rey de los francos, fue coronado emperador por el Papa en el ano 800. Su imperio abarco Francia, Alemania e Italia del norte."},
    {"bloom":"Apply","icfes":"Pensamiento Social","stem":"En clase de sociales en Cali, la profesora explica que tras la caida de Roma, Europa se fragmento en reinos germanicos. Que cambio politico importante ocurrio?","options":[["A","Se creo la democracia en toda Europa","Incorrecto. La democracia no existia en la Edad Media."],["B","Desaparecio el Imperio de Occidente y surgieron reinos independientes gobernados por jefes germanos","Correcto. El poder paso del imperio unificado a multiples reinos."],["C","Todos los reinos se unificaron bajo un solo emperador","Incorrecto. Hubo fragmentacion, no unidad."],["D","Se crearon las primeras republicas","Incorrecto. Las republicas surgieron despues."]],"correct":"B","explanation":"Con la caida de Roma, el Imperio de Occidente desaparecio. En su lugar surgieron reinos germanicos independientes: francos en Francia, visigodos en Espana, ostrogodos en Italia."},
    {"bloom":"Evaluate","icfes":"Pensamiento Social","stem":"Comparando la caida del Imperio Romano con la crisis actual de algun pais, que leccion podemos aprender?","options":[["A","Que los imperios nunca caen","Incorrecto. Todos los imperios caen eventualmente."],["B","Que la combinacion de problemas economicos, corrupcion y presion externa puede derrumbar incluso al poder mas establecido","Correcto. La leccion es que la estabilidad requiere atender problemas internos y externos."],["C","Que solo las invasiones externas causan la caida","Incorrecto. Hubo multiples causas internas."],["D","Que la historia no nos ensena nada","Incorrecto. La historia nos da lecciones valiosas."]],"correct":"B","explanation":"La caida de Roma ensena que los imperios mas poderosos pueden colapsar cuando se combinan crisis economicas, corrupcion politica y amenazas externas no controladas."},
    {"bloom":"Understand","icfes":"Pensamiento Social","stem":"Cual de las siguientes NO es una caracteristica del inicio de la Edad Media en Europa?","options":[["A","Fragmentacion politica en reinos germanicos","Incorrecto. SI es caracteristico."],["B","Declive del comercio y la vida urbana","Incorrecto. SI hubo declive urbano y comercial."],["C","Fortalecimiento de la democracia y el comercio global","Correcto. La democracia desaparicion y el comercio se redujo drasticamente."],["D","Influencia creciente de la Iglesia catolica","Incorrecto. SI hubo crecimiento de la influencia eclesiastica."]],"correct":"C","explanation":"Al inicio de la Edad Media, la democracia desaparicion y el comercio se redujo mucho. La vida se ruralizo y la gente dependia de la agricultura de subsistencia."},
]

print("DONE W18")
