#!/usr/bin/env python3
"""
Generate all SOC G6 weekly bundles W08-W40 (33 bundles, 330 questions).
Uses algorithmic question generation from topic templates stored in lists.
"""
import os, json, random, textwrap, re

OUT = r"E:\scripts-python\worldexams\questions_data\colombia\sociales-ciudadanas\grado-6\2026\weekly"
PROTO = "5.2"
YEAR = 2026

# ---- TOPIC DEFINITIONS ----
TOPICS = {
    8: {"slug":"primeras-civilizaciones-mesopotamia","title":"Primeras Civilizaciones: Mesopotamia"},
    9: {"slug":"primeras-civilizaciones-egipto","title":"Primeras Civilizaciones: Egipto"},
    10: {"slug":"primeras-civilizaciones-india-china","title":"Primeras Civilizaciones: India y China"},
    11: {"slug":"primeras-civilizaciones-fenicios-hebreos-persas","title":"Primeras Civilizaciones: Fenicios, Hebreos y Persas"},
    12: {"slug":"repaso-p2","title":"Repaso P2: Civilizaciones Antiguas"},
    13: {"slug":"grecia-antigua-organizacion-politica","title":"Grecia Antigua: Organización Política"},
    14: {"slug":"grecia-antigua-cultura-arte","title":"Grecia Antigua: Cultura y Arte"},
    15: {"slug":"roma-antigua-republica","title":"Roma Antigua: La República"},
    16: {"slug":"roma-antigua-imperio","title":"Roma Antigua: El Imperio"},
    17: {"slug":"repaso-p3","title":"Repaso P3: Grecia y Roma"},
    18: {"slug":"edad-media-caida-imperio-romano","title":"Edad Media: Caída del Imperio Romano"},
    19: {"slug":"edad-media-feudalismo","title":"Edad Media: El Feudalismo"},
    20: {"slug":"edad-media-iglesia-cultura","title":"Edad Media: Iglesia y Cultura"},
    21: {"slug":"edad-media-comercio-ciudades","title":"Edad Media: Comercio y Ciudades"},
    22: {"slug":"repaso-p4","title":"Repaso P4: Edad Media"},
    23: {"slug":"edad-moderna-renacimiento","title":"Edad Moderna: Renacimiento"},
    24: {"slug":"edad-moderna-descubrimiento-america","title":"Edad Moderna: Descubrimiento de América"},
    25: {"slug":"edad-moderna-conquista-america","title":"Edad Moderna: Conquista de América"},
    26: {"slug":"edad-moderna-reforma-contrarreforma","title":"Edad Moderna: Reforma y Contrarreforma"},
    27: {"slug":"repaso-p5","title":"Repaso P5: Edad Moderna"},
    28: {"slug":"la-tierra-sistema-solar","title":"La Tierra en el Sistema Solar"},
    29: {"slug":"mapas-tipos-elementos","title":"Mapas: Tipos y Elementos"},
    30: {"slug":"coordenadas-geograficas","title":"Coordenadas Geográficas"},
    31: {"slug":"husos-horarios","title":"Husos Horarios"},
    32: {"slug":"repaso-p6","title":"Repaso P6: Geografía Física"},
    33: {"slug":"economia-produccion","title":"Economía: Producción"},
    34: {"slug":"economia-distribucion-consumo","title":"Economía: Distribución y Consumo"},
    35: {"slug":"publicidad-medios-comunicacion","title":"Publicidad y Medios de Comunicación"},
    36: {"slug":"repaso-p7","title":"Repaso P7: Economía y Medios"},
    37: {"slug":"poblacion-mundial-distribucion","title":"Población Mundial: Distribución"},
    38: {"slug":"migraciones-cultura-global","title":"Migraciones y Cultura Global"},
    39: {"slug":"la-democracia-como-sistema","title":"La Democracia como Sistema Político"},
    40: {"slug":"repaso-integral-anual","title":"Repaso Integral Anual"},
}

Q = {}
# helper
def q(bloom, stem, opts, correct, expl):
    return {
        "bloom": bloom,
        "icfes": "Pensamiento Social",
        "stem": stem,
        "options": [[chr(65+i), t.strip(), f.strip()] for i,(t,f) in enumerate(opts)],
        "correct": correct,
        "explanation": expl
    }

# W08 Mesopotamia
Q[8] = [
    q("Remember","¿Entre qué dos ríos se desarrolló la civilización de Mesopotamia?",
      [("Río Nilo y Río Jordán","Incorrecto. El Nilo está en Egipto."),
       ("Río Tigris y Río Éufrates","Correcto. Mesopotamia significa 'tierra entre ríos'."),
       ("Río Danubio y Río Rin","Incorrecto. Están en Europa."),
       ("Río Indo y Río Ganges","Incorrecto. Están en la India.")],"B",
      "Mesopotamia se desarrolló entre los ríos Tigris y Éufrates, en el actual Irak."),
    q("Remember","¿Qué invento se atribuye a los sumerios de Mesopotamia?",
      [("El papel","Incorrecto. El papel fue inventado en China."),
       ("Los jeroglíficos","Incorrecto. Son egipcios."),
       ("La escritura cuneiforme","Correcto. Hacia el 3500 a.C."),
       ("El alfabeto fonético","Incorrecto. Es fenicio.")],"C",
      "Los sumerios crearon la escritura cuneiforme, signos en forma de cuña grabados en tablillas."),
    q("Understand","¿Por qué es importante el Código de Hammurabi?",
      [("Es el primer libro de poemas conocido","Incorrecto. No es literario."),
       ("Describe cómo construir pirámides","Incorrecto. No trata de construcción."),
       ("Uno de los primeros conjuntos de leyes escritas","Correcto. 282 leyes basadas en 'ojo por ojo'."),
       ("Narra la creación del mundo","Incorrecto. Esa es obra del Poema de Gilgamesh.")],"C",
      "El Código de Hammurabi (1754 a.C.) es uno de los primeros códigos legales escritos."),
    q("Apply","Un estudiante en Bogotá ve una maqueta de un zigurat. ¿Cuál era su función?",
      [("Tumbas para faraones","Incorrecto. Esa función la cumplían las pirámides egipcias."),
       ("Templos religiosos en forma de torre escalonada","Correcto. Cada ciudad tenía uno."),
       ("Mercados comerciales","Incorrecto. Eran templos."),
       ("Fortalezas militares","Incorrecto. Las murallas defendían las ciudades.")],"B",
      "Los zigurats eran torres escalonadas que servían como templos para el dios protector."),
    q("Understand","¿Cómo se organizaba la sociedad en Mesopotamia?",
      [("Era una sociedad sin clases","Incorrecto. Era jerárquica."),
       ("Rey, sacerdotes, escribas, comerciantes, campesinos y esclavos","Correcto. Pirámide jerárquica."),
       ("Solo dos clases: libres y esclavos","Incorrecto. Había varios niveles."),
       ("El pueblo elegía a los gobernantes","Incorrecto. Era monarquía.")],"B",
      "Sociedad jerárquica: rey, sacerdotes, escribas, comerciantes, campesinos, esclavos."),
    q("Analyze","¿Por qué Mesopotamia es considerada 'cuna de la civilización'?",
      [("Allí apareció el primer ser humano","Incorrecto. Fue en África."),
       ("Allí surgieron las primeras ciudades, escritura y Estado","Correcto. Innovaciones clave."),
       ("Se construyeron las primeras pirámides","Incorrecto. Las pirámides son egipcias."),
       ("Allí se domesticaron los primeros animales","Incorrecto. Ocurrió en el Neolítico.")],"B",
      "Mesopotamia fue cuna de la ciudad, la escritura, las leyes y la agricultura de regadío."),
    q("Remember","¿Cuál era el dios principal de los babilonios?",
      [("Zeus","Incorrecto. Zeus es griego."),
       ("Ra","Incorrecto. Ra es egipcio."),
       ("Marduk","Correcto. Patrono de Babilonia."),
       ("Odín","Incorrecto. Es nórdico.")],"C",
      "Marduk era el dios principal. Según el mito venció al caos (Tiamat)."),
    q("Apply","¿Para qué servían los canales de riego en Mesopotamia?",
      [("Para navegar entre ciudades","Incorrecto. No era su fin principal."),
       ("Para regar los cultivos","Correcto. Llevaban agua del Tigris y Éufrates."),
       ("Para proveer agua potable","Incorrecto. Eran para agricultura."),
       ("Para defender ciudades","Incorrecto. La defensa era con murallas.")],"B",
      "Los canales permitían la agricultura productiva al controlar inundaciones."),
    q("Evaluate","Comparando la escritura cuneiforme con la comunicación digital actual:",
      [("La cuneiforme era más rápida","Incorrecto. Escribir en arcilla era muy lento."),
       ("La cuneiforme era física; la digital es instantánea y global","Correcto."),
       ("Ambas usan el mismo alfabeto","Incorrecto. La cuneiforme usaba pictogramas."),
       ("Los mesopotámicos no tenían escritura","Incorrecto. Inventaron la primera.")],"B",
      "La comunicación evolucionó de tablillas físicas a mensajes globales instantáneos."),
    q("Understand","¿Qué unificó a los imperios acadio, babilónico y asirio?",
      [("Eran imperios marítimos","Incorrecto. Mesopotamia no tiene costa."),
       ("Gobernaron toda Europa","Incorrecto. Solo controlaron Mesopotamia."),
       ("Unificaron territorios entre el Tigris y Éufrates","Correcto. Todos controlaron esa región."),
       ("Fueron derrotados por Egipto","Incorrecto. Cayeron ante los persas.")],"C",
      "Acadios, babilonios y asirios controlaron la región mesopotámica en distintos periodos."),
]

# W09 Egipto
Q[9] = [
    q("Remember","¿Qué río fue esencial para Egipto?",
      [("Tigris","Incorrecto. Es de Mesopotamia."),
       ("Nilo","Correcto. Heródoto dijo: 'Egipto es un don del Nilo'."),
       ("Jordán","Incorrecto. Está en Palestina."),
       ("Indo","Incorrecto. Está en la India.")],"B",
      "El Nilo depositaba limo fértil durante sus inundaciones anuales."),
    q("Remember","¿Cómo se llamaba el gobernante egipcio considerado un dios?",
      [("Emperador","Incorrecto. Título usado en Roma."),
       ("Faraón","Correcto. Autoridad política, religiosa y militar absoluta."),
       ("Rey-sacerdote","Incorrecto. Su título era faraón."),
       ("Sátrapa","Incorrecto. Eran gobernadores persas.")],"B",
      "El faraón era un monarca absoluto, hijo del dios Ra."),
    q("Understand","¿Cuál era el propósito de las pirámides?",
      [("Observatorios astronómicos","Incorrecto. No eran observatorios."),
       ("Templos para los dioses","Incorrecto. Los templos eran aparte."),
       ("Tumbas monumentales para los faraones","Correcto."),
       ("Almacenes de grano","Incorrecto. Eran tumbas.")],"C",
      "Las pirámides preservaban el cuerpo del faraón para la vida eterna."),
    q("Apply","¿Por qué momificaban los egipcios a sus muertos?",
      [("Conservar el cuerpo para que el alma lo reclamara","Correcto. Creían que el alma necesitaba el cuerpo."),
       ("Curar enfermedades","Incorrecto. No era médico."),
       ("Crear obras de arte","Incorrecto. Era religioso."),
       ("Alimentar animales","Incorrecto. Era proceso funerario.")],"A",
      "Creían que el ka (fuerza vital) y el ba (alma) necesitaban el cuerpo."),
    q("Understand","¿Quiénes estaban en la cima social de Egipto?",
      [("Campesinos","Incorrecto. Estaban en la base."),
       ("Faraón, familia real y altos sacerdotes","Correcto."),
       ("Soldados","Incorrecto. Tenían estatus medio."),
       ("Esclavos","Incorrecto. Base de la pirámide.")],"B",
      "Faraón, nobles, sacerdotes, escribas, comerciantes, artesanos, campesinos, esclavos."),
    q("Analyze","¿Por qué los egipcios crearon un calendario de 365 días?",
      [("Lo copiaron de los romanos","Incorrecto. Es anterior."),
       ("Para predecir inundaciones del Nilo","Correcto. Marcaba el ciclo agrícola."),
       ("Celebrar el cumpleaños del faraón","Incorrecto. Era práctico."),
       ("Seguir las fases lunares","Incorrecto. Era calendario solar.")],"B",
      "Uno de los primeros calendarios solares para predecir las inundaciones del Nilo."),
    q("Remember","¿Cómo se llama la escritura egipcia?",
      [("Cuneiforme","Incorrecto. Es de Mesopotamia."),
       ("Jeroglífico","Correcto. Símbolos que representaban sonidos e ideas."),
       ("Alfabeto fenicio","Incorrecto. Es de Fenicia."),
       ("Sánscrito","Incorrecto. Es de la India.")],"B",
      "Los jeroglíficos combinaban logogramas y signos fonéticos."),
    q("Apply","¿Por qué los egipcios adoraban al dios Ra?",
      [("Era dios de la guerra","Incorrecto. Ra era dios del sol."),
       ("Dios del sol, fuente de vida","Correcto. Esencial en el desierto."),
       ("Dios del Nilo","Incorrecto. El dios del Nilo era Hapy."),
       ("Protegía las pirámides","Incorrecto. Anubis protegía a los muertos.")],"B",
      "Ra era la deidad más importante. El sol era vital para la agricultura y la vida."),
    q("Evaluate","Diferencia principal entre el gobierno egipcio y Colombia:",
      [("Ambos eligen gobernantes","Incorrecto. En Egipto no se elegía."),
       ("Egipto era teocracia con faraón divino; Colombia es democracia con separación de poderes","Correcto."),
       ("Ambos tienen Congreso","Incorrecto. Egipto no tenía legislatura."),
       ("En Colombia el presidente es un dios","Incorrecto. Colombia es laica.")],"B",
      "Egipto concentraba el poder; Colombia divide poderes ejecutivo, legislativo y judicial."),
    q("Understand","¿Qué papel tenían los escribas?",
      [("Esclavos constructores","Incorrecto. Gozaban de prestigio."),
       ("Funcionarios que registraban cosechas e impuestos","Correcto."),
       ("Guerreros del ejército","Incorrecto. No eran militares."),
       ("Sacerdotes","Incorrecto. Eran grupos distintos.")],"B",
      "Los escribas sabían leer y escribir, administraban el Estado."),
]

# Simplemente generaré el resto inline en el script tras verificar esto funciona
print("W08-W09 data loaded")
