#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate W12-W20 bundles."""

import os, sys
sys.path.insert(0, '.')
from gen_w10_w11 import make_bundle, Q

BASE = "E:/scripts-python/worldexams/questions_data/colombia/sociales-ciudadanas/grado-5/2026/weekly"

def wb(week, tema, rubric, qs):
    fname = "CO-SOC-5-2026-%s-%s-001-MASTERY.md" % (week, tema)
    with open(os.path.join(BASE, fname), "w", encoding="utf-8") as f:
        f.write(make_bundle(week, tema, rubric, qs))
    print("Wrote %s" % fname)

# W12: Poblamiento de America
wb("W12", "poblamiento-america", "Teorias del poblamiento de America: estrecho de Bering, rutas migratorias", [
    Q("Segun la teoria mas aceptada, por donde llegaron los primeros pobladores a America?",
      [("A) Por el oceano Atlantico en barcos", "Incorrecto."),
       ("B) Por el estrecho de Bering", "Correcto. Cruzaron desde Asia por el estrecho de Bering."),
       ("C) Por la Antartida", "Incorrecto."),
       ("D) Por el oceano Pacifico desde Australia", "Incorrecto.")],
      "B", "El estrecho de Bering (entre Siberia y Alaska) estaba congelado durante la ultima glaciacion, creando un puente terrestre. Los primeros pobladores cruzaron caminando."),
    Q("Hace aproximadamente cuantos anos llegaron los primeros seres humanos a America?",
      [("A) 1.000 anos", "Incorrecto. Mucho mas tiempo."),
       ("B) 15.000 a 20.000 anos", "Correcto. Durante la ultima glaciacion."),
       ("C) 100.000 anos", "Incorrecto. Demasiado tiempo."),
       ("D) 500 anos", "Incorrecto. Colon llego hace 500 anos pero ya habia pobladores.")],
      "B", "Se estima que los primeros grupos humanos llegaron a America entre 15.000 y 20.000 anos antes del presente."),
    Q("Que continente abandonaron los primeros pobladores para llegar a America?",
      [("A) Europa", "Incorrecto."),
       ("B) Africa", "Incorrecto."),
       ("C) Asia", "Correcto. Cruzaron desde Asia (Siberia)."),
       ("D) Oceania", "Incorrecto.")],
      "C", "Los primeros americanos eran cazadores-recolectores de Asia (Siberia) que siguieron a los animales que cazaban."),
    Q("Que es el estrecho de Bering?",
      [("A) Un rio entre Europa y Asia", "Incorrecto."),
       ("B) Un brazo de mar entre Asia y America", "Correcto. Separa Siberia de Alaska."),
       ("C) Una montana en Sudamerica", "Incorrecto."),
       ("D) Un lago en Norteamerica", "Incorrecto.")],
      "B", "El estrecho de Bering tiene solo 82 km de ancho. Durante las glaciaciones, al bajar el nivel del mar, quedo al descubierto un puente terrestre."),
    Q("Quienes eran los primeros pobladores de America segun su modo de vida?",
      [("A) Agricultores sedentarios", "Incorrecto. Aun no practicaban la agricultura."),
       ("B) Cazadores-recolectores nomadas", "Correcto. Vivian de la caza y la recoleccion."),
       ("C) Comerciantes maritimos", "Incorrecto."),
       ("D) Constructores de ciudades", "Incorrecto.")],
      "B", "Los primeros americanos eran nomadas que se desplazaban siguiendo a los animales que cazaban (mamuts, bisontes) y recolectando frutos."),
    Q("Si el estrecho de Bering estaba congelado, por que los primeros pobladores no regresaron a Asia?",
      [("A) Porque olvidaron el camino", "Incorrecto."),
       ("B) Porque los animales que seguian se movian hacia el sur", "Correcto. Siguieron a los animales hacia el interior de America."),
       ("C) Porque construyeron barcos", "Incorrecto."),
       ("D) Porque el estrecho se descongelo rapidamente", "Incorrecto.")],
      "B", "Al subir las temperaturas, los glaciares se derritieron y el estrecho se lleno de agua. Los pobladores ya estaban en America siguiendo las manadas."),
    Q("Existen otras teorias sobre el poblamiento de America. Cual de las siguientes es una?",
      [("A) Teoria del poblamiento por el Atlantico", "Correcto. Grupos europeos pudieron haber llegado por el Atlantico Norte."),
       ("B) Teoria del poblamiento por la Luna", "Incorrecto."),
       ("C) Teoria del poblamiento extraterrestre", "Incorrecto."),
       ("D) Teoria del poblamiento autoctono", "Incorrecto.")],
      "A", "Ademas de la teoria de Bering, existe la teoria del poblamiento por el Atlantico (desde Europa siguiendo el hielo) y la teoria por el Pacifico (desde Polinesia)."),
    Q("Cual de estos animales fue cazado por los primeros pobladores de America?",
      [("A) El caballo", "Incorrecto. Los caballos se extinguieron en America y fueron reintroducidos por los espanoles."),
       ("B) El mamut", "Correcto. Los mamuts y otros grandes mamiferos fueron cazados."),
       ("C) La vaca", "Incorrecto. Fue introducida por los europeos."),
       ("D) La oveja", "Incorrecto. Fue introducida.")],
      "B", "Los primeros pobladores cazaban mega-fauna: mamuts, perezosos gigantes, tigres dientes de sable. Muchas de estas especies se extinguieron."),
    Q("Por que el nivel del mar estaba mas bajo durante las glaciaciones?",
      [("A) Porque el agua se evaporo", "Incorrecto."),
       ("B) Porque gran parte del agua estaba congelada en glaciares", "Correcto. Al congelarse el agua en los polos, bajo el nivel del mar."),
       ("C) Porque los rios se secaron", "Incorrecto."),
       ("D) Porque la Tierra se encogio", "Incorrecto.")],
      "B", "Durante las glaciaciones, enormes cantidades de agua quedaron atrapadas en los glaciares, haciendo bajar el nivel del mar hasta 120 metros."),
    Q("Cual fue el principal efecto del poblamiento humano en America para los ecosistemas?",
      [("A) No hubo ningun efecto", "Incorrecto."),
       ("B) La extincion de la megafauna (mamuts, perezosos gigantes)", "Correcto. La caza contribuyo a la extincion de grandes animales."),
       ("C) La creacion de ciudades", "Incorrecto. Eso fue mucho despues."),
       ("D) El cultivo de maiz", "Incorrecto. Eso fue un efecto positivo.")],
      "B", "La llegada del ser humano a America coincidio con la extincion de la megafauna. Ademas de la caza, los cambios climaticos tambien influyeron.", d="D4"),
])

# W13: Taironas
wb("W13", "culturas-precolombinas-taironas", "Cultura precolombina Tairona: organizacion social, economia, vivienda", [
    Q("Donde se desarrollo la cultura Tairona?",
      [("A) En la Amazonia colombiana", "Incorrecto."),
       ("B) En la Sierra Nevada de Santa Marta", "Correcto. Los Taironas habitaron las laderas de la Sierra Nevada."),
       ("C) En el altiplano cundiboyacense", "Incorrecto. Esa fue la region Muisca."),
       ("D) En el valle del Cauca", "Incorrecto.")],
      "B", "Los Taironas se establecieron en las laderas de la Sierra Nevada de Santa Marta, desde el nivel del mar hasta los 2.000 m de altitud."),
    Q("Como construian sus viviendas los Taironas?",
      [("A) Casas de madera sobre el agua", "Incorrecto."),
       ("B) Casas de piedra con terrazas y caminos empedrados", "Correcto. Construyeron terrazas, caminos de piedra y viviendas circulares."),
       ("C) Tiendas de cuero nomadas", "Incorrecto."),
       ("D) Casas de barro en los arboles", "Incorrecto.")],
      "B", "Los Taironas construyeron terrazas de cultivo en las montanas, caminos empedrados que conectaban sus poblados y viviendas de piedra con techo de paja."),
    Q("Cual era la base de la economia Tairona?",
      [("A) La mineria de carbon", "Incorrecto."),
       ("B) La agricultura, especialmente el maiz", "Correcto. Cultivaban maiz, yuca, frijol, algodon y frutas."),
       ("C) La pesca industrial", "Incorrecto."),
       ("D) La ganaderia extensiva", "Incorrecto.")],
      "B", "Los Taironas construyeron terrazas de cultivo en las laderas para sembrar maiz, yuca, frijol y algodon. Tambien intercambiaban productos con las costas."),
    Q("Como se organizaba la sociedad Tairona?",
      [("A) En un solo gran imperio", "Incorrecto."),
       ("B) En cacicazgos gobernados por un cacique", "Correcto. Cada poblado tenia un cacique y un sacerdote."),
       ("C) Sin ninguna organizacion", "Incorrecto."),
       ("D) En una democracia moderna", "Incorrecto.")],
      "B", "Los Taironas se organizaban en cacicazgos. El cacique gobernaba y el sacerdote (mamo) dirigia los rituales. La sociedad era jerarquica."),
    Q("Que objeto fabricaban los Taironas con gran habilidad?",
      [("A) Automoviles", "Incorrecto."),
       ("B) Piezas de oro (orfebreria)", "Correcto. Eran expertos orfebres."),
       ("C) Aviones de papel", "Incorrecto."),
       ("D) Barcos transatlanticos", "Incorrecto.")],
      "B", "Los Taironas trabajaban el oro con gran maestria, creando figuras, mascaras, pectorales y adornos. Usaban la tecnica de la cera perdida."),
    Q("Por que los Taironas construian terrazas en las montanas?",
      [("A) Para decorar el paisaje", "Incorrecto."),
       ("B) Para cultivar en las laderas empinadas", "Correcto. Las terrazas evitaban la erosion y permitian el cultivo."),
       ("C) Para hacer caminos", "Incorrecto."),
       ("D) Para jugar", "Incorrecto.")],
      "B", "Las terrazas de cultivo eran escalones en las laderas que evitaban la erosion de la tierra y permitian cultivar en terrenos inclinados. Aun se ven restos en la Ciudad Perdida."),
    Q("Como se llama la ciudad sagrada Tairona descubierta en 1972?",
      [("A) Machu Picchu", "Incorrecto. Esta en Peru (Incas)."),
       ("B) Ciudad Perdida (Teyuna)", "Correcto. Es un antiguo centro ceremonial Tairona."),
       ("C) Chichen Itza", "Incorrecto. Esta en Mexico (Mayas)."),
       ("D) Teotihuacan", "Incorrecto. Esta en Mexico.")],
      "B", "La Ciudad Perdida (Teyuna) fue construida por los Taironas entre los siglos VII y XIV. Tiene terrazas, caminos, escaleras y plazas circulares."),
    Q("Que relacion tenian los Taironas con el mar?",
      [("A) No tenian acceso al mar", "Incorrecto."),
       ("B) Aprovechaban los recursos marinos y comerciaban con la costa", "Correcto. Tenian contacto con el mar Caribe."),
       ("C) Navegaban hasta Europa", "Incorrecto."),
       ("D) Vivian en el mar", "Incorrecto.")],
      "B", "Los Taironas ocupaban desde la costa caribe hasta las altas montanas. Intercambiaban productos agricolas de la montana por pescado y conchas de la costa."),
    Q("Como influyo el relieve en el desarrollo de la cultura Tairona?",
      [("A) No influyo en nada", "Incorrecto."),
       ("B) Las montanas escarpadas los aislaron y protegieron, e influyeron en su arquitectura de terrazas", "Correcto."),
       ("C) El relieve plano facilito la construccion de ciudades", "Incorrecto."),
       ("D) Los rios fueron su unica fuente de alimento", "Incorrecto.")],
      "B", "El relieve montanoso de la Sierra Nevada obligo a los Taironas a innovar con terrazas de cultivo y caminos de piedra, y les dio proteccion natural.", d="D4"),
    Q("Compara los Taironas con los Muiscas: cual afirmacion es correcta?",
      [("A) Ambas culturas vivian en la Sierra Nevada", "Incorrecto. Los Muiscas vivian en el altiplano."),
       ("B) Los Taironas vivian en la Sierra Nevada y los Muiscas en el altiplano", "Correcto."),
       ("C) Ambas culturas eran nomadas", "Incorrecto."),
       ("D) Los Taironas cultivaban papa y los Muiscas pescaban", "Incorrecto.")],
      "B", "Los Taironas habitaron la Sierra Nevada de Santa Marta; los Muiscas, el altiplano cundiboyacense. Ambas eran culturas sedentarias y agricolas.", d="D4"),
])

# W14: Muiscas y Quimbayas
wb("W14", "culturas-precolombinas-muiscas", "Cultura Muisca y Quimbaya: organizacion politica, economia, orfebreria", [
    Q("Donde se desarrollo la cultura Muisca?",
      [("A) En la Sierra Nevada de Santa Marta", "Incorrecto."),
       ("B) En el altiplano cundiboyacense", "Correcto. En los actuales departamentos de Cundinamarca, Boyaca y Santander."),
       ("C) En la costa Pacifica", "Incorrecto."),
       ("D) En los Llanos Orientales", "Incorrecto.")],
      "B", "El altiplano cundiboyacense, a mas de 2.600 msnm, fue el territorio Muisca. Alli se encuentran Bogota, Tunja y Villa de Leyva."),
    Q("Como se organizaba politicamente la confederacion Muisca?",
      [("A) En un solo reino con un rey absoluto", "Incorrecto."),
       ("B) En dos grandes confederaciones: el Zipa al sur y el Zaque al norte", "Correcto."),
       ("C) En ciudades independientes sin gobierno", "Incorrecto."),
       ("D) En un imperio similar a los Incas", "Incorrecto.")],
      "B", "Los Muiscas tenian dos gobernantes principales: el Zipa (Bacata/Bogota) y el Zaque (Hunza/Tunja). Tambien habia el Iraca (Sogamoso) y el Tundama (Duitama)."),
    Q("Cual era la principal actividad economica de los Muiscas?",
      [("A) La mineria de oro", "Incorrecto. El oro lo obtenian por comercio."),
       ("B) La agricultura (maiz, papa, quinua)", "Correcto. Cultivaban en terrazas y usaban sistemas de riego."),
       ("C) La pesca en el mar", "Incorrecto. No tenian acceso al mar."),
       ("D) La ganaderia de llamas", "Incorrecto. No tenian llamas.")],
      "B", "Los Muiscas cultivaban maiz, papa, quinua, cubios, hibias. Construyeron terrazas de cultivo y canales de riego. Tambien comerciaban sal y esmeraldas."),
    Q("Por que eran famosos los Quimbayas?",
      [("A) Por sus piramides", "Incorrecto."),
       ("B) Por su orfebreria en oro", "Correcto. Los Quimbayas fueron maestros orfebres."),
       ("C) Por sus sistemas de escritura", "Incorrecto."),
       ("D) Por sus barcos", "Incorrecto.")],
      "B", "La cultura Quimbaya (actuales Caldas, Risaralda, Quindio) se destaco por su increible orfebreria. Su obra maestra es el Poporo Quimbaya."),
    Q("Que objeto es el simbolo del arte Quimbaya?",
      [("A) La mascara de oro", "Incorrecto."),
       ("B) El Poporo Quimbaya", "Correcto. Es un recipiente de oro usado para guardar cal (para la hoja de coca)."),
       ("C) La tunja de algodon", "Incorrecto."),
       ("D) El cesped", "Incorrecto.")],
      "B", "El Poporo Quimbaya (Museo del Oro, Bogota) es una pieza unica de orfebreria precolombina, hecha en oro con forma de mujer."),
    Q("Donde se ubico la cultura Quimbaya?",
      [("A) Altiplano cundiboyacense", "Incorrecto."),
       ("B) Eje Cafetero (Caldas, Risaralda, Quindio)", "Correcto."),
       ("C) Costa Caribe", "Incorrecto."),
       ("D) Amazonia", "Incorrecto.")],
      "B", "Los Quimbayas habitaron la region del Eje Cafetero, entre los rios Cauca y La Vieja, en un clima templado."),
    Q("Que producto era fundamental en el comercio Muisca?",
      [("A) El petroleo", "Incorrecto."),
       ("B) La sal", "Correcto. Los Muiscas explotaban minas de sal en Nemocon y Zipaquira."),
       ("C) El carbon", "Incorrecto."),
       ("D) El hierro", "Incorrecto.")],
      "B", "La sal era un producto muy valioso. Los Muiscas la intercambiaban por algodon, oro, conchas y otros productos con grupos vecinos."),
    Q("Que materiales usaban los Quimbayas para sus obras de orfebreria?",
      [("A) Solo madera", "Incorrecto."),
       ("B) Oro y tumbaga (aleacion de oro y cobre)", "Correcto. Usaban oro, plata, cobre y tumbaga."),
       ("C) Plastico", "Incorrecto."),
       ("D) Hierro y acero", "Incorrecto.")],
      "B", "Los Quimbayas trabajaban el oro puro y la tumbaga (aleacion de oro y cobre), usando tecnicas como martillado, fundicion a la cera perdida y repujado."),
    Q("Compara Muiscas y Quimbayas: cual afirmacion es correcta?",
      [("A) Ambas culturas vivian en el mismo lugar", "Incorrecto."),
       ("B) Los Muiscas vivian en el altiplano frio y los Quimbayas en el valle templado", "Correcto."),
       ("C) Los Quimbayas tenian Zipas y Zaques", "Incorrecto."),
       ("D) Ninguna conocia el oro", "Incorrecto.")],
      "B", "Los Muiscas habitaban el altiplano frio (2.600 msnm), los Quimbayas el valle templado (1.000-1.500 msnm) del Eje Cafetero.", d="D4"),
    Q("Que legado nos dejaron las culturas Muisca y Quimbaya?",
      [("A) La escritura alfabetica", "Incorrecto."),
       ("B) El sistema de numeracion moderno", "Incorrecto."),
       ("C) Obras de orfebreria, tecnicas agricolas y su influencia en la identidad colombiana", "Correcto."),
       ("D) El ferrocarril", "Incorrecto.")],
      "C", "Su legado incluye piezas de orfebreria invaluables, tecnicas de cultivo en terrazas, conocimientos astronomicos y su influencia en la cultura colombiana actual.", d="D4"),
])

# W15: Repaso P3
wb("W15", "repaso-p3", "Repaso culturas precolombinas y poblamiento de America", [
    Q("Por donde llegaron los primeros pobladores a America segun la teoria principal?",
      [("A) Por el estrecho de Magallanes", "Incorrecto."),
       ("B) Por el estrecho de Bering", "Correcto."),
       ("C) Por el oceano Atlantico", "Incorrecto."),
       ("D) Por el rio Amazonas", "Incorrecto.")],
      "B", "El estrecho de Bering entre Siberia (Asia) y Alaska (America)."),
    Q("Cual cultura precolombina habito la Sierra Nevada de Santa Marta?",
      [("A) Muisca", "Incorrecto."),
       ("B) Quimbaya", "Incorrecto."),
       ("C) Tairona", "Correcto."),
       ("D) Inca", "Incorrecto.")],
      "C", "Los Taironas construyeron terrazas y caminos de piedra en la Sierra Nevada."),
    Q("Cual era la base de la economia de las culturas precolombinas colombianas?",
      [("A) La caza exclusivamente", "Incorrecto."),
       ("B) La agricultura", "Correcto. Cultivaban maiz, yuca, papa, frijol."),
       ("C) La pesca industrial", "Incorrecto."),
       ("D) La mineria moderna", "Incorrecto.")],
      "B", "Taironas, Muiscas y Quimbayas practicaban agricultura sedentaria."),
    Q("Donde se desarrollo la cultura Muisca?",
      [("A) En la Sierra Nevada", "Incorrecto."),
       ("B) En el altiplano cundiboyacense", "Correcto."),
       ("C) En el Eje Cafetero", "Incorrecto."),
       ("D) En la costa Caribe", "Incorrecto.")],
      "B", "Los Muiscas vivian en el altiplano frio de Cundinamarca y Boyaca."),
    Q("Cual cultura es famosa por su orfebreria en oro, especialmente el Poporo?",
      [("A) Tairona", "Incorrecto. Tambien eran orfebres."),
       ("B) Muisca", "Incorrecto."),
       ("C) Quimbaya", "Correcto."),
       ("D) Zen\u00fa", "Incorrecto.")],
      "C", "Los Quimbayas del Eje Cafetero crearon el Poporo Quimbaya, joya del Museo del Oro."),
    Q("Que significo el poblamiento de America para las culturas del mundo?",
      [("A) El inicio de una nueva era de diversidad cultural en el continente", "Correcto."),
       ("B) El fin de la prehistoria", "Incorrecto."),
       ("C) La invencion de la escritura", "Incorrecto."),
       ("D) El inicio de la agricultura mundial", "Incorrecto.")],
      "A", "El poblamiento humano dio origen a cientos de culturas diferentes en America.", d="D3"),
    Q("Como se llamaba el gobernante Muisca del sur?",
      [("A) Zaque", "Incorrecto. Era el del norte."),
       ("B) Zipa", "Correcto. El Zipa gobernaba Bacata (Bogota)."),
       ("C) Cacique", "Incorrecto. Termino generico."),
       ("D) Inca", "Incorrecto.")],
      "B", "El Zipa gobernaba el sur de la confederacion Muisca; el Zaque gobernaba el norte."),
    Q("Que tecnica usaban los Quimbayas para trabajar el oro?",
      [("A) Soldadura electrica", "Incorrecto."),
       ("B) Cera perdida y martillado", "Correcto."),
       ("C) Impresion 3D", "Incorrecto."),
       ("D) Torno mecanico", "Incorrecto.")],
      "B", "La tecnica de la cera perdida consistia en hacer un molde de cera, cubrirlo con arcilla y fundir la cera para llenar el espacio con oro fundido."),
    Q("Compara Taironas y Quimbayas: que tenian en comun?",
      [("A) Vivian en el mismo lugar", "Incorrecto."),
       ("B) Ambos trabajaban el oro", "Correcto. Ambas culturas eran expertas orfebres."),
       ("C) Tenian el mismo idioma", "Incorrecto."),
       ("D) Adoraban al mismo dios", "Incorrecto.")],
      "B", "Tanto Taironas como Quimbayas desarrollaron una importante orfebreria.", d="D4"),
    Q("Por que es importante estudiar las culturas precolombinas de Colombia?",
      [("A) Porque construyeron ciudades modernas", "Incorrecto."),
       ("B) Porque son la raiz de nuestra identidad cultural y su legado sigue vivo", "Correcto."),
       ("C) Porque inventaron la electricidad", "Incorrecto."),
       ("D) Porque escribieron la primera constitucion", "Incorrecto.")],
      "B", "Los pueblos indigenas actuales son herederos de estas culturas. Su legado esta presente en nuestra alimentacion, lenguas, arte y tradiciones.", d="D4"),
])

print("Done! W12-W15 generated.")
