#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate W36-W40 bundles."""

import os, sys, importlib.util
BASE = "E:/scripts-python/worldexams/questions_data/colombia/sociales-ciudadanas/grado-5/2026/weekly"
spec = importlib.util.spec_from_file_location("mod", os.path.join(BASE, "gen_w10_w11.py"))
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)
make_bundle, Q = mod.make_bundle, mod.Q

def wb(week, tema, rubric, qs):
    fname = "CO-SOC-5-2026-%s-%s-001-MASTERY.md" % (week, tema)
    with open(os.path.join(BASE, fname), "w", encoding="utf-8") as f:
        f.write(make_bundle(week, tema, rubric, qs))
    print("Wrote %s" % fname)

# W36: Organismos Internacionales
wb("W36", "organismos-internacionales", "Organismos internacionales: ONU, OEA, UNICEF, derechos humanos", [
    Q("Que significa ONU?",
      [("A) Organizacion Nacional Unida", "Incorrecto."),
       ("B) Organizacion de las Naciones Unidas", "Correcto."),
       ("C) Orden Natural Universal", "Incorrecto."),
       ("D) Oficina Nacional de Uso", "Incorrecto.")],
      "B", "La ONU fue fundada en 1945 despues de la Segunda Guerra Mundial para mantener la paz y seguridad internacional."),
    Q("Cuantos paises son miembros de la ONU?",
      [("A) 100", "Incorrecto."),
       ("B) 193", "Correcto. Casi todos los paises del mundo."),
       ("C) 50", "Incorrecto."),
       ("D) 300", "Incorrecto.")],
      "B", "La ONU tiene 193 Estados miembros. Colombia es miembro fundador desde 1945."),
    Q("Que funcion principal tiene la ONU?",
      [("A) Gobernar todos los paises", "Incorrecto."),
       ("B) Mantener la paz y seguridad internacional, promover derechos humanos y desarrollo", "Correcto."),
       ("C) Recaudar impuestos mundiales", "Incorrecto."),
       ("D) Organizar guerras", "Incorrecto.")],
      "B", "La ONU busca prevenir conflictos, proteger los derechos humanos, promover el desarrollo sostenible."),
    Q("Que es UNICEF?",
      [("A) Un partido politico", "Incorrecto."),
       ("B) El Fondo de las Naciones Unidas para la Infancia", "Correcto. Protege los derechos de los ninos."),
       ("C) Un banco", "Incorrecto."),
       ("D) Un ejercito", "Incorrecto.")],
      "B", "UNICEF trabaja en todo el mundo para proteger los derechos de los ninos: educacion, salud, nutricion."),
    Q("Que es la OEA?",
      [("A) Organizacion de Estados Americanos", "Correcto. Reune a los paises de America."),
       ("B) Oficina de Educacion Ambiental", "Incorrecto."),
       ("C) Organizacion Europea", "Incorrecto."),
       ("D) Orden de Estados Africanos", "Incorrecto.")],
      "A", "La OEA fue fundada en 1948 (Bogota) y reune a 35 paises de America."),
    Q("Que es la Declaracion Universal de los Derechos Humanos?",
      [("A) Una ley colombiana", "Incorrecto."),
       ("B) Un documento adoptado por la ONU en 1948 que establece los derechos fundamentales de todas las personas", "Correcto."),
       ("C) Un tratado de comercio", "Incorrecto."),
       ("D) Un libro de historia", "Incorrecto.")],
      "B", "La DUDH fue adoptada por la Asamblea General de la ONU el 10 de diciembre de 1948. Establece 30 derechos fundamentales que todos los paises deben respetar."),
    Q("Cuales son algunos derechos humanos fundamentales?",
      [("A) Derecho a la vida, libertad, igualdad, educacion, salud y trabajo", "Correcto."),
       ("B) Solo derecho a votar", "Incorrecto."),
       ("C) Derecho a no pagar impuestos", "Incorrecto."),
       ("D) Derecho a gobernar siempre", "Incorrecto.")],
      "A", "La DUDH incluye: derecho a la vida, libertad, igualdad ante la ley, educacion, salud, trabajo, libertad de expresion y mas."),
    Q("Que es la UNESCO?",
      [("A) Un club deportivo", "Incorrecto."),
       ("B) La Organizacion de la ONU para la Educacion, la Ciencia y la Cultura", "Correcto."),
       ("C) Un banco", "Incorrecto."),
       ("D) Un partido politico", "Incorrecto.")],
      "B", "UNESCO promueve la educacion, la ciencia, la cultura y la comunicacion. Protege el patrimonio cultural de la humanidad (sitios como el Cartagena colonial)."),
    Q("Como contribuye Colombia a los organismos internacionales?",
      [("A) No participa", "Incorrecto."),
       ("B) Participa activamente en misiones de paz de la ONU, la OEA y la CAN", "Correcto."),
       ("C) Solo paga cuotas", "Incorrecto."),
       ("D) Envia solo delegaciones", "Incorrecto.")],
      "B", "Colombia es miembro activo de la ONU, OEA, CAN, Alianza del Pacifico. Participa en misiones de paz (como en Sinai) y promueve la agenda 2030."),
    Q("Por que son importantes los organismos internacionales para Colombia?",
      [("A) No son importantes", "Incorrecto."),
       ("B) Permiten la cooperacion, la defensa de los derechos humanos, la paz y el desarrollo economico entre paises", "Correcto."),
       ("C) Gobiernan Colombia", "Incorrecto."),
       ("D) Impiden el comercio", "Incorrecto.")],
      "B", "Los organismos internacionales facilitan la cooperacion en temas como paz, derechos humanos, comercio y medio ambiente, fortaleciendo la democracia y el desarrollo.", d="D4"),
])

# W37: Derechos Humanos y Ninez
wb("W37", "derechos-humanos-ninez", "Derechos humanos y derechos del nino en Colombia", [
    Q("Que son los derechos humanos?",
      [("A) Privilegios solo para algunos", "Incorrecto."),
       ("B) Derechos inherentes a toda persona por el simple hecho de ser humana", "Correcto."),
       ("C) Leyes solo colombianas", "Incorrecto."),
       ("D) Normas de un club", "Incorrecto.")],
      "B", "Los derechos humanos son universales, inalienables e inherentes a toda persona, sin distincion de raza, genero, religion o nacionalidad."),
    Q("Cuales son las caracteristicas de los derechos humanos?",
      [("A) Universales, inalienables, indivisibles e interdependientes", "Correcto."),
       ("B) Solo para adultos", "Incorrecto."),
       ("C) Se pueden vender", "Incorrecto."),
       ("D) Solo para colombianos", "Incorrecto.")],
      "A", "Los derechos humanos son: universales (para todas las personas), inalienables (no se pueden quitar), indivisibles (todos son importantes) e interdependientes."),
    Q("Que ley en Colombia protege los derechos de los ninos y adolescentes?",
      [("A) La Ley 100 de 1993", "Incorrecto. Es de salud."),
       ("B) La Ley 1098 de 2006 (Codigo de Infancia y Adolescencia)", "Correcto."),
       ("C) La Ley 40 de 1990", "Incorrecto."),
       ("D) La Ley 30 de 1992", "Incorrecto.")],
      "B", "El Codigo de Infancia y Adolescencia (Ley 1098 de 2006) establece los derechos de los menores de 18 anos en Colombia: educacion, salud, proteccion contra el maltrato."),
    Q("Cuales son los derechos fundamentales de los ninos?",
      [("A) Solo derecho a jugar", "Incorrecto."),
       ("B) Derecho a la vida, educacion, salud, identidad, familia y proteccion", "Correcto."),
       ("C) Solo derecho a estudiar", "Incorrecto."),
       ("D) No tienen derechos", "Incorrecto.")],
      "B", "Los ninos tienen derecho a: la vida, un nombre y nacionalidad (identidad), una familia, educacion, salud, alimentacion, recreacion y proteccion."),
    Q("Que es la Convencion sobre los Derechos del Nino?",
      [("A) Una reunion de presidentes", "Incorrecto."),
       ("B) Un tratado internacional de la ONU (1989) que reconoce los derechos de todos los ninos del mundo", "Correcto."),
       ("C) Una ley colombiana", "Incorrecto."),
       ("D) Un libro de cuentos", "Incorrecto.")],
      "B", "La Convencion sobre los Derechos del Nino (1989) es el tratado de derechos humanos mas ratificado de la historia. Colombia la ratifico en 1991."),
    Q("Que instituciones protegen los derechos de los ninos en Colombia?",
      [("A) Solo la policia", "Incorrecto."),
       ("B) ICBF (Instituto Colombiano de Bienestar Familiar), Defensoria del Pueblo, comisarias de familia", "Correcto."),
       ("C) Solo los colegios", "Incorrecto."),
       ("D) Solo los hospitales", "Incorrecto.")],
      "B", "El ICBF protege a los ninos en situacion de vulnerabilidad, la Defensoria del Pueblo defiende sus derechos, y las comisarias de familia atienden casos de maltrato."),
    Q("Que hacer si se violan los derechos de un nino en Colombia?",
      [("A) No hacer nada", "Incorrecto."),
       ("B) Denunciar ante el ICBF, la policia o la Defensoria del Pueblo", "Correcto."),
       ("C) Resolverlo por cuenta propia", "Incorrecto."),
       ("D) Publicarlo en redes sociales", "Incorrecto.")],
      "B", "Cualquier persona puede denunciar la violacion de derechos de un nino llamando a la linea 141 del ICBF, o acudiendo a la policia, Defensoria del Pueblo o comisaria de familia."),
    Q("Que es el derecho a la identidad?",
      [("A) Tener un nombre, una nacionalidad y conocer a los padres", "Correcto."),
       ("B) Tener muchas fotos", "Incorrecto."),
       ("C) Tener un celular", "Incorrecto."),
       ("D) Cambiarse de nombre cada dia", "Incorrecto.")],
      "A", "El derecho a la identidad incluye tener un nombre, un apellido, una nacionalidad y, en lo posible, conocer a los padres biologicos. En Colombia se protege con el registro civil."),
    Q("Por que Colombia necesita proteger los derechos de los ninos?",
      [("A) Porque los ninos no son importantes", "Incorrecto."),
       ("B) Porque los ninos son el futuro del pais y deben crecer sanos, educados y protegidos", "Correcto."),
       ("C) Porque es una opcion", "Incorrecto."),
       ("D) Solo porque la ley lo dice", "Incorrecto.")],
      "B", "Proteger a los ninos es fundamental para construir una sociedad mejor. Ninos sanos, educados y protegidos seran ciudadanos que contribuyan al desarrollo del pais.", d="D3"),
    Q("Relaciona los derechos humanos con la democracia: cual afirmacion es correcta?",
      [("A) La democracia viola los derechos humanos", "Incorrecto."),
       ("B) La democracia y los derechos humanos estan relacionados: la democracia protege los derechos y los derechos fortalecen la democracia", "Correcto."),
       ("C) No tienen relacion", "Incorrecto."),
       ("D) Solo la democracia tiene derechos", "Incorrecto.")],
      "B", "La democracia y los derechos humanos van de la mano. Sin derechos humanos no hay democracia real, y sin democracia los derechos humanos son vulnerables.", d="D4"),
])

# W38: Convivencia y Paz
wb("W38", "convivencia-paz", "Convivencia pacifica, cultura de paz, resolucion de conflictos", [
    Q("Que es la convivencia pacifica?",
      [("A) Vivir sin relacionarse con otros", "Incorrecto."),
       ("B) La capacidad de vivir en armonia con los demas respetando las diferencias", "Correcto."),
       ("C) Estar siempre de acuerdo", "Incorrecto."),
       ("D) No hablar con nadie", "Incorrecto.")],
      "B", "La convivencia pacifica implica respetar a los demas, aceptar las diferencias (culturales, politicas, religiosas), resolver conflictos sin violencia y trabajar juntos por el bien comun."),
    Q("Que es un conflicto?",
      [("A) Una fiesta", "Incorrecto."),
       ("B) Una situacion de desacuerdo entre dos o mas personas", "Correcto."),
       ("C) Un deporte", "Incorrecto."),
       ("D) Un juego", "Incorrecto.")],
      "B", "El conflicto es natural en las relaciones humanas. Surge cuando hay diferencias de intereses, opiniones o necesidades. Lo importante es resolverlo de forma pacifica."),
    Q("Cuales son las formas de resolver un conflicto de manera pacifica?",
      [("A) A golpes", "Incorrecto. La violencia no resuelve."),
       ("B) Dialogo, negociacion, mediacion y arbitraje", "Correcto."),
       ("C) Ignorando el problema", "Incorrecto."),
       ("D) Gritando", "Incorrecto.")],
      "B", "Las formas pacificas de resolver conflictos son: el dialogo (hablar), la negociacion (llegar a acuerdos), la mediacion (un tercero ayuda) y el arbitraje (un tercero decide)."),
    Q("Que es la mediacion escolar?",
      [("A) Una clase de matematicas", "Incorrecto."),
       ("B) Un proceso donde un estudiante mediador ayuda a resolver conflictos entre companeros", "Correcto."),
       ("C) Un castigo", "Incorrecto."),
       ("D) Un examen", "Incorrecto.")],
      "B", "La mediacion escolar es una estrategia de convivencia donde estudiantes capacitados como mediadores ayudan a sus companeros a resolver conflictos de forma dialogada y pacifica."),
    Q("Que es la cultura de paz?",
      [("A) Una cultura de guerra", "Incorrecto."),
       ("B) Un conjunto de valores, actitudes y comportamientos que rechazan la violencia y promueven la paz", "Correcto."),
       ("C) Una celebracion", "Incorrecto."),
       ("D) Un tipo de musica", "Incorrecto.")],
      "B", "La cultura de paz promueve valores como el respeto, la tolerancia, la solidaridad, el dialogo y la justicia. Busca prevenir conflictos y construir una sociedad mas pacifica."),
    Q("Que son los derechos humanos en la convivencia escolar?",
      [("A) No existen en la escuela", "Incorrecto."),
       ("B) Los derechos que todos los miembros de la comunidad educativa deben respetar: respeto, no discriminacion, participacion", "Correcto."),
       ("C) Solo derechos de los profesores", "Incorrecto."),
       ("D) Solo derechos de los padres", "Incorrecto.")],
      "B", "En la escuela, los derechos humanos se aplican: derecho al respeto, a no ser discriminado, a la participacion, a la educacion de calidad y a un ambiente seguro."),
    Q("Que es el bullying y como prevenirlo?",
      [("A) Una forma de jugar", "Incorrecto."),
       ("B) El acoso escolar repetitivo; se previene con respeto, denuncia y programas de convivencia", "Correcto."),
       ("C) Un deporte", "Incorrecto."),
       ("D) Una celebracion", "Incorrecto.")],
      "B", "El bullying o acoso escolar es la agresion fisica o psicologica repetida. Se previene fomentando el respeto, denunciando casos, y creando comites de convivencia escolar."),
    Q("Que es la 'reconciliacion'?",
      [("A) Seguir peleando", "Incorrecto."),
       ("B) El proceso de restaurar una relacion despues de un conflicto", "Correcto."),
       ("C) Olvidar lo que paso", "Incorrecto."),
       ("D) Vengarse", "Incorrecto.")],
      "B", "La reconciliacion implica reconocer los errores, pedir perdon, reparar el dano y reconstruir la confianza. Es clave para la paz en relaciones personales y sociales."),
    Q("Que papel juegan los valores en la convivencia?",
      [("A) No son importantes", "Incorrecto."),
       ("B) Son fundamentales: el respeto, la tolerancia, la responsabilidad y la solidaridad permiten una convivencia armoniosa", "Correcto."),
       ("C) Solo en la casa", "Incorrecto."),
       ("D) Solo en el colegio", "Incorrecto.")],
      "B", "Los valores son la base de la convivencia. El respeto permite aceptar las diferencias, la tolerancia evita conflictos, la responsabilidad cumple con los deberes y la solidaridad ayuda al otro.", d="D3"),
    Q("Por que es importante construir paz desde la escuela?",
      [("A) Porque la escuela no tiene que ver con la paz", "Incorrecto."),
       ("B) Porque la escuela forma ciudadanos; aprender a convivir en paz prepara a los estudiantes para construir una sociedad pacifica", "Correcto."),
       ("C) Solo se aprende paz en la casa", "Incorrecto."),
       ("D) La paz no se aprende", "Incorrecto.")],
      "B", "La educacion para la paz es fundamental. La escuela no solo ensena matematicas, sino tambien valores, respeto y resolucion de conflictos. Asi se forman ciudadanos para la paz.", d="D4"),
])

# W39: Economia de Colombia
wb("W39", "economia-colombia", "Economia de Colombia: sectores economicos, recursos naturales", [
    Q("En cuantos sectores se divide la economia?",
      [("A) 2", "Incorrecto."),
       ("B) 3", "Correcto. Primario, secundario y terciario."),
       ("C) 4", "Incorrecto."),
       ("D) 5", "Incorrecto.")],
      "B", "Los sectores economicos son: primario (extraccion de recursos naturales), secundario (transformacion industrial) y terciario (servicios)."),
    Q("A que se dedica el sector primario de la economia?",
      [("A) A fabricar productos", "Incorrecto. Eso es el secundario."),
       ("B) A la extraccion de recursos naturales: agricultura, ganaderia, mineria, pesca", "Correcto."),
       ("C) A prestar servicios", "Incorrecto. Eso es el terciario."),
       ("D) A la tecnologia", "Incorrecto.")],
      "B", "El sector primario incluye: agricultura (cafe, flores, banano, arroz), ganaderia, mineria (carbon, oro, esmeraldas), pesca y silvicultura."),
    Q("Cual es el principal producto agricola de exportacion de Colombia?",
      [("A) El trigo", "Incorrecto."),
       ("B) El cafe", "Correcto. Colombia es famosa por su cafe de alta calidad."),
       ("C) El te", "Incorrecto."),
       ("D) El arroz", "Incorrecto.")],
      "B", "El cafe colombiano es reconocido mundialmente por su suavidad y aroma. Es uno de los principales productos de exportacion desde el siglo XIX."),
    Q("Que productos minerales exporta Colombia?",
      [("A) Oro, carbon, esmeraldas y niquel", "Correcto."),
       ("B) Solo cafe", "Incorrecto."),
       ("C) Solo petroleo", "Incorrecto."),
       ("D) Solo flores", "Incorrecto.")],
      "A", "Colombia exporta: carbon (uno de los mayores exportadores del mundo), oro, esmeraldas (las mejores del mundo), niquel y petroleo."),
    Q("A que se dedica el sector secundario?",
      [("A) A la agricultura", "Incorrecto. Eso es primario."),
       ("B) A transformar materias primas en productos elaborados (industria)", "Correcto."),
       ("C) A la educacion", "Incorrecto. Eso es terciario."),
       ("D) A la mineria", "Incorrecto.")],
      "B", "El sector secundario incluye la industria: fabricacion de textiles, alimentos procesados, bebidas, cemento, productos quimicos, ensamblaje de vehiculos y mas."),
    Q("Que es el sector terciario?",
      [("A) La mineria", "Incorrecto."),
       ("B) El sector de servicios: comercio, turismo, educacion, salud, transporte, banca", "Correcto."),
       ("C) La agricultura", "Incorrecto."),
       ("D) La industria", "Incorrecto.")],
      "B", "El sector terciario es el mas grande de la economia colombiana. Incluye servicios como comercio, turismo, educacion, salud, comunicaciones, finanzas y transporte."),
    Q("Que recurso energetico es importante para Colombia?",
      [("A) El carbon", "Correcto. Colombia es un gran exportador de carbon."),
       ("B) La energia nuclear", "Incorrecto. Colombia no tiene plantas nucleares."),
       ("C) El gas natural", "Tambien importante, pero el carbon es el principal."),
       ("D) La energia eolica", "Incorrecto. Es emergente pero no la principal.")],
      "A", "Colombia es uno de los principales exportadores de carbon del mundo. Tambien produce petroleo, gas natural y tiene gran potencial en energias renovables (hidroelectrica, solar, eolica)."),
    Q("Como contribuye el turismo a la economia colombiana?",
      [("A) No contribuye", "Incorrecto."),
       ("B) Genera empleo y divisas; Colombia atrae turistas por su biodiversidad, cultura y patrimonio", "Correcto."),
       ("C) Solo atrae turistas extranjeros", "Incorrecto."),
       ("D) Es un sector pequeno", "Incorrecto.")],
      "B", "El turismo es un sector creciente en Colombia. Atrae visitantes por destinos como Cartagena, el Eje Cafetero, la Amazonia, San Andres y sus parques naturales."),
    Q("Que es la economia informal y por que es un problema?",
      [("A) Trabajar en el campo", "Incorrecto."),
       ("B) Trabajos sin registro ni proteccion social; genera baja recaudacion de impuestos y falta de seguridad social", "Correcto."),
       ("C) Trabajar en empresas grandes", "Incorrecto."),
       ("D) Trabajar en el gobierno", "Incorrecto.")],
      "B", "La economia informal incluye vendedores ambulantes, trabajadores sin contrato. No pagan impuestos ni tienen salud ni pension. Es un desafio para el desarrollo economico."),
    Q("Por que es importante diversificar la economia colombiana?",
      [("A) Para depender de un solo producto", "Incorrecto."),
       ("B) Para no depender solo de recursos naturales como el petroleo y el carbon, y generar empleos en otros sectores", "Correcto."),
       ("C) Para no vender al exterior", "Incorrecto."),
       ("D) Para no tener industria", "Incorrecto.")],
      "B", "Diversificar la economia significa no depender de un solo producto. Colombia busca fortalecer la industria, la tecnologia, el turismo y los servicios para crecer de forma sostenible.", d="D4"),
])

# W40: Repaso Integral Anual
wb("W40", "repaso-integral-anual", "Repaso integral anual de Sociales y Ciudadanas Grado 5", [
    Q("Cual es el oceano mas grande del mundo?",
      [("A) Atlantico", "Incorrecto."),
       ("B) Pacifico", "Correcto. Es el mas grande y profundo."),
       ("C) Indico", "Incorrecto."),
       ("D) Artico", "Incorrecto.")],
      "B", "El oceano Pacifico es el mayor del mundo. Colombia tiene costa sobre este oceano en el Pacifico y sobre el Atlantico (Mar Caribe)."),
    Q("Cuales son los puntos cardinales?",
      [("A) Derecha e izquierda", "Incorrecto."),
       ("B) Norte, Sur, Este y Oeste", "Correcto."),
       ("C) Arriba y abajo", "Incorrecto."),
       ("D) Cerca y lejos", "Incorrecto.")],
      "B", "Los puntos cardinales son 4: Norte (N), Sur (S), Este (E) y Oeste (O). Sirven para orientarse en el espacio."),
    Q("Cuantas cordilleras tiene Colombia?",
      [("A) 2", "Incorrecto."),
       ("B) 3", "Correcto. Occidental, Central y Oriental."),
       ("C) 4", "Incorrecto."),
       ("D) 1", "Incorrecto.")],
      "B", "Los Andes se dividen en Colombia en tres cordilleras: Occidental, Central y Oriental, formando valles como el del Magdalena y el Cauca."),
    Q("Cuantas regiones naturales tiene Colombia?",
      [("A) 4", "Incorrecto."),
       ("B) 6", "Correcto. Andina, Caribe, Pacifica, Orinoquia, Amazonia e Insular."),
       ("C) 5", "Incorrecto."),
       ("D) 3", "Incorrecto.")],
      "B", "Colombia tiene 6 regiones naturales: Andina (cordilleras), Caribe (costa norte), Pacifica (costa oeste), Orinoquia (llanos), Amazonia (selva) e Insular (islas)."),
    Q("Quien lidero la Campana Libertadora que culmino en la Batalla de Boyaca?",
      [("A) Francisco de Paula Santander", "Incorrecto."),
       ("B) Simon Bolivar", "Correcto."),
       ("C) Jose de San Martin", "Incorrecto."),
       ("D) Antonio Narino", "Incorrecto.")],
      "B", "Simon Bolivar lidero la Campana Libertadora desde los Llanos, cruzo los Andes y derroto a los espanoles en la Batalla de Boyaca (7 de agosto de 1819)."),
    Q("En que ano Colombia logro su independencia definitiva?",
      [("A) 1810", "Incorrecto. Ese ano fue el grito de independencia."),
       ("B) 1819", "Correcto. La Batalla de Boyaca aseguro la independencia."),
       ("C) 1821", "Incorrecto."),
       ("D) 1886", "Incorrecto.")],
      "B", "El 7 de agosto de 1819, Simon Bolivar derroto al ejercito realista en el Puente de Boyaca. Esta fecha se celebra como Dia de la Independencia de Colombia."),
    Q("Que fue el Frente Nacional?",
      [("A) Un periodo de guerra", "Incorrecto."),
       ("B) Un pacto entre liberales y conservadores para alternarse la presidencia (1958-1974)", "Correcto."),
       ("C) Un partido politico nuevo", "Incorrecto."),
       ("D) Una dictadura", "Incorrecto.")],
      "B", "El Frente Nacional alterno el poder entre liberales y conservadores para pacificar el pais, pero excluyo a otros movimientos politicos."),
    Q("En que ano se promulgo la actual Constitucion de Colombia?",
      [("A) 1991", "Correcto."),
       ("B) 1886", "Incorrecto."),
       ("C) 1810", "Incorrecto."),
       ("D) 2000", "Incorrecto.")],
      "A", "La Constitucion de 1991 reemplazo a la de 1886. Es la ley de leyes de Colombia."),
    Q("Compara las culturas precolombinas Tairona y Muisca: como se diferenciaban?",
      [("A) Eran iguales", "Incorrecto."),
       ("B) Los Taironas vivian en la Sierra Nevada y construian terrazas de piedra; los Muiscas vivian en el Altiplano Cundiboyacense y eran expertos orfebres", "Correcto."),
       ("C) No existieron", "Incorrecto."),
       ("D) Ambas vivian en la Amazonia", "Incorrecto.")],
      "B", "Los Taironas habitaron la Sierra Nevada de Santa Marta con avanzada ingenieria en piedra. Los Muiscas habitaron el altiplano y crearon la leyenda de El Dorado.", d="D4"),
    Q("Por que es importante estudiar Ciencias Sociales?",
      [("A) Para memorizar fechas", "Incorrecto."),
       ("B) Para entender nuestra historia, el funcionamiento de la sociedad, los derechos y deberes, y formar ciudadanos criticos y participativos", "Correcto."),
       ("C) No es importante", "Incorrecto."),
       ("D) Solo para pasar examenes", "Incorrecto.")],
      "B", "Las Ciencias Sociales nos ensenan de donde venimos, como funciona la sociedad, cuales son nuestros derechos y deberes, y nos preparan para ser ciudadanos activos y responsables.", d="D4"),
])

print("W36-W40 done!")
