#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate W06-W09 bundles."""

import os, sys, importlib.util
BASE = "E:/scripts-python/worldexams/questions_data/colombia/sociales-ciudadanas/grado-5/2026/weekly"
spec = importlib.util.spec_from_file_location("mod", os.path.join(BASE, "gen_w10_w11.py"))
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)
make_bundle, Q = mod.make_bundle, mod.Q

def wb(week, tema, rubric, qs):
    fname = "CO-SOC-5-2026-%s-%s-001-MASTERY.md" % (week, tema)
    with open(os.path.join(BASE, fname), "w", encoding="utf-8") as f:
        f.write(make_bundle(week, tema, rubric, qs))
    print("Wrote %s" % fname)

# W06: Relieve de Colombia
wb("W06", "relieve-colombia", "Relieve colombiano: cordilleras, valles, llanuras y montanas", [
    Q("En cuantas cordilleras se divide la cordillera de los Andes en Colombia?",
      [("A) 2", "Incorrecto."),
       ("B) 3", "Correcto. Occidental, Central y Oriental."),
       ("C) 4", "Incorrecto."),
       ("D) 1", "Incorrecto.")],
      "B", "Los Andes se dividen en Colombia en tres cordilleras: Occidental, Central y Oriental. Entre ellas se forman los valles de los rios Magdalena y Cauca."),
    Q("Que cordillera es la mas alta de Colombia?",
      [("A) Occidental", "Incorrecto."),
       ("B) Central", "Correcto. Alli estan los picos mas altos."),
       ("C) Oriental", "Incorrecto."),
       ("D) Ninguna", "Incorrecto.")],
      "B", "La Cordillera Central tiene los picos mas altos de Colombia, incluyendo los nevados del Ruiz, Santa Isabel y Tolima."),
    Q("Cual es la montana mas alta de Colombia?",
      [("A) Nevado del Ruiz", "Incorrecto."),
       ("B) Pico Simon Bolivar (Sierra Nevada de Santa Marta)", "Correcto. Con 5.775 m."),
       ("C) Cerro de Monserrate", "Incorrecto."),
       ("D) Volcan Galeras", "Incorrecto.")],
      "B", "El pico mas alto de Colombia es el Pico Simon Bolivar en la Sierra Nevada de Santa Marta (5.775 m), seguido por el Pico Colon. No estan en los Andes sino en una sierra aislada."),
    Q("Que es un valle en el relieve colombiano?",
      [("A) Una montana muy alta", "Incorrecto."),
       ("B) Una depresion entre montanas por donde suele correr un rio", "Correcto."),
       ("C) Un desierto", "Incorrecto."),
       ("D) Una llanura costera", "Incorrecto.")],
      "B", "Los valles interandinos mas importantes son el Valle del Magdalena (entre las cordilleras Central y Oriental) y el Valle del Cauca (entre las cordilleras Occidental y Central)."),
    Q("Donde se encuentran las llanuras en Colombia?",
      [("A) Solo en la Costa Pacifica", "Incorrecto."),
       ("B) En la Costa Caribe, los Llanos Orientales y la Amazonia", "Correcto."),
       ("C) Solo en Bogota", "Incorrecto."),
       ("D) Solo en la Sierra Nevada", "Incorrecto.")],
      "B", "Las llanuras colombianas incluyen: la llanura del Caribe (al norte), los Llanos Orientales (Orinoquia) y la llanura amazonica (al sur). Son zonas planas o de suaves colinas."),
    Q("Que es la Sierra Nevada de Santa Marta?",
      [("A) Una cordillera de los Andes", "Incorrecto."),
       ("B) Una formacion montanosa aislada cerca del mar Caribe, la mas alta del pais", "Correcto."),
       ("C) Un valle", "Incorrecto."),
       ("D) Una llanura", "Incorrecto.")],
      "B", "La Sierra Nevada de Santa Marta es una formacion montanosa independiente de los Andes, ubicada en la costa Caribe. Tiene los picos mas altos de Colombia."),
    Q("Que es el nudo de los Pastos?",
      [("A) Un baile tipico", "Incorrecto."),
       ("B) Una region montanosa en Narino donde los Andes se dividen en tres cordilleras", "Correcto."),
       ("C) Un rio", "Incorrecto."),
       ("D) Una ciudad", "Incorrecto.")],
      "B", "El Nudo de los Pastos, en el departamento de Narino (sur de Colombia), es el punto donde la Cordillera de los Andes se divide en las tres cordilleras colombianas."),
    Q("Que rio separa las cordilleras Central y Oriental?",
      [("A) Rio Cauca", "Incorrecto. Separa la Occidental de la Central."),
       ("B) Rio Magdalena", "Correcto."),
       ("C) Rio Amazonas", "Incorrecto."),
       ("D) Rio Orinoco", "Incorrecto.")],
      "B", "El rio Magdalena es el principal rio de Colombia. Corre de sur a norte entre las cordilleras Central y Oriental, hasta desembocar en el mar Caribe."),
    Q("Por que Colombia tiene un relieve tan variado?",
      [("A) Porque es un pais muy grande", "Incorrecto."),
       ("B) Por la presencia de tres cordilleras, llanuras, valles, sierras y costas en ambos oceanos", "Correcto."),
       ("C) Porque tiene muchos rios", "Incorrecto."),
       ("D) Porque esta en el centro del mundo", "Incorrecto.")],
      "B", "Colombia tiene un relieve diverso gracias a la presencia de los Andes en tres cordilleras, los valles interandinos, las llanuras del Caribe y los Llanos, la Sierra Nevada y las costas en dos oceanos.", d="D3"),
    Q("Como afecta el relieve a la vida de los colombianos?",
      [("A) No afecta", "Incorrecto."),
       ("B) El relieve determina el clima, los cultivos, el transporte y la distribucion de la poblacion", "Correcto."),
       ("C) Solo afecta a los agricultores", "Incorrecto."),
       ("D) Solo afecta el turismo", "Incorrecto.")],
      "B", "El relieve influye en todos los aspectos: en las montanas hace mas frio, se cultiva cafe y papa; en las llanuras hace calor y se cultiva arroz y ganado. Las montanas dificultan el transporte.", d="D4"),
])

# W07: Hidrografia de Colombia
wb("W07", "hidrografia-colombia", "Hidrografia de Colombia: principales rios y cuencas hidrograficas", [
    Q("Cual es el rio mas largo e importante de Colombia?",
      [("A) Rio Amazonas", "Incorrecto. Solo una pequena parte esta en Colombia."),
       ("B) Rio Magdalena", "Correcto. Navegable y vertebra el pais."),
       ("C) Rio Cauca", "Incorrecto. Es el segundo en importancia."),
       ("D) Rio Orinoco", "Incorrecto.")],
      "B", "El rio Magdalena nace en la Laguna de la Magdalena (Huila) y recorre 1.540 km hasta el mar Caribe. Es navegable y ha sido historica y economicamente vital."),
    Q("En que oceano desembocan la mayoria de los rios de Colombia?",
      [("A) Oceano Pacifico", "Incorrecto."),
       ("B) Mar Caribe (Atlantico)", "Correcto. La mayoria desemboca en el Caribe."),
       ("C) Oceano Indico", "Incorrecto."),
       ("D) Oceano Artico", "Incorrecto.")],
      "B", "Los rios colombianos desembocan principalmente en el mar Caribe (Magdalena, Cauca, Sinu, Atrato, Rancheria) y en el Pacifico (San Juan, Patia, Mira). Algunos van al Amazonas y al Orinoco."),
    Q("A que cuenca hidrografica pertenece el rio Amazonas en Colombia?",
      [("A) Cuenca del Pacifico", "Incorrecto."),
       ("B) Cuenca del Caribe", "Incorrecto."),
       ("C) Cuenca del Amazonas", "Correcto."),
       ("D) Cuenca del Orinoco", "Incorrecto.")],
      "C", "La cuenca del Amazonas en Colombia incluye rios como el Caqueta, Putumayo y el Amazonas mismo. Es una region de selva tropical, muy biodiversa."),
    Q("Cuales son los principales rios de la cuenca del Orinoco en Colombia?",
      [("A) Magdalena y Cauca", "Incorrecto."),
       ("B) Meta, Guaviare y Arauca", "Correcto. Desembocan en el Orinoco."),
       ("C) Sinu y Atrato", "Incorrecto. Van al Caribe."),
       ("D) San Juan y Patia", "Incorrecto. Van al Pacifico.")],
      "B", "Los Llanos Orientales son parte de la cuenca del Orinoco. Los rios Meta, Guaviare, Arauca y Vichada fluyen hacia Venezuela para unirse al rio Orinoco."),
    Q("Que es una cuenca hidrografica?",
      [("A) Un recipiente para el agua", "Incorrecto."),
       ("B) El territorio drenado por un rio principal y sus afluentes", "Correcto."),
       ("C) Una montana", "Incorrecto."),
       ("D) Un lago", "Incorrecto.")],
      "B", "Una cuenca hidrografica es el area donde toda el agua que cae (lluvia) escurre hacia un mismo rio principal. Colombia tiene 5 grandes cuencas: Caribe, Pacifico, Amazonas, Orinoco y Catatumbo."),
    Q("Por que son importantes los rios para las comunidades colombianas?",
      [("A) Solo para pescar", "Incorrecto."),
       ("B) Para transporte, agricultura, generacion de energia, pesca y consumo humano", "Correcto."),
       ("C) Solo para turismo", "Incorrecto."),
       ("D) No son importantes", "Incorrecto.")],
      "B", "Los rios son vitales: el Magdalena es una via de transporte, los rios generan energia hidroelectrica, el agua se usa para regar cultivos y para el consumo de las poblaciones."),
    Q("Que es el rio Atrato y donde nace?",
      [("A) Nace en la Sierra Nevada y va al Caribe", "Correcto. Nace en el Cerro Plateado (Choco)."),
       ("B) Nace en los Andes", "Incorrecto."),
       ("C) Nace en la Amazonia", "Incorrecto."),
       ("D) Nace en los Llanos", "Incorrecto.")],
      "A", "El rio Atrato nace en el Cerro Plateado (Choco) y desemboca en el Golfo de Uraba (Caribe). Es navegable y muy caudaloso, en una de las regiones mas lluviosas del mundo."),
    Q("Que es la Laguna de la Cocha?",
      [("A) Un lago en la costa", "Incorrecto."),
       ("B) Una laguna en Narino, la mas grande de Colombia", "Correcto."),
       ("C) Un rio", "Incorrecto."),
       ("D) Un mar", "Incorrecto.")],
      "B", "La Laguna de la Cocha, en Narino, es la laguna natural mas grande de Colombia. Es un sitio sagrado para los indigenas y una reserva natural."),
    Q("Por que Colombia tiene tantos rios?",
      [("A) Porque es un pais pequeno", "Incorrecto."),
       ("B) Por las altas precipitaciones en casi todo el pais y la presencia de montanas que generan escorrentia", "Correcto."),
       ("C) Por la sequia", "Incorrecto."),
       ("D) Porque no hay montanas", "Incorrecto.")],
      "B", "Colombia es uno de los paises mas lluviosos del mundo. Las montanas hacen que el agua escurra formando innumerables rios. Hay 5 grandes cuencas hidrograficas.", d="D3"),
    Q("Como se relacionan el relieve y la hidrografia de Colombia?",
      [("A) No se relacionan", "Incorrecto."),
       ("B) Las montanas determinan la direccion de los rios y crean valles fertiles", "Correcto."),
       ("C) Los rios crean las montanas", "Incorrecto."),
       ("D) Los rios solo corren por las llanuras", "Incorrecto.")],
      "B", "El relieve determina la hidrografia: las cordilleras separan las cuencas, los valles concentran los rios principales (Magdalena, Cauca), y las llanuras permiten la formacion de rios lentos y meandros.", d="D4"),
])

# W08: Climas y Pisos Termicos
wb("W08", "climas-pisos-termicos", "Climas y pisos termicos en Colombia: relaciones clima-altitud", [
    Q("Por que Colombia tiene clima calido en la mayor parte del territorio?",
      [("A) Porque esta lejos del Ecuador", "Incorrecto."),
       ("B) Porque esta cerca de la linea del Ecuador", "Correcto. Recibe luz solar directa."),
       ("C) Porque tiene muchos rios", "Incorrecto."),
       ("D) Porque esta en el hemisferio norte", "Incorrecto.")],
      "B", "Colombia esta ubicada en la zona tropical, cerca de la linea del Ecuador (latitud 0). Por eso recibe luz solar intensa todo el ano, dando temperaturas altas en zonas bajas."),
    Q("Que es un piso termico?",
      [("A) Un tipo de clima caliente", "Incorrecto."),
       ("B) Una zona climatica determinada por la altitud", "Correcto."),
       ("C) Un rio caliente", "Incorrecto."),
       ("D) Una montana", "Incorrecto.")],
      "B", "Los pisos termicos son franjas climaticas que cambian con la altitud. Al subir una montana, la temperatura baja. En Colombia hay 5 pisos: calido, templado, frio, paramo y nieves perpetuas."),
    Q("Cual es el piso termico de las tierras bajas (0-1.000 m)?",
      [("A) Frio", "Incorrecto."),
       ("B) Calido", "Correcto. Temperaturas superiores a 24 grados."),
       ("C) Templado", "Incorrecto."),
       ("D) Paramo", "Incorrecto.")],
      "B", "El piso calido (0 a 1.000 m de altitud) tiene temperaturas superiores a 24 grados. Alli se cultivan banano, arroz, yuca y cacao. Incluye las costas y llanuras."),
    Q("A que altitud se encuentra el piso templado?",
      [("A) 0-1.000 m", "Incorrecto. Ese es calido."),
       ("B) 1.000-2.000 m", "Correcto. Temperaturas entre 18 y 24 grados."),
       ("C) 2.000-3.000 m", "Incorrecto. Ese es frio."),
       ("D) Mas de 4.000 m", "Incorrecto.")],
      "B", "El piso templado (1.000 a 2.000 m) tiene temperaturas entre 18 y 24 grados. Es ideal para el cultivo de cafe. Ciudades como Medellin y Pereira estan en este piso."),
    Q("Que ciudades colombianas estan en el piso frio?",
      [("A) Cartagena y Barranquilla", "Incorrecto. Estan en calido."),
       ("B) Bogota, Tunja y Pasto", "Correcto. Entre 2.000 y 3.000 m."),
       ("C) Medellin y Cali", "Incorrecto."),
       ("D) Leticia y Mitu", "Incorrecto.")],
      "B", "El piso frio (2.000 a 3.000 m) tiene temperaturas entre 12 y 18 grados. Bogota (2.600 m) esta alli. Se cultiva papa, trigo y hortalizas."),
    Q("Que es el paramo?",
      [("A) Un desierto", "Incorrecto."),
       ("B) Un ecosistema de alta montana, entre 3.000 y 4.000 m, con vegetacion de frailejones", "Correcto."),
       ("C) Una selva", "Incorrecto."),
       ("D) Una llanura", "Incorrecto.")],
      "B", "El paramo es un ecosistema unico de alta montana tropical. Tiene frailejones y temperaturas entre 0 y 12 grados. Es crucial porque almacena y regula el agua."),
    Q("Por que los paramos son importantes para Colombia?",
      [("A) No son importantes", "Incorrecto."),
       ("B) Porque almacenan agua y la liberan lentamente, abasteciendo acueductos y rios", "Correcto."),
       ("C) Porque son desiertos", "Incorrecto."),
       ("D) Porque tienen mucho petroleo", "Incorrecto.")],
      "B", "Los paramos son las 'fabricas de agua' de Colombia. Almacenan la lluvia y la niebla y la liberan gradualmente. Abastecen de agua a la mayoria de las ciudades."),
    Q("Que son las nieves perpetuas?",
      [("A) Montanas bajas", "Incorrecto."),
       ("B) Zonas por encima de 4.700 m donde la nieve nunca se derrite", "Correcto."),
       ("C) Lagos congelados", "Incorrecto."),
       ("D) Desiertos frios", "Incorrecto.")],
      "B", "Las nieves perpetuas estan en los picos mas altos (mas de 4.700 m), como los nevados del Ruiz, Santa Isabel, Tolima y la Sierra Nevada de Santa Marta."),
    Q("Como afecta el cambio climatico a los pisos termicos en Colombia?",
      [("A) No los afecta", "Incorrecto."),
       ("B) El calentamiento global esta derritiendo los nevados y alterando los ecosistemas de paramo", "Correcto."),
       ("C) Los pisos termicos suben de altitud", "Incorrecto."),
       ("D) Los pisos termicos desaparecen", "Incorrecto.")],
      "B", "El cambio climatico esta causando el retroceso de los nevados colombianos (varios han desaparecido) y afecta los paramos, poniendo en riesgo el agua para millones de personas.", d="D3"),
    Q("Por que la ubicacion de Colombia cerca del Ecuador y su relieve diverso crean climas variados?",
      [("A) No crean variedad", "Incorrecto."),
       ("B) El Ecuador da calor constante; las montanas generan pisos termicos con climas frios y paramos; asi conviven todos los climas", "Correcto."),
       ("C) Solo hay un clima", "Incorrecto."),
       ("D) Depende solo de las lluvias", "Incorrecto.")],
      "B", "Colombia tiene todos los pisos termicos: desde el calido en las costas y llanuras hasta el frio y paramo en las montanas. Esto permite cultivar desde banano hasta papa, y tener ecosistemas diversos.", d="D4"),
])

# W09: Regiones Naturales de Colombia
wb("W09", "regiones-naturales", "Regiones naturales de Colombia: Andina, Caribe y Pacifica", [
    Q("Cuantas regiones naturales tiene Colombia?",
      [("A) 4", "Incorrecto."),
       ("B) 6", "Correcto. Andina, Caribe, Pacifica, Orinoquia, Amazonia e Insular."),
       ("C) 5", "Incorrecto."),
       ("D) 3", "Incorrecto.")],
      "B", "Colombia se divide en 6 regiones naturales segun su relieve, clima y ecosistemas: Andina (montanas), Caribe (costa norte), Pacifica (costa oeste), Orinoquia (llanos), Amazonia (selva) e Insular (islas)."),
    Q("Que caracteriza a la region Andina?",
      [("A) Las llanuras", "Incorrecto."),
       ("B) Las tres cordilleras, valles interandinos y la mayoria de la poblacion", "Correcto."),
       ("C) La selva amazonica", "Incorrecto."),
       ("D) Las playas del Caribe", "Incorrecto.")],
      "B", "La region Andina es la mas poblada de Colombia. Incluye las cordilleras Occidental, Central y Oriental, los valles del Magdalena y Cauca. Alli estan Bogota, Medellin, Cali."),
    Q("Que region natural incluye la costa norte de Colombia?",
      [("A) Region Pacifica", "Incorrecto."),
       ("B) Region Caribe", "Correcto. Bana el mar Caribe."),
       ("C) Region Andina", "Incorrecto."),
       ("D) Region Insular", "Incorrecto.")],
      "B", "La region Caribe abarca la costa norte colombiana, desde el Golfo de Uraba hasta la peninsula de La Guajira. Incluye ciudades como Barranquilla, Cartagena y Santa Marta."),
    Q("Cual es el clima de la region Caribe?",
      [("A) Frio todo el ano", "Incorrecto."),
       ("B) Calido y seco, con temporada de lluvias", "Correcto. Temperaturas altas."),
       ("C) Paramo", "Incorrecto."),
       ("D) Nevada", "Incorrecto.")],
      "B", "La region Caribe tiene clima calido con temperaturas promedio de 28 grados. Tiene una temporada seca (diciembre a abril) y una lluviosa. En La Guajira es muy seco (desierto)."),
    Q("Donde se encuentra la region Pacifica colombiana?",
      [("A) En la costa del Caribe", "Incorrecto."),
       ("B) En la costa occidental, bordeando el oceano Pacifico", "Correcto."),
       ("C) En los Llanos Orientales", "Incorrecto."),
       ("D) En la Amazonia", "Incorrecto.")],
      "B", "La region Pacifica se extiende desde Panama hasta Ecuador, bordeando el oceano Pacifico. Incluye los departamentos de Choco, Valle, Cauca y Narino."),
    Q("Que caracteriza a la region Pacifica?",
      [("A) Es seca y desertica", "Incorrecto."),
       ("B) Es una de las regiones mas lluviosas del mundo, con selva tropical y rios caudalosos", "Correcto."),
       ("C) Es fria y montanosa", "Incorrecto."),
       ("D) Es una llanura", "Incorrecto.")],
      "B", "La region Pacifica es extremadamente lluviosa (hasta 12.000 mm anuales). Tiene manglares, selvas y rios como el Atrato y San Juan. Es rica en biodiversidad."),
    Q("Que grupos humanos habitan la region Pacifica?",
      [("A) Solo indigenas", "Incorrecto."),
       ("B) Comunidades afrocolombianas (mayoria) e indigenas como los Embera y Wounaan", "Correcto."),
       ("C) Solo mestizos", "Incorrecto."),
       ("D) Solo colonos", "Incorrecto.")],
      "B", "La region Pacifica tiene una fuerte herencia afrocolombiana. Tambien habitan pueblos indigenas como los Embera, Wounaan y Tule. Es conocida por su cultura, musica y tradiciones."),
    Q("Que actividad economica predomina en la region Caribe?",
      [("A) La mineria", "Incorrecto."),
       ("B) La ganaderia, la agricultura (banano, arroz) y el turismo", "Correcto."),
       ("C) La pesca de alta mar", "Incorrecto."),
       ("D) La tecnologia", "Incorrecto.")],
      "B", "La region Caribe se destaca por la ganaderia vacuna, el cultivo de banano (Uraba), arroz, algodon y el turismo en Cartagena y Santa Marta."),
    Q("Por que la region Andina es la mas poblada?",
      [("A) Porque tiene el mejor clima", "Incorrecto."),
       ("B) Porque tiene condiciones favorables para la agricultura y la vida humana, y alli se concentra la historia y economia", "Correcto."),
       ("C) Porque es la mas grande", "Incorrecto."),
       ("D) Porque es la mas lluviosa", "Incorrecto.")],
      "B", "La region Andina concentra el 70% de la poblacion. Tiene clima templado en muchas zonas, suelos fertiles, las principales ciudades (Bogota, Medellin, Cali) y la mayor actividad economica.", d="D3"),
    Q("Como se diferencian las regiones Caribe y Pacifica?",
      [("A) Son iguales", "Incorrecto."),
       ("B) Caribe: calida, seca, ganadera y turistica. Pacifica: lluviosa, selvatuca, afrocolombiana y minera", "Correcto."),
       ("C) Caribe: lluviosa. Pacifica: seca.", "Incorrecto."),
       ("D) Ambas son igual de lluviosas", "Incorrecto.")],
      "B", "La region Caribe es mas seca, con playas y ganaderia. La Pacifica es muy lluviosa, con selva, manglares y fuerte presencia afrocolombiana. Ambas son costeras pero muy diferentes en clima y cultura.", d="D4"),
])

print("W06-W09 done!")
