#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate W21-W30 bundles."""

import os, sys
BASE = "E:/scripts-python/worldexams/questions_data/colombia/sociales-ciudadanas/grado-5/2026/weekly"
sys.path.insert(0, BASE)

# Re-import helpers
from gen_w10_w11 import make_bundle, Q
import importlib.util
spec = importlib.util.spec_from_file_location("mod", os.path.join(BASE, "gen_w10_w11.py"))
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)
make_bundle = mod.make_bundle
Q = mod.Q

def wb(week, tema, rubric, qs):
    fname = "CO-SOC-5-2026-%s-%s-001-MASTERY.md" % (week, tema)
    with open(os.path.join(BASE, fname), "w", encoding="utf-8") as f:
        f.write(make_bundle(week, tema, rubric, qs))
    print("Wrote %s" % fname)

# W21: Independencia de Colombia
wb("W21", "independencia-colombia", "Independencia: 1810, El Florero de Llorente, primeras juntas", [
    Q("En que ano comenzo el proceso de independencia de Colombia?",
      [("A) 1800", "Incorrecto."),
       ("B) 1810", "Correcto. El 20 de julio de 1810."),
       ("C) 1819", "Incorrecto. Ese ano se dio la independencia definitiva en Boyaca."),
       ("D) 1820", "Incorrecto.")],
      "B", "El 20 de julio de 1810 es la fecha de la independencia de Colombia. Ese dia ocurrio el incidente del Florero de Llorente que desato el grito de independencia."),
    Q("Que hecho detono el grito de independencia del 20 de julio de 1810?",
      [("A) La muerte de Simon Bolivar", "Incorrecto. Bolivar murio despues."),
       ("B) El incidente del Florero de Llorente", "Correcto. Un prestamo de florero que no fue devuelto."),
       ("C) La llegada de los espanoles", "Incorrecto."),
       ("D) La firma de la Constitucion", "Incorrecto.")],
      "B", "El 20 de julio de 1810, los criollos organizaron un incidente con el comerciante espanol Jose Gonzalez Llorente para provocar un tumulto y formar una junta de gobierno."),
    Q("Quien fue el principal lider del grito de independencia en Bogota?",
      [("A) Simon Bolivar", "Incorrecto. Estaba en el exterior."),
       ("B) Antonio Narino", "Correcto. Fue lider del movimiento independentista."),
       ("C) Francisco de Paula Santander", "Incorrecto. Fue lider militar despues."),
       ("D) Jose Maria Obando", "Incorrecto.")],
      "B", "Antonio Narino fue uno de los principales lideres. Tradujo los Derechos del Hombre y fue precursor de la independencia. Sufrio prision por sus ideas."),
    Q("Que eran las 'juntas de gobierno' de 1810?",
      [("A) Reuniones de espanoles para reprimir a los criollos", "Incorrecto."),
       ("B) Gobiernos locales creados por los criollos para gobernar mientras el rey de Espana estaba preso", "Correcto."),
       ("C) Escuelas de gobierno", "Incorrecto."),
       ("D) Tribunales militares", "Incorrecto.")],
      "B", "Al estar Napoleon invadiendo Espana y el rey Fernando VII preso, los criollos formaron juntas de gobierno para gobernar 'en nombre del rey', aunque realmente buscaban autonomia."),
    Q("Como se llamo el periodo de 1810 a 1816 en Colombia?",
      [("A) La Gran Colombia", "Incorrecto. Fue de 1819-1830."),
       ("B) La Patria Boba", "Correcto. Periodo de conflictos internos entre centralistas y federalistas."),
       ("C) El Frente Nacional", "Incorrecto."),
       ("D) La Republica Liberal", "Incorrecto.")],
      "B", "La Patria Boba (1810-1816) fue un periodo de division entre los lideres independentistas: centralistas (liderados por Narino) y federalistas (liderados por Camilo Torres)."),
    Q("Que espanol lidero la reconquista de la Nueva Granada (1815-1816)?",
      [("A) Hernan Cortes", "Incorrecto."),
       ("B) Pablo Morillo", "Correcto. Lidero la Reconquista espanola."),
       ("C) Francisco Pizarro", "Incorrecto."),
       ("D) Diego de Losada", "Incorrecto.")],
      "B", "Pablo Morillo, llamado 'El Pacificador', llego desde Espana con un ejercito para reconquistar el virreinato. Implantio un regimen de terror y ejecuto a muchos lideres independentistas."),
    Q("Que fue la 'Reconquista' espanola?",
      [("A) La expulsion de los indigenas", "Incorrecto."),
       ("B) El intento de Espana por recuperar el control de sus colonias entre 1815 y 1819", "Correcto."),
       ("C) La conquista del Peru", "Incorrecto."),
       ("D) La fundacion de nuevas ciudades", "Incorrecto.")],
      "B", "Tras la caida de Napoleon, el rey Fernando VII recupero el trono y envio a Pablo Morillo a America para someter a los rebeldes. Muchos patriotas fueron ejecutados."),
    Q("Que ideologias politicas enfrentadas caracterizaron la Patria Boba?",
      [("A) Liberales vs Conservadores", "Incorrecto. Eso fue despues."),
       ("B) Centralistas (gobierno fuerte desde Bogota) vs Federalistas (autonomia de provincias)", "Correcto."),
       ("C) Monarquicos vs Republicanos", "Incorrecto."),
       ("D) Socialistas vs Capitalistas", "Incorrecto.")],
      "B", "Los centralistas querian un gobierno fuerte y centralizado en Bogota. Los federalistas querian que cada provincia tuviera autonomia. Esta division debilito la independencia inicial.", d="D4"),
    Q("Por que se llamo 'Patria Boba' a ese periodo?",
      [("A) Porque todos eran felices", "Incorrecto."),
       ("B) Por las disputas internas que impidieron consolidar la independencia y facilitaron la reconquista espanola", "Correcto."),
       ("C) Porque no habia gobierno", "Incorrecto."),
       ("D) Porque los patriotas eran ignorantes", "Incorrecto.")],
      "B", "Se llamo 'Patria Boba' porque mientras los patriotas se peleaban entre si, los espanoles aprovecharon para reconquistar el territorio. Las divisiones internas fueron una leccion dolorosa.", d="D4"),
    Q("Que consecuencias tuvo la Reconquista espanola?",
      [("A) El fin de la Colonia", "Incorrecto."),
       ("B) La ejecucion de muchos lideres patriotas y el restablecimiento del regimen colonial", "Correcto. Pero la llama independentista no se apago."),
       ("C) La independencia definitiva", "Incorrecto."),
       ("D) La expulsion de los espanoles", "Incorrecto.")],
      "B", "Morillo ejecuto a lideres como Camilo Torres, Francisco Jose de Caldas y Policarpa Salavarrieta. Pero en los Llanos Orientales y Venezuela, la resistencia continuaba.", d="D3"),
])

# W22: Campana Libertadora
wb("W22", "campana-libertadora", "Campana Libertadora: Simon Bolivar, Batalla de Boyaca", [
    Q("Quien fue el lider principal de la Campana Libertadora?",
      [("A) Francisco de Paula Santander", "Incorrecto. Fue su lugarteniente."),
       ("B) Simon Bolivar", "Correcto. Fue el Libertador."),
       ("C) Antonio Narino", "Incorrecto."),
       ("D) Jose Antonio Anzoategui", "Incorrecto.")],
      "B", "Simon Bolivar, nacido en Caracas en 1783, fue el lider de la independencia de 5 paises: Venezuela, Colombia, Ecuador, Peru y Bolivia."),
    Q("En que ano y lugar se libro la Batalla de Boyaca?",
      [("A) 1810 en Bogota", "Incorrecto."),
       ("B) 1819 en el puente de Boyaca", "Correcto. Fue el 7 de agosto de 1819."),
       ("C) 1821 en Carabobo", "Incorrecto. Esa fue en Venezuela."),
       ("D) 1824 en Junin", "Incorrecto. Esa fue en Peru.")],
      "B", "La Batalla de Boyaca se libro el 7 de agosto de 1819 en el puente de Boyaca, cerca de Tunja. Fue la victoria decisiva que aseguro la independencia de la Nueva Granada."),
    Q("Que ruta siguio el ejercito libertador antes de la Batalla de Boyaca?",
      [("A) Por el rio Magdalena en barco", "Incorrecto."),
       ("B) Atraveso los Andes por el paramo de Pisba", "Correcto. Una travesia muy dura."),
       ("C) Por la costa Caribe", "Incorrecto."),
       ("D) Por el rio Amazonas", "Incorrecto.")],
      "B", "El ejercito libertador cruzo los Andes desde Venezuela, atravesando el helado paramo de Pisba (Boyaca). Muchos soldados murieron de frio. Luego sorprendieron a los espanoles."),
    Q("Quien fue Francisco de Paula Santander?",
      [("A) El rey de Espana", "Incorrecto."),
       ("B) El general que comando la retaguardia y fue clave en Boyaca", "Correcto."),
       ("C) Un virrey espanol", "Incorrecto."),
       ("D) Un indigena que resistio a los espanoles", "Incorrecto.")],
      "B", "Santander fue el 'Hombre de las Leyes'. Organizo el ejercito y comando la retaguardia en la Campana Libertadora. Despues fue vicepresidente y presidente."),
    Q("Que estrategia uso Bolivar para derrotar a los espanoles?",
      [("A) Ataco directamente Cartagena", "Incorrecto."),
       ("B) La Campana Admirable: ataque sorpresa cruzando los Andes en invierno", "Correcto."),
       ("C) Negocio la rendicion", "Incorrecto."),
       ("D) Espero a que los espanoles se fueran", "Incorrecto.")],
      "B", "La Campana Libertadora fue una operacion militar brillante: cruzar los Andes en pleno invierno fue una maniobra que los espanoles no esperaban, tomandolos por sorpresa."),
    Q("Que paso el 7 de agosto de 1819 en el puente de Boyaca?",
      [("A) Se fundo Bogota", "Incorrecto."),
       ("B) El ejercito patriota derroto al ejercito espanol, asegurando la independencia", "Correcto."),
       ("C) Murio Simon Bolivar", "Incorrecto."),
       ("D) Llegaron los espanoles", "Incorrecto.")],
      "B", "En el puente de Boyaca, el ejercito patriota (liderado por Bolivar y Santander) derroto a las tropas realistas. El virrey huyo y el camino a Bogota quedo libre."),
    Q("Que tropas componian el ejercito libertador?",
      [("A) Solo criollos ricos", "Incorrecto."),
       ("B) Venezolanos, neogranadinos (colombianos), indigenas, mestizos, mulatos y extranjeros (legion britanica)", "Correcto."),
       ("C) Solo espanoles", "Incorrecto."),
       ("D) Soldados franceses", "Incorrecto.")],
      "B", "El ejercito era diverso: venezolanos y colombianos, indigenas, negros, mulatos, zambos y la Legion Britanica (soldados de Inglaterra e Irlanda)."),
    Q("Que fue el 'Congreso de Angostura'?",
      [("A) Una batalla", "Incorrecto."),
       ("B) Un congreso donde se aprobo la creacion de la Gran Colombia", "Correcto. En 1819."),
       ("C) Un tratado de paz", "Incorrecto."),
       ("D) Una ciudad", "Incorrecto.")],
      "B", "En el Congreso de Angostura (Venezuela, 1819), Bolivar propuso la creacion de la Republica de la Gran Colombia, uniendo Venezuela y Nueva Granada."),
    Q("Cual fue el papel de la Legion Britanica en la independencia?",
      [("A) No participo", "Incorrecto."),
       ("B) Soldados britanicos que lucharon junto a Bolivar", "Correcto. Aportaron experiencia y armas."),
       ("C) Espiaba para Espana", "Incorrecto."),
       ("D) Financiaba a los espanoles", "Incorrecto.")],
      "B", "La Legion Britanica eran voluntarios de Inglaterra, Escocia, Irlanda y otros paises europeos que lucharon por la independencia sudamericana."),
    Q("Por que la Batalla de Boyaca es considerada decisiva?",
      [("A) Porque fue la unica batalla", "Incorrecto."),
       ("B) Porque destruyo el poder espanol en la Nueva Granada y permitio la independencia definitiva", "Correcto."),
       ("C) Porque murieron muchos patriotas", "Incorrecto."),
       ("D) Porque fue la mas larga", "Incorrecto.")],
      "B", "En solo dos horas, el ejercito patriota capturo a los jefes espanoles, al ejercito realista y todo su armamento. El poder espanol en la region colapso.", d="D4"),
])

# W23: La Gran Colombia
wb("W23", "gran-colombia", "La Gran Colombia: creacion, territorio, disolucion", [
    Q("Que fue la Gran Colombia?",
      [("A) Un pais centroamericano", "Incorrecto."),
       ("B) Una republica que unio Venezuela, Nueva Granada y Ecuador (1819-1830)", "Correcto."),
       ("C) Un virreinato espanol", "Incorrecto."),
       ("D) Una ciudad colonial", "Incorrecto.")],
      "B", "La Gran Colombia fue creada por Simon Bolivar en 1819 e incluia los actuales Colombia, Venezuela, Ecuador y Panama. Su capital era Bogota."),
    Q("Quien fue el primer presidente de la Gran Colombia?",
      [("A) Francisco de Paula Santander", "Incorrecto. Fue vicepresidente."),
       ("B) Simon Bolivar", "Correcto. Fue el presidente."),
       ("C) Jose Antonio Paez", "Incorrecto. Fue lider en Venezuela."),
       ("D) Juan Jose Flores", "Incorrecto.")],
      "B", "Bolivar fue presidente de la Gran Colombia, y Santander fue vicepresidente encargado del gobierno en Bogota mientras Bolivar continuaba las campanas militares."),
    Q("Cuales eran los departamentos de la Gran Colombia?",
      [("A) Solo Bogota y Caracas", "Incorrecto."),
       ("B) Cundinamarca (Nueva Granada), Venezuela y Quito (Ecuador)", "Correcto. Divididos en departamentos."),
       ("C) Norte, Sur, Centro", "Incorrecto."),
       ("D) Amazonas, Andes, Caribe", "Incorrecto.")],
      "B", "La Gran Colombia se dividio en tres grandes departamentos: Cundinamarca (Nueva Granada), Venezuela (con capital en Caracas) y Quito (Ecuador). Despues se subdividieron."),
    Q("Por que se disolvio la Gran Colombia?",
      [("A) Porque era muy pequena", "Incorrecto."),
       ("B) Por conflictos regionales, luchas de poder y diferencias politicas entre centralistas y federalistas", "Correcto."),
       ("C) Por una invasion extranjera", "Incorrecto."),
       ("D) Por un terremoto", "Incorrecto.")],
      "B", "La Gran Colombia se disolvio en 1830 por: el regionalismo (Venezuela queria su propio gobierno), las diferencias politicas (centralismo vs federalismo) y la crisis de liderazgo."),
    Q("Que queria Simon Bolivar para America?",
      [("A) Dividir Sudamerica en muchos paises pequenos", "Incorrecto."),
       ("B) Unir las naciones hispanoamericanas en una gran federacion", "Correcto. Su sueno integracionista."),
       ("C) Que todo fuera parte de Espana otra vez", "Incorrecto."),
       ("D) Que el Caribe fuera el centro del mundo", "Incorrecto.")],
      "B", "Bolivar suenaba con una gran confederacion de naciones hispanoamericanas unidas. La Gran Colombia fue el primer paso, pero los conflictos internos impidieron concretar su sueno."),
    Q("Quien lidero la separacion de Venezuela de la Gran Colombia?",
      [("A) Simon Bolivar", "Incorrecto. El queria mantener la union."),
       ("B) Jose Antonio Paez", "Correcto. Lider militar venezolano."),
       ("C) Francisco de Paula Santander", "Incorrecto. El era de Nueva Granada."),
       ("D) Antonio Jose de Sucre", "Incorrecto. Apoyaba la union.")],
      "B", "Jose Antonio Paez lidero el movimiento separatista en Venezuela. Los caudillos regionales querian el poder local y no aceptaban la autoridad central de Bogota."),
    Q("Que paso con el proyecto de la Gran Colombia?",
      [("A) Fracaso y se disolvio en 1830", "Correcto. Venezuela y Ecuador se separaron."),
       ("B) Sigue existiendo hoy", "Incorrecto."),
       ("C) Se expandio hasta Estados Unidos", "Incorrecto."),
       ("D) Cambio de nombre pero siguio unida", "Incorrecto.")],
      "A", "En 1830, Venezuela y Ecuador se separaron. La Nueva Granada (hoy Colombia y Panama) continuo como un pais independiente. Bolivar murio ese mismo ano."),
    Q("Que territorio actual formo parte de la Gran Colombia?",
      [("A) Colombia, Venezuela, Ecuador, Panama y partes de Peru y Brasil", "Correcto."),
       ("B) Solo Colombia", "Incorrecto."),
       ("C) Colombia y Peru", "Incorrecto."),
       ("D) Centroamerica", "Incorrecto.")],
      "A", "La Gran Colombia incluia los actuales Colombia, Venezuela, Ecuador, Panama, y partes de Peru (norte) y Brasil (oeste). Era uno de los paises mas grandes de America."),
    Q("Compara el proyecto de la Gran Colombia con la situacion actual: cual afirmacion es correcta?",
      [("A) La Gran Colombia sobrevive hoy", "Incorrecto."),
       ("B) La Gran Colombia fue un intento de integracion que fracaso por el regionalismo, pero inspira procesos como la UNASUR", "Correcto."),
       ("C) La disolucion fue pacifica", "Incorrecto."),
       ("D) Todos los paises quieren reunificarse", "Incorrecto.")],
      "B", "La Gran Colombia fue un sueno integracionista que fracaso por el regionalismo y las diferencias politicas. Hoy, la Union de Naciones Suramericanas busca objetivos similares.", d="D4"),
    Q("Cual fue el legado de la Gran Colombia?",
      [("A) Solo guerras", "Incorrecto."),
       ("B) La idea de unidad latinoamericana, la abolicion de la esclavitud impulsada por Bolivar, y la base de las republicas actuales", "Correcto."),
       ("C) El idioma portugues", "Incorrecto."),
       ("D) La monarquia", "Incorrecto.")],
      "B", "El legado incluye el ideal de integracion latinoamericana, las banderas y escudos nacionales, la abolicion gradual de la esclavitud y las bases de las republicas.", d="D4"),
])

# W24: La Republica en el siglo XIX
wb("W24", "republica-siglo-xix", "La Republica en el siglo XIX: guerras civiles, Constitucion de 1886", [
    Q("Despues de la disolucion de la Gran Colombia, como se llamo el nuevo pais?",
      [("A) Confederacion Granadina", "Incorrecto."),
       ("B) Nueva Granada (1830-1858)", "Correcto. Despues cambio varias veces de nombre."),
       ("C) Estados Unidos de Colombia", "Incorrecto."),
       ("D) Republica de Colombia", "Incorrecto.")],
      "B", "Entre 1830 y 1858 se llamo Republica de la Nueva Granada. Luego se llamo Confederacion Granadina (1858), Estados Unidos de Colombia (1863) y finalmente Republica de Colombia (1886)."),
    Q("Que dos partidos politicos se formaron en el siglo XIX en Colombia?",
      [("A) Socialista y Comunista", "Incorrecto."),
       ("B) Liberal y Conservador", "Correcto. Se formaron en 1848-1849."),
       ("C) Democrata y Republicano", "Incorrecto."),
       ("D) Verde y Azul", "Incorrecto.")],
      "B", "Los partidos Liberal (progresista, federalista, laico) y Conservador (tradicional, centralista, catolico) se fundaron a mediados del siglo XIX y protagonizaron la historia colombiana."),
    Q("Que tipo de gobierno querian los federalistas en el siglo XIX?",
      [("A) Un gobierno central fuerte en Bogota", "Incorrecto. Eso era centralismo."),
       ("B) Estados autonomas con su propio gobierno", "Correcto. Cada estado manejaria sus asuntos."),
       ("C) Una monarquia", "Incorrecto."),
       ("D) Un imperio indigena", "Incorrecto.")],
      "B", "Los federalistas (liberales radicales) querian que cada estado (Antioquia, Boyaca, etc.) tuviera autonomia para gobernarse. Esto contrastaba con el centralismo."),
    Q("En que ano se promulgo la Constitucion de 1886?",
      [("A) 1810", "Incorrecto."),
       ("B) 1863", "Incorrecto."),
       ("C) 1886", "Correcto. La Constitucion de 1886 rigio por mas de 100 anos."),
       ("D) 1991", "Incorrecto. Esa es la actual.")],
      "C", "La Constitucion de 1886, liderada por Rafael Nunez, implanto el centralismo, fortalecio la presidencia, establecio el Concordato con la Iglesia Catolica y unio el pais bajo un solo gobierno."),
    Q("Cuantas guerras civiles hubo en Colombia durante el siglo XIX?",
      [("A) Ninguna", "Incorrecto."),
       ("B) Mas de 8 guerras civiles", "Correcto. Hubo numerosos conflictos armados."),
       ("C) Solo una", "Incorrecto."),
       ("D) Dos", "Incorrecto.")],
      "B", "Colombia tuvo mas de 8 guerras civiles en el siglo XIX, incluyendo la Guerra de los Supremos (1839), la Guerra de las Soberanias (1860) y la Guerra de los Mil Dias (1899-1902)."),
    Q("Que fue la Guerra de los Mil Dias?",
      [("A) Una guerra de 1.000 dias exactos", "Incorrecto. Duro 1.130 dias."),
       ("B) Una guerra civil entre liberales y conservadores (1899-1902)", "Correcto. Fue la mas devastadora."),
       ("C) Una guerra contra Espana", "Incorrecto."),
       ("D) Una guerra contra Peru", "Incorrecto.")],
      "B", "La Guerra de los Mil Dias (1899-1902) fue la guerra civil mas larga y destructiva del siglo XIX. Liberales vs Conservadores. Causo mas de 100.000 muertos y la posterior separacion de Panama."),
    Q("Que consecuencia tuvo la Guerra de los Mil Dias para Colombia?",
      [("A) La prosperidad economica", "Incorrecto. Fue devastadora."),
       ("B) La separacion de Panama en 1903", "Correcto. El pais quedo debilitado."),
       ("C) La union con Venezuela", "Incorrecto."),
       ("D) La abolicion del ejercito", "Incorrecto.")],
      "B", "La guerra dejo a Colombia en bancarrota y con el ejercito debilitado. Estados Unidos aprovecho para apoyar la separacion de Panama (1903) y construir el Canal de Panama."),
    Q("Que era el 'Olimpo Radical'?",
      [("A) Un partido deportivo", "Incorrecto."),
       ("B) El periodo de gobierno liberal radical (1863-1886)", "Correcto. Gobernaron bajo la Constitucion de 1863."),
       ("C) Una montana", "Incorrecto."),
       ("D) Un rio", "Incorrecto.")],
      "B", "El Olimpo Radical fue el periodo de gobierno del Partido Liberal bajo la Constitucion de 1863 (federalista). Implantaron libertad de cultos, educacion laica y abolieron la esclavitud."),
    Q("Como se llamo la constitucion que implanto el federalismo en Colombia?",
      [("A) Constitucion de 1886", "Incorrecto. Esa era centralista."),
       ("B) Constitucion de 1863 (de Rionegro)", "Correcto. Establecio los Estados Unidos de Colombia."),
       ("C) Constitucion de 1810", "Incorrecto."),
       ("D) Constitucion de 1991", "Incorrecto.")],
      "B", "La Constitucion de Rionegro (1863) creo los Estados Unidos de Colombia, con 9 estados soberanos que podian tener su propio ejercito y legislar libremente."),
    Q("Por que el siglo XIX colombiano se caracterizo por la violencia politica?",
      [("A) Por invasion extranjera permanente", "Incorrecto."),
       ("B) Por la lucha entre liberales y conservadores por el modelo de estado (centralismo vs federalismo, laicismo vs religion)", "Correcto."),
       ("C) Por la falta de recursos naturales", "Incorrecto."),
       ("D) Porque no habia gobiernos", "Incorrecto.")],
      "B", "El conflicto entre los dos partidos politicos por definir el modelo de pais (centralista/federalista, laico/catolico, proteccionista/librecambista) causo decadas de guerras civiles.", d="D4"),
])

# W25: Repaso P4
wb("W25", "repaso-p4", "Repaso independencia, Gran Colombia y siglo XIX", [
    Q("En que fecha se celebra la independencia de Colombia?",
      [("A) 7 de agosto", "Incorrecto. Es la Batalla de Boyaca."),
       ("B) 20 de julio", "Correcto."),
       ("C) 12 de octubre", "Incorrecto. Es el Dia de la Raza."),
       ("D) 25 de diciembre", "Incorrecto.")],
      "B", "El 20 de julio de 1810 se conmemora el grito de independencia con el incidente del Florero de Llorente."),
    Q("Quien lidero la Campana Libertadora y derroto a los espanoles?",
      [("A) Antonio Narino", "Incorrecto."),
       ("B) Simon Bolivar", "Correcto."),
       ("C) Francisco de Paula Santander", "Incorrecto. Fue su lugarteniente."),
       ("D) Pablo Morillo", "Incorrecto. Era espanol.")],
      "B", "Simon Bolivar cruzo los Andes y derroto a los espanoles en la Batalla de Boyaca (1819)."),
    Q("Que fue la Gran Colombia?",
      [("A) Una ciudad", "Incorrecto."),
       ("B) Un pais que unio Colombia, Venezuela, Ecuador y Panama (1819-1830)", "Correcto."),
       ("C) Un rio", "Incorrecto."),
       ("D) Una batalla", "Incorrecto.")],
      "B", "Creada por Bolivar, la Gran Colombia fue el sueno de unidad latinoamericana. Se disolvio en 1830."),
    Q("Que partidos politicos se formaron en Colombia en el siglo XIX?",
      [("A) Conservador y Liberal", "Correcto."),
       ("B) Democrata y Republicano", "Incorrecto."),
       ("C) Verde y Azul", "Incorrecto."),
       ("D) Socialista y Comunista", "Incorrecto.")],
      "A", "Fundados en 1848-1849, estos partidos han dominado la historia politica colombiana."),
    Q("Que fue la Guerra de los Mil Dias?",
      [("A) Una guerra contra Venezuela", "Incorrecto."),
       ("B) La guerra civil entre liberales y conservadores (1899-1902)", "Correcto."),
       ("C) Una guerra mundial", "Incorrecto."),
       ("D) Un conflicto indigena", "Incorrecto.")],
      "B", "La mas devastadora guerra civil del siglo XIX colombiano, que dejo al pais en bancarrota."),
    Q("Que periodo se conoce como 'La Patria Boba'?",
      [("A) 1810-1816, con disputas entre centralistas y federalistas", "Correcto."),
       ("B) 1886-1899, gobierno conservador", "Incorrecto."),
       ("C) 1863-1886, Olimpo Radical", "Incorrecto."),
       ("D) 1819-1830, la Gran Colombia", "Incorrecto.")],
      "A", "Las divisiones internas de los patriotas permitieron la reconquista espanola."),
    Q("Quien fue Pablo Morillo?",
      [("A) Un lider independentista", "Incorrecto."),
       ("B) El general espanol que reconquisto la Nueva Granada", "Correcto."),
       ("C) Un presidente colombiano", "Incorrecto."),
       ("D) Un indigena", "Incorrecto.")],
      "B", "Conocido como 'El Pacificador', lidero la Reconquista y ejecuto a muchos patriotas."),
    Q("Que consecuencias tuvo la Guerra de los Mil Dias?",
      [("A) Prosperidad para Colombia", "Incorrecto."),
       ("B) La separacion de Panama en 1903", "Correcto."),
       ("C) La abolicion de la esclavitud", "Incorrecto. Eso ocurrio antes."),
       ("D) La llegada de inmigrantes", "Incorrecto.")],
      "B", "La guerra debilito a Colombia y permitio que Estados Unidos apoyara la separacion de Panama."),
    Q("Compara la Constitucion de 1863 y la de 1886: cual afirmacion es correcta?",
      [("A) Ambas eran federalistas", "Incorrecto."),
       ("B) La de 1863 era federalista y la de 1886 era centralista", "Correcto."),
       ("C) La de 1863 era centralista y la de 1886 federalista", "Incorrecto."),
       ("D) Ambas eran iguales", "Incorrecto.")],
      "B", "La Constitucion de 1863 (Rionegro) creo los Estados Unidos de Colombia (federal). La de 1886 (Nunez) implanto el centralismo que duro hasta 1991.", d="D4"),
    Q("Por que es importante recordar las guerras civiles del siglo XIX?",
      [("A) Para celebrar la violencia", "Incorrecto."),
       ("B) Para aprender de los errores del pasado y construir la paz en el presente", "Correcto."),
       ("C) Para culpar a un solo partido", "Incorrecto."),
       ("D) Para repetir los conflictos", "Incorrecto.")],
      "B", "La historia nos muestra que la violencia politica solo trae atraso. Las guerras civiles del XIX nos ensenan la importancia del dialogo, la tolerancia y la construccion de paz.", d="D4"),
])

print("W21-W25 done!")
