#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate W26-W30 bundles."""

import os, sys, importlib.util
BASE = "E:/scripts-python/worldexams/questions_data/colombia/sociales-ciudadanas/grado-5/2026/weekly"
spec = importlib.util.spec_from_file_location("mod", os.path.join(BASE, "gen_w10_w11.py"))
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)
make_bundle, Q = mod.make_bundle, mod.Q

def wb(week, tema, rubric, qs):
    fname = "CO-SOC-5-2026-%s-%s-001-MASTERY.md" % (week, tema)
    with open(os.path.join(BASE, fname), "w", encoding="utf-8") as f:
        f.write(make_bundle(week, tema, rubric, qs))
    print("Wrote %s" % fname)

# W26: Hegemonia Conservadora
wb("W26", "hegemonia-conservadora", "Colombia siglo XX: Hegemonia conservadora (1886-1930)", [
    Q("Que fue la Hegemonia Conservadora?",
      [("A) El dominio del Partido Liberal en el gobierno", "Incorrecto. Era el conservador."),
       ("B) El periodo de gobierno del Partido Conservador de 1886 a 1930", "Correcto."),
       ("C) La independencia de Colombia", "Incorrecto."),
       ("D) La conquista espanola", "Incorrecto.")],
      "B", "La Hegemonia Conservadora fue el periodo de 44 anos (1886-1930) en que el Partido Conservador goberno Colombia ininterrumpidamente, bajo la Constitucion de 1886."),
    Q("Que hecho historico ocurrio en 1903 que marco el inicio del siglo XX colombiano?",
      [("A) La independencia", "Incorrecto."),
       ("B) La separacion de Panama", "Correcto."),
       ("C) La fundacion de Bogota", "Incorrecto."),
       ("D) La muerte de Bolivar", "Incorrecto.")],
      "B", "El 3 de noviembre de 1903, Panama se separo de Colombia con apoyo de Estados Unidos. Esto permitio a EE.UU. construir el Canal de Panama. Fue un duro golpe para Colombia."),
    Q("Que presidente conservador implanto la Constitucion de 1886 y empezo la Hegemonia?",
      [("A) Simon Bolivar", "Incorrecto."),
       ("B) Rafael Nunez", "Correcto. Fue el lider de la Regeneracion."),
       ("C) Alfonso Lopez Pumarejo", "Incorrecto. Era liberal."),
       ("D) Jorge Eliecer Gaitan", "Incorrecto. Era liberal.")],
      "B", "Rafael Nunez, lider del movimiento de la 'Regeneracion', promovio la Constitucion de 1886 que centralizo el poder y fortalecio la alianza Estado-Iglesia."),
    Q("Que relacion tenia el gobierno conservador con la Iglesia Catolica?",
      [("A) Estaban en conflicto permanente", "Incorrecto."),
       ("B) Habia una alianza estrecha; la Iglesia tenia gran influencia en la educacion y el estado civil", "Correcto."),
       ("C) La Iglesia no existia", "Incorrecto."),
       ("D) La Iglesia gobernaba el pais", "Incorrecto.")],
      "B", "Bajo la Hegemonia Conservadora, se firmo el Concordato con la Santa Sede (1887). La Iglesia controlaba la educacion, los cementerios y el registro del estado civil."),
    Q("Que recurso natural se convirtio en el principal producto de exportacion a principios del siglo XX?",
      [("A) El oro", "Incorrecto. Disminuyo su importancia."),
       ("B) El cafe", "Correcto. El cafe se convirtio en el motor de la economia."),
       ("C) El petroleo", "Incorrecto. Empezo despues."),
       ("D) El carbon", "Incorrecto.")],
      "B", "El cafe se convirtio en el principal producto de exportacion colombiano a partir de finales del siglo XIX. La economia cafetera impulso el desarrollo de infraestructura (ferrocarriles)."),
    Q("Que fue la 'Masacre de las Bananeras'?",
      [("A) Una batalla de la independencia", "Incorrecto."),
       ("B) La represion militar contra trabajadores de la United Fruit Company en 1928", "Correcto."),
       ("C) Una inundacion", "Incorrecto."),
       ("D) Un partido de futbol", "Incorrecto.")],
      "B", "En 1928, trabajadores de la United Fruit Company (Cienaga, Magdalena) protestaron por mejores condiciones laborales. El gobierno conservador ordeno la represion militar, causando cientos de muertos."),
    Q("Que lider politico denuncio la Masacre de las Bananeras?",
      [("A) Simon Bolivar", "Incorrecto."),
       ("B) Jorge Eliecer Gaitan", "Correcto. Fue el inicio de su carrera politica."),
       ("C) Alfonso Lopez Pumarejo", "Incorrecto."),
       ("D) Gustavo Rojas Pinilla", "Incorrecto.")],
      "B", "Jorge Eliecer Gaitan, entonces joven abogado y congresista, denuncio la masacre en el Congreso. Esto lo convirtio en lider del movimiento popular."),
    Q("Como empezo la aviacion comercial en Colombia?",
      [("A) Con aviones de guerra espanoles", "Incorrecto."),
       ("B) Con la creacion de Scadta (1919), la primera aerolinea comercial del mundo", "Correcto. Fue fundada en Barranquilla."),
       ("C) Con globos aerostaticos", "Incorrecto."),
       ("D) Con aviones de la Fuerza Aerea", "Incorrecto.")],
      "B", "Scadta (hoy Avianca) fue fundada en Barranquilla en 1919 por alemanes y colombianos. Fue la primera aerolinea comercial de America."),
    Q("Por que termino la Hegemonia Conservadora en 1930?",
      [("A) Por una invasion extranjera", "Incorrecto."),
       ("B) Por la division del Partido Conservador y el ascenso de los liberales con Enrique Olaya Herrera", "Correcto."),
       ("C) Por la muerte del presidente", "Incorrecto."),
       ("D) Por un golpe de estado militar", "Incorrecto.")],
      "B", "En 1930, el Partido Conservador se presento dividido en dos candidatos, permitiendo que el liberal Enrique Olaya Herrera ganara la presidencia. Asi empezo la Republica Liberal.", d="D3"),
    Q("Cual fue el legado de la Hegemonia Conservadora?",
      [("A) Solo represion", "Incorrecto."),
       ("B) Centralismo, alianza Iglesia-Estado, desarrollo ferrocarrilero, pero tambien represion de movimientos sociales", "Correcto."),
       ("C) El socialismo", "Incorrecto."),
       ("D) La independencia", "Incorrecto.")],
      "B", "La Hegemonia Conservadora centralizo el poder, modernizo parte de la infraestructura pero reprimio las protestas sociales. Sento las bases del bipartidismo del siglo XX.", d="D4"),
])

# W27: Republica Liberal
wb("W27", "republica-liberal", "Colombia siglo XX: Republica Liberal (1930-1946)", [
    Q("Quien fue el primer presidente de la Republica Liberal?",
      [("A) Jorge Eliecer Gaitan", "Incorrecto. Nunca fue presidente."),
       ("B) Enrique Olaya Herrera", "Correcto. Presidento de 1930 a 1934."),
       ("C) Alfonso Lopez Pumarejo", "Incorrecto. Fue el segundo."),
       ("D) Eduardo Santos", "Incorrecto. Fue el tercero.")],
      "B", "Enrique Olaya Herrera gano las elecciones de 1930 con el apoyo de liberales y conservadores disidentes. Su gobierno fue de 'Concentracion Nacional'."),
    Q("Que fue la Revolucion en Marcha?",
      [("A) Una guerra civil", "Incorrecto."),
       ("B) El programa de reformas del presidente Alfonso Lopez Pumarejo (1934-1938)", "Correcto."),
       ("C) Una marcha de protesta", "Incorrecto."),
       ("D) La construccion de ferrocarriles", "Incorrecto.")],
      "B", "La Revolucion en Marcha fue un conjunto de reformas progresistas: reforma agraria, reforma educativa laica y publica, y reforma tributaria."),
    Q("Que reformas implanto Alfonso Lopez Pumarejo?",
      [("A) Ninguna", "Incorrecto."),
       ("B) Reforma agraria, educacion laica publica, derecho de huelga, reforma tributaria", "Correcto."),
       ("C) Abolicion del ejercito", "Incorrecto."),
       ("D) Monarquia constitucional", "Incorrecto.")],
      "B", "Lopez Pumarejo modernizo el Estado colombiano: promovio la educacion publica laica, el derecho a la huelga, la reforma agraria y la intervencion del Estado en la economia."),
    Q("Que hecho tragico ocurrio el 9 de abril de 1948?",
      [("A) La independencia de Colombia", "Incorrecto."),
       ("B) El asesinato de Jorge Eliecer Gaitan", "Correcto."),
       ("C) La muerte de Simon Bolivar", "Incorrecto."),
       ("D) La Batalla de Boyaca", "Incorrecto.")],
      "B", "El 9 de abril de 1948, Jorge Eliecer Gaitan, lider popular liberal, fue asesinado en Bogota. Su muerte causo el 'Bogotazo', un levantamiento popular que dejo miles de muertos."),
    Q("Que fue el 'Bogotazo'?",
      [("A) Un terremoto en Bogota", "Incorrecto."),
       ("B) El levantamiento popular tras el asesinato de Gaitan", "Correcto. La ciudad estallo en violencia."),
       ("C) La fundacion de Bogota", "Incorrecto."),
       ("D) Una celebracion deportiva", "Incorrecto.")],
      "B", "El Bogotazo fue una insurreccion popular espontanea. La gente enfurecida destruyo el centro de Bogota. La violencia se extendio a todo el pais, iniciando 'La Violencia'."),
    Q("Que fue 'La Violencia' en Colombia?",
      [("A) Una pelicula", "Incorrecto."),
       ("B) El periodo de guerra civil bipartidista entre 1946 y 1958", "Correcto. Murieron cientos de miles."),
       ("C) La conquista espanola", "Incorrecto."),
       ("D) La independencia", "Incorrecto.")],
      "B", "La Violencia (1946-1958) fue un conflicto armado entre liberales y conservadores, especialmente en zonas rurales. Causo entre 200.000 y 300.000 muertos y miles de desplazados."),
    Q("Quien fue Jorge Eliecer Gaitan?",
      [("A) Un presidente conservador", "Incorrecto."),
       ("B) Un lider liberal popular que lucho por los derechos del pueblo", "Correcto."),
       ("C) Un general espanol", "Incorrecto."),
       ("D) Un escritor", "Incorrecto.")],
      "B", "Gaitan fue un abogado y politico liberal que denuncio la Masacre de las Bananeras y lidero un movimiento popular. Su asesinato cambio la historia de Colombia."),
    Q("Cual era el lema de Gaitan?",
      [("A) 'Patria, Libertad, Union'", "Incorrecto."),
       ("B) 'Por la restauracion moral de la Republica'", "Correcto."),
       ("C) 'Independencia o muerte'", "Incorrecto."),
       ("D) 'Todos por la patria'", "Incorrecto.")],
      "B", "Gaitan propugnaba por la justicia social, la moralizacion de la politica y la defensa de los mas pobres. Su movimiento se llamo gaitanismo."),
    Q("Como afecto la Republica Liberal a la educacion en Colombia?",
      [("A) No hubo cambios", "Incorrecto."),
       ("B) Promovio la educacion publica, laica y gratuita, creando escuelas en todo el pais", "Correcto."),
       ("C) Cerraron todas las escuelas", "Incorrecto."),
       ("D) Solo educacion religiosa", "Incorrecto.")],
      "B", "La Republica Liberal impulso la educacion publica. La Ley 39 de 1903 ya habia organizado la educacion, pero los liberales ampliaron la cobertura y la hicieron laica."),
    Q("Por que la Republica Liberal es importante para Colombia?",
      [("A) Porque empezo la guerra", "Incorrecto."),
       ("B) Porque modernizo el Estado, implanto reformas sociales y laborales, y fortalecio la democracia", "Correcto."),
       ("C) Porque abolio el gobierno", "Incorrecto."),
       ("D) Porque implanto la monarquia", "Incorrecto.")],
      "B", "La Republica Liberal modernizo el pais: reformas agrarias, educacion publica, derechos laborales, intervencion del Estado en la economia. Muchas de sus reformas aun son vigentes.", d="D4"),
])

# W28: Frente Nacional
wb("W28", "frente-nacional", "Frente Nacional (1958-1974): alternacion politica", [
    Q("Que fue el Frente Nacional?",
      [("A) Un partido de futbol", "Incorrecto."),
       ("B) Un pacto entre liberales y conservadores para alternarse la presidencia entre 1958 y 1974", "Correcto."),
       ("C) Una guerra", "Incorrecto."),
       ("D) Un grupo guerrillero", "Incorrecto.")],
      "B", "El Frente Nacional fue un acuerdo bipartidista para terminar con La Violencia: liberales y conservadores se turnarian la presidencia por 16 anos."),
    Q("Por que se creo el Frente Nacional?",
      [("A) Para iniciar una guerra", "Incorrecto."),
       ("B) Para poner fin a la violencia bipartidista y restaurar la democracia tras la dictadura de Rojas Pinilla", "Correcto."),
       ("C) Para unir Colombia con Venezuela", "Incorrecto."),
       ("D) Para instaurar una monarquia", "Incorrecto.")],
      "B", "Tras la dictadura militar de Gustavo Rojas Pinilla (1953-1957) y decadas de violencia, los partidos Liberal y Conservador acordaron alternarse el poder para pacificar el pais."),
    Q("Quien fue el primer presidente del Frente Nacional?",
      [("A) Alberto Lleras Camargo", "Correcto. Liberal, presidento 1958-1962."),
       ("B) Simon Bolivar", "Incorrecto."),
       ("C) Gustavo Rojas Pinilla", "Incorrecto. Fue el dictador antes."),
       ("D) Jorge Eliecer Gaitan", "Incorrecto.")],
      "A", "Alberto Lleras Camargo fue el primer presidente del Frente Nacional (1958-1962). Su gobierno busco pacificar el pais y promover reformas."),
    Q("Como funcionaba la alternacion del Frente Nacional?",
      [("A) Cada partido gobernaba 8 anos", "Correcto. 4 periodos de 4 anos alternados."),
       ("B) Gobernaba el que ganara las elecciones libremente", "Incorrecto. Estaba pactado."),
       ("C) Gobernaba siempre el mismo partido", "Incorrecto."),
       ("D) No habia gobierno", "Incorrecto.")],
      "A", "El Frente Nacional duro 16 anos (4 periodos): 1958-1962 Liberal (Lleras), 1962-1966 Conservador (Valencia), 1966-1970 Liberal (Lleras Restrepo), 1970-1974 Conservador (Pastrana)."),
    Q("Que critica se le hacia al Frente Nacional?",
      [("A) Que era muy democratico", "Incorrecto."),
       ("B) Que excluia a otros partidos y movimientos politicos (tercerias)", "Correcto. Solo liberales y conservadores podian gobernar."),
       ("C) Que daba mucho poder al pueblo", "Incorrecto."),
       ("D) Que era comunista", "Incorrecto.")],
      "B", "El Frente Nacional fue criticado por excluir a otros movimientos politicos (como la ANAPO de Rojas Pinilla). Esta exclusion llevo al surgimiento de grupos guerrilleros."),
    Q("Que grupos guerrilleros surgieron durante el Frente Nacional?",
      [("A) Los espanoles", "Incorrecto."),
       ("B) FARC, ELN, EPL (entre 1964 y 1967)", "Correcto. Surgen como oposicion armada."),
       ("C) Los liberales", "Incorrecto."),
       ("D) Los conservadores", "Incorrecto.")],
      "B", "Las FARC (1964), el ELN (1964) y el EPL (1967) surgieron como grupos guerrilleros de inspiracion comunista, en parte como respuesta a la exclusion politica del Frente Nacional."),
    Q("Que presidente del Frente Nacional implanto la reforma constitucional de 1968?",
      [("A) Alberto Lleras Camargo", "Incorrecto."),
       ("B) Carlos Lleras Restrepo", "Correcto."),
       ("C) Guillermo Leon Valencia", "Incorrecto."),
       ("D) Misael Pastrana", "Incorrecto.")],
      "B", "Carlos Lleras Restrepo (1966-1970) implanto la reforma constitucional de 1968, que modernizo el Estado, creo el Departamento Nacional de Planeacion y fortalecio el ejecutivo."),
    Q("Que eleccion del Frente Nacional fue especialmente controversial?",
      [("A) 1958", "Incorrecto."),
       ("B) 1970", "Correcto. Hubo denuncias de fraude contra Rojas Pinilla."),
       ("C) 1962", "Incorrecto."),
       ("D) 1966", "Incorrecto.")],
      "B", "Las elecciones de 1970 enfrentaron a Misael Pastrana (oficial) y Gustavo Rojas Pinilla (ANAPO). Hubo denuncias de fraude electoral. Esto llevo al surgimiento del M-19."),
    Q("Que grupo guerrillero surgio tras las elecciones de 1970?",
      [("A) FARC", "Incorrecto. Surgio en 1964."),
       ("B) ELN", "Incorrecto. Surgio en 1964."),
       ("C) M-19 (Movimiento 19 de Abril)", "Correcto. Surge por el presunto fraude."),
       ("D) EPL", "Incorrecto.")],
      "C", "El M-19 nacio en 1974 como respuesta al fraude electoral de 1970. Fue un movimiento guerrillero urbano de inspiracion nacionalista, diferente a las guerrillas rurales comunistas."),
    Q("Cual fue el balance del Frente Nacional?",
      [("A) Un fracaso total", "Incorrecto. Tuvo logros."),
       ("B) Paz y desarrollo economico, pero tambien exclusion politica y surgimiento de guerrillas", "Correcto."),
       ("C) La independencia", "Incorrecto."),
       ("D) La instauracion del comunismo", "Incorrecto.")],
      "B", "El Frente Nacional logro pacificar el pais y estabilizar la economia, pero excluyo a otras fuerzas politicas, lo que contribuyo al surgimiento de la guerrilla.", d="D4"),
])

# W29: Colombia Contemporanea
wb("W29", "colombia-contemporanea", "Colombia contemporanea: conflicto armado, proceso de paz, siglo XXI", [
    Q("Que conflicto interno ha vivido Colombia desde mediados del siglo XX?",
      [("A) Una invasion extranjera", "Incorrecto."),
       ("B) Un conflicto armado interno con guerrillas, paramilitares y narcotrafico", "Correcto."),
       ("C) Una guerra mundial", "Incorrecto."),
       ("D) Una monarquia", "Incorrecto.")],
      "B", "Colombia ha vivido un conflicto armado interno de mas de 50 anos que ha involucrado guerrillas (FARC, ELN), paramilitares, fuerzas del Estado y el narcotrafico."),
    Q("Que fue el proceso de paz con las FARC?",
      [("A) Una guerra", "Incorrecto."),
       ("B) Las negociaciones entre el gobierno colombiano y las FARC que terminaron con un acuerdo de paz en 2016", "Correcto."),
       ("C) Una batalla", "Incorrecto."),
       ("D) Un partido politico", "Incorrecto.")],
      "B", "Tras 4 anos de conversaciones en La Habana (Cuba), el gobierno de Juan Manuel Santos y las FARC firmaron un acuerdo de paz en 2016. Las FARC dejaron las armas y se convirtieron en partido politico."),
    Q("Quien fue presidente de Colombia cuando se firmo el acuerdo de paz con las FARC?",
      [("A) Alvaro Uribe Velez", "Incorrecto."),
       ("B) Juan Manuel Santos", "Correcto. Recibio el Premio Nobel de Paz 2016."),
       ("C) Andres Pastrana", "Incorrecto."),
       ("D) Ernesto Samper", "Incorrecto.")],
      "B", "Juan Manuel Santos (presidente 2010-2018) lidero el proceso de paz con las FARC. Por esto recibio el Premio Nobel de Paz en 2016."),
    Q("Que es el narcotrafico y como afecto a Colombia?",
      [("A) Es el cultivo de cafe", "Incorrecto."),
       ("B) El trafico ilegal de drogas, que ha causado violencia, corrupcion y deterioro social", "Correcto."),
       ("C) Un deporte nacional", "Incorrecto."),
       ("D) Una tradicion indigena", "Incorrecto.")],
      "B", "El narcotrafico ha sido uno de los principales factores de violencia en Colombia desde los anos 70. Carteles como el de Medellin (Pablo Escobar) y Cali generaron terrorismo y corrupcion."),
    Q("Quien fue Pablo Escobar?",
      [("A) Un presidente colombiano", "Incorrecto."),
       ("B) El lider del Cartel de Medellin, uno de los narcotraficantes mas poderosos del mundo", "Correcto."),
       ("C) Un escritor", "Incorrecto."),
       ("D) Un deportista", "Incorrecto.")],
      "B", "Pablo Escobar lidero el Cartel de Medellin en los anos 80 y principios de los 90. Su organizacion terrorista asesino a politicos, jueces y policias. Murio en 1993."),
    Q("Que acciones se tomaron contra el narcotrafico en Colombia?",
      [("A) Ninguna", "Incorrecto."),
       ("B) Extradicion de narcotraficantes, fumigacion de cultivos, persecucion policial y acuerdos de sometimiento a la justicia", "Correcto."),
       ("C) Legalizacion total", "Incorrecto."),
       ("D) Alianza con los carteles", "Incorrecto.")],
      "B", "Colombia ha combatido el narcotrafico con extradicion a EE.UU., erradicacion de cultivos ilicitos, operativos policiales y acuerdos de sometimiento (como con el Cartel de Cali)."),
    Q("Como ha sido la Constitucion de 1991 para Colombia?",
      [("A) Fue un fracaso", "Incorrecto."),
       ("B) Una nueva constitucion que amplio derechos, creo mecanismos de participacion ciudadana y modernizo el Estado", "Correcto."),
       ("C) No cambio nada", "Incorrecto."),
       ("D) Instauro la monarquia", "Incorrecto.")],
      "B", "La Constitucion de 1991 reemplazo a la de 1886. Reconocio derechos fundamentales, la diversidad etnica y cultural, creo la tutela y otros mecanismos de participacion."),
    Q("Que es la 'Justicia Especial para la Paz' (JEP)?",
      [("A) Un tribunal militar", "Incorrecto."),
       ("B) Un tribunal creado por el acuerdo de paz para juzgar los delitos del conflicto armado", "Correcto."),
       ("C) Una carcel", "Incorrecto."),
       ("D) Un partido politico", "Incorrecto.")],
      "B", "La JEP es el sistema de justicia transicional creado por el Acuerdo de Paz con las FARC. Juzga los delitos mas graves del conflicto armado. Ofrece penas alternativas a cambio de verdad."),
    Q("Que es el 'posconflicto' en Colombia?",
      [("A) La guerra contra las FARC", "Incorrecto."),
       ("B) La etapa posterior a la firma del acuerdo de paz, buscando construir paz territorial y superar las causas del conflicto", "Correcto."),
       ("C) La colonizacion", "Incorrecto."),
       ("D) La independencia", "Incorrecto.")],
      "B", "El posconflicto es el proceso de construccion de paz despues del acuerdo. Incluye la reintegracion de excombatientes, la reparacion a victimas y el desarrollo rural."),
    Q("Cual es el mayor desafio de Colombia en el siglo XXI?",
      [("A) La independencia", "Incorrecto."),
       ("B) Construir una paz estable y duradera, superar la desigualdad social y proteger el medio ambiente", "Correcto."),
       ("C) Conquistar nuevos territorios", "Incorrecto."),
       ("D) Volver a la colonia", "Incorrecto.")],
      "B", "Los principales desafios de Colombia hoy son: consolidar la paz, reducir la desigualdad, combatir el narcotrafico, proteger la biodiversidad y fortalecer la democracia.", d="D4"),
])

# W30: Repaso P5
wb("W30", "repaso-p5", "Repaso Colombia siglo XX y contemporanea", [
    Q("Que periodo se conoce como Hegemonia Conservadora?",
      [("A) 1886-1930, gobierno del Partido Conservador", "Correcto."),
       ("B) 1930-1946, gobierno liberal", "Incorrecto."),
       ("C) 1958-1974, Frente Nacional", "Incorrecto."),
       ("D) 1819-1830, Gran Colombia", "Incorrecto.")],
      "A", "La Hegemonia Conservadora duro 44 anos bajo la Constitucion de 1886."),
    Q("Que fue la Republica Liberal (1930-1946)?",
      [("A) Un gobierno conservador", "Incorrecto."),
       ("B) Un periodo de reformas sociales y modernizacion del Estado", "Correcto."),
       ("C) Una dictadura militar", "Incorrecto."),
       ("D) La colonia", "Incorrecto.")],
      "B", "Incluyo la 'Revolucion en Marcha' de Lopez Pumarejo con reformas agraria, educativa y laboral."),
    Q("Que hecho ocurrio el 9 de abril de 1948?",
      [("A) La independencia", "Incorrecto."),
       ("B) El asesinato de Gaitan y el Bogotazo", "Correcto."),
       ("C) La Batalla de Boyaca", "Incorrecto."),
       ("D) La Constitucion de 1886", "Incorrecto.")],
      "B", "El asesinato de Jorge Eliecer Gaitan desato el Bogotazo y el inicio de La Violencia."),
    Q("Que fue el Frente Nacional?",
      [("A) Una guerra", "Incorrecto."),
       ("B) Pacto de alternacion presidencial entre liberales y conservadores (1958-1974)", "Correcto."),
       ("C) Un partido politico nuevo", "Incorrecto."),
       ("D) Una constitucion", "Incorrecto.")],
      "B", "El Frente Nacional busco superar la violencia bipartidista pero excluyo a terceros."),
    Q("Que grupo guerrillero surgio por el presunto fraude electoral de 1970?",
      [("A) FARC", "Incorrecto."),
       ("B) ELN", "Incorrecto."),
       ("C) M-19", "Correcto."),
       ("D) EPL", "Incorrecto.")],
      "C", "El M-19 (Movimiento 19 de Abril) nacio como respuesta al fraude denunciado por Rojas Pinilla."),
    Q("En que ano se firmo el acuerdo de paz con las FARC?",
      [("A) 1991", "Incorrecto."),
       ("B) 2016", "Correcto."),
       ("C) 1958", "Incorrecto."),
       ("D) 2000", "Incorrecto.")],
      "B", "Firmado en el Teatro Colon de Bogota, el acuerdo puso fin a mas de 50 anos de conflicto con las FARC."),
    Q("Quien fue Pablo Escobar?",
      [("A) Un presidente colombiano", "Incorrecto."),
       ("B) El lider del Cartel de Medellin", "Correcto."),
       ("C) Un poeta", "Incorrecto."),
       ("D) Un deportista", "Incorrecto.")],
      "B", "Pablo Escobar fue el narcotraficante mas famoso de Colombia, lider del Cartel de Medellin en los anos 80."),
    Q("Que es la Constitucion de 1991?",
      [("A) La actual constitucion colombiana", "Correcto."),
       ("B) Una ley de educacion", "Incorrecto."),
       ("C) Un tratado de paz", "Incorrecto."),
       ("D) La primera constitucion", "Incorrecto.")],
      "A", "La Constitucion de 1991 reemplazo a la de 1886. Amplio derechos y creo la tutela."),
    Q("Compara la Hegemonia Conservadora y la Republica Liberal: cual es la diferencia clave?",
      [("A) Eran iguales", "Incorrecto."),
       ("B) Los conservadores promovian la alianza Iglesia-Estado; los liberales, la educacion laica y las reformas sociales", "Correcto."),
       ("C) Ambas eran laicas", "Incorrecto."),
       ("D) Ambas reprimian al pueblo", "Incorrecto.")],
      "B", "Los conservadores defendian la tradicion y la religion; los liberales promovian la modernizacion, la laicidad y las reformas sociales.", d="D4"),
    Q("Por que es importante conocer la historia del conflicto armado colombiano?",
      [("A) Para justificar la violencia", "Incorrecto."),
       ("B) Para entender las causas de la violencia, valorar la paz y no repetir los errores del pasado", "Correcto."),
       ("C) Para culpar a un solo bando", "Incorrecto."),
       ("D) Para olvidar el pasado", "Incorrecto.")],
      "B", "Conocer el conflicto nos permite entender sus causas (desigualdad, exclusion, narcotrafico), valorar los esfuerzos de paz y construir un futuro mejor.", d="D4"),
])

print("W26-W30 done!")
