#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate W16-W20 bundles."""

import os, sys
sys.path.insert(0, 'E:/scripts-python/worldexams/questions_data/colombia/sociales-ciudadanas/grado-5/2026/weekly')

# Import helpers from the first script
exec_globals = {}
with open(os.path.join(sys.path[0], 'gen_w10_w11.py'), 'r', encoding='utf-8') as f:
    code = f.read()
# Extract just the helper functions
exec(code, exec_globals)
make_bundle = exec_globals['make_bundle']
Q = exec_globals['Q']

BASE = sys.path[0]

def wb(week, tema, rubric, qs):
    fname = "CO-SOC-5-2026-%s-%s-001-MASTERY.md" % (week, tema)
    with open(os.path.join(BASE, fname), "w", encoding="utf-8") as f:
        f.write(make_bundle(week, tema, rubric, qs))
    print("Wrote %s" % fname)


# W16: Llegada de los espanoles
wb("W16", "llegada-espanoles", "La conquista espanola: llegada, fundaciones, resistencia indigena", [
    Q("En que ano llego Cristobal Colon a America?",
      [("A) 1492", "Correcto. Colon llego el 12 de octubre de 1492."),
       ("B) 1500", "Incorrecto."),
       ("C) 1510", "Incorrecto."),
       ("D) 1498", "Incorrecto. Colon llego por primera vez en 1492.")],
      "A", "Cristobal Colon, patrocinado por los Reyes Catolicos de Espana, llego a America el 12 de octubre de 1492, creyendo haber llegado a Asia."),
    Q("Quien fue el primer espanol en explorar el territorio colombiano?",
      [("A) Hernan Cortes", "Incorrecto. Conquisto Mexico."),
       ("B) Alonso de Ojeda", "Correcto. Llego a la Guajira en 1499."),
       ("C) Francisco Pizarro", "Incorrecto. Conquisto Peru."),
       ("D) Gonzalo Jimenez de Quesada", "Incorrecto. Fundo Bogota despues.")],
      "B", "Alonso de Ojeda, acompanado por Juan de la Cosa y Americo Vespucio, llego al cabo de la Vela (Guajira) en 1499."),
    Q("Cual fue la primera ciudad fundada por los espanoles en Colombia?",
      [("A) Bogota", "Incorrecto. Fue fundada en 1538."),
       ("B) Santa Marta", "Correcto. Fundada en 1525 por Rodrigo de Bastidas."),
       ("C) Cartagena", "Incorrecto. Fundada en 1533."),
       ("D) Cali", "Incorrecto. Fundada en 1536.")],
      "B", "Santa Marta, fundada el 29 de julio de 1525, es la ciudad mas antigua de Colombia. Le siguen Cartagena (1533) y Cali (1536)."),
    Q("Quien fundo la ciudad de Bogota?",
      [("A) Sebastian de Belalcazar", "Incorrecto. Fundo Cali y Popayan."),
       ("B) Gonzalo Jimenez de Quesada", "Correcto. Fundo Bogota el 6 de agosto de 1538."),
       ("C) Pedro de Heredia", "Incorrecto. Fundo Cartagena."),
       ("D) Rodrigo de Bastidas", "Incorrecto. Fundo Santa Marta.")],
      "B", "Gonzalo Jimenez de Quesada llego al altiplano cundiboyacense en 1537 y fundo Santafe de Bogota el 6 de agosto de 1538."),
    Q("Que cultura indigena fue conquistada por Jimenez de Quesada?",
      [("A) Tairona", "Incorrecto."),
       ("B) Muisca", "Correcto. Los Muiscas fueron conquistados por Jimenez de Quesada."),
       ("C) Quimbaya", "Incorrecto."),
       ("D) Zen\u00fa", "Incorrecto.")],
      "B", "Jimenez de Quesada conquisto el territorio Muisca, derrotando al Zipa Sagipa y al Zaque Quemuenchatocha."),
    Q("Que fue la 'encomienda' durante la colonia?",
      [("A) Un sistema educativo", "Incorrecto."),
       ("B) Un sistema por el cual los espanoles recibian indigenas para trabajar a cambio de evangelizarlos", "Correcto."),
       ("C) Un tipo de barco", "Incorrecto."),
       ("D) Un impuesto a los indigenas", "Incorrecto.")],
      "B", "La encomienda era una institucion colonial que asignaba un grupo de indigenas a un espanol (encomendero), quien debia evangelizarlos a cambio de su trabajo."),
    Q("Que resistieron los indigenas Taironas ante los espanoles?",
      [("A) Se rindieron sin luchar", "Incorrecto."),
       ("B) Ofrecieron resistencia armada durante decadas", "Correcto. Los Taironas resistieron tenazmente."),
       ("C) Ayudaron a los espanoles", "Incorrecto."),
       ("D) Huyeron a Europa", "Incorrecto.")],
      "B", "Los Taironas resistieron la invasion espanola durante decadas. Su ubicacion en montanas escarpadas les permitio defenderse hasta ser finalmente sometidos."),
    Q("Que ciudades fundo Sebastian de Belalcazar en Colombia?",
      [("A) Santa Marta y Cartagena", "Incorrecto."),
       ("B) Cali, Popayan y Pasto", "Correcto."),
       ("C) Bogota y Tunja", "Incorrecto."),
       ("D) Medellin y Bucaramanga", "Incorrecto.")],
      "B", "Sebastian de Belalcazar, proveniente de Peru, fundo Cali (1536), Popayan (1537) y Pasto (1537) en el suroccidente de Colombia."),
    Q("Como afecto la llegada de los espanoles a la poblacion indigena?",
      [("A) La poblacion indigena crecio", "Incorrecto."),
       ("B) Hubo una gran disminucion por guerras, enfermedades y trabajos forzados", "Correcto."),
       ("C) No hubo cambios", "Incorrecto."),
       ("D) Los indigenas esclavizaron a los espanoles", "Incorrecto.")],
      "B", "La poblacion indigena se redujo drasticamente por la violencia de la conquista, las enfermedades europeas (viruela, sarampion) contra las que no tenian defensas, y el trabajo forzado.", d="D4"),
    Q("Por que los espanoles pudieron conquistar America a pesar de ser menos numerosos?",
      [("A) Porque los indigenas los invitaron", "Incorrecto."),
       ("B) Por las armas de fuego, caballos, alianzas con grupos indigenas y las enfermedades que debilitaron a la poblacion nativa", "Correcto."),
       ("C) Porque los indigenas no tenian idioma", "Incorrecto."),
       ("D) Porque los espanoles eran invisibles", "Incorrecto.")],
      "B", "Los espanoles tenian ventajas militares (armas de fuego, caballos, armaduras), politicas (alianzas con grupos indigenas enemigos) y biologicas (enfermedades).", d="D4"),
])

# W17: La Colonia - Virreinato
wb("W17", "colonia-virreinato", "La Colonia: Virreinato de Nueva Granada, instituciones coloniales", [
    Q("En que ano se creo el Virreinato de Nueva Granada?",
      [("A) 1492", "Incorrecto."),
       ("B) 1717", "Correcto. Fue creado por la corona espanola."),
       ("C) 1810", "Incorrecto. Ese ano comenzo la independencia."),
       ("D) 1538", "Incorrecto. Ese ano se fundo Bogota.")],
      "B", "El Virreinato de Nueva Granada fue creado en 1717 (restablecido en 1739) e incluia los actuales Colombia, Ecuador, Panama y Venezuela."),
    Q("Que era el Virreinato de Nueva Granada?",
      [("A) Una republica independiente", "Incorrecto."),
       ("B) Una division administrativa del Imperio Espanol en America del Sur", "Correcto."),
       ("C) Un reino indigena", "Incorrecto."),
       ("D) Una colonia inglesa", "Incorrecto.")],
      "B", "El Virreinato era la maxima unidad administrativa espanola en America. El virrey representaba al rey de Espana y gobernaba desde Santa Fe (Bogota)."),
    Q("Como se llamaba la capital del Virreinato de Nueva Granada?",
      [("A) Cartagena", "Incorrecto. Era el principal puerto."),
       ("B) Santafe (Bogota)", "Correcto. La capital era Santafe de Bogota."),
       ("C) Quito", "Incorrecto. Era otra ciudad importante."),
       ("D) Caracas", "Incorrecto. Era parte del virreinato.")],
      "B", "Santa Fe (hoy Bogota) fue la capital del Virreinato. Alli residia el virrey y funcionaban la Real Audiencia y las autoridades coloniales."),
    Q("Que era la Real Audiencia?",
      [("A) Un mercado", "Incorrecto."),
       ("B) Un tribunal de justicia y organo de gobierno", "Correcto. Juzgaba y administraba."),
       ("C) Un tipo de moneda", "Incorrecto."),
       ("D) Un grupo musical", "Incorrecto.")],
      "B", "La Real Audiencia era el tribunal de justicia mas importante del virreinato, pero tambien tenia funciones de gobierno cuando el virrey estaba ausente."),
    Q("Que ciudad era el principal puerto del Virreinato de Nueva Granada?",
      [("A) Santa Marta", "Incorrecto."),
       ("B) Cartagena de Indias", "Correcto. Era el puerto mas importante."),
       ("C) Buenaventura", "Incorrecto."),
       ("D) Tumaco", "Incorrecto.")],
      "B", "Cartagena de Indias fue el principal puerto del virreinato. Desde alli se embarcaba el oro hacia Espana y llegaban los barcos con mercancias europeas."),
    Q("Que eran los 'resguardos indigenas'?",
      [("A) Tierras donde los indigenas vivian separados de los espanoles", "Correcto. Eran territorios colectivos."),
       ("B) Carceles para espanoles", "Incorrecto."),
       ("C) Escuelas para indigenas", "Incorrecto."),
       ("D) Minas de oro", "Incorrecto.")],
      "A", "Los resguardos eran tierras cedidas por la corona a las comunidades indigenas para que vivieran y cultivaran. Aunque protegian sus derechos, tambien los aislaban y controlaban."),
    Q("Que papel jugaba la Iglesia Catolica durante la Colonia?",
      [("A) Ninguno importante", "Incorrecto."),
       ("B) Evangelizaba, educaba y administraba registros civiles", "Correcto. Tenia enorme poder."),
       ("C) Organizaba rebeliones", "Incorrecto."),
       ("D) Comerciaba con otros paises", "Incorrecto.")],
      "B", "La Iglesia Catolica tenia un rol central: evangelizaba a los indigenas, dirigia la educacion, llevaba los registros de nacimientos, matrimonios y defunciones."),
    Q("Que recurso natural fue el mas explotado en el Virreinato de Nueva Granada?",
      [("A) El petroleo", "Incorrecto."),
       ("B) El oro", "Correcto. La mineria de oro fue la principal actividad economica."),
       ("C) El carbon", "Incorrecto."),
       ("D) El gas natural", "Incorrecto.")],
      "B", "El oro fue el recurso mas importante del virreinato. Las minas de Antioquia, Cauca y Choco producian grandes cantidades que se enviaban a Espana."),
    Q("Como estaba organizada la sociedad colonial?",
      [("A) Todos eran iguales", "Incorrecto."),
       ("B) En una piramide social con espanoles en la cima, indigenas y esclavos en la base", "Correcto."),
       ("C) Los indigenas gobernaban", "Incorrecto."),
       ("D) No habia clases sociales", "Incorrecto.")],
      "B", "La sociedad colonial era jerarquica: espanoles peninsulares (cima), criollos, mestizos, indigenas y esclavos africanos (base).", d="D3"),
    Q("Por que se creo el Virreinato de Nueva Granada?",
      [("A) Para independizar a Colombia", "Incorrecto."),
       ("B) Para mejorar la administracion de los territorios y protegerlos de ataques extranjeros", "Correcto."),
       ("C) Para construir carreteras modernas", "Incorrecto."),
       ("D) Para fundar universidades", "Incorrecto.")],
      "B", "Antes de 1717, el territorio dependia del Virreinato del Peru. Se creo el nuevo virreinato para administrar mejor la region y defenderla de piratas ingleses y franceses.", d="D4"),
])

# W18: Sociedad Colonial
wb("W18", "sociedad-colonial", "Sociedad colonial: castas, clases sociales y oficios", [
    Q("Como se llamaba la mezcla de espanol e indigena?",
      [("A) Mulato", "Incorrecto. Mulato es espanol con africano."),
       ("B) Mestizo", "Correcto. Mestizo es hijo de espanol e indigena."),
       ("C) Zambo", "Incorrecto. Zambo es indigena con africano."),
       ("D) Criollo", "Incorrecto. Criollo es espanol nacido en America.")],
      "B", "El mestizaje fue un fenomeno central de la Colonia. Mestizo = espanol + indigena. Mulato = espanol + africano. Zambo = indigena + africano."),
    Q("Quienes eran los 'criollos' en la sociedad colonial?",
      [("A) Espanoles nacidos en Espana", "Incorrecto. Esos eran peninsulares."),
       ("B) Hijos de espanoles nacidos en America", "Correcto."),
       ("C) Indigenas convertidos al cristianismo", "Incorrecto."),
       ("D) Esclavos africanos", "Incorrecto.")],
      "B", "Los criollos eran descendientes de espanoles nacidos en America. Eran ricos y educados, pero no podian ocupar los altos cargos del gobierno, reservados a peninsulares."),
    Q("Que grupo social estaba en la cima de la piramide colonial?",
      [("A) Los mestizos", "Incorrecto."),
       ("B) Los indigenas", "Incorrecto."),
       ("C) Los espanoles peninsulares", "Correcto. Nacidos en Espana."),
       ("D) Los criollos", "Incorrecto. Estaban por debajo de los peninsulares.")],
      "C", "Los espanoles peninsulares (chapetones) ocupaban los cargos mas altos: virreyes, oidores de la Audiencia, gobernadores y obispos."),
    Q("A que se dedicaban principalmente los mestizos en la Colonia?",
      [("A) Eran virreyes", "Incorrecto."),
       ("B) Eran artesanos, comerciantes pequenos, agricultores y trabajadores", "Correcto. Ocupaban oficios variados."),
       ("C) Eran esclavos en minas", "Incorrecto."),
       ("D) Eban sacerdotes catolicos", "Incorrecto.")],
      "B", "Los mestizos no eran esclavos pero tampoco tenian los privilegios de los espanoles. Trabajaban como artesanos, pequenos comerciantes, capataces, agricultores y soldados."),
    Q("Como se llamaba el sistema de castas en la Colonia?",
      [("A) Democracia racial", "Incorrecto."),
       ("B) Sistema de clasificacion social segun el origen etnico y la mezcla racial", "Correcto."),
       ("C) Igualdad de derechos", "Incorrecto."),
       ("D) Monarquia constitucional", "Incorrecto.")],
      "B", "El sistema de castas clasificaba a las personas segun su origen racial y el grado de mezcla. Existian decenas de categorias como mestizo, mulato, zambo, castizo, etc."),
    Q("Como llegaron los africanos a America durante la Colonia?",
      [("A) Como exploradores", "Incorrecto."),
       ("B) Como esclavos traidos forzosamente en barcos negreros", "Correcto."),
       ("C) Como misioneros", "Incorrecto."),
       ("D) Como comerciantes libres", "Incorrecto.")],
      "B", "Millones de africanos fueron capturados y traidos a America como esclavos para trabajar en minas, plantaciones y servicios domesticos. Era parte del comercio triangular."),
    Q("Que trabajos realizaban los esclavos africanos en el Virreinato?",
      [("A) Eran gobernadores", "Incorrecto."),
       ("B) Mineria de oro, plantaciones, servicio domestico y construccion", "Correcto."),
       ("C) Eran sacerdotes", "Incorrecto."),
       ("D) Eran comerciantes ricos", "Incorrecto.")],
      "B", "Los esclavos africanos trabajaban principalmente en las minas de oro (Choco, Antioquia, Cauca), en haciendas agricolas y como sirvientes en las casas de los espanoles."),
    Q("Que eran los 'oficios' en la Colonia?",
      [("A) Cargos politicos", "Incorrecto."),
       ("B) Trabajos manuales como herrero, zapatero, carpintero, sastre", "Correcto."),
       ("C) Ceremonias religiosas", "Incorrecto."),
       ("D) Impuestos coloniales", "Incorrecto.")],
      "B", "Los oficios eran trabajos manuales especializados. Los artesanos se organizaban en gremios que regulaban la produccion, los precios y la formacion de aprendices."),
    Q("Por que los criollos estaban inconformes con el sistema colonial?",
      [("A) Porque eran pobres", "Incorrecto. Muchos eran ricos."),
       ("B) Aunque tenian riqueza, no podian acceder a los altos cargos de gobierno, reservados a peninsulares", "Correcto."),
       ("C) Porque querian pagar mas impuestos", "Incorrecto."),
       ("D) Porque no tenian educacion", "Incorrecto.")],
      "B", "Esta exclusion de los criollos del poder politico fue una de las causas principales del movimiento de independencia.", d="D4"),
    Q("Como influye la epoca colonial en la Colombia actual?",
      [("A) No tiene ninguna influencia", "Incorrecto."),
       ("B) Dejo el idioma espanol, la religion catolica, la arquitectura, el mestizaje y muchas tradiciones culturales", "Correcto."),
       ("C) Solo dejo impuestos", "Incorrecto."),
       ("D) Dejo un sistema democratico moderno", "Incorrecto.")],
      "B", "El legado colonial es inmenso: idioma espanol, religion catolica, arquitectura colonial, el mestizaje racial y cultural, las ciudades fundadas y muchas tradiciones.", d="D4"),
])

# W19: Economia Colonial
wb("W19", "economia-colonial", "Economia colonial: mineria, agricultura, comercio y mita", [
    Q("Cual fue la principal actividad economica del Virreinato de Nueva Granada?",
      [("A) La industria textil", "Incorrecto."),
       ("B) La mineria de oro", "Correcto. La mineria fue la base de la economia colonial."),
       ("C) La pesca", "Incorrecto."),
       ("D) La fabricacion de automoviles", "Incorrecto.")],
      "B", "La mineria de oro fue la actividad mas importante. Las minas de Antioquia, Choco, Cauca y Tolima producian oro que se enviaba a Espana."),
    Q("Que era la 'mita'?",
      [("A) Un impuesto en moneda", "Incorrecto."),
       ("B) Un sistema de trabajo obligatorio para los indigenas", "Correcto."),
       ("C) Un tipo de cultivo", "Incorrecto."),
       ("D) Un baile tipico", "Incorrecto.")],
      "B", "La mita era un sistema de trabajo obligatorio por turnos. Los indigenas debian trabajar temporalmente en minas, obrajes o construcciones publicas."),
    Q("Que productos agricolas cultivaban los espanoles en el Nuevo Reino?",
      [("A) Trigo, cebada y vid", "Correcto. Introdujeron cultivos europeos."),
       ("B) Maiz, papa y yuca (cultivos nativos)", "Incorrecto. Esos ya eran cultivados por indigenas."),
       ("C) Arroz y soya", "Incorrecto."),
       ("D) Cafe y platano", "Incorrecto. Se introdujeron despues.")],
      "A", "Los espanoles introdujeron cultivos europeos como trigo, cebada, vid (uva), olivo, ca\u00f1a de azucar y frutales. Tambien trajeron animales como vacas, caballos, ovejas y cerdos."),
    Q("Que era el 'comercio triangular'?",
      [("A) Comercio entre tres ciudades colombianas", "Incorrecto."),
       ("B) Ruta comercial entre Europa, Africa y America", "Correcto. Europa enviaba mercancias a Africa por esclavos, y estos iban a America por oro y materias primas."),
       ("C) Comercio entre virreinatos", "Incorrecto."),
       ("D) Trueque entre indigenas", "Incorrecto.")],
      "B", "El comercio triangular conectaba Europa (manufacturas), Africa (esclavos) y America (oro, plata, azucar). Fue la base del comercio colonial."),
    Q("Que eran las 'haciendas' coloniales?",
      [("A) Pequenas tiendas", "Incorrecto."),
       ("B) Grandes propiedades rurales que producian para el mercado", "Correcto."),
       ("C) F\u00e1bricas textiles", "Incorrecto."),
       ("D) Escuelas para indigenas", "Incorrecto.")],
      "B", "Las haciendas eran grandes extensiones de tierra donde se producian alimentos, ganado y otros productos. Eran auto-suficientes y empleaban a indigenas y mestizos."),
    Q("Quien trabajaba en las minas de oro?",
      [("A) Solo espanoles", "Incorrecto."),
       ("B) Principalmente esclavos africanos e indigenas sometidos a la mita", "Correcto."),
       ("C) Mestizos libres voluntariamente", "Incorrecto."),
       ("D) Monjes catolicos", "Incorrecto.")],
      "B", "Las minas de oro eran trabajadas principalmente por esclavos africanos (especialmente en el Choco y Cauca) y por indigenas obligados por la mita."),
    Q("Que era el 'estanco' en la economia colonial?",
      [("A) Un lago artificial", "Incorrecto."),
       ("B) El monopolio del estado sobre la produccion y venta de ciertos productos", "Correcto. Ejemplo: el estanco del aguardiente."),
       ("C) Un barco mercante", "Incorrecto."),
       ("D) Un tipo de impuesto agricola", "Incorrecto.")],
      "B", "Los estancos eran monopolios del estado colonial sobre productos como el tabaco, el aguardiente y la sal. Solo el gobierno podia producirlos y venderlos."),
    Q("Que eran los 'obrajes'?",
      [("A) Minas de oro", "Incorrecto."),
       ("B) Talleres donde se producian tejidos y otros bienes", "Correcto."),
       ("C) Iglesias coloniales", "Incorrecto."),
       ("D) Mercados indigenas", "Incorrecto.")],
      "B", "Los obrajes eran talleres textiles donde se producian panos, ropa y otros tejidos. Trabajaban indigenas en condiciones de trabajo forzado."),
    Q("Como afecto la mineria de oro a la poblacion indigena?",
      [("A) Los hizo ricos", "Incorrecto."),
       ("B) Disminuyo drasticamente su poblacion por el trabajo forzado y las enfermedades", "Correcto."),
       ("C) No los afecto", "Incorrecto."),
       ("D) Mejoro su calidad de vida", "Incorrecto.")],
      "B", "La mineria causo una catastrofe demografica entre los indigenas: murieron por el trabajo excesivo, la violencia y las enfermedades. Por eso se trajeron esclavos africanos.", d="D4"),
    Q("Que papel jugaba Cartagena en la economia colonial?",
      [("A) Era la capital del virreinato", "Incorrecto. La capital era Santafe."),
       ("B) Era el principal puerto comercial y militar del virreinato", "Correcto."),
       ("C) Era un pueblo minero", "Incorrecto."),
       ("D) Era centro de produccion textil", "Incorrecto.")],
      "B", "Cartagena era el puerto mas importante. Por alli entraban mercancias europeas y esclavos africanos, y se exportaba oro hacia Espana. Tambien era una plaza militar fortificada.", d="D3"),
])

# W20: Repaso General P1-P3
wb("W20", "repaso-general-p1-p3", "Repaso general conquista, colonia y sociedad colonial", [
    Q("En que ano y quien fundo Santa Marta?",
      [("A) 1525, Rodrigo de Bastidas", "Correcto."),
       ("B) 1538, Gonzalo Jimenez de Quesada", "Incorrecto. Ese fundo Bogota."),
       ("C) 1533, Pedro de Heredia", "Incorrecto. Fundo Cartagena."),
       ("D) 1536, Sebastian de Belalcazar", "Incorrecto. Fundo Cali.")],
      "A", "Santa Marta (1525) es la ciudad mas antigua de Colombia, fundada por Rodrigo de Bastidas."),
    Q("Que era la encomienda en la Colonia?",
      [("A) Una escuela para indigenas", "Incorrecto."),
       ("B) Asignacion de indigenas a un espanol para trabajar a cambio de evangelizacion", "Correcto."),
       ("C) Un tipo de barco mercante", "Incorrecto."),
       ("D) Un impuesto colonial", "Incorrecto.")],
      "B", "La encomienda fue la institucion basica de la Colonia. El encomendero cuidaba y evangelizaba a los indigenas a cambio de su trabajo."),
    Q("Cual era la maxima autoridad del Virreinato de Nueva Granada?",
      [("A) El Zipa", "Incorrecto."),
       ("B) El virrey", "Correcto. Representaba al rey de Espana."),
       ("C) El presidente de la Republica", "Incorrecto."),
       ("D) El papa", "Incorrecto.")],
      "B", "El virrey era la maxima autoridad en el virreinato, nombrado por el rey de Espana."),
    Q("Que mezcla racial produce un 'mestizo'?",
      [("A) Espanol y africano", "Incorrecto. Eso es mulato."),
       ("B) Espanol e indigena", "Correcto."),
       ("C) Indigena y africano", "Incorrecto. Eso es zambo."),
       ("D) Dos espanoles", "Incorrecto.")],
      "B", "Mestizo = espanol + indigena. Mulato = espanol + africano. Zambo = indigena + africano."),
    Q("Cual era la principal actividad economica del Virreinato?",
      [("A) El turismo", "Incorrecto."),
       ("B) La mineria de oro", "Correcto."),
       ("C) La industria automotriz", "Incorrecto."),
       ("D) La tecnologia digital", "Incorrecto.")],
      "B", "El oro era el principal producto de exportacion del Virreinato de Nueva Granada."),
    Q("Quien conquisto a los Muiscas y fundo Bogota?",
      [("A) Sebastian de Belalcazar", "Incorrecto."),
       ("B) Gonzalo Jimenez de Quesada", "Correcto."),
       ("C) Pedro de Heredia", "Incorrecto."),
       ("D) Rodrigo de Bastidas", "Incorrecto.")],
      "B", "Jimenez de Quesada llego al altiplano en 1537 y fundo Santafe de Bogota en 1538."),
    Q("Como afecto la conquista a la poblacion indigena?",
      [("A) Mejoro su calidad de vida", "Incorrecto."),
       ("B) La poblacion se redujo drasticamente por guerras, enfermedades y trabajos forzados", "Correcto."),
       ("C) No hubo cambios significativos", "Incorrecto."),
       ("D) Los indigenas conquistaron Espana", "Incorrecto.")],
      "B", "Fue un desastre demografico: entre guerras, enfermedades europeas y explotacion laboral, millones de indigenas murieron.", d="D3"),
    Q("Que eran los criollos?",
      [("A) Indigenas cristianizados", "Incorrecto."),
       ("B) Hijos de espanoles nacidos en America", "Correcto."),
       ("C) Esclavos africanos liberados", "Incorrecto."),
       ("D) Espanoles nacidos en Espana", "Incorrecto.")],
      "B", "Los criollos eran descendientes de espanoles nacidos en America. Eran ricos pero no accedian a los altos cargos del gobierno."),
    Q("Por que los criollos lideraron la independencia?",
      [("A) Porque no tenian dinero", "Incorrecto."),
       ("B) Porque estaban excluidos del poder politico a pesar de su riqueza y educacion", "Correcto."),
       ("C) Porque los indigenas los obligaron", "Incorrecto."),
       ("D) Porque Espana les ofrecio mas poder", "Incorrecto.")],
      "B", "Los criollos estaban inconformes con la discriminacion politica. Querian gobernar su propio territorio.", d="D4"),
    Q("Que legado nos dejo la Colonia?",
      [("A) Solo destruccion", "Incorrecto."),
       ("B) El idioma espanol, la religion catolica, las ciudades, el mestizaje cultural y la arquitectura colonial", "Correcto."),
       ("C) La tecnologia moderna", "Incorrecto."),
       ("D) El sistema democratico actual", "Incorrecto.")],
      "B", "La Colonia nos dejo un legado complejo: idioma, religion, arquitectura, el mestizaje racial y cultural que caracteriza a Colombia hoy.", d="D4"),
])

print("Done! W16-W20 generated.")
