#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate W31-W35 bundles."""

import os, sys, importlib.util
BASE = "E:/scripts-python/worldexams/questions_data/colombia/sociales-ciudadanas/grado-5/2026/weekly"
spec = importlib.util.spec_from_file_location("mod", os.path.join(BASE, "gen_w10_w11.py"))
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)
make_bundle, Q = mod.make_bundle, mod.Q

def wb(week, tema, rubric, qs):
    fname = "CO-SOC-5-2026-%s-%s-001-MASTERY.md" % (week, tema)
    with open(os.path.join(BASE, fname), "w", encoding="utf-8") as f:
        f.write(make_bundle(week, tema, rubric, qs))
    print("Wrote %s" % fname)

# W31: Constitucion de 1991
wb("W31", "constitucion-1991", "Constitucion de 1991: derechos fundamentales, mecanismos de participacion", [
    Q("En que ano se promulgo la actual Constitucion de Colombia?",
      [("A) 1886", "Incorrecto. Esa fue la anterior."),
       ("B) 1991", "Correcto. Reemplazo a la de 1886."),
       ("C) 1810", "Incorrecto."),
       ("D) 1958", "Incorrecto.")],
      "B", "La Constitucion de 1991 fue promulgada el 4 de julio. Resulto de una Asamblea Nacional Constituyente convocada por la Septima Papeleta."),
    Q("Que fue la 'Septima Papeleta'?",
      [("A) Un partido politico", "Incorrecto."),
       ("B) El movimiento estudiantil que impulso la creacion de una nueva constitucion en 1990", "Correcto."),
       ("C) Una ley electoral", "Incorrecto."),
       ("D) Un medio de comunicacion", "Incorrecto.")],
      "B", "Los estudiantes impulsaron la Septima Papeleta para que los ciudadanos votaran por una Asamblea Constituyente. Esto llevo a la Constitucion de 1991."),
    Q("Cuales son los derechos fundamentales segun la Constitucion de 1991?",
      [("A) Solo el derecho a votar", "Incorrecto."),
       ("B) Derecho a la vida, igualdad, libertad, educacion, salud, trabajo y mas", "Correcto."),
       ("C) Solo derechos politicos", "Incorrecto."),
       ("D) Ningun derecho", "Incorrecto.")],
      "B", "La Constitucion consagra derechos fundamentales: vida, igualdad, libertad de expresion, educacion, salud, trabajo, debido proceso."),
    Q("Que mecanismo de proteccion de derechos creo la Constitucion de 1991?",
      [("A) El juicio oral", "Incorrecto."),
       ("B) La Accion de Tutela", "Correcto. Cualquier persona puede pedir proteccion inmediata de sus derechos."),
       ("C) El voto popular", "Incorrecto."),
       ("D) No creo mecanismos", "Incorrecto.")],
      "B", "La tutela es un mecanismo rapido y gratuito para reclamar ante un juez la proteccion de derechos fundamentales vulnerados."),
    Q("Que es la diversidad etnica y cultural reconocida por la Constitucion?",
      [("A) Que todos son iguales sin diferencias", "Incorrecto."),
       ("B) El reconocimiento de Colombia como pais pluri-etnico y multicultural", "Correcto."),
       ("C) Que solo existe una cultura", "Incorrecto."),
       ("D) Que los indigenas no existen", "Incorrecto.")],
      "B", "La Constitucion reconoce que Colombia es diversa: indigenas, afrocolombianos, ROM y raizales tienen derechos culturales y territoriales."),
    Q("Cuales son los mecanismos de participacion ciudadana?",
      [("A) Solo el voto", "Incorrecto."),
       ("B) Voto, plebiscito, referendo, consulta popular, cabildo abierto, iniciativa legislativa y revocatoria del mandato", "Correcto."),
       ("C) No existen mecanismos", "Incorrecto."),
       ("D) Solo las encuestas", "Incorrecto.")],
      "B", "La Constitucion creo varios mecanismos: voto, plebiscito, referendo, cabildo abierto, y revocatoria del mandato."),
    Q("Que funcion cumple la Corte Constitucional?",
      [("A) Juzgar delitos comunes", "Incorrecto."),
       ("B) Velar por que las leyes esten de acuerdo con la Constitucion", "Correcto."),
       ("C) Elegir al presidente", "Incorrecto."),
       ("D) Recaudar impuestos", "Incorrecto.")],
      "B", "La Corte Constitucional revisa leyes y actos del gobierno para asegurar que no violen la Constitucion. Tambien revisa tutelas."),
    Q("Que derecho protege la libertad de expresion?",
      [("A) Derecho a guardar silencio", "Incorrecto."),
       ("B) Derecho a expresar y difundir libremente el pensamiento y opiniones", "Correcto."),
       ("C) Derecho a no ser escuchado", "Incorrecto."),
       ("D) Derecho a mentir impunemente", "Incorrecto.")],
      "B", "El Articulo 20 de la Constitucion garantiza la libertad de expresion sin censura previa."),
    Q("Por que la Constitucion de 1991 fue importante para la paz?",
      [("A) Porque declaro la guerra", "Incorrecto."),
       ("B) Porque abrio espacios de participacion, reconocio la diversidad y busco incluir a todos", "Correcto."),
       ("C) Porque elimino el gobierno", "Incorrecto."),
       ("D) No tuvo relacion con la paz", "Incorrecto.")],
      "B", "La Constitucion busco construir paz a traves de la inclusion: derechos de minorias, mecanismos de participacion y justicia.", d="D4"),
    Q("Compara la Constitucion de 1886 con la de 1991.",
      [("A) La de 1886 era mas democratica", "Incorrecto."),
       ("B) La de 1886 era centralista; la de 1991 es participativa y pluralista", "Correcto."),
       ("C) Son iguales", "Incorrecto."),
       ("D) La de 1991 es mas autoritaria", "Incorrecto.")],
      "B", "La de 1886 centralizo el poder y limito la participacion. La de 1991 descentralizo, creo la tutela y reconocio la diversidad.", d="D4"),
])

# W32: Organizacion del Estado
wb("W32", "organizacion-estado", "Organizacion del Estado colombiano: ramas del poder publico", [
    Q("En cuantas ramas se divide el poder publico en Colombia?",
      [("A) 2", "Incorrecto."),
       ("B) 3", "Correcto. Legislativa, Ejecutiva y Judicial."),
       ("C) 4", "Incorrecto."),
       ("D) 5", "Incorrecto.")],
      "B", "Las tres ramas evitan la concentracion del poder: Legislativa (hace leyes), Ejecutiva (las ejecuta) y Judicial (las aplica)."),
    Q("Quien ejerce la Rama Ejecutiva?",
      [("A) El Congreso", "Incorrecto."),
       ("B) El Presidente de la Republica y su gabinete", "Correcto."),
       ("C) La Corte Suprema", "Incorrecto."),
       ("D) La Procuraduria", "Incorrecto.")],
      "B", "La Rama Ejecutiva esta encabezada por el Presidente (Jefe de Estado y de Gobierno), ministros, gobernadores y alcaldes."),
    Q("Que funcion tiene la Rama Legislativa?",
      [("A) Ejecutar las leyes", "Incorrecto."),
       ("B) Hacer las leyes y controlar al gobierno", "Correcto."),
       ("C) Juzgar a los delincuentes", "Incorrecto."),
       ("D) Declarar la guerra", "Incorrecto.")],
      "B", "El Congreso (Senado y Camara de Representantes) elabora las leyes y ejerce control politico sobre el gobierno."),
    Q("Cuantos senadores tiene el Congreso colombiano?",
      [("A) 100", "Incorrecto."),
       ("B) 108", "Correcto. 100 elegidos nacionalmente, 2 indigenas y 5 del partido FARC."),
       ("C) 50", "Incorrecto."),
       ("D) 200", "Incorrecto.")],
      "B", "El Senado tiene 108 miembros elegidos para periodos de 4 anos. Representan a todo el pais."),
    Q("Que organos son las altas cortes de la Rama Judicial?",
      [("A) La policia", "Incorrecto."),
       ("B) Corte Suprema de Justicia, Corte Constitucional y Consejo de Estado", "Correcto."),
       ("C) El Congreso", "Incorrecto."),
       ("D) El Presidente", "Incorrecto.")],
      "B", "Las altas cortes son: Corte Suprema (justicia ordinaria), Corte Constitucional (constitucionalidad) y Consejo de Estado (contencioso administrativo)."),
    Q("Quien elige al Presidente en Colombia?",
      [("A) El Congreso", "Incorrecto."),
       ("B) El pueblo mediante voto popular directo", "Correcto."),
       ("C) La Corte Suprema", "Incorrecto."),
       ("D) Los gobernadores", "Incorrecto.")],
      "B", "El presidente es elegido por voto popular directo para un periodo de 4 anos."),
    Q("Que son los organismos de control del Estado?",
      [("A) Empresas privadas", "Incorrecto."),
       ("B) Entidades que vigilan el funcionamiento del Estado", "Correcto."),
       ("C) Partidos politicos", "Incorrecto."),
       ("D) Medios de comunicacion", "Incorrecto.")],
      "B", "Los organismos de control son: Procuraduria (vigila funcionarios), Contraloria (controla gasto) y Defensoria del Pueblo (protege DDHH)."),
    Q("Como se organiza territorialmente Colombia?",
      [("A) En provincias", "Incorrecto."),
       ("B) En departamentos, municipios y distritos", "Correcto."),
       ("C) En estados federales", "Incorrecto."),
       ("D) En colonias", "Incorrecto.")],
      "B", "Colombia tiene 32 departamentos, mas de 1100 municipios y distritos especiales (Bogota, Cartagena, Barranquilla, Santa Marta)."),
    Q("Que funcion cumplen los gobernadores?",
      [("A) Gobernar el pais", "Incorrecto."),
       ("B) Administrar los departamentos y ejecutar politicas regionales", "Correcto."),
       ("C) Hacer leyes nacionales", "Incorrecto."),
       ("D) Juzgar delitos", "Incorrecto.")],
      "B", "Los gobernadores son jefes de la administracion departamental, elegidos por voto popular por 4 anos."),
    Q("Por que es importante la separacion de poderes?",
      [("A) Para concentrar el poder", "Incorrecto."),
       ("B) Para evitar abusos y garantizar la democracia mediante el equilibrio entre ramas", "Correcto."),
       ("C) Para que no haya gobierno", "Incorrecto."),
       ("D) Para que el presidente tenga poder absoluto", "Incorrecto.")],
      "B", "La separacion de poderes (Montesquieu) evita la tirania. Cada rama controla a las otras.", d="D4"),
])

# W33: Democracia y Participacion
wb("W33", "democracia-participacion", "Democracia y participacion ciudadana: voto, mecanismos, deberes", [
    Q("Que es la democracia?",
      [("A) Un sistema donde solo gobierna una persona", "Incorrecto."),
       ("B) Un sistema donde el pueblo tiene el poder y decide", "Correcto."),
       ("C) Un sistema sin gobierno", "Incorrecto."),
       ("D) Un sistema de reyes", "Incorrecto.")],
      "B", "Democracia significa 'gobierno del pueblo'. En Colombia es participativa y pluralista."),
    Q("A partir de que edad pueden votar los colombianos?",
      [("A) 16 anos", "Incorrecto."),
       ("B) 18 anos", "Correcto."),
       ("C) 21 anos", "Incorrecto."),
       ("D) 14 anos", "Incorrecto.")],
      "B", "Los ciudadanos pueden votar desde los 18 anos. El voto no es obligatorio en Colombia."),
    Q("Que es el voto?",
      [("A) Un juego", "Incorrecto."),
       ("B) El mecanismo para elegir gobernantes", "Correcto."),
       ("C) Un impuesto", "Incorrecto."),
       ("D) Una fiesta", "Incorrecto.")],
      "B", "El voto permite elegir presidente, congresistas, gobernadores, alcaldes, diputados y concejales."),
    Q("Que es un plebiscito?",
      [("A) Una eleccion de presidente", "Incorrecto."),
       ("B) Una consulta del presidente al pueblo sobre decisiones importantes", "Correcto."),
       ("C) Un impuesto", "Incorrecto."),
       ("D) Una reunion del congreso", "Incorrecto.")],
      "B", "Ejemplo: el plebiscito del Acuerdo de Paz en 2016."),
    Q("Que es la revocatoria del mandato?",
      [("A) Elegir un nuevo presidente", "Incorrecto."),
       ("B) Quitar del cargo a un alcalde o gobernador antes de terminar su periodo", "Correcto."),
       ("C) Una celebracion", "Incorrecto."),
       ("D) Un tipo de tutela", "Incorrecto.")],
      "B", "Permite a los ciudadanos destituir mediante voto a un alcalde o gobernador que no cumpla."),
    Q("Cuales son los deberes de los ciudadanos?",
      [("A) Solo pagar impuestos", "Incorrecto."),
       ("B) Cumplir la Constitucion, respetar derechos ajenos, participar, defender la paz y proteger recursos", "Correcto."),
       ("C) No existen deberes", "Incorrecto."),
       ("D) Solo votar", "Incorrecto.")],
      "B", "Deberes: acatar la ley, respetar derechos, participar en la vida civica, defender la paz y proteger el ambiente."),
    Q("Que es un partido politico?",
      [("A) Una celebracion", "Incorrecto."),
       ("B) Una organizacion de ciudadanos que comparte una ideologia y busca el poder", "Correcto."),
       ("C) Una empresa", "Incorrecto."),
       ("D) Un medio de comunicacion", "Incorrecto.")],
      "B", "Los partidos agrupan personas con ideas similares sobre como gobernar. Ej: Liberal, Conservador, Centro Democratico."),
    Q("Que es un cabildo abierto?",
      [("A) Una reunion del congreso", "Incorrecto."),
       ("B) Una reunion publica de los concejos municipales donde los ciudadanos participan", "Correcto."),
       ("C) Una iglesia", "Incorrecto."),
       ("D) Un mercado", "Incorrecto.")],
      "B", "El cabildo abierto permite a los ciudadanos participar directamente en las discusiones del concejo municipal."),
    Q("Por que la participacion ciudadana es importante?",
      [("A) No es necesaria", "Incorrecto."),
       ("B) Fortalece la democracia, permite influir en decisiones y controlar a gobernantes", "Correcto."),
       ("C) Debilita el gobierno", "Incorrecto."),
       ("D) Solo sirve para quejarse", "Incorrecto.")],
      "B", "La participacion es el corazon de la democracia: votar, vigilar y participar fortalece el sistema.", d="D3"),
    Q("Que diferencia hay entre democracia representativa y participativa?",
      [("A) Son lo mismo", "Incorrecto."),
       ("B) En la representativa elegimos representantes; en la participativa decidimos directamente", "Correcto."),
       ("C) En la participativa no se vota", "Incorrecto."),
       ("D) En la representativa no hay gobierno", "Incorrecto.")],
      "B", "Ambas se complementan: elegimos representantes pero tambien participamos en plebiscitos y referendos.", d="D4"),
])

# W34: Repaso P6
wb("W34", "repaso-p6", "Repaso Constitucion, Estado y democracia", [
    Q("En que ano se promulgo la actual Constitucion de Colombia?",
      [("A) 1886", "Incorrecto."),
       ("B) 1991", "Correcto."),
       ("C) 1810", "Incorrecto."),
       ("D) 2000", "Incorrecto.")],
      "B", "La Constitucion de 1991 reemplazo a la de 1886."),
    Q("Cuales son las tres ramas del poder publico?",
      [("A) Ejecutiva, Legislativa y Judicial", "Correcto."),
       ("B) Federal, Estatal y Municipal", "Incorrecto."),
       ("C) Economica, Social y Cultural", "Incorrecto."),
       ("D) Alta, Media y Baja", "Incorrecto.")],
      "A", "Cada rama tiene funciones especificas y se controlan mutuamente."),
    Q("Que mecanismo creo la Constitucion de 1991 para proteger derechos?",
      [("A) El juicio oral", "Incorrecto."),
       ("B) La Accion de Tutela", "Correcto."),
       ("C) El voto", "Incorrecto."),
       ("D) El impuesto", "Incorrecto.")],
      "B", "La tutela es un recurso rapido y gratuito para proteger derechos fundamentales."),
    Q("A partir de que edad se puede votar en Colombia?",
      [("A) 16 anos", "Incorrecto."),
       ("B) 18 anos", "Correcto."),
       ("C) 21 anos", "Incorrecto."),
       ("D) 25 anos", "Incorrecto.")],
      "B", "La mayoria de edad en Colombia es a los 18 anos."),
    Q("Que es un plebiscito?",
      [("A) Una eleccion", "Incorrecto."),
       ("B) Una consulta del presidente al pueblo", "Correcto."),
       ("C) Un impuesto", "Incorrecto."),
       ("D) Una ley", "Incorrecto.")],
      "B", "Ejemplo: el plebiscito de 2016 para refrendar el Acuerdo de Paz."),
    Q("Quien ejerce la Rama Ejecutiva?",
      [("A) El Congreso", "Incorrecto."),
       ("B) El Presidente", "Correcto."),
       ("C) La Corte Suprema", "Incorrecto."),
       ("D) La Procuraduria", "Incorrecto.")],
      "B", "El presidente, ministros, gobernadores y alcaldes ejercen la rama ejecutiva."),
    Q("Que funcion tiene la Rama Legislativa?",
      [("A) Ejecutar leyes", "Incorrecto."),
       ("B) Hacer las leyes y controlar al gobierno", "Correcto."),
       ("C) Juzgar delitos", "Incorrecto."),
       ("D) Recaudar impuestos", "Incorrecto.")],
      "B", "El Congreso (Senado y Camara) elabora las leyes."),
    Q("Cuantos departamentos tiene Colombia?",
      [("A) 32", "Correcto."),
       ("B) 20", "Incorrecto."),
       ("C) 50", "Incorrecto."),
       ("D) 10", "Incorrecto.")],
      "A", "Colombia tiene 32 departamentos y un Distrito Capital."),
    Q("Compara democracia representativa y participativa.",
      [("A) Son lo mismo", "Incorrecto."),
       ("B) Representativa: elegimos representantes; participativa: decidimos directamente", "Correcto."),
       ("C) En la participativa no votamos", "Incorrecto."),
       ("D) La representativa es mejor", "Incorrecto.")],
      "B", "Ambas se complementan en Colombia.", d="D4"),
    Q("Por que la separacion de poderes es fundamental?",
      [("A) Para que el presidente tenga todo el poder", "Incorrecto."),
       ("B) Para evitar la concentracion de poder y garantizar equilibrio", "Correcto."),
       ("C) Para que no haya gobierno", "Incorrecto."),
       ("D) Para que solo un partido gobierne", "Incorrecto.")],
      "B", "La separacion de poderes evita abusos.", d="D4"),
])

# W35: Relaciones Internacionales
wb("W35", "relaciones-internacionales", "Colombia y sus relaciones internacionales: fronteras, tratados, integracion", [
    Q("Con cuantos paises limita Colombia por tierra?",
      [("A) 3", "Incorrecto."),
       ("B) 5", "Correcto: Panama, Venezuela, Brasil, Peru y Ecuador."),
       ("C) 7", "Incorrecto."),
       ("D) 2", "Incorrecto.")],
      "B", "Colombia limita con 5 paises: Panama, Venezuela, Brasil, Peru y Ecuador. Tambien tiene fronteras maritimas."),
    Q("Que pais separa a Colombia de America Central?",
      [("A) Venezuela", "Incorrecto."),
       ("B) Panama", "Correcto."),
       ("C) Costa Rica", "Incorrecto."),
       ("D) Nicaragua", "Incorrecto.")],
      "B", "Panama, que era parte de Colombia, conecta Sudamerica con Centroamerica."),
    Q("Que es la CAN?",
      [("A) Un canal de television", "Incorrecto."),
       ("B) Comunidad Andina: integracion economica entre Colombia, Peru, Ecuador y Bolivia", "Correcto."),
       ("C) Un partido politico", "Incorrecto."),
       ("D) Una montana", "Incorrecto.")],
      "B", "La CAN busca la integracion economica y social de los paises andinos."),
    Q("Que fue el conflicto de Leticia?",
      [("A) Una guerra por la Patagonia", "Incorrecto."),
       ("B) Un conflicto colombo-peruano (1932-1933) por el Trapecio Amazonico", "Correcto."),
       ("C) Una disputa por Galapagos", "Incorrecto."),
       ("D) Un conflicto por la Sierra Nevada", "Incorrecto.")],
      "B", "Civiles peruanos tomaron Leticia en 1932. Se resolvio diplomaticamente con el Protocolo de Rio de Janeiro."),
    Q("Colombia es miembro de la Alianza del Pacifico?",
      [("A) No", "Incorrecto."),
       ("B) Si, es miembro fundador junto con Mexico, Peru y Chile", "Correcto."),
       ("C) Solo como observador", "Incorrecto."),
       ("D) Nunca pertenecio", "Incorrecto.")],
      "B", "La Alianza del Pacifico (2011) fortalece el comercio con Asia-Pacifico."),
    Q("Que es MERCOSUR y cual es la relacion de Colombia?",
      [("A) Un grupo del Caribe", "Incorrecto."),
       ("B) Un bloque economico del Cono Sur; Colombia es miembro asociado", "Correcto."),
       ("C) Un ejercito", "Incorrecto."),
       ("D) Una universidad", "Incorrecto.")],
      "B", "MERCOSUR integra a Brasil, Argentina, Paraguay, Uruguay. Colombia es asociado."),
    Q("Que es la OEA?",
      [("A) Una empresa privada", "Incorrecto."),
       ("B) Organizacion de Estados Americanos; Colombia es miembro fundador", "Correcto."),
       ("C) Un partido politico", "Incorrecto."),
       ("D) Un tratado de comercio", "Incorrecto.")],
      "B", "La OEA reune a los paises de America para promover democracia y derechos humanos."),
    Q("Que frontera maritima es controversial?",
      [("A) La del Pacifico", "Incorrecto."),
       ("B) La del Golfo de Venezuela con Venezuela", "Correcto."),
       ("C) La del Atlantico", "Incorrecto."),
       ("D) La del Caribe con Panama", "Incorrecto.")],
      "B", "Las fronteras maritimas en el Golfo de Venezuela han sido tema de controversia."),
    Q("Por que son importantes las relaciones internacionales?",
      [("A) No son importantes", "Incorrecto."),
       ("B) Para comerciar, recibir inversion y cooperar en seguridad y medio ambiente", "Correcto."),
       ("C) Para aislarse", "Incorrecto."),
       ("D) Solo para prestamos", "Incorrecto.")],
      "B", "Las relaciones internacionales son clave: comercio, inversion, cooperacion tecnica y lucha contra el narcotrafico.", d="D3"),
    Q("Que es la diplomacia?",
      [("A) Una guerra", "Incorrecto."),
       ("B) El arte de negociar y mantener relaciones pacificas entre paises", "Correcto."),
       ("C) Un impuesto", "Incorrecto."),
       ("D) Un idioma", "Incorrecto.")],
      "B", "La diplomacia resuelve conflictos sin guerra y promueve la cooperacion.", d="D3"),
])

print("W31-W35 done!")
