#!/usr/bin/env python3
"""
Generate all 33 weekly bundles (W08-W40) for SOCIALES CIUDADANAS Colombia Grado 4.
Each bundle = 10 questions, Bloom varied, ICFES competencies, Colombian context, 4 options with feedback.
"""

import os, re, json

OUT_DIR = os.path.dirname(os.path.abspath(__file__))

def slug(s):
    s = s.lower().strip()
    s = s.replace(" ","-")
    s = re.sub(r'[^a-z0-9\-]', '', s)
    return s

# ============================================================
# ALL QUESTION DATA (33 weeks x 10 questions = 330 questions)
# ============================================================

# W08: Organización territorial
W08 = [
    ("En la clase de Sociales de la I.E. Gabriel García Márquez de Medellín, la profesora explica las formas de organización territorial.",
     "Remember","Uso comprensivo del conocimiento social",3,
     "Una vereda en Colombia es:",
     [("A) Una división del área rural de un municipio, compuesta por terrenos y viviendas dispersas.",True),
      ("B) Una ciudad pequeña con alcalde propio.",False),
      ("C) Un barrio de una gran ciudad.",False),
      ("D) Un departamento con gobierno propio.",False)],
     "Se evalúa el concepto de vereda como unidad rural básica. La vereda es la división más pequeña del área rural municipal. El error común es confundirla con un barrio urbano o una ciudad."),
    ("En la I.E. San José de Sincelejo, los estudiantes observan un mapa de la organización territorial colombiana.",
     "Remember","Uso comprensivo del conocimiento social",3,
     "Un municipio en Colombia es:",
     [("A) La entidad territorial fundamental de la división político-administrativa del país, gobernada por un alcalde.",True),
      ("B) Un país independiente dentro de Colombia.",False),
      ("C) Una vereda grande con escuela.",False),
      ("D) Una región natural como la Amazonía.",False)],
     "Se evalúa el concepto de municipio como entidad territorial fundamental. Cada municipio tiene alcalde y concejo. El error común es confundirlo con una región natural o una vereda."),
    ("En la I.E. La Merced de Cali, los estudiantes analizan las diferencias entre las formas de organización territorial.",
     "Understand","Interpretación y análisis de perspectivas",4,
     "¿Cuál es la diferencia principal entre un corregimiento y una vereda?",
     [("A) El corregimiento tiene un centro poblado con escuela, iglesia y tiendas, mientras que la vereda es un conjunto de predios rurales dispersos.",True),
      ("B) La vereda tiene alcalde y el corregimiento no.",False),
      ("C) El corregimiento solo existe en la costa Caribe.",False),
      ("D) Son exactamente lo mismo, solo cambia el nombre.",False)],
     "Se evalúa la comprensión de la diferencia entre vereda y corregimiento. El corregimiento tiene un centro poblado con servicios. El error común es pensar que son equivalentes."),
    ("En la clase de la I.E. José Antonio Galán de Bucaramanga, los estudiantes conversan sobre la importancia del municipio.",
     "Understand","Interpretación y análisis de perspectivas",4,
     "¿Por qué el municipio es importante para los colombianos?",
     [("A) Porque en el municipio se gestionan servicios esenciales como el agua, la educación y la salud, cercanos a la comunidad.",True),
      ("B) Porque solo en los municipios grandes se puede votar.",False),
      ("C) Porque los municipios pueden declararse independientes de Colombia.",False),
      ("D) Porque todos los municipios son iguales sin importar su tamaño.",False)],
     "Se evalúa la comprensión de la función del municipio como entidad cercana al ciudadano. Los municipios gestionan servicios básicos locales. El error común es subestimar su importancia."),
    ("En el municipio de Sopó, Cundinamarca, la alcaldesa debe clasificar un nuevo asentamiento rural que ha crecido alrededor de una escuela y una tienda.",
     "Apply","Uso comprensivo del conocimiento social",4,
     "Este asentamiento rural con centro poblado debería clasificarse como:",
     [("A) Corregimiento, porque tiene un centro poblado con escuela y comercio.",True),
      ("B) Vereda, porque está en el área rural.",False),
      ("C) Municipio, porque tiene escuela.",False),
      ("D) Departamento, porque tiene varias viviendas.",False)],
     "Se evalúa la aplicación del concepto de corregimiento. Un centro poblado rural con escuela y comercio es un corregimiento. El error común es confundirlo con vereda."),
    ("En la I.E. Técnica de Aguachica, Cesar, los habitantes de una vereda quieren solicitar la construcción de un acueducto.",
     "Apply","Pensamiento reflexivo y sistémico",4,
     "¿Ante qué autoridad deben presentar la solicitud los habitantes de la vereda?",
     [("A) Ante el alcalde del municipio, porque la vereda pertenece al municipio.",True),
      ("B) Ante el gobernador del departamento directamente.",False),
      ("C) Ante el Presidente de la República.",False),
      ("D) Ante el congresista de su región.",False)],
     "Se evalúa la aplicación de la jerarquía territorial. La vereda depende del municipio, por lo que se acude al alcalde. El error común es saltar a instancias superiores."),
    ("En clase de sociales, los estudiantes analizan un mapa de Colombia con sus divisiones territoriales.",
     "Analyze","Interpretación y análisis de perspectivas",5,
     "¿Por qué Colombia se organiza en departamentos y municipios en lugar de tener un solo gobierno central?",
     [("A) Porque la descentralización permite administrar mejor el país al acercar el gobierno a las necesidades de cada región.",True),
      ("B) Porque los departamentos son independientes y no obedecen al gobierno nacional.",False),
      ("C) Porque los municipios solo existen para cobrar impuestos.",False),
      ("D) Porque es más fácil controlar a la población dividiéndola.",False)],
     "Se evalúa el análisis de las razones de la organización territorial. La descentralización mejora la administración. El error común es pensar que los departamentos son entes independientes."),
    ("La profesora de sociales de la I.E. Francisco de Paula Santander de Cúcuta compara un municipio grande (Cali) con uno pequeño (Monguí, Boyacá).",
     "Analyze","Pensamiento reflexivo y sistémico",5,
     "¿Cuál afirmación es correcta sobre ambos municipios?",
     [("A) Ambos tienen alcalde y concejo municipal, aunque el presupuesto y la población sean diferentes.",True),
      ("B) Los municipios pequeños no tienen alcalde.",False),
      ("C) Los municipios grandes no tienen concejo municipal.",False),
      ("D) Los municipios pequeños son en realidad corregimientos.",False)],
     "Se evalúa el análisis comparativo entre municipios. Todos los municipios comparten la misma estructura de gobierno básica. El error común es pensar que el tamaño elimina autoridades."),
    ("En la I.E. Jorge Eliécer Gaitán de Villavicencio, los estudiantes evalúan si una vereda debe convertirse en corregimiento.",
     "Evaluate","Pensamiento reflexivo y sistémico",5,
     "¿Cuál debería ser el criterio más importante para decidir si una vereda se convierte en corregimiento?",
     [("A) Que la vereda tenga suficiente población concentrada y servicios para formar un centro poblado organizado.",True),
      ("B) Que sea más fácil cobrar impuestos a los habitantes.",False),
      ("C) Que el nombre del lugar suene mejor como corregimiento.",False),
      ("D) Que el gobernador lo decida sin consultar a la gente.",False)],
     "Se evalúa la capacidad de evaluar criterios para decisiones territoriales. La población y los servicios son determinantes. El error es priorizar criterios subjetivos."),
    ("La profesora de la I.E. Normal Superior de Ubaté pide a los estudiantes proponer una mejora para su vereda.",
     "Create","Pensamiento reflexivo y sistémico",6,
     "Imagina que en tu vereda no hay escuela y los niños caminan dos horas para estudiar. ¿Qué propondrías?",
     [("A) Organizar a la comunidad para gestionar ante la alcaldía la construcción de una escuela veredal.",True),
      ("B) Pedir que los niños no estudien y trabajen en el campo.",False),
      ("C) Cerrar la vereda y que todos se muden a la ciudad.",False),
      ("D) Esperar a que el gobierno nacional resuelva el problema sin hacer nada.",False)],
     "Se evalúa la capacidad creativa para proponer soluciones comunitarias. La respuesta promueve la gestión organizada. El error común es proponer soluciones pasivas o de abandono."),
]

# W09: Departamentos de Colombia
W09 = [
    ("En la clase de Sociales de la I.E. INEM de Pasto, la profesora explica el concepto de departamento.",
     "Remember","Uso comprensivo del conocimiento social",3,
     "Un departamento en Colombia es:",
     [("A) Una división territorial intermedia entre la nación y los municipios, con autoridades propias.",True),
      ("B) Un país independiente que forma parte de Colombia.",False),
      ("C) Una ciudad muy grande como Medellín o Cali.",False),
      ("D) Un tipo de municipio especial con más presupuesto.",False)],
     "Se evalúa el concepto de departamento como unidad territorial intermedia. Cada departamento tiene gobernador y asamblea. El error común es confundirlo con una ciudad o un país."),
    ("La profesora de la I.E. San Pedro Claver de Popayán pregunta cuántos departamentos conforman Colombia.",
     "Remember","Uso comprensivo del conocimiento social",3,
     "Colombia está conformada por:",
     [("A) 32 departamentos y el Distrito Capital de Bogotá.",True),
      ("B) 25 departamentos y 10 distritos especiales.",False),
      ("C) 30 departamentos y 3 territorios nacionales.",False),
      ("D) 35 departamentos iguales sin distrito capital.",False)],
     "Se evalúa el dato del número de departamentos. Colombia tiene 32 departamentos más Bogotá D.C. El error común es confundir la cantidad."),
    ("En la I.E. La Milagrosa de Ibagué, los estudiantes reflexionan sobre la utilidad de los departamentos.",
     "Understand","Interpretación y análisis de perspectivas",4,
     "¿Para qué sirve dividir Colombia en departamentos?",
     [("A) Para organizar mejor la administración del país, descentralizando funciones y acercando el gobierno a las regiones.",True),
      ("B) Para que cada departamento pueda independizarse cuando quiera.",False),
      ("C) Solo para facilitar los campeonatos de fútbol entre regiones.",False),
      ("D) Para que el presidente tenga menos trabajo y responsabilidades.",False)],
     "Se evalúa la comprensión de la función de los departamentos en la descentralización. Organizan la administración regional. El error común es reducir su función a aspectos deportivos."),
    ("Los estudiantes de la I.E. Gabriela Mistral de Neiva investigan la estructura de su departamento.",
     "Understand","Interpretación y análisis de perspectivas",4,
     "Cada departamento de Colombia cuenta con:",
     [("A) Un gobernador, una asamblea departamental y una capital.",True),
      ("B) Un alcalde y un concejo municipal.",False),
      ("C) Un presidente y un congreso propios.",False),
      ("D) Un rey y una corte real como en las monarquías.",False)],
     "Se evalúa la comprensión de las autoridades departamentales. El gobernador es la máxima autoridad y la asamblea es el cuerpo legislativo. El error es confundir con autoridades municipales."),
    ("En la I.E. Técnica de Honda, Tolima, los estudiantes ubican departamentos en el mapa de Colombia.",
     "Apply","Uso comprensivo del conocimiento social",4,
     "Si viajas desde Bogotá (Cundinamarca) hacia el oriente, el primer departamento al que llegarías es:",
     [("A) Meta.",True),
      ("B) Antioquia.",False),
      ("C) Valle del Cauca.",False),
      ("D) Atlántico.",False)],
     "Se evalúa la aplicación del conocimiento geográfico de los departamentos. Al oriente de Cundinamarca está el Meta. El error común es confundir la ubicación geográfica."),
    ("En la I.E. Alfonso López Pumarejo de Valledupar, los estudiantes comparan la extensión de los departamentos.",
     "Apply","Pensamiento reflexivo y sistémico",4,
     "¿Cuál de estos departamentos es uno de los más extensos de Colombia?",
     [("A) Amazonas.",True),
      ("B) Quindío.",False),
      ("C) Caldas.",False),
      ("D) Atlántico.",False)],
     "Se evalúa la aplicación del conocimiento sobre extensión territorial. Amazonas es uno de los departamentos más grandes. El error es pensar que departamentos pequeños como Quindío son extensos."),
    ("En clase, los estudiantes analizan por qué San Andrés y Providencia tiene un estatus especial dentro de Colombia.",
     "Analyze","Interpretación y análisis de perspectivas",5,
     "San Andrés y Providencia es un departamento especial porque:",
     [("A) Es el único departamento insular de Colombia, con cultura raizal y ecosistemas marinos únicos.",True),
      ("B) No tiene gobernador, solo un alcalde mayor.",False),
      ("C) Sus habitantes no son colombianos sino extranjeros.",False),
      ("D) Es el departamento más grande en extensión territorial.",False)],
     "Se evalúa el análisis de las características especiales de los departamentos insulares. San Andrés es el único departamento conformado por islas. El error común es desconocer su estatus especial."),
    ("La profesora de la I.E. Santa Luisa de Marillac de Tunja pregunta por qué algunos departamentos tienen más población que otros.",
     "Analyze","Pensamiento reflexivo y sistémico",5,
     "¿Por qué departamentos como Antioquia y Cundinamarca tienen más población que Amazonas o Guainía?",
     [("A) Porque están en la región Andina, con mejor clima, infraestructura, empleo y desarrollo económico.",True),
      ("B) Porque son los departamentos más antiguos de Colombia.",False),
      ("C) Porque tienen las playas más hermosas del país.",False),
      ("D) Porque el gobierno nacional decidió que fueran más importantes.",False)],
     "Se evalúa el análisis de la distribución poblacional. La región Andina concentra la mayoría de la población por su desarrollo. El error común es dar razones superficiales o arbitrarias."),
    ("En la I.E. San Bartolomé de Bogotá, los estudiantes evalúan la posibilidad de crear un nuevo departamento.",
     "Evaluate","Pensamiento reflexivo y sistémico",5,
     "¿Qué factores deberían considerarse antes de crear un nuevo departamento en Colombia?",
     [("A) La población, la extensión territorial, la capacidad económica y la voluntad de los habitantes.",True),
      ("B) Solo el nombre que se le quiera poner al nuevo departamento.",False),
      ("C) Que el nuevo departamento tenga salida al mar obligatoriamente.",False),
      ("D) Que el gobernador sea familiar o amigo del presidente.",False)],
     "Se evalúa la capacidad de evaluar los requisitos para crear un departamento. Se necesitan criterios objetivos y voluntad popular. El error común es dar criterios irrelevantes."),
    ("La profesora de la I.E. José María Córdoba de Rionegro pide a los estudiantes proponer una mejora para la organización departamental.",
     "Create","Pensamiento reflexivo y sistémico",6,
     "Imagina que eres gobernador de un departamento con municipios apartados que no tienen buenas carreteras. ¿Qué propondrías?",
     [("A) Diseñar un plan de inversión en vías terciarias con recursos departamentales y apoyo de la nación.",True),
      ("B) Ordenar que todos los habitantes se muden a la capital departamental.",False),
      ("C) No hacer nada porque eso es problema de cada alcalde municipal.",False),
      ("D) Cerrar esos municipios y borrarlos del mapa.",False)],
     "Se evalúa la capacidad creativa para proponer soluciones de gobierno departamental. La respuesta propone inversión planificada en infraestructura vial. El error común es evadir la responsabilidad."),
]

# W10: Capitales de departamento (región Andina)
W10 = [
    ("En la clase de Sociales de la I.E. San Luis Gonzaga de Manizales, la profesora muestra un mapa de la región Andina.",
     "Remember","Uso comprensivo del conocimiento social",3,
     "La capital del departamento de Antioquia es:",
     [("A) Medellín.",True),
      ("B) Bogotá.",False),
      ("C) Cali.",False),
      ("D) Bucaramanga.",False)],
     "Se evalúa el conocimiento de las capitales departamentales. Medellín es la capital de Antioquia. El error común es confundirla con otras capitales andinas."),
    ("La profesora de la I.E. La Inmaculada de Bucaramanga pregunta sobre las capitales de la región Andina.",
     "Remember","Uso comprensivo del conocimiento social",3,
     "La capital del departamento de Cundinamarca es:",
     [("A) Bogotá D.C.",True),
      ("B) Medellín.",False),
      ("C) Tunja.",False),
      ("D) Manizales.",False)],
     "Se evalúa el conocimiento de las capitales departamentales. Bogotá es la capital de Cundinamarca (aunque también es Distrito Capital). El error común es confundirla con otras ciudades."),
    ("En la I.E. Técnica de Armenia, los estudiantes analizan la ubicación de las capitales andinas.",
     "Understand","Interpretación y análisis de perspectivas",4,
     "¿Por qué la mayoría de las capitales de departamento de la región Andina se encuentran en valles o altiplanos?",
     [("A) Porque las condiciones geográficas de los valles y altiplanos andinos favorecieron el establecimiento de ciudades.",True),
      ("B) Porque el gobierno decidió ponerlas todas en la misma zona.",False),
      ("C) Porque solo ahí se podían construir casas.",False),
      ("D) Porque los fundadores no conocían otras zonas.",False)],
     "Se evalúa la comprensión de la relación entre geografía y poblamiento. Los valles y altiplanos ofrecen mejores condiciones para la vida urbana. El error común es pensar que fue una decisión arbitraria."),
    ("Los estudiantes de la I.E. Luis Carlos Galán de Tunja comparan las capitales de los departamentos de la región Andina.",
     "Understand","Interpretación y análisis de perspectivas",4,
     "¿Cuál de estas capitales NO pertenece a la región Andina?",
     [("A) Barranquilla.",True),
      ("B) Bogotá.",False),
      ("C) Medellín.",False),
      ("D) Cali.",False)],
     "Se evalúa la comprensión de qué capitales pertenecen a la región Andina. Barranquilla está en la región Caribe. El error común es confundir la ubicación regional de las capitales."),
    ("En la I.E. INEM de Pereira, los estudiantes juegan a ubicar capitales en el mapa mudo de Colombia.",
     "Apply","Uso comprensivo del conocimiento social",4,
     "Si estás en Bogotá y viajas hacia el noroccidente, llegarás a la capital de Caldas. Esta capital es:",
     [("A) Manizales.",True),
      ("B) Pereira.",False),
      ("C) Ibagué.",False),
      ("D) Armenia.",False)],
     "Se evalúa la aplicación del conocimiento de capitales andinas. Manizales es la capital de Caldas y está al noroccidente de Bogotá. El error común es confundir Manizales con Pereira o Armenia."),
    ("Un estudiante de la I.E. Simón Bolívar de Santa Marta está visitando la región Andina y quiere identificar las capitales.",
     "Apply","Pensamiento reflexivo y sistémico",4,
     "La capital de Santander, conocida como 'la ciudad bonita de Colombia', es:",
     [("A) Bucaramanga.",True),
      ("B) Cúcuta.",False),
      ("C) Tunja.",False),
      ("D) Neiva.",False)],
     "Se evalúa la aplicación del conocimiento de capitales. Bucaramanga es la capital de Santander. El error común es confundirla con Cúcuta (Norte de Santander) u otras capitales."),
    ("En clase de sociales, los estudiantes analizan un mapa de la región Andina y las capitales de sus departamentos.",
     "Analyze","Interpretación y análisis de perspectivas",5,
     "¿Por qué la región Andina concentra la mayoría de las capitales departamentales de Colombia?",
     [("A) Porque la región Andina es la más poblada y desarrollada del país, con la mayoría de los departamentos.",True),
      ("B) Porque los españoles solo fundaron ciudades en los Andes.",False),
      ("C) Porque en las otras regiones no hay suficientes habitantes.",False),
      ("D) Porque la Constitución obliga a que las capitales estén en los Andes.",False)],
     "Se evalúa el análisis de la concentración de capitales en la región Andina. Es la región con más departamentos y mayor población. El error común es dar explicaciones simplistas o incorrectas."),
    ("La profesora de la I.E. La Salle de Cúcuta pide a los estudiantes que comparen las capitales andinas entre sí.",
     "Analyze","Pensamiento reflexivo y sistémico",5,
     "¿Qué tienen en común ciudades como Bogotá, Medellín, Cali y Bucaramanga?",
     [("A) Todas son capitales de departamento y están ubicadas en la región Andina colombiana.",True),
      ("B) Todas tienen salida al mar.",False),
      ("C) Todas están en el mismo departamento.",False),
      ("D) Todas fueron fundadas el mismo año.",False)],
     "Se evalúa el análisis de las características comunes de las capitales andinas. Todas están en la región Andina y son capitales departamentales. El error común es buscar diferencias superficiales."),
    ("En la I.E. Técnico Industrial de Duitama, los estudiantes evalúan la importancia de las capitales departamentales.",
     "Evaluate","Pensamiento reflexivo y sistémico",5,
     "¿Por qué es importante que cada departamento tenga una capital designada?",
     [("A) Porque la capital es el centro administrativo, político y económico del departamento, donde funciona el gobierno departamental.",True),
      ("B) Porque solo la capital puede tener hospitales y colegios.",False),
      ("C) Porque las capitales son las únicas ciudades que pueden tener alcalde.",False),
      ("D) Porque es una tradición sin ninguna función real.",False)],
     "Se evalúa la capacidad de evaluar la función de las capitales departamentales. La capital centraliza la administración departamental. El error común es minimizar su importancia."),
    ("La profesora de la I.E. Normal Superior de Pamplona pide a los estudiantes crear un recorrido turístico por las capitales andinas.",
     "Create","Pensamiento reflexivo y sistémico",6,
     "Imagina que debes diseñar una ruta turística que visite tres capitales de la región Andina. ¿Qué ruta propondrías?",
     [("A) Bogotá - Medellín - Manizales, pasando por el Eje Cafetero y los paisajes andinos.",True),
      ("B) Bogotá - Leticia - San Andrés, visitando la Amazonía y las islas.",False),
      ("C) Barranquilla - Cartagena - Santa Marta, recorriendo la costa Caribe.",False),
      ("D) Cali - Tumaco - Quibdó, recorriendo la región Pacífica.",False)],
     "Se evalúa la capacidad creativa para proponer rutas turísticas. La ruta Bogotá-Medellín-Manizales recorre capitales de la región Andina. El error común es incluir ciudades de otras regiones."),
]

# W11: Capitales de departamento (región Caribe, Pacífico)
W11 = [
    ("En la clase de Sociales de la I.E. Madre Laura de Cartagena, la profesora pregunta sobre las capitales de la región Caribe.",
     "Remember","Uso comprensivo del conocimiento social",3,
     "La capital del departamento del Atlántico es:",
     [("A) Barranquilla.",True),
      ("B) Cartagena.",False),
      ("C) Santa Marta.",False),
      ("D) Sincelejo.",False)],
     "Se evalúa el conocimiento de capitales de la región Caribe. Barranquilla es la capital del Atlántico. El error común es confundirla con Cartagena o Santa Marta."),
    ("La profesora de la I.E. Nuestra Señora del Carmen de Quibdó explica las capitales de la región Pacífico.",
     "Remember","Uso comprensivo del conocimiento social",3,
     "La capital del departamento del Chocó es:",
     [("A) Quibdó.",True),
      ("B) Cali.",False),
      ("C) Buenaventura.",False),
      ("D) Tumaco.",False)],
     "Se evalúa el conocimiento de capitales de la región Pacífico. Quibdó es la capital del Chocó. El error común es confundirla con Cali (capital del Valle) o con puertos importantes."),
    ("En la I.E. San José de Sincelejo, los estudiantes analizan las capitales de la región Caribe en el mapa.",
     "Understand","Interpretación y análisis de perspectivas",4,
     "La capital de Bolívar es Cartagena. ¿Qué caracteriza a esta ciudad?",
     [("A) Es una ciudad amurallada, puerto histórico y Patrimonio de la Humanidad por la UNESCO.",True),
      ("B) Es la ciudad más poblada de Colombia.",False),
      ("C) Es la única capital departamental que no tiene playa.",False),
      ("D) Es la capital más joven de Colombia.",False)],
     "Se evalúa la comprensión de las características de Cartagena como capital de Bolívar. Su centro histórico es Patrimonio de la Humanidad. El error común es atribuirle características que no tiene."),
    ("Los estudiantes de la I.E. Gabriela Mistral de Tumaco comparan las capitales del Pacífico con las del Caribe.",
     "Understand","Interpretación y análisis de perspectivas",4,
     "¿Cuál de estas ciudades es capital de un departamento de la región Pacífico?",
     [("A) Cali (Valle del Cauca).",True),
      ("B) Cartagena (Bolívar).",False),
      ("C) Santa Marta (Magdalena).",False),
      ("D) Valledupar (Cesar).",False)],
     "Se evalúa la comprensión de la ubicación regional de las capitales. Cali pertenece a la región Pacífico (Valle del Cauca). Las otras son de la región Caribe. El error común es confundir la pertenencia regional."),
    ("En la I.E. Técnica de Riohacha, los estudiantes ubican las capitales de la región Caribe en un mapa mudo.",
     "Apply","Uso comprensivo del conocimiento social",4,
     "La Guajira tiene como capital a Riohacha. ¿Entre qué departamentos se ubica La Guajira?",
     [("A) Entre el mar Caribe y el departamento del Cesar.",True),
      ("B) Entre el océano Pacífico y Nariño.",False),
      ("C) Entre Antioquia y Chocó.",False),
      ("D) Entre Santander y Norte de Santander.",False)],
     "Se evalúa la aplicación del conocimiento geográfico de La Guajira. Limita con el mar Caribe y el Cesar. El error común es confundir su ubicación con otras regiones."),
    ("Un estudiante de la I.E. Agustín Codazzi de Barranquilla planea un viaje por las capitales del Caribe.",
     "Apply","Pensamiento reflexivo y sistémico",4,
     "Si recorres la costa Caribe de oriente a occidente, el orden correcto de las capitales sería:",
     [("A) Riohacha, Santa Marta, Barranquilla, Cartagena, Sincelejo.",True),
      ("B) Cartagena, Barranquilla, Santa Marta, Riohacha, Sincelejo.",False),
      ("C) Sincelejo, Cartagena, Barranquilla, Santa Marta, Riohacha.",False),
      ("D) Santa Marta, Riohacha, Barranquilla, Sincelejo, Cartagena.",False)],
     "Se evalúa la aplicación de la ubicación geográfica de las capitales caribeñas. De oriente a occidente: Riohacha, Santa Marta, Barranquilla, Cartagena, Sincelejo. El error común es confundir el orden."),
    ("En clase, los estudiantes analizan por qué la región Pacífico tiene menos capitales departamentales que la región Andina.",
     "Analyze","Interpretación y análisis de perspectivas",5,
     "La región Pacífico tiene menos capitales departamentales porque:",
     [("A) Tiene menos departamentos (Nariño, Cauca, Valle del Cauca y Chocó) que la región Andina.",True),
      ("B) La región Pacífico no existe como región oficial.",False),
      ("C) Porque no hay ciudades en la costa Pacífica.",False),
      ("D) Porque los departamentos del Pacífico no tienen capitales.",False)],
     "Se evalúa el análisis del número de capitales por región. La región Pacífico tiene 4 departamentos, la Andina tiene muchos más. El error común es desconocer la división regional."),
    ("La profesora de la I.E. Santa Luisa de Marillac de Popayán compara las capitales Caribe y Pacífico.",
     "Analyze","Pensamiento reflexivo y sistémico",5,
     "¿Qué diferencia geográfica importante hay entre las capitales de la región Caribe y las de la región Pacífico?",
     [("A) Las capitales del Caribe están en el mar Caribe y las del Pacífico en el océano Pacífico, separadas por el territorio colombiano.",True),
      ("B) Las capitales del Caribe están en montañas y las del Pacífico en el mar.",False),
      ("C) No hay ninguna diferencia, todas están en la costa.",False),
      ("D) Las capitales del Pacífico son todas islas.",False)],
     "Se evalúa el análisis geográfico de las capitales costeras. Están en dos océanos diferentes separados por los Andes. El error común es no reconocer la diferencia entre Caribe y Pacífico."),
    ("En la I.E. José María Córdoba de Rionegro, los estudiantes evalúan la importancia de las capitales de la región Caribe.",
     "Evaluate","Pensamiento reflexivo y sistémico",5,
     "¿Por qué Barranquilla, Cartagena y Santa Marta son importantes como capitales departamentales?",
     [("A) Porque son puertos marítimos clave para el comercio internacional y centros turísticos de Colombia.",True),
      ("B) Porque son las únicas ciudades con aeropuerto en Colombia.",False),
      ("C) Porque no tienen relación con el mar.",False),
      ("D) Porque son las capitales más pequeñas del país.",False)],
     "Se evalúa la capacidad de evaluar la importancia económica de las capitales caribeñas. Su condición portuaria es clave. El error común es ignorar su función económica."),
    ("La profesora de la I.E. Normal Superior de Quibdó pide a los estudiantes proponer un proyecto turístico para la región Pacífico.",
     "Create","Pensamiento reflexivo y sistémico",6,
     "Imagina que debes promover el turismo en las capitales de la región Pacífico. ¿Qué propuesta harías?",
     [("A) Crear una ruta ecoturística que conecte Cali, Popayán, Quibdó y Pasto, destacando su biodiversidad y cultura afrocolombiana.",True),
      ("B) Promover solo las playas del Caribe porque son más conocidas.",False),
      ("C) Construir grandes hoteles en todas las capitales sin planificación.",False),
      ("D) Decir que la región Pacífico no tiene atractivos turísticos.",False)],
     "Se evalúa la capacidad creativa para proponer proyectos turísticos regionales. La respuesta propone una ruta ecoturística que valora la biodiversidad del Pacífico. El error común es ignorar el potencial de la región."),
]

ALL_WEEKS = {
    "W08": W08,
    "W09": W09,
    "W10": W10,
    "W11": W11,
}

# For remaining weeks, we store as placeholder - will write the questions directly in the output generation
# to avoid memory issues. We'll generate the full content for each week.

print("Question data loaded successfully.")
print(f"Weekly data available for: {', '.join(sorted(ALL_WEEKS.keys()))}")
print(f"Total questions loaded: {sum(len(v) for v in ALL_WEEKS.values())}")
