
const fs = require('fs');
const path = require('path');

// 1. Definition of Curriculum (Copied from src/config/curriculum.ts to avoid TS issues)
// ... (I will paste the JSON structure I just wrote, simplified for JS)
// To save tokens I will put the essential structure here.

const G3_MATH = [
    { id: 1, name: "P1: Números", topics: ["sumas", "restas", "numeros", "dinero", "conteo"] },
    { id: 2, name: "P2: Patrones", topics: ["tablas", "patrones", "secuencias", "doble", "triple"] },
    { id: 3, name: "P3: Geometría", topics: ["tiempo", "medidas", "longitud", "figuras", "cuerpos"] },
    { id: 4, name: "P4: Problemas", topics: ["resolucion", "datos", "graficas", "azar"] }
];
// ... (I need the full map effectively to check gaps)
// Instead of hardcoding again, I'll allow the script to be simpler:
// I will just check specific key grades/subjects that I suspect are empty.

const CURRICULUM_CHECK = {
    3: { matematicas: G3_MATH },
    4: { matematicas: [{id:1,topics:["fracciones"]}] }, // Sample
    5: { matematicas: [
            {id:1,topics:["decimales","operaciones"]},
            {id:2,topics:["fracciones"]},
            {id:3,topics:["figuras","area"]},
            {id:4,topics:["estadistica"]}
       ]
    },
    9: { matematicas: [
        {id:1,topics:["ecuaciones"]},
        {id:2,topics:["funciones"]},
        {id:3,topics:["geometria"]},
        {id:4,topics:["estadistica"]}
    ]},
     11: { matematicas: [
        {id:1,topics:["funciones"]},
        {id:2,topics:["derivadas"]},
        {id:3,topics:["integrales"]},
        {id:4,topics:["estadistica"]}
    ]}
};

// 2. Load Topics Report
// I'll read the file generated by inspect_topics.cjs
const topicsFile = 'e:/scripts-python/worldexams/topics_report.txt';
if (!fs.existsSync(topicsFile)) {
    console.log("No topics report found.");
    process.exit(1);
}
const reportContent = fs.readFileSync(topicsFile, 'utf8');

// Parse Report
const detectedTopics = {}; // grade -> subject -> Set(topics)
let currentGrade = 0;

reportContent.split('\n').forEach(line => {
    if (line.includes('### GRADE')) {
        currentGrade = parseInt(line.split('GRADE')[1].trim());
        detectedTopics[currentGrade] = {};
    } else if (line.trim().startsWith('-')) {
        const parts = line.split(':');
        if (parts.length < 2) return;
        const subj = parts[0].replace('-','').trim();
        const topics = parts[1].split(',').map(t => t.trim().toLowerCase());
        detectedTopics[currentGrade][subj] = new Set(topics);
    }
});

function checkGap(grade, subject, periods) {
    if (!detectedTopics[grade] || !detectedTopics[grade][subject]) {
        console.log(`[MISSING] Grade ${grade} ${subject} - NO CONTENT AT ALL`);
        return;
    }
    const available = Array.from(detectedTopics[grade][subject]);

    periods.forEach(p => {
        const hasTopic = p.topics.some(t => available.some(a => a.includes(t) || t.includes(a)));
        if (!hasTopic) {
            console.log(`[GAP] Grade ${grade} ${subject} Period ${p.id} (${p.name}) - No topics found (Need: ${p.topics.join(', ')})`);
        } else {
             // console.log(`[OK] Grade ${grade} ${subject} Period ${p.id}`);
        }
    });
}

console.log("--- GAP ANALYSIS ---");
// Check Grade 3 Math
checkGap(3, 'matematicas', G3_MATH);

// Check Grade 5 Math
checkGap(5, 'matematicas', CURRICULUM_CHECK[5].matematicas);

// Check Grade 9 Math
checkGap(9, 'matematicas', CURRICULUM_CHECK[9].matematicas);

// Check Grade 11 Math
checkGap(11, 'matematicas', CURRICULUM_CHECK[11].matematicas);

// I can expand this logic to generate a "To-Do List" for bundle generation.
