#!/usr/bin/env python3
"""
Generate MASTERY bundles for Grado 7 - W03 through W40
Subjects: MATEMATICAS, CIENCIAS NATURALES, LENGUA
Protocol v5.2
"""

import os
import json

BASE = r"E:\scripts-python\worldexams\questions_data\colombia"

# ─── Config ───────────────────────────────────────────────────────────────

SUBJECTS = {
    "matematicas": {
        "topics": ["numeros-enteros", "racionales", "algebra-basica", "ecuaciones-lineales", "proporcionalidad", "estadistica"],
        "prefix": "CO-MAT",
        "dir": "matematicas",
    },
    "ciencias-naturales": {
        "topics": ["sistema-nervioso", "sistema-endocrino", "genetica-basica", "ADN", "reproduccion", "salud"],
        "prefix": "CO-CN",
        "dir": "ciencias-naturales",
    },
    "lengua": {
        "topics": ["generos-literarios", "literatura-colombiana-sXIX", "textos-argumentativos", "ensayo", "poesia"],
        "prefix": "CO-LEN",
        "dir": "lengua",
    },
}

# ─── Question Templates ───────────────────────────────────────────────────

MAT_QUESTIONS = {
    "numeros-enteros": [
        # D3 Remember
        {"v": 1, "d": "D3", "bloom": "Remember", "icfes": "Uso comprensivo del conocimiento científico",
         "ctx": "En el colegio, la profesora pregunta sobre la definición del valor absoluto de un número entero.",
         "es": 0.85,
         "q": "¿Qué es el valor absoluto de un número entero?",
         "opts": [
            ("A", "La distancia desde el número hasta el cero en la recta numérica.", True),
            ("B", "El número sin importar su signo, pero siempre negativo.", False),
            ("C", "El resultado de sumar el número con su opuesto.", False),
            ("D", "El número redondeado a la decena más cercana.", False),
         ],
         "exp": "El valor absoluto de un entero es su distancia al cero en la recta numérica, siempre un número no negativo. |−5| = 5, |3| = 3."},
        # D4 Understand
        {"v": 2, "d": "D4", "bloom": "Understand", "icfes": "Explicación de fenómenos",
         "ctx": "En una ciudad colombiana, la temperatura pasó de 5°C a -4°C durante la noche. Camila registra los datos.",
         "es": 0.80,
         "q": "¿Cuántos grados descendió la temperatura?",
         "opts": [
            ("A", "9°C", True),
            ("B", "1°C", False),
            ("C", "5°C", False),
            ("D", "-9°C", False),
         ],
         "exp": "La diferencia es 5 − (−4) = 5 + 4 = 9°C de descenso. Como restamos un negativo, sumamos."},
        # D4 Apply
        {"v": 3, "d": "D4", "bloom": "Apply", "icfes": "Uso comprensivo del conocimiento científico",
         "ctx": "Pedro tenía $25.000 en su alcancía y gastó $32.000 en un videojuego. Pidió prestado a su mamá.",
         "es": 0.78,
         "q": "¿Cuál es el saldo de Pedro después del gasto?",
         "opts": [
            ("A", "-$7.000", True),
            ("B", "$7.000", False),
            ("C", "-$57.000", False),
            ("D", "$57.000", False),
         ],
         "exp": "25.000 − 32.000 = −7.000, indicando una deuda de $7.000. Los números negativos representan deudas."},
        # D5 Apply
        {"v": 4, "d": "D5", "bloom": "Apply", "icfes": "Indagación",
         "ctx": "Un buzo en San Andrés está a -15 m y luego desciende 8 m más.",
         "es": 0.75,
         "q": "¿A qué profundidad está el buzo después del descenso?",
         "opts": [
            ("A", "-23 m", True),
            ("B", "-7 m", False),
            ("C", "23 m", False),
            ("D", "7 m", False),
         ],
         "exp": "−15 + (−8) = −23 m. Descender más profundidad significa sumar más negativo."},
        # D5 Understand
        {"v": 5, "d": "D5", "bloom": "Understand", "icfes": "Explicación de fenómenos",
         "ctx": "En clase, el profesor escribe en el tablero: −2, 5, −7, 0, 3, −1.",
         "es": 0.78,
         "q": "¿Cuál es el orden de menor a mayor?",
         "opts": [
            ("A", "−7, −2, −1, 0, 3, 5", True),
            ("B", "5, 3, 0, −1, −2, −7", False),
            ("C", "−7, 5, −2, 3, −1, 0", False),
            ("D", "0, −1, −2, 3, 5, −7", False),
         ],
         "exp": "En la recta numérica, los números negativos con mayor valor absoluto son menores. −7 < −2 < −1 < 0 < 3 < 5."},
        # D5 Apply - operaciones combinadas
        {"v": 6, "d": "D5", "bloom": "Apply", "icfes": "Uso comprensivo del conocimiento científico",
         "ctx": "Santiago resuelve: (−8) + 3 − (−2) × 4 en su cuaderno.",
         "es": 0.72,
         "q": "¿Cuál es el resultado?",
         "opts": [
            ("A", "3", True),
            ("B", "−13", False),
            ("C", "−1", False),
            ("D", "−20", False),
         ],
         "exp": "Primero la multiplicación: (−2)×4 = −8. Luego: −8 + 3 − (−8) = −8 + 3 + 8 = 3."},
        # D6 Analyze
        {"v": 7, "d": "D6", "bloom": "Analyze", "icfes": "Indagación",
         "ctx": "En un concurso de matemáticas, deben hallar el número que falta: □ + (−5) = 7.",
         "es": 0.65,
         "q": "¿Qué número debe ir en el cuadro?",
         "opts": [
            ("A", "12", True),
            ("B", "2", False),
            ("C", "−12", False),
            ("D", "−2", False),
         ],
         "exp": "x + (−5) = 7 → x = 7 − (−5) = 7 + 5 = 12."},
        # D6 Analyze
        {"v": 8, "d": "D6", "bloom": "Analyze", "icfes": "Explicación de fenómenos",
         "ctx": "Camila dice que (−6) × (−4) = −24, pero su profesor dice que está mal.",
         "es": 0.62,
         "q": "¿Cuál es el error?",
         "opts": [
            ("A", "Debe ser +24 porque menos por menos es más.", True),
            ("B", "Debe ser −10 porque se suman.", False),
            ("C", "Debe ser 10 porque −6 + (−4) = −10.", False),
            ("D", "Está correcto, negativo por negativo da negativo.", False),
         ],
         "exp": "(−6)×(−4) = +24. La regla: signos iguales dan positivo; signos diferentes dan negativo."},
        # D7 Evaluate
        {"v": 9, "d": "D7", "bloom": "Evaluate", "icfes": "Uso comprensivo del conocimiento científico",
         "ctx": "En Pereira, Andrés afirma: n − (−8) siempre es mayor que n + 2 para cualquier entero n.",
         "es": 0.55,
         "q": "¿Es correcta la afirmación?",
         "opts": [
            ("A", "Sí, porque n − (−8) = n + 8, que es 6 unidades mayor que n + 2.", True),
            ("B", "No, porque depende del valor de n.", False),
            ("C", "Sí, pero solo si n es positivo.", False),
            ("D", "No, porque n + 8 es menor que n + 2.", False),
         ],
         "exp": "n − (−8) = n + 8. Comparado con n + 2, siempre es 6 unidades mayor para cualquier n entero."},
        # D7 Evaluate
        {"v": 10, "d": "D7", "bloom": "Evaluate", "icfes": "Indagación",
         "ctx": "En el colegio INEM de Neiva, la profesora pregunta: si a = −4 y b = −6, ¿qué expresión es mayor: a + b o a × b?",
         "es": 0.52,
         "q": "¿Cuál es la respuesta?",
         "opts": [
            ("A", "a × b, porque (−4)+(−6) = −10 y (−4)×(−6) = 24, y 24 > −10.", True),
            ("B", "a + b, porque la suma siempre es mayor que la multiplicación.", False),
            ("C", "Son iguales.", False),
            ("D", "a + b, porque −10 > 24.", False),
         ],
         "exp": "Suma: −4 + (−6) = −10. Producto: (−4)×(−6) = +24. Como 24 > −10, el producto es mayor."},
        # D8 Analyze
        {"v": 11, "d": "D8", "bloom": "Analyze", "icfes": "Explicación de fenómenos",
         "ctx": "María calcula |−6| + |−4| − |2| en su taller de matemáticas.",
         "es": 0.48,
         "q": "¿Cuál es el resultado?",
         "opts": [
            ("A", "8", True),
            ("B", "12", False),
            ("C", "0", False),
            ("D", "−8", False),
         ],
         "exp": "|−6| = 6, |−4| = 4, |2| = 2. 6 + 4 − 2 = 8."},
        # D8 Evaluate
        {"v": 12, "d": "D8", "bloom": "Evaluate", "icfes": "Uso comprensivo del conocimiento científico",
         "ctx": "El profesor plantea: \"Si multiplico tres números enteros y el resultado es negativo, ¿cuántos factores negativos hay?\"",
         "es": 0.45,
         "q": "¿Cuál es la respuesta correcta?",
         "opts": [
            ("A", "Debe haber un número impar de factores negativos.", True),
            ("B", "Debe haber un número par de factores negativos.", False),
            ("C", "Todos deben ser negativos.", False),
            ("D", "Ninguno puede ser negativo.", False),
         ],
         "exp": "El producto de números negativos es negativo solo si hay una cantidad impar de factores negativos. (−)×(−)×(−) = (−) porque 3 es impar."},
    ],
    "racionales": [
        # D3 Remember
        {"v": 1, "d": "D3", "bloom": "Remember", "icfes": "Uso comprensivo del conocimiento científico",
         "ctx": "En el colegio de Cali, la profesora pregunta cómo se llama el número de arriba en una fracción.",
         "es": 0.85,
         "q": "¿Cómo se llama el número superior de una fracción (a/b)?",
         "opts": [
            ("A", "Numerador", True),
            ("B", "Denominador", False),
            ("C", "Cociente", False),
            ("D", "Divisor", False),
         ],
         "exp": "En la fracción a/b, a es el numerador (partes tomadas) y b es el denominador (partes totales)."},
        # D4 Understand
        {"v": 2, "d": "D4", "bloom": "Understand", "icfes": "Explicación de fenómenos",
         "ctx": "María quiere compartir una hamburguesa dividida en 6 partes iguales y come 2.",
         "es": 0.82,
         "q": "¿Qué fracción representa lo que comió María?",
         "opts": [
            ("A", "2/6", True),
            ("B", "6/2", False),
            ("C", "4/6", False),
            ("D", "2/4", False),
         ],
         "exp": "Comió 2 de 6 partes, que es la fracción 2/6. Al simplificar, 2/6 = 1/3."},
        # D4 Apply
        {"v": 3, "d": "D4", "bloom": "Apply", "icfes": "Uso comprensivo del conocimiento científico",
         "ctx": "Carlos divide una cartulina de 2 metros en 5 partes iguales para un proyecto escolar.",
         "es": 0.80,
         "q": "¿Cuánto mide cada parte en metros?",
         "opts": [
            ("A", "0.4 m", True),
            ("B", "0.2 m", False),
            ("C", "0.5 m", False),
            ("D", "2.5 m", False),
         ],
         "exp": "2 ÷ 5 = 0.4 m. También se expresa como 2/5 de metro."},
        # D5 Apply
        {"v": 4, "d": "D5", "bloom": "Apply", "icfes": "Indagación",
         "ctx": "Laura prepara limonada: 1/2 taza de jugo de limón y 2/3 taza de agua.",
         "es": 0.75,
         "q": "¿Cuánto líquido tiene la mezcla?",
         "opts": [
            ("A", "7/6 de taza", True),
            ("B", "3/5 de taza", False),
            ("C", "2/6 de taza", False),
            ("D", "1 taza", False),
         ],
         "exp": "1/2 + 2/3 = 3/6 + 4/6 = 7/6 = 1 entero y 1/6 de taza."},
        # D5 Understand
        {"v": 5, "d": "D5", "bloom": "Understand", "icfes": "Explicación de fenómenos",
         "ctx": "El profesor muestra: 3/6, 1/2, 4/8, 5/10.",
         "es": 0.78,
         "q": "¿Qué tienen en común estas fracciones?",
         "opts": [
            ("A", "Todas son equivalentes a 1/2.", True),
            ("B", "Todas son mayores que 1.", False),
            ("C", "Todas tienen el mismo numerador.", False),
            ("D", "Ninguna se puede simplificar.", False),
         ],
         "exp": "3/6 = 1/2, 4/8 = 1/2, 5/10 = 1/2. Todas simplifican a 1/2."},
        # D6 Apply
        {"v": 6, "d": "D6", "bloom": "Apply", "icfes": "Uso comprensivo del conocimiento científico",
         "ctx": "En la tienda escolar, un paquete de galletas cuesta $4.500 y Ana tiene $12.000.",
         "es": 0.72,
         "q": "¿Qué fracción de su dinero gastó Ana?",
         "opts": [
            ("A", "3/8", True),
            ("B", "4/12", False),
            ("C", "1/3", False),
            ("D", "4500/1200", False),
         ],
         "exp": "4500/12000 = 45/120 = 3/8. Gastó 3 de cada 8 partes de su dinero."},
        # D6 Analyze (multiplication)
        {"v": 7, "d": "D6", "bloom": "Analyze", "icfes": "Indagación",
         "ctx": "Valentina debe multiplicar: 3/4 × 8/9 en su taller.",
         "es": 0.65,
         "q": "¿Cuál es el resultado simplificado?",
         "opts": [
            ("A", "2/3", True),
            ("B", "24/36", False),
            ("C", "11/13", False),
            ("D", "3/4", False),
         ],
         "exp": "3/4 × 8/9 = 24/36 = 2/3. Se puede cancelar: tachando 3 y 9, y 4 y 8."},
        # D7 Analyze (comparison)
        {"v": 8, "d": "D7", "bloom": "Analyze", "icfes": "Explicación de fenómenos",
         "ctx": "Camila debe ordenar: 3/4, 2/5, 1/2, 7/10 de menor a mayor.",
         "es": 0.58,
         "q": "¿Cuál es el orden correcto?",
         "opts": [
            ("A", "2/5, 1/2, 3/4, 7/10", False),
            ("B", "1/2, 2/5, 3/4, 7/10", False),
            ("C", "2/5, 1/2, 7/10, 3/4", True),
            ("D", "3/4, 7/10, 1/2, 2/5", False),
         ],
         "exp": "Con mcm 20: 3/4=15/20, 2/5=8/20, 1/2=10/20, 7/10=14/20. Orden: 8/20 < 10/20 < 14/20 < 15/20."},
        # D7 Evaluate
        {"v": 9, "d": "D7", "bloom": "Evaluate", "icfes": "Uso comprensivo del conocimiento científico",
         "ctx": "Andrés dice: \"1/3 de 3/5 de una torta es 1/5 de la torta\".",
         "es": 0.52,
         "q": "¿Es correcto Andrés?",
         "opts": [
            ("A", "Sí, 1/3 × 3/5 = 3/15 = 1/5.", True),
            ("B", "No, sería 1/3 + 3/5.", False),
            ("C", "Sí, porque 1/3 de 3/5 se suma.", False),
            ("D", "No, sería 9/15.", False),
         ],
         "exp": "1/3 de 3/5 = 1/3 × 3/5 = 3/15 = 1/5. Correcto."},
        # D8 Evaluate (decimal periodic)
        {"v": 10, "d": "D8", "bloom": "Evaluate", "icfes": "Indagación",
         "ctx": "La profesora pregunta: ¿0.666... es un número racional?",
         "es": 0.48,
         "q": "¿Cuál es la respuesta?",
         "opts": [
            ("A", "Sí, porque 0.666... = 2/3.", True),
            ("B", "No, porque tiene infinitos decimales.", False),
            ("C", "Sí, pero solo como 6/10.", False),
            ("D", "No, los decimales periódicos no son racionales.", False),
         ],
         "exp": "0.666... = 2/3. Todo decimal periódico se puede expresar como fracción, por tanto es racional."},
        # D8 Analyze (division)
        {"v": 11, "d": "D8", "bloom": "Analyze", "icfes": "Explicación de fenómenos",
         "ctx": "Sebastián debe dividir: (2/3) ÷ (5/6).",
         "es": 0.50,
         "q": "¿Cuál es el resultado?",
         "opts": [
            ("A", "12/15 = 4/5", True),
            ("B", "10/18 = 5/9", False),
            ("C", "2/5", False),
            ("D", "5/4", False),
         ],
         "exp": "(2/3) ÷ (5/6) = 2/3 × 6/5 = 12/15 = 4/5. Se invierte el divisor y se multiplica."},
        # D9 Evaluate (real-world)
        {"v": 12, "d": "D9", "bloom": "Evaluate", "icfes": "Uso comprensivo del conocimiento científico",
         "ctx": "Dos recetas: una usa 3/4 taza de harina y la otra 2/3 taza. ¿Cuál usa más y cuánta más?",
         "es": 0.42,
         "q": "¿Cuál es la diferencia?",
         "opts": [
            ("A", "1/12 de taza más la primera.", True),
            ("B", "1/2 taza más la primera.", False),
            ("C", "1/6 de taza más la segunda.", False),
            ("D", "Son iguales.", False),
         ],
         "exp": "3/4 − 2/3 = 9/12 − 8/12 = 1/12. La primera receta usa 1/12 de taza más de harina."},
    ],
    "algebra-basica": [
        {"v": 1, "d": "D3", "bloom": "Remember", "icfes": "Uso comprensivo del conocimiento científico",
         "ctx": "En la clase de álgebra del colegio de Bogotá, la profesora pregunta qué es una variable.",
         "es": 0.85,
         "q": "¿Qué es una variable en álgebra?",
         "opts": [
            ("A", "Un símbolo que representa un número desconocido o variable.", True),
            ("B", "Un número fijo que no cambia nunca.", False),
            ("C", "El resultado de una operación.", False),
            ("D", "Una letra que siempre vale 1.", False),
         ],
         "exp": "Una variable es un símbolo (generalmente una letra como x, y, a) que representa un valor desconocido que puede cambiar."},
        {"v": 2, "d": "D4", "bloom": "Understand", "icfes": "Explicación de fenómenos",
         "ctx": "Pedro dice que si x = 5, entonces x + 3 = 8.",
         "es": 0.82,
         "q": "¿Qué significa la expresión x + 3?",
         "opts": [
            ("A", "Un número que es 3 unidades mayor que x.", True),
            ("B", "El triple de x.", False),
            ("C", "x multiplicado por 3.", False),
            ("D", "Un número 3 veces más pequeño que x.", False),
         ],
         "exp": "x + 3 representa el valor de x aumentado en 3 unidades. Si x = 5, x + 3 = 8."},
        {"v": 3, "d": "D4", "bloom": "Apply", "icfes": "Uso comprensivo del conocimiento científico",
         "ctx": "La edad de Carlos es el doble de la de su hermana. Si la hermana tiene h años.",
         "es": 0.78,
         "q": "¿Qué expresión representa la edad de Carlos?",
         "opts": [
            ("A", "2h", True),
            ("B", "h + 2", False),
            ("C", "h/2", False),
            ("D", "h − 2", False),
         ],
         "exp": "El doble de h se escribe 2h. Si la hermana tiene 10 años, Carlos tiene 2×10 = 20 años."},
        {"v": 4, "d": "D5", "bloom": "Apply", "icfes": "Indagación",
         "ctx": "Valentina tenía a caramelos. Comió 5 y luego le regalaron 3.",
         "es": 0.75,
         "q": "¿Qué expresión representa los caramelos que tiene Valentina ahora?",
         "opts": [
            ("A", "a − 5 + 3 = a − 2", True),
            ("B", "a + 5 − 3 = a + 2", False),
            ("C", "5 − a + 3 = 8 − a", False),
            ("D", "a − 5 − 3 = a − 8", False),
         ],
         "exp": "Tenía a, comió 5 (a−5), le regalaron 3 (a−5+3). Al simplificar: a − 2."},
        {"v": 5, "d": "D5", "bloom": "Understand", "icfes": "Explicación de fenómenos",
         "ctx": "En el colegio de Medellín, el profesor escribe: \"El triple de un número más 4 es 19\".",
         "es": 0.76,
         "q": "¿Cuál es la expresión algebraica?",
         "opts": [
            ("A", "3x + 4 = 19", True),
            ("B", "x + 3 + 4 = 19", False),
            ("C", "3(x + 4) = 19", False),
            ("D", "3x = 19 + 4", False),
         ],
         "exp": "\"El triple de un número\" es 3x. \"más 4\" es +4. \"es 19\" es = 19. Así: 3x + 4 = 19."},
        {"v": 6, "d": "D6", "bloom": "Apply", "icfes": "Uso comprensivo del conocimiento científico",
         "ctx": "Santiago simplifica: 3x + 5y − 2x + y en su cuaderno de Barranquilla.",
         "es": 0.70,
         "q": "¿Cuál es la expresión simplificada?",
         "opts": [
            ("A", "x + 6y", True),
            ("B", "5x + 6y", False),
            ("C", "x + 4y", False),
            ("D", "5x + 4y", False),
         ],
         "exp": "Se agrupan términos semejantes: 3x − 2x = x. 5y + y = 6y. Resultado: x + 6y."},
        {"v": 7, "d": "D6", "bloom": "Analyze", "icfes": "Indagación",
         "ctx": "Camila dice que las expresiones 2(x + 3) y 2x + 6 son equivalentes.",
         "es": 0.64,
         "q": "¿Tiene razón Camila?",
         "opts": [
            ("A", "Sí, por la propiedad distributiva.", True),
            ("B", "No, 2(x+3) = 2x+3.", False),
            ("C", "Sí, pero solo si x = 0.", False),
            ("D", "No, son diferentes para todo valor de x.", False),
         ],
         "exp": "2(x + 3) = 2·x + 2·3 = 2x + 6. Sí son equivalentes por la propiedad distributiva."},
        {"v": 8, "d": "D7", "bloom": "Analyze", "icfes": "Explicación de fenómenos",
         "ctx": "María evalúa 2x² + 3x − 1 cuando x = 2.",
         "es": 0.58,
         "q": "¿Cuál es el valor numérico?",
         "opts": [
            ("A", "13", True),
            ("B", "11", False),
            ("C", "15", False),
            ("D", "9", False),
         ],
         "exp": "2(2)² + 3(2) − 1 = 2(4) + 6 − 1 = 8 + 6 − 1 = 13."},
        {"v": 9, "d": "D7", "bloom": "Evaluate", "icfes": "Uso comprensivo del conocimiento científico",
         "ctx": "Andrés dice: \"Si x + y = 10 y x − y = 4, entonces x = 7.\"",
         "es": 0.52,
         "q": "¿Es correcto?",
         "opts": [
            ("A", "Sí, sumando las ecuaciones: 2x = 14, x = 7.", True),
            ("B", "No, x sería 5.", False),
            ("C", "Sí, porque 7+3=10 y 7-3=4.", True),  # duplicate truth
            ("D", "No se puede determinar.", False),
         ],
         "exp": "Sumando: (x+y)+(x−y)=10+4 → 2x=14 → x=7. Sí, y entonces y=3."},
        {"v": 10, "d": "D7", "bloom": "Evaluate", "icfes": "Indagación",
         "ctx": "En Pereira, preguntan: ¿Cuál es el valor numérico de (a+b)² cuando a=3 y b=4?",
         "es": 0.50,
         "q": "¿Cuál es el resultado?",
         "opts": [
            ("A", "49", True),
            ("B", "25", False),
            ("C", "13", False),
            ("D", "7", False),
         ],
         "exp": "(3+4)² = 7² = 49. No confundir con a² + b² = 9 + 16 = 25."},
        {"v": 11, "d": "D8", "bloom": "Analyze", "icfes": "Explicación de fenómenos",
         "ctx": "Sebastián simplifica: 2a · 3b · a.",
         "es": 0.48,
         "q": "¿Cuál es el resultado?",
         "opts": [
            ("A", "6a²b", True),
            ("B", "5a²b", False),
            ("C", "6ab", False),
            ("D", "2a·3b·a = 5ab", False),
         ],
         "exp": "2·3 = 6. a·a = a². b queda. Resultado: 6a²b."},
        {"v": 12, "d": "D8", "bloom": "Evaluate", "icfes": "Uso comprensivo del conocimiento científico",
         "ctx": "En el colegio de Villavicencio, el profesor pregunta si 2x + 3y es igual a 5xy.",
         "es": 0.45,
         "q": "¿Son equivalentes?",
         "opts": [
            ("A", "No, porque x e y son términos diferentes que no se pueden sumar así.", True),
            ("B", "Sí, 2+3=5 y x+y=xy.", False),
            ("C", "Sí, para valores específicos.", False),
            ("D", "No, porque 2x+3y = 6xy.", False),
         ],
         "exp": "2x + 3y NO es 5xy. 2x y 3y son términos NO semejantes (tienen diferentes variables). 5xy es un producto, no una suma."},
    ],
    "ecuaciones-lineales": [
        {"v": 1, "d": "D3", "bloom": "Remember", "icfes": "Uso comprensivo del conocimiento científico",
         "ctx": "En el colegio de Bucaramanga, preguntan: \"Una ecuación lineal tiene...\"",
         "es": 0.85,
         "q": "¿Cuál es la forma general de una ecuación lineal con una variable?",
         "opts": [
            ("A", "ax + b = 0, donde a ≠ 0", True),
            ("B", "ax² + bx + c = 0", False),
            ("C", "ax³ = 0", False),
            ("D", "a + b = x", False),
         ],
         "exp": "La ecuación lineal o de primer grado es ax + b = 0, con a ≠ 0. Su solución es x = −b/a."},
        {"v": 2, "d": "D4", "bloom": "Understand", "icfes": "Explicación de fenómenos",
         "ctx": "María ve la ecuación \"3x = 12\" y dice que x = 4.",
         "es": 0.82,
         "q": "¿Qué operación usó María para resolver?",
         "opts": [
            ("A", "Dividió ambos lados entre 3.", True),
            ("B", "Sumó 3 a ambos lados.", False),
            ("C", "Restó 3 de ambos lados.", False),
            ("D", "Multiplicó ambos lados por 3.", False),
         ],
         "exp": "Para despejar x en 3x = 12, se divide entre 3: x = 12/