#!/usr/bin/env python3
"""
Master Generator: Generate ALL missing weekly bundles for Colombia grades 3-11.
Targets issues #483, #484, #485, #486.

Uses template-based question generation (no external API calls).
Protocol v5.2 YAML frontmatter format.

Bundle sizes: G3-5 = 8, G6-7 = 10, G8-10 = 12, G11 = 20
"""

import os
import random
import json
import datetime

random.seed(42)

BASE = r"E:\scripts-python\worldexams\questions_data\colombia"

SUBJECT_CONFIG = {
    'matematicas': {'code': 'MAT', 'dir': 'matematicas'},
    'ciencias-naturales': {'code': 'CIE', 'dir': 'ciencias-naturales'},
    'lengua': {'code': 'LEN', 'dir': 'lengua'},
    'lectura-critica': {'code': 'LEC', 'dir': 'lectura-critica'},
    'sociales-ciudadanas': {'code': 'SOC', 'dir': 'sociales-ciudadanas'},
    'ingles': {'code': 'ING', 'dir': 'ingles'},
}

BUNDLE_SIZES = {3: 8, 4: 8, 5: 8, 6: 10, 7: 10, 8: 12, 9: 12, 10: 15, 11: 20}

# Colombian towns and schools for context
TOWNS = [
    "Bogotá", "Medellín", "Cali", "Barranquilla", "Cartagena",
    "Bucaramanga", "Pereira", "Ibagué", "Neiva", "Villavicencio",
    "Pasto", "Manizales", "Santa Marta", "Cúcuta", "Sincelejo",
    "Tunja", "Popayán", "Armenia", "Montería", "San Andrés",
    "Valledupar", "Riohacha", "Quibdó", "Leticia", "Mocoa"
]
SCHOOLS = [
    "Colegio San José", "Colegio La Salle", "Colegio INEM",
    "Colegio Champagnat", "Colegio San Bartolomé", "Colegio Nacional",
    "Colegio La Presentación", "Colegio San Carlos",
    "Colegio Agustín Nieto Caballero", "Colegio Los Andes",
    "Colegio Nuevo Horizonte", "Colegio San Luis Beltrán"
]
STUDENTS = [
    "Carlos", "María", "Andrés", "Laura", "Juan", "Valentina",
    "Felipe", "Camila", "Santiago", "Isabella", "Mateo", "Sofía",
    "Daniel", "Gabriela", "David", "Ana", "Miguel", "Lucía"
]


def pick_town():
    return random.choice(TOWNS)

def pick_school():
    return random.choice(SCHOOLS)

def pick_student():
    return random.choice(STUDENTS)

def ws(week_num):
    return f"W{week_num:02d}"

# ============================================================
# TOPIC STRUCTURE for all grades and subjects
# ============================================================

# G3-G5 topics by subject
TOPICS_PRIMARY = {
    'matematicas': {
        3: [
            (1, "numeros-hasta-1000", "Números hasta 1000"),
            (2, "valor-posicional-centenas", "Valor posicional"),
            (3, "suma-reagrupacion", "Suma con reagrupación"),
            (4, "resta-prestado", "Resta con prestado"),
            (5, "repaso-p1", "Repaso P1"),
            (6, "multiplicacion-sumandos", "Multiplicación"),
            (7, "tablas-2-5", "Tablas 2-5"),
            (8, "tablas-6-10", "Tablas 6-10"),
            (9, "division-reparto", "División"),
            (10, "repaso-p2", "Repaso P2"),
            (11, "fracciones-intro", "Fracciones"),
            (12, "fracciones-comparacion", "Comparación fracciones"),
            (13, "fracciones-equivalentes", "Fracciones equivalentes"),
            (14, "figuras-geometricas", "Figuras geométricas"),
            (15, "repaso-p3", "Repaso P3"),
            (16, "angulos-simetria", "Ángulos y simetría"),
            (17, "medicion-longitud", "Medición longitud"),
            (18, "medicion-peso-capacidad", "Peso y capacidad"),
            (19, "tiempo-reloj", "Tiempo"),
            (20, "repaso-p4", "Repaso P4"),
            (21, "calendario", "Calendario"),
            (22, "pictogramas", "Pictogramas"),
            (23, "graficas-barras", "Gráficas de barras"),
            (24, "probabilidad", "Probabilidad"),
            (25, "repaso-p5", "Repaso P5"),
            (26, "suma-4-cifras", "Suma 4 cifras"),
            (27, "resta-4-cifras", "Resta 4 cifras"),
            (28, "multiplicacion-2x1", "Multiplicación 2x1"),
            (29, "multiplicacion-3x1", "Multiplicación 3x1"),
            (30, "repaso-p6", "Repaso P6"),
            (31, "perimetro", "Perímetro"),
            (32, "area", "Área"),
            (33, "cuerpos-geometricos", "Cuerpos geométricos"),
            (34, "patrones-secuencias", "Patrones"),
            (35, "repaso-p7", "Repaso P7"),
            (36, "dinero", "Dinero"),
            (37, "problemas-combinados", "Problemas combinados"),
            (38, "estimacion", "Estimación"),
            (39, "razonamiento", "Razonamiento"),
            (40, "repaso-anual", "Repaso anual"),
        ],
        4: [
            (1, "numeros-4-cifras", "Números 4 cifras"),
            (2, "valor-posicional-miles", "Valor posicional hasta miles"),
            (3, "suma-4-cifras", "Suma 4 cifras"),
            (4, "resta-4-cifras", "Resta 4 cifras"),
            (5, "repaso-p1", "Repaso P1"),
            (6, "multiplicacion-1-dijito", "Multiplicación 1 dígito"),
            (7, "tablas-multiplicar", "Tablas de multiplicar"),
            (8, "multiplicacion-2-dijitos", "Multiplicación 2 dígitos"),
            (9, "division-exacta", "División exacta"),
            (10, "repaso-p2", "Repaso P2"),
            (11, "fracciones-introduccion", "Fracciones"),
            (12, "fracciones-comp-op", "Operaciones fracciones"),
            (13, "decimales", "Decimales"),
            (14, "geometria-plana", "Geometría plana"),
            (15, "repaso-p3", "Repaso P3"),
            (16, "angulos", "Ángulos"),
            (17, "perimetro-area", "Perímetro y área"),
            (18, "simetria", "Simetría"),
            (19, "medicion", "Medición"),
            (20, "repaso-p4", "Repaso P4"),
            (21, "tiempo-calendario", "Calendario"),
            (22, "pictogramas-tablas", "Pictogramas"),
            (23, "graficas-lineales", "Gráficas"),
            (24, "probabilidad", "Probabilidad"),
            (25, "repaso-p5", "Repaso P5"),
            (26, "multiplicacion-centenas", "Multiplicar centenas"),
            (27, "division-residuo", "División con residuo"),
            (28, "fracciones-heterogeneas", "Fracciones heterogéneas"),
            (29, "decimales-suma-resta", "Decimales suma/resta"),
            (30, "repaso-p6", "Repaso P6"),
            (31, "clasificacion-angulos", "Clasificación ángulos"),
            (32, "triangulos-clasificacion", "Triángulos"),
            (33, "cuadrilateros", "Cuadriláteros"),
            (34, "diagrama-puntos", "Diagrama puntos"),
            (35, "repaso-p7", "Repaso P7"),
            (36, "patrones-numericos", "Patrones"),
            (37, "sistemas-medicion", "Sistemas medición"),
            (38, "problemas-varios", "Problemas varios"),
            (39, "razonamiento-logico", "Razonamiento lógico"),
            (40, "repaso-anual", "Repaso anual"),
        ],
        5: [
            (1, "numeros-decimales", "Números decimales"),
            (2, "fracciones-mixtas", "Fracciones y mixtas"),
            (3, "operaciones-fracciones", "Operaciones fracciones"),
            (4, "decimales-op", "Operaciones decimales"),
            (5, "repaso-p1", "Repaso P1"),
            (6, "porcentajes", "Porcentajes"),
            (7, "multiplicacion-3cifras", "Multiplicar 3 cifras"),
            (8, "division-2cifras", "Dividir 2 cifras"),
            (9, "multiplicacion-decimales", "Mult. decimales"),
            (10, "repaso-p2", "Repaso P2"),
            (11, "geometria-poligonos", "Geometría polígonos"),
            (12, "area-poligonos", "Área polígonos"),
            (13, "perimetro-area-circulo", "Perímetro y área círculo"),
            (14, "volumen-cubos", "Volumen"),
            (15, "repaso-p3", "Repaso P3"),
            (16, "potenciacion", "Potenciación"),
            (17, "radicacion", "Radicación"),
            (18, "numeros-primos", "Números primos"),
            (19, "mcm-mcd", "MCM y MCD"),
            (20, "repaso-p4", "Repaso P4"),
            (21, "proporcionalidad", "Proporcionalidad"),
            (22, "regla-de-tres", "Regla de tres"),
            (23, "escala-mapas", "Escala"),
            (24, "estadistica-basica", "Estadística básica"),
            (25, "repaso-p5", "Repaso P5"),
            (26, "media-mediana-moda", "Media, mediana, moda"),
            (27, "probabilidad-eventos", "Probabilidad eventos"),
            (28, "sistema-coordenadas", "Sistema coordenadas"),
            (29, "transformaciones", "Transformaciones"),
            (30, "repaso-p6", "Repaso P6"),
            (31, "presupuesto-ahorro", "Presupuesto"),
            (32, "interes-simple", "Interés simple"),
            (33, "graficos-circulares", "Gráficos circulares"),
            (34, "combinaciones", "Combinaciones"),
            (35, "repaso-p7", "Repaso P7"),
            (36, "patrones-graficos", "Patrones gráficos"),
            (37, "variables-expresiones", "Variables"),
            (38, "ecuaciones-simples", "Ecuaciones simples"),
            (39, "razonamiento-abstracto", "Razonamiento abstracto"),
            (40, "repaso-anual", "Repaso anual"),
        ]
    },
    'ingles': {
        4: [
            (1, "greetings", "Greetings"),
            (2, "colors", "Colors"),
            (3, "numbers-1-50", "Numbers 1-50"),
            (4, "family-members", "Family"),
            (5, "repaso-p1", "Repaso P1"),
            (6, "school-objects", "School objects"),
            (7, "classroom-commands", "Commands"),
            (8, "body-parts", "Body parts"),
            (9, "animals", "Animals"),
            (10, "repaso-p2", "Repaso P2"),
            (11, "food-drinks", "Food & drinks"),
            (12, "clothes", "Clothes"),
            (13, "weather", "Weather"),
            (14, "days-months", "Days & months"),
            (15, "repaso-p3", "Repaso P3"),
            (16, "verb-to-be", "Verb to be"),
            (17, "have-has", "Have/Has"),
            (18, "can-cannot", "Can/Can't"),
            (19, "present-simple", "Present simple"),
            (20, "repaso-p4", "Repaso P4"),
            (21, "prepositions", "Prepositions"),
            (22, "question-words", "Question words"),
            (23, "describing-people", "Describing people"),
            (24, "my-house", "My house"),
            (25, "repaso-p5", "Repaso P5"),
            (26, "daily-routine", "Daily routine"),
            (27, "time-hour", "Time"),
            (28, "like-dont-like", "Like/Don't like"),
            (29, "actions-verbs", "Action verbs"),
            (30, "repaso-p6", "Repaso P6"),
            (31, "my-town", "My town"),
            (32, "directions", "Directions"),
            (33, "professions", "Professions"),
            (34, "hobbies", "Hobbies"),
            (35, "repaso-p7", "Repaso P7"),
            (36, "reading-comprehension", "Reading"),
            (37, "simple-writing", "Simple writing"),
            (38, "vocabulary-review", "Vocabulary review"),
            (39, "listening-skills", "Listening"),
            (40, "repaso-anual", "Annual review"),
        ],
        5: [
            (1, "present-continuous", "Present continuous"),
            (2, "adjectives", "Adjectives"),
            (3, "comparatives", "Comparatives"),
            (4, "superlatives", "Superlatives"),
            (5, "repaso-p1", "Repaso P1"),
            (6, "past-simple-to-be", "Past simple (to be)"),
            (7, "past-simple-regular", "Past simple (regular)"),
            (8, "past-simple-irregular", "Past simple (irregular)"),
            (9, "wh-questions", "Wh-questions"),
            (10, "repaso-p2", "Repaso P2"),
            (11, "frequency-adverbs", "Frequency adverbs"),
            (12, "quantifiers", "Quantifiers"),
            (13, "articles", "Articles"),
            (14, "possessives", "Possessives"),
            (15, "repaso-p3", "Repaso P3"),
            (16, "future-be-going-to", "Future: going to"),
            (17, "future-will", "Future: will"),
            (18, "may-might", "May/Might"),
            (19, "sequencing", "Sequencing"),
            (20, "repaso-p4", "Repaso P4"),
            (21, "giving-opinions", "Giving opinions"),
            (22, "agree-disagree", "Agree/Disagree"),
            (23, "making-suggestions", "Suggestions"),
            (24, "polite-requests", "Polite requests"),
            (25, "repaso-p5", "Repaso P5"),
            (26, "connectors-basics", "Connectors"),
            (27, "cause-effect", "Cause & effect"),
            (28, "describing-process", "Describing processes"),
            (29, "compare-cultures", "Comparing cultures"),
            (30, "repaso-p6", "Repaso P6"),
            (31, "nature-environment", "Nature & environment"),
            (32, "recycling-actions", "Recycling"),
            (33, "science-vocabulary", "Science vocabulary"),
            (34, "health-wellness", "Health & wellness"),
            (35, "repaso-p7", "Repaso P7"),
            (36, "storytelling", "Storytelling"),
            (37, "book-review", "Book review"),
            (38, "summary-writing", "Summary writing"),
            (39, "describing-events", "Describing events"),
            (40, "repaso-anual", "Annual review"),
        ],
        7: [
            (1, "present-perfect", "Present perfect"),
            (2, "since-for", "Since/For"),
            (3, "already-yet", "Already/Yet"),
            (4, "ever-never", "Ever/Never"),
            (5, "present-perfect-continuous", "Present perfect continuous"),
            (6, "past-perfect", "Past perfect"),
            (7, "reported-speech", "Reported speech"),
            (8, "reported-questions", "Reported questions"),
            (9, "passive-present", "Passive present"),
            (10, "repaso-p1", "Repaso P1"),
            (11, "passive-past", "Passive past"),
            (12, "first-conditional", "First conditional"),
            (13, "second-conditional", "Second conditional"),
            (14, "conditionals-if", "Conditionals if/when"),
            (15, "repaso-p2", "Repaso P2"),
            (16, "relative-clauses", "Relative clauses"),
            (17, "defining-relative", "Defining relative"),
            (18, "non-defining", "Non-defining relative"),
            (19, "modals-probability", "Modals of probability"),
            (20, "repaso-p3", "Repaso P3"),
            (21, "modals-obligation", "Modals of obligation"),
            (22, "phrasal-verbs", "Phrasal verbs"),
            (23, "collocations", "Collocations"),
            (24, "prefixes-suffixes", "Prefixes & suffixes"),
            (25, "repaso-p4", "Repaso P4"),
            (26, "debate-language", "Debate language"),
            (27, "formal-letters", "Formal letters"),
            (28, "argumentative-essay", "Argumentative essay"),
            (29, "summarizing", "Summarizing"),
            (30, "repaso-p5", "Repaso P5"),
            (31, "media-literacy", "Media literacy"),
            (32, "social-issues", "Social issues"),
            (33, "technology-impact", "Technology impact"),
            (34, "cultural-diversity", "Cultural diversity"),
            (35, "repaso-p6", "Repaso P6"),
            (36, "complex-sentences", "Complex sentences"),
            (37, "literary-analysis", "Literary analysis"),
            (38, "reading-strategies", "Reading strategies"),
            (39, "creative-writing", "Creative writing"),
            (40, "repaso-anual", "Annual review"),
        ],
        8: [
            (1, "conditional-type-3", "Conditional type 3"),
            (2, "third-conditional-form", "Third conditional"),
            (3, "mixed-conditionals", "Mixed conditionals"),
            (4, "wishes-regrets", "Wishes & regrets"),
            (5, "repaso-p1", "Repaso P1"),
            (6, "passive-simple-present", "Passive (present)"),
            (7, "passive-simple-past", "Passive (past)"),
            (8, "passive-perfect-tenses", "Passive (perfect)"),
            (9, "passive-modals", "Passive (modals)"),
            (10, "repaso-p2", "Repaso P2"),
            (11, "environment-vocabulary", "Environment vocabulary"),
            (12, "reading-environment", "Reading: environment"),
            (13, "sustainability", "Sustainability"),
            (14, "compare-environment", "Compare environment"),
            (15, "repaso-p3", "Repaso P3"),
            (16, "grammar-review", "Grammar review"),
            (17, "vocabulary-review", "Vocabulary review"),
            (18, "reading-comprehension", "Reading comprehension"),
            (19, "mock-test", "Mock test"),
            (20, "repaso-p4", "Repaso P4"),
            (21, "present-perfect-passive", "Present perfect passive"),
            (22, "future-passive", "Future passive"),
            (23, "gerunds-infinitives", "Gerunds & infinitives"),
            (24, "prepositions-advanced", "Prepositions advanced"),
            (25, "repaso-p5", "Repaso P5"),
            (26, "causative-have-get", "Causatives"),
            (27, "inversion", "Inversion"),
            (28, "emphasis-cleft", "Emphasis"),
            (29, "hedging-language", "Hedging"),
            (30, "repaso-p6", "Repaso P6"),
            (31, "global-issues", "Global issues"),
            (32, "science-technology", "Science & tech"),
            (33, "arts-culture", "Arts & culture"),
            (34, "academic-writing", "Academic writing"),
            (35, "repaso-p7", "Repaso P7"),
            (36, "critical-thinking", "Critical thinking"),
            (37, "research-skills", "Research skills"),
            (38, "presentations", "Presentations"),
            (39, "debate-ethics", "Debate & ethics"),
            (40, "repaso-anual", "Annual review"),
        ],
    }
}

# G8-G11 topics (from generate_bundles_v5.py)
TOPICS_G8_G11 = {
    'matematicas': {
        8: [(1, "lenguaje-algebraico"), (2, "terminos-semejantes"), (3, "valor-numerico"), (4, "reduccion-expresiones"), (5, "repaso-p1"),
            (11, "binomio-cuadrado"), (12, "binomio-conjugado"), (13, "binomio-al-cubo"), (14, "productos-notables-mixtos"), (15, "repaso-p2"),
            (21, "factor-comun"), (22, "diferencia-cuadrados"), (23, "trinomio-cuadrado"), (24, "teorema-pitagoras"), (25, "repaso-p3"),
            (31, "medidas-tendencia"), (32, "graficos-estadisticos"), (33, "probabilidad-basica"), (34, "eventos-excluyentes"), (35, "repaso-p4"),
            # Extra weeks to fill W21-W40 for P3-P4 extended
            (26, "polinomios-suma"), (27, "polinomios-resta"), (28, "ecuaciones-lineales"), (29, "sistemas-2x2"), (30, "repaso-p5"),
            (36, "areas-figuras"), (37, "volumenes"), (38, "movimiento-uniforme"), (39, "porcentajes-financieros"), (40, "repaso-integral")],
        9: [(1, "ecuaciones-lineales"), (2, "metodo-sustitucion"), (3, "metodo-igualacion"), (4, "metodo-reduccion"), (5, "repaso-p1"),
            (11, "definicion-funcion"), (12, "pendiente-intercepto"), (13, "grafica-funcion"), (14, "aplicaciones-lineales"), (15, "repaso-p2"),
            (21, "funcion-cuadratica"), (22, "vertice-ejes"), (23, "solucion-ecuaciones"), (24, "aplicaciones-cuadraticas"), (25, "repaso-p3"),
            (31, "radicales-basicos"), (32, "operaciones-radicales"), (33, "razones-trigonometricas"), (34, "triangulos-rectangulos"), (35, "repaso-p4"),
            # Extra
            (26, "inecuaciones"), (27, "funcion-exponencial"), (28, "funcion-logaritmica"), (29, "sucesiones"), (30, "repaso-p5"),
            (36, "analisis-graficos"), (37, "estadistica-descriptiva"), (38, "regresion-lineal"), (39, "matematicas-financieras"), (40, "repaso-integral")],
        10: [(1, "circulo-unitario"), (2, "funciones-trig"), (3, "identidades-basicas"), (4, "ley-seno-coseno"), (5, "repaso-p1"),
             (11, "vectores-2d"), (12, "operaciones-vectoriales"), (13, "matrices-basicas"), (14, "determinantes"), (15, "repaso-p2"),
             (21, "circunferencia"), (22, "parabola"), (23, "elipse"), (24, "hiperbola"), (25, "repaso-p3"),
             (31, "limites-basicos"), (32, "propiedades-limites"), (33, "limites-indeterminados"), (34, "continuidad"), (35, "repaso-p4"),
             # Extra
             (26, "derivadas-nocion"), (27, "derivadas-polinomios"), (28, "optimizacion"), (29, "integral-intro"), (30, "repaso-p5"),
             (36, "probabilidad-condicional"), (37, "distribucion-normal"), (38, "muestreo"), (39, "intervalos-confianza"), (40, "repaso-integral")],
        11: [(1, "limites-al-infinito"), (2, "limites-laterales"), (3, "continuidad-funciones"), (4, "teorema-valor-medio"), (5, "repaso-p1"),
             (11, "derivada-definicion"), (12, "reglas-derivacion"), (13, "derivada-compuesta"), (14, "aplicaciones-derivadas"), (15, "repaso-p2"),
             (21, "integral-indefinida"), (22, "integral-definida"), (23, "teorema-fundamental"), (24, "aplicaciones-integrales"), (25, "repaso-p3"),
             (31, "probabilidad-avanzada"), (32, "distribuciones"), (33, "inferencia-estadistica"), (34, "correlacion"), (35, "repaso-p4"),
             # Extra
             (26, "sumatorias"), (27, "series-numericas"), (28, "ecuaciones-diferenciales-intro"), (29, "aplicaciones-calculo"), (30, "repaso-p5"),
             (36, "modelacion-matematica"), (37, "programacion-lineal"), (38, "teoria-grafos"), (39, "analisis-combinatorio"), (40, "repaso-integral")],
    },
    'ciencias-naturales': {
        8: [(1, "celula-unidad-vida"), (2, "organelos-celulares"), (3, "membrana-transporte"), (4, "reproduccion-celular"), (5, "repaso-p1"),
            (11, "sistema-digestivo"), (12, "sistema-respiratorio"), (13, "sistema-circulatorio"), (14, "sistema-nervioso"), (15, "repaso-p2"),
            (21, "elementos-compuestos"), (22, "tabla-periodica"), (23, "enlaces-quimicos"), (24, "reacciones-quimicas"), (25, "repaso-p3"),
            (31, "movimiento-rectilineo"), (32, "leyes-newton"), (33, "fuerza-masa"), (34, "energia-trabajo"), (35, "repaso-p4"),
            # Extra
            (26, "clasificacion-seresh"), (27, "reino-plantae"), (28, "reino-animalia"), (29, "sistemas-excrecion"), (30, "repaso-p5"),
            (36, "electricidad-basica"), (37, "magnetismo"), (38, "ondas"), (39, "luz"), (40, "repaso-integral")],
        9: [(1, "adn-arn"), (2, "leyes-mendel"), (3, "herencia-genetica"), (4, "evolucion-seleccion"), (5, "repaso-p1"),
            (11, "ecosistemas"), (12, "cadenas-alimenticias"), (13, "ciclos-biogeoquimicos"), (14, "biodiversidad"), (15, "repaso-p2"),
            (21, "nomenclatura-quimica"), (22, "oxidos-bases"), (23, "acidos-sales"), (24, "reacciones-inorganicas"), (25, "repaso-p3"),
            (31, "cinematica-mru"), (32, "mruv-caida-libre"), (33, "estequiometria"), (34, "mol-masa-molar"), (35, "repaso-p4"),
            # Extra
            (26, "transporte-celular"), (27, "fotosintesis"), (28, "respiracion-celular"), (29, "sistemas-articulacion"), (30, "repaso-p5"),
            (36, "presion-fluidos"), (37, "termodinamica"), (38, "cambios-estado"), (39, "propiedades-periodicas"), (40, "repaso-integral")],
        10: [(1, "dinamica-rotacion"), (2, "trabajo-energia"), (3, "potencia-rendimiento"), (4, "cantidad-movimiento"), (5, "repaso-p1"),
             (11, "enlace-covalente"), (12, "enlace-ionico"), (13, "fuerzas-intermoleculares"), (14, "estados-materia"), (15, "repaso-p2"),
             (21, "poblaciones"), (22, "comunidades-ecologicas"), (23, "flujo-energia"), (24, "sucesion-ecologica"), (25, "repaso-p3"),
             (31, "hidrocarburos"), (32, "grupos-funcionales"), (33, "isomeria"), (34, "polimeros"), (35, "repaso-p4"),
             # Extra
             (26, "gravitacion"), (27, "oscilaciones"), (28, "sonido"), (29, "espectro-em"), (30, "repaso-p5"),
             (36, "biologia-molecular"), (37, "ingenieria-genetica"), (38, "ciclo-celular"), (39, "mitosis-meiosis"), (40, "repaso-integral")],
        11: [(1, "compuestos-organicos"), (2, "reacciones-organicas"), (3, "biomoleculas"), (4, "metabolismo-celular"), (5, "repaso-p1"),
             (11, "carbohidratos"), (12, "lipidos-proteinas"), (13, "enzimas"), (14, "respiracion-celular"), (15, "repaso-p2"),
             (21, "fotosintesis"), (22, "sintesis-proteinas"), (23, "regulacion-genica"), (24, "biotecnologia"), (25, "repaso-p3"),
             (31, "relatividad"), (32, "fisica-cuantica"), (33, "ondas-electromagneticas"), (34, "fisica-nuclear"), (35, "repaso-p4"),
             # Extra
             (26, "quimica-ambiental"), (27, "bioetica"), (28, "salud-publica"), (29, "epidemiologia"), (30, "repaso-p5"),
             (36, "astrofisica"), (37, "cosmologia"), (38, "nanotecnologia"), (39, "fisica-particulas"), (40, "repaso-integral")],
    },
    'lengua': {
        8: [(1, "mitos-leyendas"), (2, "popol-vuh"), (3, "poesia-precolombina"), (4, "narrativa-indigena"), (5, "repaso-p1"),
            (11, "cronistas-indias"), (12, "poesia-colonial"), (13, "teatro-colonial"), (14, "sor-juana"), (15, "repaso-p2"),
            (21, "modernismo"), (22, "creacionismo"), (23, "surrealismo"), (24, "poesia-vanguardista"), (25, "repaso-p3"),
            (31, "estructura-ensayo"), (32, "ensayo-literario"), (33, "ensayo-cientifico"), (34, "ensayo-politico"), (35, "repaso-p4"),
            (26, "literatura-indigena"), (27, "literatura-afro"), (28, "narrativa-contemporanea"), (29, "cuento-colombiano"), (30, "repaso-p5"),
            (36, "genero-lirico"), (37, "genero-dramatico"), (38, "genero-narrativo"), (39, "literatura-infantil"), (40, "repaso-integral")],
        9: [(1, "narrativa-colombiana"), (2, "garcia-marquez"), (3, "poesia-colombiana"), (4, "teatro-colombiano"), (5, "repaso-p1"),
            (11, "modernismo-hispanoamericano"), (12, "ruben-dario"), (13, "posmodernismo"), (14, "narrativa-moderna"), (15, "repaso-p2"),
            (21, "