-- Create table for exam results
create table public.exam_results (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_name text not null,
  score integer not null,
  total_questions integer not null,
  subject text not null,
  percentage integer generated always as ((score::float / total_questions::float) * 100) stored
);

-- Enable Row Level Security (RLS)
alter table public.exam_results enable row level security;

-- Create policy to allow anyone to insert results (for now, can be restricted later)
create policy "Allow public inserts"
on public.exam_results
for insert
to public
with check (true);

-- Create policy to allow anyone to read results
create policy "Allow public read"
on public.exam_results
for select
to public
using (true);
