# Generator Part 1: W01-W08
import os, sys, json
sys.path.insert(0, os.path.dirname(__file__))
from _gen_all import W, make_q
C = "Pensamiento Social"

def save_qs(w, qs):
    W[w]["qs"] = qs
    d = os.path.join(os.path.dirname(__file__), "_gen_data")
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(d, f"qs_w{w:02d}.json"), "w", encoding="utf-8") as f:
        json.dump(qs, f, ensure_ascii=False)
    print(f"W{w:02d}: {len(qs)} qs")

# ── W01 ──────────────────────────────────────────────────────────────────
save_qs(1, [
    make_q("Remember", C, "¿Cuáles son las tres grandes etapas de la Prehistoria?",
           ["Paleolítico, Mesolítico, Neolítico", "Paleolítico, Neolítico, Edad de los Metales",
            "Edad de Piedra, Bronce, Hierro", "Paleolítico, Antigua, Media"], 1,
           "La Prehistoria se divide en Paleolítico (piedra tallada), Neolítico (revolución agrícola) y Edad de los Metales (metalurgia)."),
    make_q("Remember", C, "¿Qué homínido fabricó las primeras herramientas de piedra?",
           ["Homo sapiens", "Homo habilis", "Neandertal", "Australopithecus"], 1,
           "El Homo habilis ('hombre hábil'), hace ~2.5 millones de años, fabricó las primeras herramientas de piedra."),
    make_q("Understand", C, "La Revolución Neolítica significó el paso de...",
           ["caza-recolección a agricultura y sedentarismo", "piedra tallada a metales", "aldeas a ciudades", "nomadismo a escritura"], 0,
           "Transformó a los humanos de depender de la naturaleza a producir sus propios alimentos."),
    make_q("Apply", C, "Arqueólogos encuentran herramientas de piedra tallada y fogatas en una cueva antioqueña. ¿A qué etapa pertenecen?",
           ["Neolítico", "Edad de los Metales", "Paleolítico", "Edad Antigua"], 2,
           "Los hallazgos de piedra tallada, fogatas y restos de caza son típicos del Paleolítico nómada."),
    make_q("Understand", C, "¿Qué avance define a la Edad de los Metales?",
           ["Escritura cuneiforme", "Metalurgia: fundición de cobre, bronce y hierro", "Agricultura de regadío", "Pirámides"], 1,
           "La metalurgia permitió herramientas más resistentes y el surgimiento de las primeras ciudades."),
    make_q("Analyze", C, "¿Por qué la Prehistoria se divide basada en la tecnología de herramientas?",
           ["Los historiadores no se ponen de acuerdo", "Cada cambio tecnológico transformó la organización social", "Solo importaban las armas", "No hay otra forma"], 1,
           "Cada cambio (piedra tallada, pulida, metales) transformó la economía y la vida humana."),
    make_q("Remember", C, "¿Qué significa 'Paleolítico'?",
           ["Piedra nueva", "Piedra antigua", "Edad del metal", "Tierra entre ríos"], 1,
           "Del griego 'palaios' (antiguo) y 'lithos' (piedra) = piedra antigua."),
    make_q("Apply", C, "La Prehistoria terminó con la escritura. ¿Hace cuánto?",
           ["100 años", "~5.500 años (3500 a.C.)", "50.000 años", "2 millones de años"], 1,
           "La escritura cuneiforme sumeria (~3500 a.C.) marca el límite entre Prehistoria e Historia."),
    make_q("Evaluate", C, "Comparando organización social Paleolítico vs Neolítico:",
           ["Paleolítico igualitario; Neolítico con jerarquías por excedentes", "Ambos igualitarios", "Paleolítico más desigual", "Neolítico todos esclavos"], 0,
           "Las bandas paleolíticas eran igualitarias; los excedentes neolíticos generaron élites."),
    make_q("Understand", C, "¿Qué distingue la Edad de los Metales del Neolítico?",
           ["En el Neolítico se inventó la escritura", "En la Edad de los Metales surgió la metalurgia y las primeras ciudades",
            "Todos eran agricultores", "No hay diferencias"], 1,
           "La metalurgia requirió especialistas y generó comercio, propiciando el crecimiento urbano."),
])

# ── W02 ──────────────────────────────────────────────────────────────────
save_qs(2, [
    make_q("Remember", C, "¿Cómo obtenían alimento los paleolíticos?",
           ["Cultivando la tierra", "Cazando, pescando y recolectando frutos y raíces", "En mercados", "Intercambiando con aldeas"], 1,
           "Eran cazadores-recolectores: cazaban animales, pescaban y recolectaban frutos silvestres."),
    make_q("Remember", C, "¿Cuál fue un descubrimiento clave del Paleolítico?",
           ["Agricultura", "Control del fuego", "Rueda", "Navegación"], 1,
           "El fuego (~1.5 millones de años) permitió cocinar, calentarse y defenderse."),
    make_q("Understand", C, "¿Por qué eran nómadas los paleolíticos?",
           ["No sabían construir", "Debían seguir animales y buscar alimento", "Les gustaba explorar", "Evitaban depredadores"], 1,
           "Al agotarse los recursos locales, se desplazaban a zonas con más alimentos."),
    make_q("Apply", C, "Pinturas rupestres de animales se encuentran en cuevas. ¿Cuál era su función?",
           ["Decorar", "Fines rituales de caza", "Enseñar a leer", "Mapas"], 1,
           "Se cree que tenían propósito ritual: representar animales para asegurar una caza exitosa."),
    make_q("Understand", C, "¿Cómo se organizaban socialmente los paleolíticos?",
           ["Imperios", "Pequeñas bandas de 20-30 parientes", "Ciudades-estado", "Reinos"], 1,
           "Vivían en pequeñas bandas nómadas unidas por lazos familiares, sin jerarquías fijas."),
    make_q("Analyze", C, "¿Por qué no fabricaban herramientas de metal?",
           ["La piedra era mejor", "No conocían la metalurgia (altas temperaturas)", "No había metales", "Por tradición"], 1,
           "La metalurgia requiere hornos y técnicas que se desarrollarían miles de años después."),
    make_q("Remember", C, "¿Qué herramientas fabricaban?",
           ["De metal", "De piedra tallada: bifaces, raspadores", "De piedra pulida", "De plástico"], 1,
           "Tallaban la piedra golpeándola para obtener lascas cortantes."),
    make_q("Apply", C, "¿Por qué vivían en cuevas?",
           ["No sabían construir", "Protección natural contra clima y depredadores", "Religión", "Buscar minerales"], 1,
           "Las cuevas ofrecían refugio natural contra la lluvia, el frío y los animales."),
    make_q("Evaluate", C, "Esperanza de vida paleolítica (~30 años) vs actual (~75). ¿Causa principal?",
           ["Genéticamente débiles", "Falta de medicina, alta mortalidad infantil", "Mala dieta", "Clima hostil"], 1,
           "Se debía a enfermedades sin tratamiento, accidentes de caza y alta mortalidad infantil."),
    make_q("Understand", C, "¿Qué relación tenían con la naturaleza?",
           ["La controlaban", "Dependían totalmente de ella para sobrevivir", "La modificaban", "La ignoraban"], 1,
           "Dependían completamente del entorno: conocían ciclos de animales y plantas."),
])

# ── W03 ──────────────────────────────────────────────────────────────────
save_qs(3, [
    make_q("Remember", C, "¿Qué significa 'Neolítico'?",
           ["Piedra antigua", "Piedra nueva (pulida)", "Edad del metal", "Nueva era"], 1,
           "'Neolítico' = 'piedra nueva', por la técnica de pulir la piedra."),
    make_q("Remember", C, "¿Qué se domesticó primero en el Creciente Fértil?",
           ["Maíz y papa", "Trigo, cebada, cabras y ovejas", "Arroz", "Sorgo"], 1,
           "En el Creciente Fértil (~9000 a.C.) se domesticaron trigo, cebada, cabras y ovejas."),
    make_q("Understand", C, "¿Cómo cambió la vida con el sedentarismo neolítico?",
           ["Volvieron a cuevas", "Aldeas permanentes, cerámica, crecimiento poblacional", "Siguieron nómadas", "Sin arte"], 1,
           "El sedentarismo permitió viviendas estables, aldeas y almacenamiento de excedentes."),
    make_q("Apply", C, "¿Para qué servía la cerámica neolítica?",
           ["Decorar", "Almacenar granos, cocinar, transportar agua", "Escribir", "Armas"], 1,
           "Era esencial para almacenar excedentes agrícolas y cocinar."),
    make_q("Understand", C, "¿Qué animales se domesticaron primero?",
           ["Caballos", "Cabras, ovejas y cerdos", "Vacas", "Perros"], 1,
           "Proporcionaban carne, leche, lana y cuero."),
    make_q("Analyze", C, "¿Por qué la agricultura empezó en el Creciente Fértil?",
           ["Eran más inteligentes", "Suelos fértiles, buen clima, especies domesticables", "Allí se descubrió el fuego", "Sin depredadores"], 1,
           "Tenía suelos aluviales, clima mediterráneo y especies como trigo silvestre."),
    make_q("Remember", C, "¿Primeras aldeas neolíticas?",
           ["Roma y Atenas", "Jericó y Çatalhöyük", "París y Londres", "Bogotá y Cartagena"], 1,
           "Jericó (~9000 a.C.) y Çatalhöyük (~7500 a.C.) son de los asentamientos más antiguos."),
    make_q("Apply", C, "División del trabajo neolítico: ¿qué significa?",
           ["Todos igual", "Especialización: agricultores, alfareros, tejedores", "Solo hombres", "No trabajaban"], 1,
           "Los excedentes permitieron que algunos se especializaran en otras actividades."),
    make_q("Evaluate", C, "¿Ventaja y desventaja del Neolítico?",
           ["Más tiempo libre", "Estabilidad y población; nuevas enfermedades y desigualdad", "Más igualdad", "Sin cambios"], 1,
           "Trajo estabilidad pero también enfermedades (por animales) y jerarquías sociales."),
    make_q("Understand", C, "¿Importancia de la piedra pulida?",
           ["Decorativa", "Herramientas más precisas para agricultura", "Joyas", "Menos resistente"], 1,
           "Producía bordes uniformes y herramientas más resistentes para labrar la tierra."),
])

# ── W04 ──────────────────────────────────────────────────────────────────
save_qs(4, [
    make_q("Remember", C, "¿Entre qué ríos se desarrolló Mesopotamia?",
           ["Nilo y Jordán", "Tigris y Éufrates", "Danubio y Rin", "Indo y Ganges"], 1,
           "Mesopotamia ('tierra entre ríos') se desarrolló entre el Tigris y el Éufrates."),
    make_q("Remember", C, "¿Qué inventaron los sumerios ~3500 a.C.?",
           ["Alfabeto", "Escritura cuneiforme", "Jeroglíficos", "Alfabeto latino"], 1,
           "Los sumerios inventaron la escritura cuneiforme sobre tablillas de arcilla."),
    make_q("Understand", C, "¿Por qué es importante el Código de Hammurabi?",
           ["Primera obra literaria", "Primer código de leyes escrito (282 leyes)", "Construcción de zigurats", "Creación del mundo"], 1,
           "El Código de Hammurabi (1754 a.C.) regulaba la sociedad babilónica."),
    make_q("Apply", C, "¿Para qué servían los zigurats?",
           ["Tumbas", "Templos religiosos escalonados", "Mercados", "Fortalezas"], 1,
           "Eran torres escalonadas que funcionaban como templos para los dioses protectores."),
    make_q("Understand", C, "Sociedad mesopotámica:",
           ["Igualitaria", "Jerárquica: rey, sacerdotes, escribas, comerciantes, campesinos, esclavos", "Solo libres y esclavos", "Democrática"], 1,
           "Pirámide social con el rey en la cima y esclavos en la base."),
    make_q("Analyze", C, "¿Por qué Mesopotamia es 'cuna de la civilización'?",
           ["Primer humano", "Primeras ciudades, escritura, Estado, leyes", "Primeras pirámides", "Descubrimiento del fuego"], 1,
           "Allí surgieron ciudades, escritura, Estado, leyes, rueda y agricultura de regadío."),
    make_q("Remember", C, "Dios principal de Babilonia:",
           ["Zeus", "Marduk", "Ra", "Quetzalcóatl"], 1,
           "Marduk era el dios patrono de Babilonia."),
    make_q("Apply", C, "¿Propósito de los canales de riego?",
           ["Navegar", "Llevar agua a cultivos", "Agua potable", "Defensa"], 1,
           "Controlaban inundaciones y llevaban agua del Tigris y Éufrates a los cultivos."),
    make_q("Evaluate", C, "Comparando escritura cuneiforme con comunicación digital:",
           ["Cuneiforme más rápida", "Física y local vs. virtual e instantánea global", "Mismo alfabeto", "No tenían escritura"], 1,
           "La cuneiforme requería tablillas físicas; hoy la información viaja en segundos."),
    make_q("Understand", C, "¿Qué compartían acadios, babilonios y asirios?",
           ["Imperios marítimos", "Unificaron territorios en Mesopotamia", "Misma capital", "Derrotados por Egipto"], 1,
           "Controlaron la región mesopotámica en distintos períodos."),
])

# ── W05 ──────────────────────────────────────────────────────────────────
save_qs(5, [
    make_q("Remember", C, "¿Qué río fue esencial para Egipto?",
           ["Tigris", "Nilo", "Éufrates", "Indo"], 1,
           "El Nilo: 'Egipto es un don del Nilo' (Herodoto). Sus inundaciones depositaban limo fértil."),
    make_q("Remember", C, "Gobernante egipcio considerado dios:",
           ["Emperador", "Faraón", "Rey-sacerdote", "Visir"], 1,
           "El faraón era máxima autoridad política, religiosa y militar."),
    make_q("Understand", C, "¿Propósito de las pirámides?",
           ["Observatorios", "Templos", "Tumbas monumentales para faraones", "Almacenes"], 2,
           "Las pirámides albergaban la momia del faraón y sus tesoros para la otra vida."),
    make_q("Apply", C, "¿Propósito de la momificación?",
           ["Medicina", "Conservar el cuerpo para la vida eterna", "Castigo", "Alimento animal"], 1,
           "Preservaba el cuerpo para que el alma lo reconociera en la otra vida."),
    make_q("Understand", C, "Cima de la sociedad egipcia:",
           ["Campesinos", "Faraón, familia real, altos sacerdotes", "Soldados", "Esclavos"], 1,
           "Pirámide: faraón, familia real, sacerdotes, nobles, escribas, comerciantes, campesinos, esclavos."),
    make_q("Analyze", C, "¿Por qué crearon un calendario de 365 días?",
           ["Copiaron de romanos", "Predecir inundaciones del Nilo y agricultura", "Cumpleaños", "Luna"], 1,
           "Uno de los primeros calendarios solares para predecir las inundaciones anuales del Nilo."),
    make_q("Remember", C, "Escritura egipcia:",
           ["Cuneiforme", "Jeroglífico", "Alfabeto fenicio", "Lineal B"], 1,
           "Los jeroglíficos combinaban logogramas y signos fonéticos."),
    make_q("Apply", C, "¿Por qué adoraban al dios Ra?",
           ["Dios guerra", "Dios del sol, fuente de vida en el desierto", "Dios del Nilo", "Protegía pirámides"], 1,
           "Ra determinaba los ciclos agrícolas y la vida misma."),
    make_q("Evaluate", C, "Egipto faraónico vs democracia colombiana:",
           ["Ambos eligen", "Egipto: teocracia/faraón divino. Colombia: democracia/poderes independientes", "Ambos tienen congreso", "Colombia tiene faraón"], 1,
           "Egipto concentraba poder en el faraón; Colombia separa poderes ejecutivo, legislativo y judicial."),
    make_q("Understand", C, "¿Papel de los escribas?",
           ["Esclavos constructores", "Funcionarios que registraban cosechas e impuestos", "Guerreros", "Sacerdotes"], 1,
           "Administraban el Estado: registraban cosechas, impuestos y documentos oficiales."),
])

# ── W06 ──────────────────────────────────────────────────────────────────
save_qs(6, [
    make_q("Remember", C, "¿A orillas de qué río se desarrolló la civilización del Valle del Indo?",
           ["Ganges", "Indo", "Brahmaputra", "Nilo"], 1,
           "La civilización del Indo (Harappa, Mohenjo-Daro) floreció ~2500 a.C."),
    make_q("Remember", C, "Escritura más antigua de China:",
           ["Jeroglíficos", "Cuneiforme", "Huesos oraculares (Shang)", "Sánscrito"], 2,
           "Caracteres en huesos oraculares de la dinastía Shang (1600-1046 a.C.)."),
    make_q("Understand", C, "Sistema de castas indio:",
           ["Gobierno", "Jerarquía social hereditaria en grupos cerrados", "Escritura", "Templos"], 1,
           "Dividía en brahmanes, chatrias, vaisias y sudras. Era hereditario."),
    make_q("Apply", C, "¿Qué enseñaba Buda?",
           ["Muchos dioses", "Camino para superar el sufrimiento (Nirvana)", "Guerra santa", "Pirámides"], 1,
           "Buda enseñó el Noble Camino Óctuple para alcanzar la iluminación."),
    make_q("Understand", C, "Confucio enseñaba:",
           ["Vida después de la muerte", "Armonía social, respeto y rectitud moral", "Conquista militar", "Un dios"], 1,
           "Enseñó valores como respeto y educación para la armonía social."),
    make_q("Analyze", C, "¿Por qué fue importante la Gran Muralla?",
           ["Templo", "Protección contra invasiones del norte", "Mercado", "Canal"], 1,
           "Protegía la frontera norte de invasiones de mongoles y otros pueblos."),
    make_q("Remember", C, "Invento chino que revolucionó navegación:",
           ["Astrolabio", "Brújula", "Telescopio", "Barco de vapor"], 1,
           "La brújula magnética fue inventada en la dinastía Han."),
    make_q("Apply", C, "Característica del hinduismo:",
           ["Un dios", "Muchos dioses y reencarnación (karma)", "Sin dioses", "Adora al faraón"], 1,
           "Politeísta, cree en la reencarnación determinada por el karma."),
    make_q("Evaluate", C, "Similitud India y China antiguas:",
           ["Democracias", "Civilizaciones fluviales alrededor de grandes ríos", "Mismo alfabeto", "Sin comercio"], 1,
           "India (Indo, Ganges) y China (Amarillo, Yangtsé): ambas fluviales."),
    make_q("Understand", C, "Aislamiento cultural de China:",
           ["Rodeada de mares", "Himalaya, desiertos y mar la aislaban", "Sin fronteras", "Muros"], 1,
           "El Himalaya, Gobi y Pacífico favorecieron un desarrollo cultural único."),
])

# ── W07 ──────────────────────────────────────────────────────────────────
save_qs(7, [
    make_q("Remember", C, "¿Por qué son famosos los fenicios?",
           ["Pirámides", "Comercio marítimo y creación del alfabeto", "Imperio militar", "Democracia"], 1,
           "Grandes navegantes y comerciantes. Crearon el primer alfabeto fonético de 22 signos."),
    make_q("Remember", C, "Aporte cultural fenicio:",
           ["Cuneiforme", "Alfabeto fonético de 22 signos", "Jeroglíficos", "Rueda"], 1,
           "Base de los alfabetos griego, latino y el nuestro."),
    make_q("Understand", C, "Creencia distintiva de los hebreos:",
           ["Politeísmo", "Monoteísmo (Yahvé)", "Ateísmo", "Sol"], 1,
           "Fueron pioneros en el monoteísmo. Base del judaísmo, cristianismo e islam."),
    make_q("Apply", C, "El Éxodo describe:",
           ["Construcción del templo", "Salida de hebreos de Egipto con Moisés", "Conquista de Jericó", "Creación de Israel"], 1,
           "Liberación de la esclavitud en Egipto hacia la Tierra Prometida."),
    make_q("Understand", C, "¿Cómo administraban los persas su imperio?",
           ["Guerras", "Satrapías con gobernadores y respeto cultural", "Democracia", "Esclavitud"], 1,
           "Dividido en provincias (satrapías). Ciro respetaba costumbres locales."),
    make_q("Analyze", C, "Éxito del Imperio Persa:",
           ["Ejército poderoso", "Tolerancia cultural y eficiente administración", "Eliminaban pueblos", "Imponían religión"], 1,
           "Respetaban culturas locales y construyeron caminos para administrar."),
    make_q("Remember", C, "Rey persa que conquistó Babilonia:",
           ["Darío I", "Ciro el Grande", "Jerjes", "Artajerjes"], 1,
           "Ciro conquistó Babilonia en 539 a.C. y liberó a los hebreos."),
    make_q("Apply", C, "¿Qué heredamos del alfabeto fenicio?",
           ["Números", "Nuestras letras (vía griegos y romanos)", "Cuneiforme", "Jeroglíficos"], 1,
           "El alfabeto latino deriva del griego, que adaptó el fenicio."),
    make_q("Evaluate", C, "Persas vs asirios: diferencia principal:",
           ["Persas más violentos", "Persas respetaban culturas; asirios deportaban pueblos", "Iguales", "Persas sin religión"], 1,
           "Asirios deportaban pueblos; persas solo exigían tributo."),
    make_q("Understand", C, "Religión fundada por Zoroastro:",
           ["Hinduismo", "Zoroastrismo (bien vs mal)", "Budismo", "Judaísmo"], 1,
           "Enseñaba la lucha entre Ahura Mazda (bien) y Angra Mainyu (mal)."),
])

# ── W08 ──────────────────────────────────────────────────────────────────
save_qs(8, [
    make_q("Remember", C, "¿Qué marca el paso de Prehistoria a Historia?",
           ["Rueda", "Escritura (~3500 a.C.)", "Fuego", "Agricultura"], 1,
           "La escritura cuneiforme sumeria marca el inicio de la Historia."),
    make_q("Understand", C, "¿Qué fue primero?",
           ["Neolítico", "Paleolítico", "Ambos", "Edad de los Metales"], 1,
           "Paleolítico (~2.5 millones de años) antes que Neolítico (~10.000 a.C.)."),
    make_q("Apply", C, "Civilización entre Tigris y Éufrates:",
           ["Egipto", "Mesopotamia", "India", "China"], 1,
           "Mesopotamia = 'tierra entre ríos'."),
    make_q("Remember", C, "Tres etapas de la Prehistoria:",
           ["Antigua, Media, Moderna", "Paleolítico, Neolítico, Edad de los Metales", "Bronce, Hierro, Acero", "1, 2, 3"], 1,
           "Paleolítico, Neolítico y Edad de los Metales."),
    make_q("Understand", C, "Civilización que construyó pirámides:",
           ["Mesopotamia", "Egipto", "India", "Fenicia"], 1,
           "Los egipcios construyeron pirámides como tumbas para faraones."),
    make_q("Analyze", C, "¿Por qué los ríos fueron importantes para las primeras civilizaciones?",
           ["Rutas de guerra", "Agua, suelo fértil, transporte y comercio", "Vivían los dioses", "Separaban reinos"], 1,
           "Los grandes ríos daban agua para cultivos, pesca y transporte."),
    make_q("Remember", C, "Pueblo que creó el alfabeto fonético:",
           ["Egipcios", "Fenicios", "Griegos", "Romanos"], 1,
           "Los fenicios crearon el primer alfabeto de 22 signos."),
    make_q("Apply", C, "Pueblo que practicó el monoteísmo primero:",
           ["Fenicios", "Hebreos", "Persas", "Egipcios"], 1,
           "Los hebreos fueron el primer pueblo monoteísta."),
    make_q("Evaluate", C, "¿Cuál fue la principal herencia de las primeras civilizaciones?",
           ["La escritura, leyes, matemáticas y astronomía", "Solo las pirámides", "Ninguna", "Solo la guerra"], 0,
           "Legaron escritura, códigos legales, avances matemáticos y astronómicos."),
    make_q("Understand", C, "Característica común de las primeras civilizaciones:",
           ["Eran marítimas", "Se desarrollaron en valles fluviales fértiles", "Eran democráticas", "Rechazaban el comercio"], 1,
           "Todas surgieron en valles de grandes ríos con suelos fértiles."),
])

print("Part 1 complete: W01-W08")
