#!/usr/bin/env python3
"""Generate W06-W07 bundles for Lectura Critica G4."""
import sys
sys.path.insert(0, r"E:\scripts-python\worldexams\questions_data\colombia\lectura-critica\grado-4\2026\weekly")
from gen_all_v2 import make, opt

make(6, "comprension-inferencial-causas", "Comprensi\u00f3n inferencial: inferir causas",
"inferencia, causas, relaciones causales, por qu\u00e9", 0.72, [
("R","L","Causa expl\u00edcita.","*\"Los ni\u00f1os no salieron al recreo porque estaba lloviendo muy fuerte.\"* \u00bfPor qu\u00e9 no salieron?",opt(("A","Estaban castigados.",False),("B","Llov\u00eda muy fuerte.",True,"Correcto."),("C","No quer\u00edan.",False),("D","Era muy tarde.",False)),"Identificar causa expl\u00edcita."),
("R","L","Causa agricultura.","*\"El cultivo de caf\u00e9 disminuy\u00f3 porque hubo una sequ\u00eda larga.\"* \u00bfCausa?",opt(("A","Campesinos se fueron.",False),("B","La sequ\u00eda larga.",True,"Correcto."),("C","No hab\u00eda semillas.",False),("D","Caf\u00e9 dif\u00edcil.",False)),"Causa expl\u00edcita."),
("U","G","Causa fen\u00f3meno.","*\"El r\u00edo se desbord\u00f3 porque llovi\u00f3 tres d\u00edas seguidos.\"* \u00bfCausa?",opt(("A","Calor del sol.",False),("B","Tres d\u00edas de lluvia.",True,"Correcto."),("C","Basura en el r\u00edo.",False),("D","Un terremoto.",False)),"Causa de fen\u00f3meno."),
("U","G","Causa emoci\u00f3n.","*\"Mar\u00eda se puso feliz al recibir carta de su abuela en Sincelejo.\"* \u00bfPor qu\u00e9 feliz?",opt(("A","Gan\u00f3 premio.",False),("B","Recibi\u00f3 carta de su abuela.",True,"Correcto."),("C","Sali\u00f3 al parque.",False),("D","Comi\u00f3 helado.",False)),"Causa de emoci\u00f3n."),
("U","G","Conector causal.","*\"El equipo perdi\u00f3, as\u00ed que estaban tristes.\"* \u00bfPalabra causal?",opt(("A","perdi\u00f3",False),("B","as\u00ed que",True,"Correcto."),("C","equipo",False),("D","tristes",False)),"Conector causal."),
("Ap","I","Causa acci\u00f3n.","*\"Pedro lleg\u00f3 tarde y la profe lo anot\u00f3.\"* \u00bfCausa?",opt(("A","Lleg\u00f3 temprano.",False),("B","Lleg\u00f3 bien.",False),("C","Lleg\u00f3 tarde.",True,"Correcto."),("D","No hizo tarea.",False)),"Inferir causa."),
("Ap","I","Causa ambiental.","*\"En la quebrada ya no hay peces. Los jabones y qu\u00edmicos los mataron.\"* \u00bfCausa?",opt(("A","Los pescadores.",False),("B","Jabones y qu\u00edmicos.",True,"Correcto."),("C","El cambio de clima.",False),("D","Los patos.",False)),"Causa ambiental."),
("An","I","Causa vs efecto.","*\"El \u00e1rbol se cay\u00f3 por el viento fuerte. Bloque\u00f3 la carretera.\"* \u00bfCAUSA?",opt(("A","Bloque\u00f3 la carretera.",False,"Efecto."),("B","El viento fuerte.",True,"Correcto."),("C","El \u00e1rbol se cay\u00f3.",False,"Evento."),("D","Carretera mojada.",False)),"Diferenciar causa de efecto."),
("An","R","Evaluar causa.","*\"La planta se marchit\u00f3. Dices que fue porque no le gustaba la maceta.\"* \u00bfV\u00e1lida?",opt(("A","S\u00ed, las plantas tienen gustos.",False),("B","No, necesita agua, sol o nutrientes.",True,"Correcto."),("C","S\u00ed, todas son v\u00e1lidas.",False),("D","No, pero da igual.",False)),"Evaluar causa razonable."),
("An","R","Causa probable.","*\"Juan no pas\u00f3 el examen.\"* \u00bfCausa m\u00e1s probable?",opt(("A","Mala suerte.",False),("B","No estudi\u00f3 suficiente.",True,"Correcto."),("C","Examen imposible.",False),("D","Profe mala.",False)),"Seleccionar causa razonable."),
], "Bundle sobre inferencia de causas.")

make(7, "comprension-inferencial-consecuencias", "Comprensi\u00f3n inferencial: inferir consecuencias",
"inferencia, consecuencias, efectos, resultados", 0.72, [
("R","L","Consecuencia expl\u00edcita.","*\"No estudi\u00f3, por eso sac\u00f3 nota baja.\"* \u00bfConsecuencia?",opt(("A","Nota alta.",False),("B","Nota baja.",True,"Correcto."),("C","Premio.",False),("D","Felicitaciones.",False)),"Consecuencia expl\u00edcita."),
("R","L","Consecuencia lluvia.","*\"Llovi\u00f3 toda la noche, el r\u00edo creci\u00f3 y calles se inundaron.\"* \u00bfConsecuencia?",opt(("A","Hizo sol.",False),("B","R\u00edo creci\u00f3 y calles se inundaron.",True,"Correcto."),("C","Ni\u00f1os jugaron.",False),("D","Paseo.",False)),"Consecuencia expl\u00edcita."),
("U","G","Consecuencia positiva.","*\"Sembraron \u00e1rboles, hubo menos deslizamientos.\"* \u00bfConsecuencia?",opt(("A","M\u00e1s deslizamientos.",False),("B","Menos deslizamientos.",True,"Correcto."),("C","Nada.",False),("D","\u00c1rboles se secaron.",False)),"Consecuencia positiva."),
("U","G","Consecuencia limpieza.","*\"Recogieron basura del patio. Colegio limpio.\"* \u00bfConsecuencia?",opt(("A","Colegio sucio.",False),("B","Colegio limpio.",True,"Correcto."),("C","Estudiantes se fueron.",False),("D","Lleg\u00f3 basura.",False)),"Consecuencia positiva."),
("U","G","Conector consecuencia.","*\"El volc\u00e1n hizo erupci\u00f3n, por lo tanto ceniza cubri\u00f3 cultivos.\"* \u00bfConector?",opt(("A","volc\u00e1n",False),("B","erupci\u00f3n",False),("C","por lo tanto",True,"Correcto."),("D","cultivos",False)),"Conector de consecuencia."),
("Ap","I","Predecir peligro.","*\"Do\u00f1a Marta dej\u00f3 la olla en el fog\u00f3n encendido y sali\u00f3.\"* \u00bfQu\u00e9 podr\u00eda pasar?",opt(("A","Comida se enfri\u00f3.",False),("B","Podr\u00eda quemarse y causar incendio.",True,"Correcto."),("C","Nada grave.",False),("D","Llegaron visitas.",False)),"Predecir consecuencia peligrosa."),
("Ap","I","Consecuencia l\u00f3gica.","*\"Ni\u00f1os jugaron con arena mojada y se ensuciaron. Mam\u00e1 estricta.\"* \u00bfQu\u00e9 pasa?",opt(("A","Los felicit\u00f3.",False),("B","Les llam\u00f3 la atenci\u00f3n.",True,"Correcto."),("C","No se dio cuenta.",False),("D","Compr\u00f3 ropa nueva.",False)),"Inferir consecuencia l\u00f3gica."),
("An","I","Cadena de consecuencias.","*\"No desayun\u00f3. En ed. f\u00edsica se sinti\u00f3 d\u00e9bil.\"* \u00bfCadena?",opt(("A","No desayunar -> d\u00e9bil -> bajo rendimiento.",True,"Correcto."),("B","Ed.f\u00edsica -> no desayunar.",False,"Invertido."),("C","D\u00e9bil -> no desayunar.",False,"Invertido."),("D","No hay relaci\u00f3n.",False)),"Cadena causal."),
("An","R","Causa vs consecuencia.","*\"Golpearon ventana con piedra y el vidrio se rompi\u00f3.\"* \u00bfCONSECUENCIA?",opt(("A","Golpearon con piedra.",False,"Causa."),("B","Vidrio se rompi\u00f3.",True,"Correcto."),("C","Piedra era grande.",False),("D","Ventana fr\u00e1gil.",False)),"Diferenciar."),
("An","R","Consecuencia sequ\u00eda.","*\"En la Guajira no ha llovido en 6 meses.\"* \u00bfConsecuencia posible?",opt(("A","Cultivos crecieron.",False),("B","Escasez de agua, cultivos se secan.",True,"Correcto."),("C","R\u00edos crecieron.",False),("D","Hace fr\u00edo.",False)),"Consecuencia de sequ\u00eda."),
], "Bundle sobre inferencia de consecuencias.")
