#!/usr/bin/env python3
"""Generate W05 bundle for Lectura Critica G4."""
import sys
sys.path.insert(0, r"E:\scripts-python\worldexams\questions_data\colombia\lectura-critica\grado-4\2026\weekly")
from gen_all_v2 import make, opt

make(5, "repaso-p1", "Repaso P1",
"repaso: idea principal, detalles, secuencia, personajes",
0.70, [
("U","G","Repaso idea principal.",
"*\"Los mangos son frutas tropicales. En Colombia hay muchas variedades.\"* \u00bfIdea principal?",
opt(("A","Los mangos son rojos.",False),("B","Los mangos son frutas tropicales de Colombia.",True,"Correcto."),("C","Los mangos son caros.",False),("D","Los mangos crecen en el desierto.",False)),
"Repaso idea principal."),
("R","L","Repaso detalle expl\u00edcito.",
"*\"La iguana verde mide hasta 2 metros de largo.\"* \u00bfCu\u00e1nto mide?",
opt(("A","1 metro.",False),("B","2 metros.",True,"Correcto."),("C","3 metros.",False),("D","50 cm.",False)),
"Repaso detalle expl\u00edcito."),
("U","G","Repaso secuencia.",
"*\"Primero lavar las frutas, despu\u00e9s picarlas y finalmente licuarlas.\"* \u00bfQu\u00e9 se hace despu\u00e9s de lavar?",
opt(("A","Licuar.",False,"Eso es al final."),("B","Picar las frutas.",True,"Correcto."),("C","Servir.",False),("D","Comprar.",False)),
"Repaso orden de pasos."),
("U","G","Repaso personaje.",
"*\"Don Jos\u00e9 es un campesino que cultiva caf\u00e9 en la Sierra Nevada.\"* \u00bfQu\u00e9 es Don Jos\u00e9?",
opt(("A","M\u00e9dico.",False),("B","Campesino cafetero.",True,"Correcto."),("C","Profesor.",False),("D","Pescador.",False)),
"Repaso personaje."),
("Ap","I","Repaso idea impl\u00edcita.",
"*\"Las aulas tienen luz tenue. Los estudiantes bostezan. Algunos se duermen.\"* \u00bfQu\u00e9 pasa?",
opt(("A","Est\u00e1n felices.",False),("B","Est\u00e1n aburridos o con sue\u00f1o.",True,"Correcto."),("C","Est\u00e1n jugando.",False),("D","Cantan.",False)),
"Repaso inferencia."),
("R","L","Repaso detalle: lugar.",
"*\"La Feria de las Flores se celebra en Medell\u00edn cada a\u00f1o.\"* \u00bfD\u00f3nde se celebra?",
opt(("A","Bogot\u00e1.",False),("B","Medell\u00edn.",True,"Correcto."),("C","Cali.",False),("D","Barranquilla.",False)),
"Repaso detalle-lugar."),
("An","I","Repaso comparar.",
"*\"Un texto dice: \u2018El c\u00f3ndor es grande\u2019. Otro dice: \u2018El colibr\u00ed es peque\u00f1o\u2019.\"* \u00bfQu\u00e9 hacen?",
opt(("A","Comparar dos aves.",True,"Correcto."),("B","Describir el clima.",False),("C","Dar opini\u00f3n.",False),("D","Contar cuento.",False)),
"Repaso comparaci\u00f3n."),
("An","R","Repaso evaluar.",
"*\"\u00bfEs la frase \u2018Las tortugas son malas\u2019 una idea principal v\u00e1lida?\"*",
opt(("A","S\u00ed, alguien lo dice.",False),("B","No, es opini\u00f3n, no hecho.",True,"Correcto."),("C","S\u00ed, todas v\u00e1lidas.",False),("D","Depende.",False)),
"Repaso evaluar ideas."),
("An","R","Repaso orden cronol\u00f3gico.",
"*\"\u00bfQu\u00e9 pasa si en una receta primero horneas y luego mezclas?\"*",
opt(("A","Funciona igual.",False),("B","No funciona, el orden importa.",True,"Correcto."),("C","Solo si horneas bien.",False),("D","Se puede al rev\u00e9s.",False)),
"Repaso importancia del orden."),
("Ap","I","Repaso personaje: acciones.",
"*\"La ni\u00f1a devolvi\u00f3 la billetera que encontr\u00f3 en la calle.\"* \u00bfC\u00f3mo es?",
opt(("A","Deshonesta.",False),("B","Honesta.",True,"Correcto."),("C","Desordenada.",False),("D","Perezosa.",False)),
"Repaso inferir personalidad."),
], "Bundle de repaso P1.")
