#!/usr/bin/env python3
"""Generate W11-W15 bundles for Lectura Critica G4."""
import sys
sys.path.insert(0, r"E:\scripts-python\worldexams\questions_data\colombia\lectura-critica\grado-4\2026\weekly")
from gen_all_v2 import make, opt

make(11, "textos-informativos-noticias", "Textos informativos: noticias",
"noticias, texto informativo, estructura, titulares", 0.74, [
("R","L","Titular noticia.","*\"NOTICIA: Estudiantes de Buga ganan concurso nacional de lectura\"* \u00bfDe qu\u00e9 trata?",opt(("A","Deporte en Buga.",False),("B","Estudiantes ganan concurso de lectura.",True,"Correcto."),("C","Cierre de escuela.",False),("D","Concierto en Buga.",False)),"Tema del titular."),
("R","L","Fecha noticia.","*\"El viernes 15 de marzo, la escuela de Buga gan\u00f3 el concurso.\"* \u00bfCu\u00e1ndo?",opt(("A","Viernes 15 de marzo.",True,"Correcto."),("B","Lunes 10.",False),("C","S\u00e1bado 16.",False),("D","Domingo 17.",False)),"Fecha."),
("U","G","Qu\u00e9 pas\u00f3.","*\"Bucaramanga inaugur\u00f3 un nuevo parque infantil en La Joya. 200 ni\u00f1os disfrutar\u00e1n.\"* \u00bfQu\u00e9 pas\u00f3?",opt(("A","Inauguraron parque.",True,"Correcto."),("B","Cerraron parque.",False),("C","Construyeron escuela.",False),("D","Sembraron \u00e1rboles.",False)),"Evento principal."),
("U","G","D\u00f3nde ocurri\u00f3.","*\"En Sop\u00f3, Cundinamarca, se realiz\u00f3 la primera feria del libro infantil.\"* \u00bfD\u00f3nde?",opt(("A","Bogot\u00e1.",False),("B","Sop\u00f3, Cundinamarca.",True,"Correcto."),("C","Medell\u00edn.",False),("D","Cali.",False)),"Lugar."),
("U","G","Prop\u00f3sito noticia.","*\"Noticia: cierre temporal de la v\u00eda al Llano por derrumbes.\"* \u00bfProp\u00f3sito?",opt(("A","Entretener.",False),("B","Informar sobre el cierre.",True,"Correcto."),("C","Vender productos.",False),("D","Opinar.",False)),"Prop\u00f3sito informativo."),
("Ap","I","Inferir causa.","*\"Festival de la cometa en Villa de Leyva cancelado por fuertes vientos.\"* \u00bfCausa?",opt(("A","Falta dinero.",False),("B","Fuertes vientos.",True,"Correcto."),("C","Pocos participantes.",False),("D","Lluvia.",False)),"Causa cancelaci\u00f3n."),
("Ap","I","Hecho vs opini\u00f3n.","*\"La obra del acueducto termin\u00f3 a tiempo. \u2018Es un gran avance\u2019, dijo alcalde.\"* \u00bfHECHO?",opt(("A","Es gran avance.",False,"Opini\u00f3n."),("B","La obra termin\u00f3 a tiempo.",True,"Correcto."),("C","Alcalde es bueno.",False,"Opini\u00f3n."),("D","Pueblo feliz.",False,"Opini\u00f3n.")),"Distinguir hecho de opini\u00f3n."),
("An","I","Analizar titular.","*\"Titular: \u2018Joven de 12 a\u00f1os crea app para cuidar el agua\u2019\"* \u00bfQu\u00e9 informa?",opt(("A","Joven cre\u00f3 app sobre agua.",True,"Correcto."),("B","App cuesta dinero.",False),("C","Gan\u00f3 premio.",False),("D","App es mala.",False)),"Analizar titular."),
("An","R","\u00bfEs noticia?","*\"Mi gato se subi\u00f3 al \u00e1rbol.\"* \u00bfEs noticia para el peri\u00f3dico?",opt(("A","S\u00ed, interesante.",False),("B","No, hecho personal sin relevancia p\u00fablica.",True,"Correcto."),("C","S\u00ed, todos los gatos son noticia.",False),("D","No, pero podr\u00eda.",False)),"Evaluar noticiabilidad."),
("An","R","Elementos noticia.","*\"Noticia: \u00bfQu\u00e9?, \u00bfQui\u00e9n?, \u00bfCu\u00e1ndo?, \u00bfD\u00f3nde?, \u00bfPor qu\u00e9?\"* \u00bfQu\u00e9 NO es elemento?",opt(("A","Lugar.",False,"S\u00ed."),("B","Opini\u00f3n del periodista.",True,"Correcto."),("C","Fecha.",False,"S\u00ed."),("D","Involucrados.",False,"S\u00ed.")),"Elementos."),
], "Bundle noticias.")

make(12, "textos-informativos-divulgacion", "Textos informativos: art\u00edculos de divulgaci\u00f3n",
"divulgaci\u00f3n, texto expositivo, informaci\u00f3n cient\u00edfica", 0.73, [
("R","L","Dato cient\u00edfico.","*\"El colibr\u00ed mueve sus alas hasta 80 veces por segundo.\"* \u00bfCu\u00e1ntas veces?",opt(("A","20.",False),("B","50.",False),("C","80.",True,"Correcto."),("D","100.",False)),"Dato expl\u00edcito."),
("R","L","Animal descrito.","*\"El c\u00f3ndor de los Andes es el ave voladora m\u00e1s grande.\"* \u00bfQu\u00e9 animal?",opt(("A","Colibr\u00ed.",False),("B","C\u00f3ndor de los Andes.",True,"Correcto."),("C","Guacamaya.",False),("D","Tuc\u00e1n.",False)),"Sujeto."),
("U","G","Prop\u00f3sito divulgativo.","*\"Hormigas pueden oler az\u00facar a varios metros.\"* \u00bfProp\u00f3sito?",opt(("A","Entretener.",False),("B","Informar descubrimiento.",True,"Correcto."),("C","Vender az\u00facar.",False),("D","Opinar.",False)),"Prop\u00f3sito."),
("U","G","Dato curioso.","*\"Ballenas jorobadas viajan al Pac\u00edfico colombiano para tener cr\u00edas.\"* \u00bfPor qu\u00e9 viajan?",opt(("A","Turismo.",False),("B","Tener cr\u00edas.",True,"Correcto."),("C","Comer.",False),("D","Descansar.",False)),"Informaci\u00f3n explicativa."),
("U","G","Explicaci\u00f3n cient\u00edfica.","*\"Fotos\u00edntesis: plantas convierten luz solar en energ\u00eda.\"* \u00bfQu\u00e9 convierten?",opt(("A","Agua en aire.",False),("B","Luz solar en energ\u00eda.",True,"Correcto."),("C","Tierra en alimento.",False),("D","Viento en electricidad.",False)),"Proceso."),
("Ap","I","Inferir significado.","*\"La capa de ozono protege de rayos ultravioleta.\"* \u00bfQu\u00e9 es ultravioleta?",opt(("A","Rayos que no vemos.",True,"Correcto."),("B","Rayos de colores.",False),("C","Luz visible.",False),("D","Sonidos del sol.",False)),"Inferir por contexto."),
("Ap","I","Relacionar concepto.","*\"Herb\u00edvoros comen plantas, ej: vaca y caballo.\"* \u00bfCu\u00e1l es herb\u00edvoro?",opt(("A","Le\u00f3n.",False,"Carn\u00edvoro."),("B","Vaca.",True,"Correcto."),("C","Tibur\u00f3n.",False,"Carn\u00edvoro."),("D","\u00c1guila.",False,"Carn\u00edvoro.")),"Concepto-ejemplo."),
("An","I","Comparar datos.","*\"\u00c1rbol m\u00e1s alto Colombia: 80m. Del mundo: 116m.\"* \u00bfConclusi\u00f3n?",opt(("A","Colombia tiene el m\u00e1s alto.",False),("B","El del mundo supera al de Colombia.",True,"Correcto."),("C","Son iguales.",False),("D","Colombia no tiene \u00e1rboles.",False)),"Concluir."),
("An","R","Evaluar fuente.","*\"Art\u00edculo dice que las plantas hablan entre s\u00ed.\"* \u00bfCiencia o ficci\u00f3n?",opt(("A","Hecho comprobado.",False),("B","Ficci\u00f3n, no comprobado.",True,"Correcto."),("C","Falso.",False),("D","Todos hablan.",False)),"Credibilidad."),
("An","R","Prop\u00f3sito divulgaci\u00f3n.","*\"\u00bfSab\u00edas que el coraz\u00f3n del colibr\u00ed late 1.200 veces/min?\"* \u00bfPara qu\u00e9?",opt(("A","Dar miedo.",False),("B","Ense\u00f1ar algo interesante.",True,"Correcto."),("C","Vender colibr\u00edes.",False),("D","Entretener con ficci\u00f3n.",False)),"Reconocer prop\u00f3sito."),
], "Bundle divulgaci\u00f3n.")

make(13, "textos-narrativos-cuentos-fabulas", "Textos narrativos: cuentos y f\u00e1bulas",
"cuentos, f\u00e1bulas, moraleja, narraci\u00f3n", 0.75, [
("R","L","Nombre personaje.","*\"Hab\u00eda una vez una tortuga llamada Matilde en la ci\u00e9naga de Zapatosa.\"* \u00bfC\u00f3mo se llama?",opt(("A","Mar\u00eda.",False),("B","Matilde.",True,"Correcto."),("C","Sof\u00eda.",False),("D","Carolina.",False)),"Nombre."),
("R","L","Lugar.","*\"En una vereda de Boyac\u00e1, un campesino encontr\u00f3 un tesoro.\"* \u00bfD\u00f3nde?",opt(("A","Bogot\u00e1.",False),("B","Vereda de Boyac\u00e1.",True,"Correcto."),("C","Cali.",False),("D","Santa Marta.",False)),"Escenario."),
("U","G","Conflicto.","*\"El rat\u00f3n quer\u00eda cruzar el r\u00edo pero no sab\u00eda nadar.\"* \u00bfConflicto?",opt(("A","Es nadador.",False),("B","No puede cruzar porque no sabe nadar.",True,"Correcto."),("C","R\u00edo seco.",False),("D","Miedo al agua.",False)),"Conflicto."),
("U","G","Moraleja.","*\"Liebre se burlaba de tortuga lenta. Tortuga gan\u00f3 carrera.\"* \u00bfMoraleja?",opt(("A","Correr r\u00e1pido gana.",False),("B","Constancia vence confianza excesiva.",True,"Correcto."),("C","Tortugas son mejores.",False),("D","Liebres no corren.",False)),"Moraleja."),
("U","G","Caracter\u00edstica.","*\"Hormiga trabajaba guardando comida. Cigarra cantaba.\"* \u00bfC\u00f3mo es la hormiga?",opt(("A","Perezosa.",False),("B","Trabajadora.",True,"Correcto."),("C","Cantante.",False),("D","Desordenada.",False)),"Caracter\u00edstica."),
("Ap","I","Inferir sentimiento.","*\"Ni\u00f1o perdi\u00f3 su perro en Sincelejo y comenz\u00f3 a llorar.\"* \u00bfC\u00f3mo se sent\u00eda?",opt(("A","Feliz.",False),("B","Triste.",True,"Correcto."),("C","Enojado.",False),("D","Aburrido.",False)),"Emoci\u00f3n."),
("Ap","I","Predecir desenlace.","*\"Ni\u00f1o busc\u00f3 su perro por todo el pueblo y entr\u00f3 a la iglesia...\"* \u00bfQu\u00e9 pasa?",opt(("A","Encontr\u00f3 a su perro.",True,"Probable."),("B","Perro desapareci\u00f3.",False,"Tono negativo."),("C","Iglesia se cay\u00f3.",False),("D","Ni\u00f1o se fue.",False)),"Predecir."),
("An","I","Causa en cuento.","*\"\u00c1rbol no daba frutos porque ra\u00edces enfermas.\"* \u00bfCausa?",opt(("A","\u00c1rbol no da frutos.",False,"Efecto."),("B","Ra\u00edces enfermas.",True,"Correcto."),("C","Sequ\u00eda.",False),("D","Plagas.",False)),"Causa narrativa."),
("An","R","Evaluar moraleja.","*\"F\u00e1bula cigarra y hormiga.\"* \u00bfEnse\u00f1anza?",opt(("A","Cantar es mejor.",False),("B","Prever y trabajar para el futuro.",True,"Correcto."),("C","Solo hormigas inteligentes.",False),("D","Verano es para jugar.",False)),"Evaluar moraleja."),
("An","R","Crear final.","*\"Final donde perro encuentra a su due\u00f1o.\"* \u00bfBuen final?",opt(("A","Perro se perdi\u00f3.",False,"No resuelve."),("B","Due\u00f1o abraz\u00f3 al perro y volvieron felices.",True,"Correcto."),("C","Perro se fue a otro pa\u00eds.",False),("D","Due\u00f1o compr\u00f3 otro perro.",False)),"Evaluar final."),
], "Bundle cuentos y f\u00e1bulas.")

make(14, "textos-narrativos-estructura", "Textos narrativos: estructura (inicio, nudo, desenlace)",
"estructura narrativa, inicio, nudo, desenlace", 0.73, [
("R","L","Inicio.","*\"\u00c9rase una vez, en el Valle del Cauca, un ni\u00f1o llamado Andr\u00e9s que so\u00f1aba con volar.\"* \u00bfQu\u00e9 parte?",opt(("A","Final.",False),("B","Inicio.",True,"Correcto."),("C","Nudo.",False),("D","Moraleja.",False)),"Inicio."),
("R","L","Desenlace.","*\"Y al final, Andr\u00e9s construy\u00f3 un planeador y vol\u00f3.\"* \u00bfQu\u00e9 parte?",opt(("A","Inicio.",False),("B","Nudo.",False),("C","Desenlace.",True,"Correcto."),("D","Presentaci\u00f3n.",False)),"Desenlace."),
("U","G","Nudo.","*\"Andr\u00e9s quer\u00eda volar pero no ten\u00eda alas y se burlaban.\"* \u00bfParte?",opt(("A","Inicio.",False),("B","Nudo.",True,"Correcto. Conflicto."),("C","Desenlace.",False),("D","T\u00edtulo.",False)),"Nudo."),
("U","G","Orden.","*\"1. Hab\u00eda un pez. 2. Quer\u00eda volar. 3. Salt\u00f3 y se sinti\u00f3 libre.\"* \u00bfOrden?",opt(("A","Final, inicio, nudo.",False),("B","Inicio, nudo, desenlace.",True,"Correcto."),("C","Nudo, inicio, final.",False),("D","Desenlace, nudo, inicio.",False)),"Orden estructural."),
("U","G","Funci\u00f3n inicio.","*\"\u00c9rase una vez...\"* \u00bfPara qu\u00e9 sirve?",opt(("A","Cerrar cuento.",False),("B","Presentar conflicto.",False),("C","Empezar narraci\u00f3n.",True,"Correcto."),("D","Dar moraleja.",False)),"Funci\u00f3n."),
("Ap","I","Predecir nudo.","*\"Inicio: ni\u00f1a encuentra llave misteriosa.\"* \u00bfQu\u00e9 pasa despu\u00e9s?",opt(("A","Ni\u00f1a investiga la llave.",True,"Correcto."),("B","Se va a dormir.",False),("C","Llave se pierde.",False),("D","No hace nada.",False)),"Predecir nudo."),
("Ap","I","Crear desenlace.","*\"Nudo: lobo sopla casa de paja.\"* \u00bfDesenlace?",opt(("A","Lobo se va.",False,"No resuelve."),("B","Casa cae, cerdito corre a casa de ladrillos.",True,"Correcto."),("C","Lobo se duerme.",False),("D","Casa no se cae.",False)),"Desenlace."),
("An","I","Estructura incompleta.","*\"Texto: un d\u00eda sali\u00f3 el sol y todos fueron felices.\"* \u00bfQu\u00e9 falta?",opt(("A","Inicio y nudo.",True,"Solo hay desenlace."),("B","Nada.",False),("C","Solo inicio.",False),("D","Solo nudo.",False)),"Analizar estructura."),
("An","R","Sin nudo.","*\"Cuento sin nudo.\"* \u00bfQu\u00e9 pasa?",opt(("A","Es m\u00e1s corto.",False),("B","No hay conflicto, es aburrido.",True,"Correcto."),("C","Mejor.",False),("D","M\u00e1s personajes.",False)),"Importancia del conflicto."),
("An","R","Elementos necesarios.","*\"\u00bfQu\u00e9 debe tener un cuento?\"*",opt(("A","Solo inicio y final.",False),("B","Inicio, nudo y desenlace.",True,"Correcto."),("C","Solo personajes.",False),("D","Solo descripciones.",False)),"Estructura completa."),
], "Bundle estructura narrativa.")

make(15, "repaso-p3", "Repaso P3",
"repaso: textos informativos, narrativos, estructura", 0.70, [
("U","G","Noticia vs cuento.","*\"A: Ayer llovi\u00f3 en Bogot\u00e1. B: \u00c9rase una nube que lloraba.\"* \u00bfCu\u00e1l es noticia?",opt(("A","A.",True,"Correcto."),("B","B.",False),("C","Ambos.",False),("D","Ninguno.",False)),"Diferenciar."),
("R","L","Dato divulgaci\u00f3n.","*\"El \u00e1rbol de guadua crece hasta 30 metros.\"* \u00bfCu\u00e1nto?",opt(("A","10m.",False),("B","30m.",True,"Correcto."),("C","50m.",False),("D","100m.",False)),"Dato."),
("U","G","Moraleja.","*\"Liebre y tortuga.\"* \u00bfEnse\u00f1a?",opt(("A","Correr es malo.",False),("B","Constancia vence confianza.",True,"Correcto."),("C","Liebres malas.",False),("D","Tortugas vuelan.",False)),"Moraleja."),
("U","G","Estructura.","*\"1. Juan. 2. Juan pierde mochila. 3. Juan encuentra mochila.\"* \u00bfOrden?",opt(("A","1,2,3.",True,"Correcto."),("B","3,2,1.",False),("C","2,1,3.",False),("D","1,3,2.",False)),"Estructura."),
("Ap","I","Tipo de texto.","*\"Texto que explica c\u00f3mo se forman los volcanes.\"* \u00bfTipo?",opt(("A","Cuento.",False),("B","Divulgaci\u00f3n.",True,"Correcto."),("C","Noticia.",False),("D","Poema.",False)),"Tipo."),
("An","I","Comparar textos.","*\"Noticia: informa hechos. Cuento: narra ficci\u00f3n.\"* \u00bfDiferencia?",opt(("A","Iguales.",False),("B","Noticia real, cuento ficci\u00f3n.",True,"Correcto."),("C","Cuento real, noticia ficci\u00f3n.",False),("D","Ninguna.",False)),"Diferencias."),
("An","R","\u00bfHay nudo?","*\"Juan se levant\u00f3, desayun\u00f3 y fue a la escuela.\"* \u00bfHay nudo?",opt(("A","S\u00ed, conflicto.",False),("B","No, rutina sin conflicto.",True,"Correcto."),("C","Ir a escuela es problema.",False),("D","No se sabe.",False)),"Evaluar conflicto."),
("An","R","Hecho vs opini\u00f3n.","*\"El proyecto es el mejor de la ciudad.\"* \u00bfHecho?",opt(("A","S\u00ed.",False),("B","No, opini\u00f3n.",True,"Correcto."),("C","Ambos.",False),("D","No se sabe.",False)),"Hecho/opini\u00f3n."),
("An","R","Personaje.","*\"La abuela teje mochilas way\u00fau.\"* \u00bfCaracter\u00edstica?",opt(("A","M\u00e9dica.",False),("B","Artesana.",True,"Correcto."),("C","Profe.",False),("D","Conductora.",False)),"Caracter\u00edstica."),
("Ap","I","Prop\u00f3sito.","*\"Texto para vender un producto.\"* \u00bfProp\u00f3sito?",opt(("A","Informar.",False),("B","Persuadir.",True,"Correcto."),("C","Entretener.",False),("D","Ense\u00f1ar.",False)),"Prop\u00f3sito."),
], "Bundle repaso P3.")
