#!/usr/bin/env python3
"""Generate W01-W10 bundles for Lectura Critica G4."""
import sys
sys.path.insert(0, r"E:\scripts-python\worldexams\questions_data\colombia\lectura-critica\grado-4\2026\weekly")
from gen_all_v2 import make, opt

# ═══ W01: Comprensión literal: idea principal ═══
make(1, "comprension-literal-idea-principal",
"Comprensi\u00f3n literal: idea principal",
"idea principal, comprensi\u00f3n literal, textos cortos, informaci\u00f3n expl\u00edcita",
0.76, [
("R","L","Idea principal en oraci\u00f3n.",
"*\"La tortuga es un animal que vive muchos a\u00f1os y puede pesar hasta 300 kilos.\"* \u00bfCu\u00e1l es la idea principal?",
opt(("A","Las tortugas son lentas.",False),
("B","Las tortugas viven muchos a\u00f1os y pesan hasta 300 kilos.",True,"Correcto. Es la informaci\u00f3n principal de la oraci\u00f3n."),
("C","Las tortugas nadan r\u00e1pido.",False),
("D","Las tortugas ponen huevos.",False)),
"Idea principal expl\u00edcita."),
("R","L","Idea principal de dos oraciones.",
"*\"Los ni\u00f1os reciclaron botellas pl\u00e1sticas. Con ellas hicieron macetas para el jard\u00edn de la escuela.\"* \u00bfCu\u00e1l es la idea principal?",
opt(("A","Los ni\u00f1os botan botellas.",False),
("B","Los ni\u00f1os usaron botellas recicladas para hacer jardineras.",True,"Correcto."),
("C","El jard\u00edn cerr\u00f3.",False),
("D","Las macetas son de barro.",False)),
"Idea principal del conjunto."),
("R","L","Personaje principal.",
"*\"Hab\u00eda una vez un campesino llamado Jos\u00e9 que viv\u00eda en una vereda de Boyac\u00e1.\"* \u00bfQui\u00e9n es el personaje principal?",
opt(("A","El pueblo de Boyac\u00e1.",False),
("B","Jos\u00e9, el campesino.",True,"Correcto."),
("C","La vereda.",False),
("D","Los animales.",False)),
"Identificar personaje principal."),
("U","G","Tema de texto.",
"*\"En las monta\u00f1as de Colombia crecen muchas orqu\u00eddeas. Hay m\u00e1s de 4.000 especies.\"* \u00bfDe qu\u00e9 trata el texto?",
opt(("A","De los p\u00e1jaros.",False),
("B","De las orqu\u00eddeas de Colombia.",True,"Correcto."),
("C","De las monta\u00f1as.",False),
("D","De los colores.",False)),
"Identificar tema."),
("U","G","Resumir idea principal.",
"*\"En la costa Caribe, los ni\u00f1os juegan f\u00fatbol en la arena. Tambi\u00e9n construyen castillos y recogen conchas.\"* \u00bfCu\u00e1l es la idea principal?",
opt(("A","Los ni\u00f1os trabajan en la costa.",False),
("B","Los ni\u00f1os juegan y se divierten en la playa.",True,"Correcto."),
("C","La costa es peligrosa.",False),
("D","Solo juegan solos.",False)),
"Resumir en oraci\u00f3n."),
("Ap","I","Idea principal impl\u00edcita.",
"*\"El agua del r\u00edo estaba sucia. Los peces desaparecieron. Los pescadores ya no pescan.\"* \u00bfCu\u00e1l es la idea principal?",
opt(("A","Los peces se fueron de vacaciones.",False),
("B","La contaminaci\u00f3n del r\u00edo afect\u00f3 a los peces y pescadores.",True,"Correcto. Se infiere del texto."),
("C","El r\u00edo est\u00e1 limpio.",False),
("D","Los pescadores descansan.",False)),
"Inferir idea principal."),
("Ap","I","Seleccionar el mejor t\u00edtulo.",
"*\"Las hormigas trabajan juntas. Cada una tiene una tarea. As\u00ed construyen su hormiguero.\"* \u00bfCu\u00e1l es el mejor t\u00edtulo?",
opt(("A","Hormigas solitarias.",False),
("B","El trabajo en equipo de las hormigas.",True,"Correcto."),
("C","C\u00f3mo vuelan las hormigas.",False),
("D","El color de las hormigas.",False)),
"Elegir t\u00edtulo adecuado."),
("An","I","Diferenciar detalles.",
"*\"La guadua es una planta que crece r\u00e1pido. Se usa en construcci\u00f3n. Es muy resistente.\"* \u00bfCu\u00e1l es un DETALLE, no la idea principal?",
opt(("A","La guadua es resistente.",True,"Correcto. Eso es un detalle de apoyo."),
("B","La guadua es una planta \u00fatil.",False,"Esa es la idea principal."),
("C","La guadua crece en Colombia.",False,"Idea general."),
("D","La guadua es natural.",False)),
"Distinguir detalle de idea principal."),
("An","R","Evaluar si la idea es correcta.",
"*\"Los loros hablan como las personas.\"* \u00bfEs esta una idea principal correcta para un texto cient\u00edfico?",
opt(("A","S\u00ed, los loros hablan.",False),
("B","No, los loros imitan sonidos pero no hablan con significado.",True,"Correcto. La afirmaci\u00f3n no es precisa."),
("C","S\u00ed, porque tienen cuerdas vocales.",False),
("D","No, pero es entretenido.",False)),
"Evaluar validez de idea."),
("An","R","Crear t\u00edtulo para un p\u00e1rrafo.",
"*\"El caf\u00e9 colombiano se cultiva en las monta\u00f1as. Es reconocido en todo el mundo por su sabor suave.\"* \u00bfMejor t\u00edtulo?",
opt(("A","C\u00f3mo hacer caf\u00e9.",False),
("B","El caf\u00e9 colombiano: sabor de monta\u00f1a.",True,"Correcto. Resume ambas ideas."),
("C","Las monta\u00f1as de Colombia.",False),
("D","Cafeteras del mundo.",False)),
"Sintetizar t\u00edtulo."),
], "Bundle de idea principal para grado 4. Contextos colombianos variados.")

# ═══ W02: Detalles explícitos ═══
make(2, "comprension-literal-detalles",
"Comprensi\u00f3n literal: detalles expl\u00edcitos",
"detalles expl\u00edcitos, informaci\u00f3n literal, datos, n\u00fameros, fechas",
0.78, [
("R","L","Edad de personaje.",
"*\"Ana tiene 9 a\u00f1os y vive en Sincelejo.\"* \u00bfCu\u00e1ntos a\u00f1os tiene Ana?",
opt(("A","7 a\u00f1os.",False),
("B","8 a\u00f1os.",False),
("C","9 a\u00f1os.",True,"Correcto."),
("D","10 a\u00f1os.",False)),
"Identificar edad expl\u00edcita."),
("R","L","Color de objeto.",
"*\"La mochila de Pedro es azul con rayas rojas.\"* \u00bfDe qu\u00e9 color es la mochila?",
opt(("A","Verde.",False),
("B","Azul con rayas rojas.",True,"Correcto."),
("C","Roja con rayas azules.",False),
("D","Negra.",False)),
"Identificar color."),
("R","L","Lugar.",
"*\"La escuela Rafael N\u00fa\u00f1ez queda en la calle 10 con carrera 15, en Monter\u00eda.\"* \u00bfD\u00f3nde queda la escuela?",
opt(("A","Bogot\u00e1.",False),
("B","Monter\u00eda.",True,"Correcto."),
("C","Medell\u00edn.",False),
("D","Cali.",False)),
"Identificar lugar expl\u00edcito."),
("U","G","Cantidad.",
"*\"En la biblioteca hay 150 libros de cuentos y 80 libros de ciencias.\"* \u00bfCu\u00e1ntos libros de ciencias hay?",
opt(("A","150.",False,"Esa es la cantidad de cuentos."),
("B","230.",False,"Es la suma."),
("C","80.",True,"Correcto."),
("D","100.",False)),
"Identificar cantidad expl\u00edcita."),
("U","G","Nombre del animal.",
"*\"El perro de Mar\u00eda se llama Copito porque es blanco y esponjoso.\"* \u00bfC\u00f3mo se llama el perro?",
opt(("A","Nieve.",False),
("B","Copito.",True,"Correcto."),
("C","Blanco.",False),
("D","Peluche.",False)),
"Identificar nombre."),
("Ap","I","Detalle num\u00e9rico.",
"*\"El \u00e1rbol de mango mide 12 metros de alto y da frutos 2 veces al a\u00f1o.\"* \u00bfCu\u00e1nto mide el \u00e1rbol?",
opt(("A","10 metros.",False),
("B","12 metros.",True,"Correcto."),
("C","15 metros.",False),
("D","20 metros.",False)),
"Identificar medida expl\u00edcita."),
("Ap","I","Fecha.",
"*\"El 20 de julio de 1810 fue un d\u00eda importante para Colombia.\"* \u00bfEn qu\u00e9 fecha ocurri\u00f3?",
opt(("A","20 de julio de 1810.",True,"Correcto."),
("B","20 de junio de 1810.",False),
("C","7 de agosto de 1819.",False),
("D","15 de septiembre de 1810.",False)),
"Identificar fecha expl\u00edcita."),
("An","I","Comparar cantidades.",
"*\"En primer grado hay 25 estudiantes. En segundo hay 30.\"* \u00bfEn qu\u00e9 grado hay m\u00e1s estudiantes?",
opt(("A","En primero.",False,"Primero tiene 25."),
("B","En segundo.",True,"Correcto. Segundo tiene 30."),
("C","Tienen el mismo n\u00famero.",False),
("D","No se puede saber.",False)),
"Comparar cantidades."),
("An","R","Ubicar en el texto.",
"*\"La capital de Colombia es Bogot\u00e1. Est\u00e1 a 2.600 metros sobre el nivel del mar.\"* \u00bfQu\u00e9 informaci\u00f3n NO est\u00e1 en el texto?",
opt(("A","Bogot\u00e1 es la capital.",False,"S\u00ed est\u00e1."),
("B","Est\u00e1 a 2.600 metros.",False,"S\u00ed est\u00e1."),
("C","Bogot\u00e1 tiene 8 millones de habitantes.",True,"Esa informaci\u00f3n no aparece en el texto."),
("D","Bogot\u00e1 est\u00e1 en Colombia.",False,"Se puede inferir.")),
"Reconocer qu\u00e9 no est\u00e1 expl\u00edcito."),
("An","R","Verificar exactitud.",
"*\"El texto dice: \u2018El colibr\u00ed es un ave peque\u00f1a\u2019.\"* Un compa\u00f1ero dice que es un insecto. \u00bfQui\u00e9n tiene la raz\u00f3n?",
opt(("A","El compa\u00f1ero, porque es peque\u00f1o.",False),
("B","El texto, porque dice que es un ave.",True,"Correcto. Debemos confiar en la informaci\u00f3n del texto."),
("C","Ambos tienen raz\u00f3n.",False),
("D","Ninguno.",False)),
"Verificar informaci\u00f3n le\u00edda."),
], "Bundle de detalles expl\u00edcitos. Contextos cotidianos colombianos.")

# ═══ W03: Secuencia de eventos ═══
make(3, "secuencia-eventos",
"Secuencia de eventos en un texto",
"secuencia temporal, orden cronol\u00f3gico, conectores, primero, luego, despu\u00e9s",
0.74, [
("R","L","Primer evento.",
"*\"Primero sembraron la semilla, luego regaron y finalmente la taparon con tierra.\"* \u00bfQu\u00e9 hicieron primero?",
opt(("A","Regar.",False),
("B","Sembrar la semilla.",True,"Correcto."),
("C","Tapar con tierra.",False),
("D","Nada.",False)),
"Identificar primer paso."),
("R","L","\u00daltimo evento.",
"*\"Primero pel\u00f3 la papa, despu\u00e9s la cort\u00f3 en tiras y por \u00faltimo la fri\u00f3.\"* \u00bfQu\u00e9 hizo al final?",
opt(("A","Pel\u00f3 la papa.",False),
("B","Cort\u00f3 la papa.",False),
("C","Fri\u00f3 la papa.",True,"Correcto."),
("D","Lav\u00f3 la papa.",False)),
"Identificar \u00faltimo paso."),
("U","G","Orden correcto.",
"*\"1. Se levant\u00f3. 2. Desayun\u00f3. 3. Se cepill\u00f3 los dientes. 4. Sali\u00f3 a la escuela.\"* \u00bfQu\u00e9 va despu\u00e9s de desayunar?",
opt(("A","Se levant\u00f3.",False,"Ya pas\u00f3."),
("B","Se cepill\u00f3 los dientes.",True,"Correcto."),
("C","Sali\u00f3 a la escuela.",False,"Todav\u00eda no."),
("D","Nada.",False)),
"Identificar secuencia."),
("U","G","Conector de secuencia.",
"*\"Lav\u00f3 la ropa, despu\u00e9s la tendi\u00f3 al sol.\"* \u00bfQu\u00e9 palabra indica orden?",
opt(("A","Lav\u00f3.",False),
("B","despu\u00e9s.",True,"Correcto."),
("C","ropa.",False),
("D","sol.",False)),
"Identificar conector temporal."),
("U","G","Orden cronol\u00f3gico en d\u00eda.",
"*\"Por la ma\u00f1ana fue al m\u00e9dico. Al mediod\u00eda almorz\u00f3. En la tarde fue al parque.\"* \u00bfCu\u00e1ndo almorz\u00f3?",
opt(("A","En la ma\u00f1ana.",False),
("B","Al mediod\u00eda.",True,"Correcto."),
("C","Por la tarde.",False),
("D","En la noche.",False)),
"Ubicar evento en el tiempo."),
("Ap","I","Evento faltante.",
"*\"1. Compr\u00f3 ingredientes. 2. ________. 3. Horne\u00f3 el pastel.\"* \u00bfQu\u00e9 falta?",
opt(("A","Se durmi\u00f3.",False),
("B","Prepar\u00f3 la mezcla del pastel.",True,"Correcto."),
("C","Sali\u00f3 a jugar.",False),
("D","Ley\u00f3 un libro.",False)),
"Inferir paso faltante."),
("Ap","I","Orden inverso.",
"*\"En la noche se acost\u00f3. Antes de eso, cen\u00f3. Y antes de cenar, lav\u00f3 los platos.\"* \u00bfQu\u00e9 hizo primero?",
opt(("A","Se acost\u00f3.",False,"Fue lo \u00faltimo."),
("B","Cen\u00f3.",False,"Fue en medio."),
("C","Lav\u00f3 los platos.",True,"Correcto. Fue lo primero."),
("D","Nada.",False)),
"Reconstruir orden inverso."),
("An","I","Reconstruir historia.",
"*\"Final: el pollito sali\u00f3 del cascar\u00f3n. Inicio: la mam\u00e1 gallina puso un huevo.\"* \u00bfQu\u00e9 va en medio?",
opt(("A","El huevo se rompi\u00f3 solo.",False),
("B","La gallina incub\u00f3 el huevo.",True,"Correcto."),
("C","El pollito vol\u00f3.",False),
("D","El huevo rod\u00f3.",False)),
"Reconstruir secuencia narrativa."),
("An","R","Evaluar si hay orden.",
"*\"El texto no tiene palabras como primero, luego, despu\u00e9s.\"* \u00bfEs f\u00e1cil entender el orden?",
opt(("A","S\u00ed, siempre se entiende.",False),
("B","No, porque faltan conectores que ayuden a seguir la secuencia.",True,"Correcto."),
("C","Da igual.",False),
("D","Depende del lector.",False)),
"Evaluar importancia de conectores."),
("An","R","Planificar secuencia.",
"*\"Para hacer una cometa se necesita: 1. Cortar papel 2. Pegar varitas 3. Atar hilo.\"* Si se invierte el orden, \u00bffunciona?",
opt(("A","S\u00ed, funciona igual.",False),
("B","No, el orden importa.",True,"Correcto. Hay que seguir los pasos en orden."),
("C","A veces funciona.",False),
("D","Da lo mismo.",False)),
"Evaluar importancia del orden."),
], "Bundle de secuencia de eventos. Conectores temporales.")

# ═══ W04: Personajes y sus características ═══
make(4, "personajes-caracteristicas",
"Personajes y sus caracter\u00edsticas",
"personajes, caracter\u00edsticas f\u00edsicas, personalidad, descripci\u00f3n",
0.75, [
("R","L","Nombre del personaje.",
"*\"Hab\u00eda una vez un perro llamado Max que viv\u00eda en Santa Marta.\"* \u00bfC\u00f3mo se llama el perro?",
opt(("A","Rex.",False),
("B","Max.",True,"Correcto."),
("C","Toby.",False),
("D","Luna.",False)),
"Identificar nombre."),
("R","L","Caracter\u00edstica f\u00edsica.",
"*\"La abuela de Camilo tiene el cabello blanco y usa gafas.\"* \u00bfC\u00f3mo es el cabello de la abuela?",
opt(("A","Negro.",False),
("B","Blanco.",True,"Correcto."),
("C","Caf\u00e9.",False),
("D","Rojo.",False)),
"Identificar caracter\u00edstica f\u00edsica."),
("U","G","Personalidad del personaje.",
"*\"Sof\u00eda siempre compart\u00eda su almuerzo con los que no tra\u00edan.\"* \u00bfC\u00f3mo es Sof\u00eda?",
opt(("A","Ego\u00edsta.",False),
("B","Generosa.",True,"Correcto. Compartir es una acci\u00f3n generosa."),
("C","Triste.",False),
("D","Perezosa.",False)),
"Inferir personalidad por acciones."),
("U","G","Profesi\u00f3n.",
"*\"Don Carlos arregla los dientes de las personas en su consultorio.\"* \u00bfQu\u00e9 es Don Carlos?",
opt(("A","M\u00e9dico general.",False),
("B","Odont\u00f3logo.",True,"Correcto."),
("C","Veterinario.",False),
("D","Profesor.",False)),
"Identificar oficio."),
("U","G","Sentimiento.",
"*\"Cuando Mar\u00eda vio su nota, salt\u00f3 de alegr\u00eda y abraz\u00f3 a su mam\u00e1.\"* \u00bfC\u00f3mo se sinti\u00f3 Mar\u00eda?",
opt(("A","Triste.",False),
("B","Enojada.",False),
("C","Alegre.",True,"Correcto."),
("D","Aburrida.",False)),
"Identificar emoci\u00f3n."),
("Ap","I","Describir personaje.",
"*\"Pedro es alto, delgado y siempre ayuda a los dem\u00e1s.\"* \u00bfCu\u00e1l de las siguientes NO es una caracter\u00edstica de Pedro?",
opt(("A","Alto.",False,"S\u00ed es caracter\u00edstica."),
("B","Delgado.",False,"S\u00ed es caracter\u00edstica."),
("C","Bajo.",True,"El texto dice que es alto."),
("D","Ayudador.",False,"S\u00ed es caracter\u00edstica.")),
"Clasificar caracter\u00edsticas."),
("Ap","I","Distinguir personaje principal.",
"*\"Un ni\u00f1o llamado Tom\u00e1s encontr\u00f3 un loro herido. El loro se llamaba Pepe. Tom\u00e1s cuid\u00f3 de Pepe hasta que san\u00f3.\"* \u00bfQui\u00e9n es el personaje principal?",
opt(("A","Pepe el loro.",False,"Es importante pero no principal."),
("B","Tom\u00e1s.",True,"Correcto. La historia gira en torno a \u00e9l."),
("C","El veterinario.",False,"No aparece."),
("D","La mam\u00e1.",False,"No aparece.")),
"Identificar personaje principal."),
("An","I","Comparar personajes.",
"*\"Ana es tranquila y ordenada. Luis es inquieto y desordenado.\"* \u00bfQu\u00e9 tienen en com\u00fan?",
opt(("A","Son iguales.",False),
("B","Ambos tienen una personalidad definida.",True,"Correcto."),
("C","Ambos son inquietos.",False),
("D","Ambos son ordenados.",False)),
"Identificar caracter\u00edsticas compartidas."),
("An","R","Evaluar coherencia del personaje.",
"*\"El texto dice que el personaje es generoso, pero no comparte sus juguetes.\"* \u00bfHay coherencia?",
opt(("A","S\u00ed, es normal.",False),
("B","No, hay contradicci\u00f3n entre lo que dice y lo que hace.",True,"Correcto."),
("C","Da igual.",False),
("D","Solo a veces.",False)),
"Evaluar coherencia de personaje."),
("An","R","Describir con adjetivos.",
"*\"La mam\u00e1 de Juan cocina rico y siempre recibe a los invitados con sonrisa.\"* \u00bfCu\u00e1l de estos adjetivos la describe mejor?",
opt(("A","Antip\u00e1tica.",False),
("B","Acogedora y amable.",True,"Correcto."),
("C","Perezosa.",False),
("D","Triste.",False)),
"Elegir adjetivos apropiados."),
], "Bundle de personajes y caracter\u00edsticas. Contextos familiares colombianos.")

print("W01-W04 generated.")
